### ISSUE TITLE
面板网站只有页面但是没人和录播讯息No Data

### ISSUE THREAD

**Issue by anlo1220** [hr3lxphr6j/bililive-go#100]
网址开面板 会出现这个 网站只有页面但是没人和录播讯息No Data

> 
> 2020/08/03 01:02:10 http: panic serving 127.0.0.1:6664: interface conversion: interface {} is nil, not *live.Info
> goroutine 4495 [running]:
> net/http.(*conn).serve.func1(0xc0003d74a0)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:1772 +0x139
> panic(0x9d6c40, 0xc00360a660)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/runtime/panic.go:975 +0x3e3
> github.com/hr3lxphr6j/bililive-go/src/servers.parseInfo(0xccbc80, 0xc00360a390, 0xccff80, 0xc00038a6c0, 0xc000418300)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/servers/handler.go:25 +0x242
> github.com/hr3lxphr6j/bililive-go/src/servers.getAllLives(0xcc9b00, 0xc0004740e0, 0xc0017c2400)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/servers/handler.go:35 +0x191
> net/http.HandlerFunc.ServeHTTP(0xbf3478, 0xcc9b00, 0xc0004740e0, 0xc0017c2400)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2012 +0x44
> github.com/gorilla/mux.CORSMethodMiddleware.func1.1(0xcc9b00, 0xc0004740e0, 0xc0017c2400)
>         /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.7.4/middleware.go:51 +0xf4
> net/http.HandlerFunc.ServeHTTP(0xc0014ae3a0, 0xcc9b00, 0xc0004740e0, 0xc0017c2400)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2012 +0x44
> github.com/hr3lxphr6j/bililive-go/src/servers.log.func1(0xcc9b00, 0xc0004740e0, 0xc0017c2400)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/servers/middleware.go:16 +0x31c
> net/http.HandlerFunc.ServeHTTP(0xc0014ae3c0, 0xcc9b00, 0xc0004740e0, 0xc0017c2400)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2012 +0x44
> github.com/hr3lxphr6j/bililive-go/src/servers.initMux.func1.1(0xcc9b00, 0xc0004740e0, 0xc0017c2200)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/servers/server.go:29 +0x1d2
> net/http.HandlerFunc.ServeHTTP(0xc00360a300, 0xcc9b00, 0xc0004740e0, 0xc0017c2200)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2012 +0x44
> github.com/gorilla/mux.(*Router).ServeHTTP(0xc00128c0c0, 0xcc9b00, 0xc0004740e0, 0xc0017c2000)
>         /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
> net/http.serverHandler.ServeHTTP(0xc000475180, 0xcc9b00, 0xc0004740e0, 0xc0017c2000)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2807 +0xa3
> net/http.(*conn).serve(0xc0003d74a0, 0xccbbc0, 0xc000dba640)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:1895 +0x86c
> created by net/http.(*Server).Serve
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2933 +0x35c
> 2020/08/03 01:02:33 http: panic serving 127.0.0.1:6916: interface conversion: interface {} is nil, not *live.Info
> goroutine 4900 [running]:
> net/http.(*conn).serve.func1(0xc00047cdc0)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:1772 +0x139
> panic(0x9d6c40, 0xc0012b86f0)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/runtime/panic.go:975 +0x3e3
> github.com/hr3lxphr6j/bililive-go/src/servers.parseInfo(0xccbc80, 0xc0012b82a0, 0xccff80, 0xc000295ca0, 0xc0021da400)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/servers/handler.go:25 +0x242
> github.com/hr3lxphr6j/bililive-go/src/servers.getAllLives(0xcc9b00, 0xc0004740e0, 0xc002790700)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/servers/handler.go:35 +0x191
> net/http.HandlerFunc.ServeHTTP(0xbf3478, 0xcc9b00, 0xc0004740e0, 0xc002790700)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2012 +0x44
> github.com/gorilla/mux.CORSMethodMiddleware.func1.1(0xcc9b00, 0xc0004740e0, 0xc002790700)
>         /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.7.4/middleware.go:51 +0xf4
> net/http.HandlerFunc.ServeHTTP(0xc00009df00, 0xcc9b00, 0xc0004740e0, 0xc002790700)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2012 +0x44
> github.com/hr3lxphr6j/bililive-go/src/servers.log.func1(0xcc9b00, 0xc0004740e0, 0xc002790700)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/servers/middleware.go:16 +0x31c
> net/http.HandlerFunc.ServeHTTP(0xc00009df20, 0xcc9b00, 0xc0004740e0, 0xc002790700)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2012 +0x44
> github.com/hr3lxphr6j/bililive-go/src/servers.initMux.func1.1(0xcc9b00, 0xc0004740e0, 0xc002790600)
>         /home/travis/gopath/src/github.com/hr3lxphr6j/bililive-go/src/servers/server.go:29 +0x1d2
> net/http.HandlerFunc.ServeHTTP(0xc0012b8180, 0xcc9b00, 0xc0004740e0, 0xc002790600)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2012 +0x44
> github.com/gorilla/mux.(*Router).ServeHTTP(0xc00128c0c0, 0xcc9b00, 0xc0004740e0, 0xc002790300)
>         /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
> net/http.serverHandler.ServeHTTP(0xc000475180, 0xcc9b00, 0xc0004740e0, 0xc002790300)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2807 +0xa3
> net/http.(*conn).serve(0xc00047cdc0, 0xccbbc0, 0xc0021da080)
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:1895 +0x86c
> created by net/http.(*Server).Serve
>         /home/travis/.gimme/versions/go1.14.3.linux.amd64/src/net/http/server.go:2933 +0x35c
>

**Comment by hr3lxphr6j** [comment]
你添加了多少个直播间？

**Comment by anlo1220** [comment]
117个

**Comment by hr3lxphr6j** [comment]
> 117个

https://github.com/hr3lxphr6j/bililive-go/blob/master/src/cmd/bililive/bililive.go#L57 我以为没人会打爆这个cache

**Comment by daxiaamo** [comment]
最高是128个直播间可以正常显示吗？

**Comment by hr3lxphr6j** [comment]
> 最高是128个直播间可以正常显示吗？

理论上吧，我没测过

**Comment by kira1928** [comment]
@anlo1220 现在还有这个问题吗？

**Comment by kira1928** [comment]
已在最新版中将可录制房间上限调至 1024
