### ISSUE TITLE
发现虎牙直播有一个直播间录不了，对比能录的其他直播间发现编码格式有区别，不知道有没有关系

### ISSUE THREAD

**Issue by marvinssky** [hr3lxphr6j/bililive-go#106]
虎牙直播间号：414670
没有返回的报错，但是没有录下来的直播录像；
对比能录的其他直播间发现编码格式有区别，不知道有没有关系：第一图是她直播间，编码格式H265，其他能录的直播间我看了下基本是H264（如第二图）

**Comment by marvinssky** [comment]
![2](https://user-images.githubusercontent.com/37216223/91863419-ac21af80-eca1-11ea-8f53-43006b12bff1.jpg)

![1](https://user-images.githubusercontent.com/37216223/91863427-afb53680-eca1-11ea-966e-854346636e65.jpg)

**Comment by hr3lxphr6j** [comment]
Duplicate of #74

**Comment by marvinssky** [comment]
好的，了解了，谢谢呀
