### ISSUE TITLE
可否提供录制若干时间后自动切片的功能

### ISSUE THREAD

**Issue by yowanep** [hr3lxphr6j/bililive-go#109]
部分主播由于直播时间过长（耐久类型）可能会导致单次直播录制文件较为庞大，在拖入剪辑软件/上传云盘（部分网盘存在单文件大小限制）或者分享给他人的话可能会有一点不便，可否添加一个录制到一定容量或录制若干时间自动切片的功能？

**Comment by 1136623363** [comment]
同求

**Comment by Qixingchen** [comment]
> 同求

见
https://github.com/hr3lxphr6j/bililive-go/wiki/More-Tips#%E6%9B%B4%E5%A4%9A%E5%A7%BF%E5%8A%BF  
max_duration

**Comment by 1136623363** [comment]
ok，看到了
