### ISSUE TITLE
发现docker部署的一个bug

### ISSUE THREAD

**Issue by daofeng2015** [hr3lxphr6j/bililive-go#111]
部署后 删除一个主播,状态码会返回400,但是单独用二进制和单独的app测试正常
![image](https://user-images.githubusercontent.com/14891398/96014414-ebcee000-0e78-11eb-939f-a463748e7403.png)
ubuntu本地服务器和云服务器ubuntu一样错误

**Comment by hr3lxphr6j** [comment]
response的具体内容是什么

**Comment by daofeng2015** [comment]
> response的具体内容是什么

没有内容 是一个DELETE连接

**Comment by hr3lxphr6j** [comment]
> > response的具体内容是什么
> 
> 没有内容 是一个DELETE连接

image tag，docker run的参数都是什么呢

**Comment by daofeng2015** [comment]
> > > response的具体内容是什么
> > 
> > 
> > 没有内容 是一个DELETE连接
> 
> image tag，docker run的参数都是什么呢
docker run -itd -v ~/bililive:/srv/bililive -p 2345:8080 chigusa/bililive-go
chigusa/bililive-go   latest

**Comment by daofeng2015** [comment]
![image](https://user-images.githubusercontent.com/14891398/96099987-73166500-0f06-11eb-9df7-8a38550e02f3.png)
这是本地测试成功的案例

**Comment by hr3lxphr6j** [comment]
我这没法复现这个问题。。

**Comment by daofeng2015** [comment]
单机测试.保存设置这个前端页面判断返回的是json.但是go后端传过去的ok字符串.......

**Comment by daofeng2015** [comment]
> 我这没法复现这个问题。。

这个问题我找到解决办法了.是docker权限的问题.导致文件状态无法改变.就提示400状态了
