### ISSUE TITLE
有关软件打开的问题

### ISSUE THREAD

**Issue by FK2-Dreaming** [hr3lxphr6j/bililive-go#116]
我已经尝试按照教程分别安装了ffmepg以及bilive-go，但是尝试打开的时候软件exe闪退，后台已经挂了梯子，很疑惑，想请教一下，新人不太懂

**Comment by hr3lxphr6j** [comment]
https://github.com/hr3lxphr6j/bililive-go/wiki/Quick-Guide

**Comment by FK2-Dreaming** [comment]
是整个bililive-go都无法打开，我已经成功下载然后将ffmpeg解压到同一个文件夹了

**Comment by hr3lxphr6j** [comment]
没参数打开闪退是预期内的

**Comment by daofeng2015** [comment]
> 我已经尝试按照教程分别安装了ffmepg以及bilive-go，但是尝试打开的时候软件exe闪退，后台已经挂了梯子，很疑惑，想请教一下，新人不太懂

请看readme或者wiki 里面有详细的介绍.不是直接点exe文件的
