### ISSUE TITLE
screen 长时间挂后台录制出错

### ISSUE THREAD

**Issue by hackroad** [hr3lxphr6j/bililive-go#12]
time="2018-12-21 21:11:50" level=info msg="Live End" host_name="娱加-莫儿" id=c4cb17b48c9c9728408fc6f9cacbcdf4 room_name="诺克萨斯  小黑车 嘟嘟嘟" status=false url="https://www.huya.com/10838506"
time="2018-12-21 21:11:50" level=info msg="Recorde End" host_name="娱加-莫儿" id=c4cb17b48c9c9728408fc6f9cacbcdf4 room_name="诺克萨斯  小黑车 嘟嘟嘟" status=false url="https://www.huya.com/10838506"
time="2018-12-21 21:11:53" level=debug msg=EOF
time="2018-12-21 21:12:20" level=info msg="Live Start" host_name="娱加-莫儿" id=c4cb17b48c9c9728408fc6f9cacbcdf4 room_name="诺克萨斯  小黑车 嘟嘟嘟" status=true url="https://www.huya.com/10838506"
time="2018-12-21 21:12:20" level=info msg="Recorde Start" host_name="娱加-莫儿" id=c4cb17b48c9c9728408fc6f9cacbcdf4 room_name="诺克萨斯  小黑车 嘟嘟嘟" status=true url="https://www.huya.com/10838506"
time="2018-12-21 21:12:50" level=info msg="Live End" host_name="娱加-莫儿" id=c4cb17b48c9c9728408fc6f9cacbcdf4 room_name="诺克萨斯  小黑车 嘟嘟嘟" status=false url="https://www.huya.com/10838506"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7cb274]

goroutine 31525 [running]:
github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Close.func1()
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:96 +0x44
sync.(*Once).Do(0xc000302720, 0xc00070cf18)
        /usr/local/Cellar/go/1.11.1/libexec/src/sync/once.go:44 +0xb3
github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Close(0xc000103dc0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:94 +0x52
github.com/hr3lxphr6j/bililive-go/src/recorders.(*RecorderManager).RemoveRecorder(0xc0003fc4b0, 0x9845e0, 0xc00015a6f0, 0xc000021cc0, 0x20, 0x0, 0x0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder_manager.go:94 +0xb5
github.com/hr3lxphr6j/bililive-go/src/recorders.(*RecorderManager).Start.func2(0xc000320160)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder_manager.go:49 +0xad
created by github.com/hr3lxphr6j/bililive-go/src/lib/events.(*EventDispatcher).DispatchEvent
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/lib/events/event_dispatcher.go:56 +0xd4

**Comment by hr3lxphr6j** [comment]
#17
