### ISSUE TITLE
[BUG]在未知情况下导致的内部错误问题

### ISSUE THREAD

**Issue by older-fox** [hr3lxphr6j/bililive-go#121]
已知在网页端添加直播间并保存后，重启服务会导致部分直播间出现内部错误
日志如下
![image](https://user-images.githubusercontent.com/34577787/99207127-16a1b080-27f8-11eb-8e71-798c0ea8e8cb.png)

另：
在直播间直播结束后，同样有小几率出现信息获取错误，原因未知。debug开启后同样未返回相关错误消息。

另：
在网页端添加直播间后，网页部分元素未及时更新或撤销显示
![image](https://user-images.githubusercontent.com/34577787/99207200-4ea8f380-27f8-11eb-87da-d63550598924.png)

另：
在启动服务时出现内部错误后，再次在网页端尝试添加该直播间会出现接口返回为空的情况。但状态码为200
![image](https://user-images.githubusercontent.com/34577787/99207245-6d0eef00-27f8-11eb-9e30-5a9b4373f69c.png)

目前发现的仅这些，环境Centos 8.0  已知网络连接正常

**Comment by WTFTWTM** [comment]
更新：
在重启多次后恢复正常，仍旧未知原因
![image](https://user-images.githubusercontent.com/34577787/99209124-620a8d80-27fd-11eb-97ff-8398882144c1.png)

在上一条回复中，出现问题的是B站直播间，斗鱼无影响。

![image](https://user-images.githubusercontent.com/34577787/99209136-6d5db900-27fd-11eb-98b5-116e8c10db10.png)

**Comment by WTFTWTM** [comment]
刚说完恢复
问题再次出现
![image](https://user-images.githubusercontent.com/34577787/99209475-3340e700-27fe-11eb-9ccd-478ad54a568a.png)
稍等给出抓包内容

**Comment by WTFTWTM** [comment]
![image](https://user-images.githubusercontent.com/34577787/99210022-a008b100-27ff-11eb-9df2-2eb4031ff632.png)
跟踪部分Issue后发现是该接口被拦截导致

**Comment by WTFTWTM** [comment]
综合考虑后，请求能否不再获取房间信息

更换为平台+房间号的方式保存，这样同样可以避免主播名出现特殊字符导致的保存失败或乱码问题。

推荐将这个功能作为一个可选的开关，感谢作者的努力。谢谢

**Comment by hr3lxphr6j** [comment]
> ![image](https://user-images.githubusercontent.com/34577787/99210022-a008b100-27ff-11eb-9df2-2eb4031ff632.png)
> 跟踪部分Issue后发现是该接口被拦截导致

估计被限速了把

**Comment by WTFTWTM** [comment]
> > ![image](https://user-images.githubusercontent.com/34577787/99210022-a008b100-27ff-11eb-9df2-2eb4031ff632.png)
> > 跟踪部分Issue后发现是该接口被拦截导致
> 
> 估计被限速了把

请问能否将该功能作为可选开关配置，防止出现类似BUG，因为接口限速是必然，不能因为一个功能导致整站录播失效？

**Comment by WTFTWTM** [comment]
![image](https://user-images.githubusercontent.com/34577787/99857233-be86f780-2bc5-11eb-925f-d17ff7338a7f.png)
在升级版本后仍旧出现房间信息无法获取导致录播失败

**Comment by hr3lxphr6j** [comment]
> ![image](https://user-images.githubusercontent.com/34577787/99857233-be86f780-2bc5-11eb-925f-d17ff7338a7f.png)
> 在升级版本后仍旧出现房间信息无法获取导致录播失败

配置文件发下

**Comment by WTFTWTM** [comment]
rpc:
  enable: true
  bind: 127.0.0.1:19730
debug: true
interval: 15
out_put_path: ./
feature:
  use_native_flv_parser: false
live_rooms:
- https://live.bilibili.com/195909
- https://live.bilibili.com/69167
- https://live.bilibili.com/21716679
- https://live.bilibili.com/37034
- https://live.bilibili.com/22508204
- https://live.bilibili.com/2611014
out_put_tmpl: '{{ .Live.GetPlatformCNName }}/{{ .Live.GetRawUrl | filenameFilter }}/[{{ now | htmlDate }}].flv'
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
@hr3lxphr6j

**Comment by kira1928** [comment]
现在还有这个问题吗？

**Comment by older-fox** [comment]
> 现在还有这个问题吗？

哥哥，两年了...

**Comment by kira1928** [comment]
@older-fox 
呃，原作者忙于生活，我这刚接手开始清理 issue，望理解。。

**Comment by kira1928** [comment]
我看 2020 年代的其他 issue 里也有几个类似问题，都是 b 站请求被拦截。
有人说是默认设置的请求间隔只有 15 秒（`interval: 15` 这里），太短了，调大一点可以减少被 ban 风险。

**Comment by kira1928** [comment]
年代久远，issue 就关闭了。需要的话可以重新打开。
