### ISSUE TITLE
docker运行换端口问题

### ISSUE THREAD

**Issue by wangebcjd** [hr3lxphr6j/bililive-go#124]
用docker run --restart=always -v ~/Videos:/srv/bililive -p 8080:8080 -d chigusa/bililive-go运行
这个只能占用8080端口吗？我把第一个8080改成8081的话它占用的还是8080端口，只是外部访问端口变了而已，怎么才能让程序占用vps内部的非8080端口呢？

**Comment by hr3lxphr6j** [comment]
https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose
改变expose的端口就行，为什么要改变容器内监听的端口

**Comment by wangebcjd** [comment]
好的，谢谢
