### ISSUE TITLE
关于配置文件及录制斗鱼高比特率直播间问题

### ISSUE THREAD

**Issue by Byyyi** [hr3lxphr6j/bililive-go#125]
配置文件会永久影响bgo之后运行么 另外不知道是不是因为我配置yml文件有错误 劳烦帮忙诊错一下
另外录制一些斗鱼的高比特率直播间后会分割为时间单位非常小（3-4s左右）的视频分割段 并且还有检测时间间隔后才进行下次录制（例如196；5132174） 而一些画质低的直播间就可以稳定的录制一个文件（例如74751；276200；60637） 并且两者cmd显示无差别 
![FV B}TBJJ{KYT KHV91 G](https://user-images.githubusercontent.com/38751442/101245471-0a2cbb80-3705-11eb-95d8-301adff03b69.png)

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/102473397-6216db00-4092-11eb-9f0d-0fb9addd2bf7.png)
检查下网络？
