### ISSUE TITLE
Twitch录制一直提示直播间不存在

### ISSUE THREAD

**Issue by WingSix** [hr3lxphr6j/bililive-go#127]
试了几个直播间，都是一样的结果
> time="2020-12-09 23:58:46" level=info msg="BiliLive-go Version: v0.5.14 Link Start"
time="2020-12-09 23:58:46" level=debug msg="{AppName:BiliLive-go AppVersion:v0.5.14 BuildTime:2020-11-19_10:27:22 GitHash:ef6168c80a5aa512431419882705460171e701ad Pid:92927 Platform:darwin/amd64 GoVersion:go1.15.5}"
time="2020-12-09 23:58:46" level=debug msg="&{RPC:{Enable:false Bind::8080} Debug:true Interval:20 OutPutPath:./ Feature:{UseNativeFlvParser:false} LiveRooms:[https://www.twitch.tv/moistcr1tikal] OutputTmpl: file: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s}}"
time="2020-12-09 23:58:49" level=error msg="room not exists" url="https://www.twitch.tv/moistcr1tikal"
time="2020-12-09 23:58:49" level=info msg="Bye~"

**Comment by xiaocsl** [comment]
最近刚好要看一些 twitch api 

因为 twitch api 更新了,代码里用的还是 V3 的接口..
现在接口到 V5 了,有些地方的认证之类的需要更改..

部分请求响应信息有变更,认证流程有变更,不过有些接口添加一个. Header 就行了..
看 @hr3lxphr6j 最近会更新不,果断时间没更新的话,我要是有时间改一下的话.

另外,针对只 twitch 走代理..挺省事的..作者用的自己的 github.com/hr3lxphr6j/requests 实际上就 http_client ..
给 twitch 单独一个 session 就行了..果断时间有时间的话,提个PR...看给通过不..
