### ISSUE TITLE
斗鱼 都无法录制

### ISSUE THREAD

**Issue by anlo1220** [hr3lxphr6j/bililive-go#129]
斗鱼 都无法录制
用德国Debian独服 和家里window电脑测试都不能 使用最新版本(旧的没测试)

有显示主播信息以及创建资料夹 但没视频

```
bililive -i https://www.douyu.com/591967 --debug
time="2020-12-14 03:14:51" level=info msg="BiliLive-go Version: v0.5.14 Link Start"
time="2020-12-14 03:14:51" level=debug msg="{AppName:BiliLive-go AppVersion:v0.5.14 BuildTime:2020-11-19_10:30:04 GitHash:ef6168c80a5aa512431419882705460171e701ad Pid:4683 Platform:linux/amd64 GoVersion:go1.15.5}"
time="2020-12-14 03:14:51" level=debug msg="&{RPC:{Enable:false Bind::8080} Debug:true Interval:20 OutPutPath:./ Feature:{UseNativeFlvParser:false} LiveRooms:[https://www.douyu.com/591967] OutputTmpl: file: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s}}"
time="2020-12-14 03:14:53" level=info msg="Live Start" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
time="2020-12-14 03:14:53" level=info msg="Record Start" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
time="2020-12-14 03:14:53" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
time="2020-12-14 03:14:54" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
time="2020-12-14 03:14:54" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
time="2020-12-14 03:14:55" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
time="2020-12-14 03:14:55" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
time="2020-12-14 03:14:56" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
time="2020-12-14 03:14:59" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
^Ctime="2020-12-14 03:14:59" level=info msg="Record End" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
time="2020-12-14 03:14:59" level=info msg="Bye~"
```

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/102038310-e7379100-3e01-11eb-9115-79b5446e8f0f.png)
我这里昨晚录制的爽球直播没啥问题，今天我挂下那个直播间观察下

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/102311803-767ea900-3fa8-11eb-9fbc-a99a793fa785.png)
我这里是可以的，你家里的电脑直接访问斗鱼网页可以播放吗？

**Comment by anlo1220** [comment]
可以直接访问斗鱼网页

**Comment by anlo1220** [comment]
用加拿大的vps也是同样情况，这机子没载过斗鱼所以应该不是ban ip
`root@debian:~# /root/bililive-linux-amd64 -i https://www.douyu.com/9375319 --debug
time="2020-12-18 19:44:49" level=info msg="BiliLive-go Version: v0.5.14 Link Start"
time="2020-12-18 19:44:49" level=debug msg="{AppName:BiliLive-go AppVersion:v0.5.14 BuildTime:2020-11-19_10:30:04 GitHash:ef6168c80a5aa512431419882705460171e701ad Pid:30082 Platform:linux/amd64 GoVersion:go1.15.5}"
time="2020-12-18 19:44:49" level=debug msg="&{RPC:{Enable:false Bind::8080} Debug:true Interval:20 OutPutPath:./ Feature:{UseNativeFlvParser:false} LiveRooms:[https://www.douyu.com/9375319] OutputTmpl: file: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s}}"
time="2020-12-18 19:44:52" level=info msg="Live Start" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛"
time="2020-12-18 19:44:52" level=info msg="Record Start" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛"
time="2020-12-18 19:44:53" level=debug msg="exit status 1" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛"
time="2020-12-18 19:44:54" level=debug msg="exit status 1" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛"
time="2020-12-18 19:44:54" level=debug msg="exit status 1" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛"
^Ctime="2020-12-18 19:44:55" level=info msg="Record End" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛"
time="2020-12-18 19:44:55" level=info msg="Bye~"
`

**Comment by hr3lxphr6j** [comment]
> 用加拿大的vps也是同样情况，这机子没载过斗鱼所以应该不是ban ip
> `root@debian:~# /root/bililive-linux-amd64 -i https://www.douyu.com/9375319 --debug time="2020-12-18 19:44:49" level=info msg="BiliLive-go Version: v0.5.14 Link Start" time="2020-12-18 19:44:49" level=debug msg="{AppName:BiliLive-go AppVersion:v0.5.14 BuildTime:2020-11-19_10:30:04 GitHash:ef6168c80a5aa512431419882705460171e701ad Pid:30082 Platform:linux/amd64 GoVersion:go1.15.5}" time="2020-12-18 19:44:49" level=debug msg="&{RPC:{Enable:false Bind::8080} Debug:true Interval:20 OutPutPath:./ Feature:{UseNativeFlvParser:false} LiveRooms:[https://www.douyu.com/9375319] OutputTmpl: file: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s}}" time="2020-12-18 19:44:52" level=info msg="Live Start" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛" time="2020-12-18 19:44:52" level=info msg="Record Start" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛" time="2020-12-18 19:44:53" level=debug msg="exit status 1" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛" time="2020-12-18 19:44:54" level=debug msg="exit status 1" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛" time="2020-12-18 19:44:54" level=debug msg="exit status 1" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛" ^Ctime="2020-12-18 19:44:55" level=info msg="Record End" host="斗鱼和平官方赛事" room="和平精英-黄金大奖赛17点决赛" time="2020-12-18 19:44:55" level=info msg="Bye~"`

我不清楚斗鱼会不会屏蔽非大陆IP。。。

**Comment by Immity** [comment]
我在hetzner独服上是可以的，建议使用docker版本

**Comment by Immity** [comment]
> 斗鱼 都无法录制
> 用德国Debian独服 和家里window电脑测试都不能 使用最新版本(旧的没测试)
> 
> 有显示主播信息以及创建资料夹 但没视频
> 
> ```
> bililive -i https://www.douyu.com/591967 --debug
> time="2020-12-14 03:14:51" level=info msg="BiliLive-go Version: v0.5.14 Link Start"
> time="2020-12-14 03:14:51" level=debug msg="{AppName:BiliLive-go AppVersion:v0.5.14 BuildTime:2020-11-19_10:30:04 GitHash:ef6168c80a5aa512431419882705460171e701ad Pid:4683 Platform:linux/amd64 GoVersion:go1.15.5}"
> time="2020-12-14 03:14:51" level=debug msg="&{RPC:{Enable:false Bind::8080} Debug:true Interval:20 OutPutPath:./ Feature:{UseNativeFlvParser:false} LiveRooms:[https://www.douyu.com/591967] OutputTmpl: file: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s}}"
> time="2020-12-14 03:14:53" level=info msg="Live Start" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> time="2020-12-14 03:14:53" level=info msg="Record Start" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> time="2020-12-14 03:14:53" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> time="2020-12-14 03:14:54" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> time="2020-12-14 03:14:54" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> time="2020-12-14 03:14:55" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> time="2020-12-14 03:14:55" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> time="2020-12-14 03:14:56" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> time="2020-12-14 03:14:59" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> ^Ctime="2020-12-14 03:14:59" level=info msg="Record End" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> time="2020-12-14 03:14:59" level=info msg="Bye~"
> ```

https://github.com/hr3lxphr6j/bililive-go/issues/63#issuecomment-635724477

**Comment by anlo1220** [comment]
> > 斗鱼 都无法录制
> > 用德国Debian独服 和家里window电脑测试都不能 使用最新版本(旧的没测试)
> > 有显示主播信息以及创建资料夹 但没视频
> > ```
> > bililive -i https://www.douyu.com/591967 --debug
> > time="2020-12-14 03:14:51" level=info msg="BiliLive-go Version: v0.5.14 Link Start"
> > time="2020-12-14 03:14:51" level=debug msg="{AppName:BiliLive-go AppVersion:v0.5.14 BuildTime:2020-11-19_10:30:04 GitHash:ef6168c80a5aa512431419882705460171e701ad Pid:4683 Platform:linux/amd64 GoVersion:go1.15.5}"
> > time="2020-12-14 03:14:51" level=debug msg="&{RPC:{Enable:false Bind::8080} Debug:true Interval:20 OutPutPath:./ Feature:{UseNativeFlvParser:false} LiveRooms:[https://www.douyu.com/591967] OutputTmpl: file: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s}}"
> > time="2020-12-14 03:14:53" level=info msg="Live Start" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > time="2020-12-14 03:14:53" level=info msg="Record Start" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > time="2020-12-14 03:14:53" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > time="2020-12-14 03:14:54" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > time="2020-12-14 03:14:54" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > time="2020-12-14 03:14:55" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > time="2020-12-14 03:14:55" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > time="2020-12-14 03:14:56" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > time="2020-12-14 03:14:59" level=debug msg="exit status 1" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > ^Ctime="2020-12-14 03:14:59" level=info msg="Record End" host="美食老王" room="红烧鱼，红烧猪肉丸子，凉面走着"
> > time="2020-12-14 03:14:59" level=info msg="Bye~"
> > ```
> 
> [#63 (comment)](https://github.com/hr3lxphr6j/bililive-go/issues/63#issuecomment-635724477)

感谢 我用docker也能了

**Comment by pongfcnkl** [comment]
可能是代理问题
录制前暂时把代理关掉就好了
set HTTP_PROXY=
set HTTPS_PROXY=
