### ISSUE TITLE
建议：cli上显示直播间的标题以及主播名（未开播时也显示）

### ISSUE THREAD

**Issue by zhuoziqiang** [hr3lxphr6j/bililive-go#130]
每隔__秒更新一次

**Comment by hr3lxphr6j** [comment]
有什么意义呢。。

**Comment by zhuoziqiang** [comment]
> 有什么意义呢。。

因为有些主播会在标题上写"几日几点直播"之类的信息

**Comment by hr3lxphr6j** [comment]
> > 有什么意义呢。。
> 
> 因为有些主播会在标题上写"几日几点直播"之类的信息

你可以去页面上看，也可以调api拿到，我认为log是排查问题用的，展示过多信息会影响对问题的定位
