### ISSUE TITLE
默认查询间隔设定的过低

### ISSUE THREAD

**Issue by kafu0611** [hr3lxphr6j/bililive-go#132]
推荐把默认的直播间状态查询间隔时间的幅度设的更长一些(至少在30秒到一分钟左右)

如果按照默认设置的话就算只在bilibili上监控一个直播间也会在使用一段时间之后被拖入黑名单反馈412错误
导致无法正确获取直播间状态或者录制出现问题

虽然是可以修改的
但是每次部署都要重新来一遍其实挺麻烦的...

**Comment by kira1928** [comment]
b站不太清楚，不过我用这个项目录虎牙和斗鱼目前是没有问题的。
我用的是 docker 版，用的应该是 20 秒间隔的那个配置。

在这个 issue 之后两年里好像没有遇到很多提 b 站被 ban 问题的，所以我先把这边的 issue 关掉了。
如果有很多人反应遇到这个问题的话再修改默认值吧。
