### ISSUE TITLE
支持自选封装容器

### ISSUE THREAD

**Issue by Immity** [hr3lxphr6j/bililive-go#135]
如题，flv快进会卡住，能否直接封装为mp4或者mkv

**Comment by hr3lxphr6j** [comment]
选择mp4封装如果中途ffmpeg挂掉那么整段录像就废掉无法播放
想要mp4或mkv可以写个cronjob
`fd -e flv --changed-before 1min -x echo ffmpeg -i {} -c copy {.}.mp4 \;`

**Comment by Immity** [comment]
太菜了，写了个勉强能用的
```
#!/bin/bash
for i in "`find /home/data/bililive -mmin +1 -name "*.flv"`"
do 
    ffmpeg -i "$i" -c copy "${i%.*}.mp4";
    rm -rf "$i";
done
```
`*/3 * * * * bash /home/config/bililive.sh`

下面这个命令无法正常运行，扩展名不知道怎么去掉

`find /home/data/bililive/ -mmin +1 -name "*.flv" -exec  ffmpeg -i {} -c copy {}.mp4 \;`

**Comment by hr3lxphr6j** [comment]
> 太菜了，写了个勉强能用的
> 
> ```
> #!/bin/bash
> for i in "`find /home/data/bililive -mmin +1 -name "*.flv"`"
> do 
>     ffmpeg -i "$i" -c copy "${i%.*}.mp4";
>     rm -rf "$i";
> done
> ```
> 
> `*/3 * * * * bash /home/config/bililive.sh`
> 
> 下面这个命令无法正常运行，扩展名不知道怎么去掉
> 
> `find /home/data/bililive/ -mmin +1 -name "*.flv" -exec ffmpeg -i {} -c copy {}.mp4 \;`

[fd](https://github.com/sharkdp/fd)可以`{.}`来表示去掉扩展名的文件名
