### ISSUE TITLE
偶有出现无法检测B站直播间状态

### ISSUE THREAD

**Issue by Faultiness** [hr3lxphr6j/bililive-go#136]
环境：Debian 10, aarch64
版本：[linux-arm64](https://github.com/hr3lxphr6j/bililive-go/releases/download/v0.5.14/bililive-linux-arm64.tar.gz)
配置情况：国内移动网，监听B站三个直播间。config.yml中设置interval为120秒，使用systemctl部署。
报错情况：
稳定运行一天后，重启系统后报错“房间不存在”。重启服务/设备均无效。（疑为风控）
日志如下：
![图片](https://user-images.githubusercontent.com/12472447/103212476-d597d280-4945-11eb-8848-9c702465f41f.png)

**Comment by anlo1220** [comment]
这是被ban ip 改成600秒比较不容易被ban

**Comment by KSOYU** [comment]
> 这是被ban ip 改成600秒比较不容易被ban

win版录播姬是怎么做到

**Comment by kira1928** [comment]
可能和 #132 相关

**Comment by kira1928** [comment]
年久失联，issue 先关闭。
