### ISSUE TITLE
web端可否加入访问验证功能

### ISSUE THREAD

**Issue by zyhibook** [hr3lxphr6j/bililive-go#137]
部署在公网上，web端无密码验证，会导致任何人都可以添加直播间连接，
是否可以加入web端的admin密码验证，
看wiki上的token是只对api有效的。

**Comment by Immity** [comment]
使用nginx反代一下吧
`    location /bililive {
        return 301 /bililive/;
    }
    location /bililive/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_redirect off;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        auth_basic "Authorization";
        auth_basic_user_file /nginx/pass/bililive.pass;
    }`

**Comment by zyhibook** [comment]
> 使用nginx反代一下吧
> 
> ```
>    location /bililive {
>         return 301 /bililive/;
>     }
>     location /bililive/ {
>         proxy_pass http://127.0.0.1:8080/;
>         proxy_redirect off;
>         proxy_set_header        X-Real-IP       $remote_addr;
>         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header Host $host;
>         auth_basic "Authorization";
>         auth_basic_user_file /nginx/pass/bililive.pass;
>     }
> ```

感谢你的方法，已解决，
不够web端访问认证能直接集成在docker里面就更方便了。
