### ISSUE TITLE
这个软件只能通过cmd之类的命令行方式使用吗？没有图形化界面？

### ISSUE THREAD

**Issue by Nevidebla** [hr3lxphr6j/bililive-go#140]
为什么在首页上的这个截图里面就有图形界面？我怎样可以使用到？
![image](https://user-images.githubusercontent.com/54260027/106996524-20fe9580-67bc-11eb-9d3d-2fe4ab3ba2ba.png)
![image](https://user-images.githubusercontent.com/54260027/106996528-24921c80-67bc-11eb-89df-e8261d4c6775.png)

**Comment by hr3lxphr6j** [comment]
浏览器打开`http://127.0.0.1:8080`
