### ISSUE TITLE
求支持抖音和youtube

### ISSUE THREAD

**Issue by anlo1220** [hr3lxphr6j/bililive-go#142]
求支持抖音和youtube

**Comment by pongfcnkl** [comment]
抖音吾爱有，全自动录制。
https://www.52pojie.cn/thread-1303081-1-1.html

**Comment by cxumol** [comment]
youtube 直接用 youtube-dl 就行

**Comment by hr3lxphr6j** [comment]
抖音的直播没web版，我懒得装APP抓包

**Comment by pongfcnkl** [comment]
抖音已经有web版了
https://www.douyin.com/

**Comment by pongfcnkl** [comment]
我发现了个可以直接用抖音号获取视频链接的go项目
https://github.com/caiguanhao/dylive
