### ISSUE TITLE
请求支持腾讯会议直播､ 雪球直播

### ISSUE THREAD

**Issue by cxumol** [hr3lxphr6j/bililive-go#144]
腾讯会议直播, 类似实现例如 https://github.com/Cloudiver/tencent_meeting

雪球直播,  直播间例如 https://xueqiu.com/live/678990

**Comment by hr3lxphr6j** [comment]
BGO在设计上是监控一个**用户（主播）的直播间**，所以需要一个用户实体作为监控的对象

腾讯会议的会议码应该是随机生成的与用户无关，无法监控
雪球我在用户页面也没找的直播间相关的信息
