### ISSUE TITLE
虎牙直播更新之后无法录制

### ISSUE THREAD

**Issue by daxiaamo** [hr3lxphr6j/bililive-go#150]
虎牙直播更新之后无法录制，希望能修复

**Comment by daxiaamo** [comment]
在一些情况下录制的视频会是许多小的视频片段，但是有时确实正常的视频文件。

**Comment by hr3lxphr6j** [comment]
提供下直播间url，我这里录制的两个都很正常
![image](https://user-images.githubusercontent.com/12208550/117531287-62e5e480-b014-11eb-836c-b99b276cbac0.png)
![image](https://user-images.githubusercontent.com/12208550/117531294-6da07980-b014-11eb-88dd-186e3bfdf008.png)

**Comment by kira1928** [comment]
现在还能重现这个问题吗？
可以的话希望提供一下有问题的直播间的 url

**Comment by kira1928** [comment]
issue 年代久远，就此关闭了。
