### ISSUE TITLE
Http Rest API 无法使用

### ISSUE THREAD

**Issue by wangliv2** [hr3lxphr6j/bililive-go#151]
使用 docker 版本
最新的`v0.6.0-rc.2`编译
配置文件中的`rpc`也是开启的
部分配置如下：
```
rpc:
  enable: true
  bind: :8080
```

但是当执行  `curl 127.0.0.1:8080/lives` 提示 `404 page not found`
网页版本（即`127.0.0.1:8080`）是能正常使用的。
我需要如何解决这个问题呢？请求帮助
PS：能否支持弹幕的录制、定时录播的功能？

**Comment by hr3lxphr6j** [comment]
`curl 127.0.0.1:8080/api/lives`
`定时录播`指的什么

**Comment by kira1928** [comment]
原因就是作者上面提到的，你使用了错误的 url 导致的。
不是 `127.0.0.1:8080/lives` 而是 `127.0.0.1:8080/api/lives`
