### ISSUE TITLE
请问 use_native_flv_parser 的功能

### ISSUE THREAD

**Issue by Hello-Moeka** [hr3lxphr6j/bililive-go#152]
请问 use_native_flv_parser 的功能，可以解决时间戳问题吗还是

**Comment by hr3lxphr6j** [comment]
1. 想把ffmpeg的这个依赖去掉
2. 有些直播平台（比如虎牙）魔改了flv来支持hevc，ffmpeg官方并不想支持，之后`native_flv_parser`会尝试支持这种
