### ISSUE TITLE
samba 权限问题

### ISSUE THREAD

**Issue by lloyd18** [hr3lxphr6j/bililive-go#156]
在路由器用docker运行samba和bililive-go，用win10访问，但是有权限问题，不能删除bililive-go下的文件
bililive-go 以外的文件是可以自由增删的，有没有大佬帮帮忙

![photo_2021-06-10_15-04-15](https://user-images.githubusercontent.com/10294460/121480083-4535e180-c9fd-11eb-9d31-6e4794d3fd96.jpg)

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/121481187-7662e180-c9fe-11eb-9467-1d47e949addb.png)
uid指定下

**Comment by lloyd18** [comment]
> ![image](https://user-images.githubusercontent.com/12208550/121481187-7662e180-c9fe-11eb-9467-1d47e949addb.png)
> uid指定下

谢谢，还是不太懂，我是小白一个，具体是指定bililive-go的uid吗？我的uid是这样的
`root@OpenWrt:/mnt/sdb1# id docker
uid=65536(docker) gid=65536(docker) groups=65536(docker),65536(docker)
root@OpenWrt:/mnt/sdb1# id
uid=0(root) gid=0(root)`

那个完整命令要怎么填？

**Comment by hr3lxphr6j** [comment]
> > ![image](https://user-images.githubusercontent.com/12208550/121481187-7662e180-c9fe-11eb-9467-1d47e949addb.png)
> > uid指定下
> 
> 谢谢，还是不太懂，我是小白一个，具体是指定bililive-go的uid吗？我的uid是这样的
> `root@OpenWrt:/mnt/sdb1# id docker uid=65536(docker) gid=65536(docker) groups=65536(docker),65536(docker) root@OpenWrt:/mnt/sdb1# id uid=0(root) gid=0(root)`
> 
> 那个完整命令要怎么填？

uid添你samba用户的uid

**Comment by lloyd18** [comment]
> > > ![image](https://user-images.githubusercontent.com/12208550/121481187-7662e180-c9fe-11eb-9467-1d47e949addb.png)
> > > uid指定下
> > 
> > 
> > 谢谢，还是不太懂，我是小白一个，具体是指定bililive-go的uid吗？我的uid是这样的
> > `root@OpenWrt:/mnt/sdb1# id docker uid=65536(docker) gid=65536(docker) groups=65536(docker),65536(docker) root@OpenWrt:/mnt/sdb1# id uid=0(root) gid=0(root)`
> > 那个完整命令要怎么填？
> 
> uid添你samba用户的uid

大佬，我不会加啊，这两条docker命令 要不你帮我看看需要怎么改？
samba: `docker run -it --name samba -p 139:139 -p 445:445 -v /mnt/sdb1:/mount -d dperson/samba -u "用户;密码" -s "sdb1;/mount/;yes;no;no;all;none"`
bililive-go:`docker run --restart=always -v /mnt/sdb1/bililive-go:/srv/bililive -p 8080:8080 -d chigusa/bililive-go`

**Comment by hr3lxphr6j** [comment]
samba: `docker run -it --name samba -p 139:139 -p 445:445 -v /mnt/sdb1:/mount -d dperson/samba -u "用户;密码;1000" -s "sdb1;/mount/;yes;no;no;all;none"`

bililive-go:`docker run --restart=always -v /mnt/sdb1/bililive-go:/srv/bililive -p 8080:8080 -d  -u 1000 chigusa/bililive-go`

试试看

**Comment by lloyd18** [comment]
> samba: `docker run -it --name samba -p 139:139 -p 445:445 -v /mnt/sdb1:/mount -d dperson/samba -u "用户;密码;1000" -s "sdb1;/mount/;yes;no;no;all;none"`
> 
> bililive-go:`docker run --restart=always -v /mnt/sdb1/bililive-go:/srv/bililive -p 8080:8080 -d -u 1000 chigusa/bililive-go`
> 
> 试试看

谢谢帮助，有点忙，还没试，有空再试，先赞赏你请你喝杯奶茶

**Comment by kira1928** [comment]
@lloyd18 
后来问题解决了吗？

**Comment by kira1928** [comment]
年久失联，issue 先关闭。
