### ISSUE TITLE
最新版docker启动无法在armbian系统下运行

### ISSUE THREAD

**Issue by a554233472** [hr3lxphr6j/bililive-go#158]
0.15以及0.6-RC2正常， 昨天使用最新版 在docker中启动之后无法打开网页控制面板，即使修改配置文件重启后也无法运行，日志显示有检测到开播 但是并不会下载任何文件，系统Armbian-Ubuntu20.04，设备斐讯N1

**Comment by hr3lxphr6j** [comment]
具体哪个版本，设备什么架构

**Comment by a554233472** [comment]
> 具体哪个版本，设备什么架构

最新版 标签latest，设备ARM架构，芯片 晶晨Amlogic S905D Cortex-A53

**Comment by hr3lxphr6j** [comment]
> > 具体哪个版本，设备什么架构
> 
> 最新版 标签latest，设备ARM架构，芯片 晶晨Amlogic S905D Cortex-A53

docker里的配置文件我搞错了。。。，我之后更新下
