### ISSUE TITLE
能否在录制完成后添加转码成mp4的命令呢

### ISSUE THREAD

**Issue by chenlu964** [hr3lxphr6j/bililive-go#159]
如果能用ffmpeg录制，应该也能转码把，最好是转码后删除源文件。就是1.flv录制完成转码成1.MP4后删除1.flv。
转码命令：
ffmpeg -i test.flv -acodec copy -vcodec copy -f mp4 test.mp4

**Comment by hr3lxphr6j** [comment]
[reformat2mp4.sh](https://gist.github.com/hr3lxphr6j/827060b7f0ceedad829da11694dcbccc)
写个cronjob

**Comment by chenlu964** [comment]
感谢

**Comment by chenlu964** [comment]
> [reformat2mp4.sh](https://gist.github.com/hr3lxphr6j/827060b7f0ceedad829da11694dcbccc)
> 写个cronjob

感谢

**Comment by gouku** [comment]
@hr3lxphr6j 如果能提供内置转换就好了，因为我看录制其实也是ffmpeg录制的。我这边有十多台机器通过docker+k8s部署的，每次单独设置crontab在本机装有点麻烦。自己单独跑个crontab的容器感觉也比较浪费资源。。。

**Comment by uyoungco** [comment]
> @hr3lxphr6j 如果能提供内置转换就好了，因为我看录制其实也是ffmpeg录制的。我这边有十多台机器通过docker+k8s部署的，每次单独设置crontab在本机装有点麻烦。自己单独跑个crontab的容器感觉也比较浪费资源。。。

是大佬

**Comment by kira1928** [comment]
v0.6.5 增加了录制结束后自动转换成 `{原视频文件名.flv.mp4}`，和视频转换成功后自动删除原始 flv 文件的配置选项。
```
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
```
