### ISSUE TITLE
最新版无法添加抖音直播间

### ISSUE THREAD

**Issue by chenlu964** [hr3lxphr6j/bililive-go#160]
比如： https://v.douyin.com/emv1NeS/
一直卡在添加直播间，是不是链接格式需要额外设置呢
![QQ截图20210626151538](https://user-images.githubusercontent.com/86452332/123505414-91d21b80-d691-11eb-891c-9ff389430bdc.png)

**Comment by chenlu964** [comment]
已成功解救，https://live.douyin.com/加速主播的抖音Id就是房间号

**Comment by chenlu964** [comment]
https://l

**Comment by JaydenFish** [comment]
怎么close了?我现在就是这种情况.

**Comment by blackedxyz** [comment]
无解了？？

**Comment by kira1928** [comment]
v0.6.5 版本已修复抖音直播录制功能。
不过目前可以接受的 url 格式和 https://v.douyin.com/emv1NeS/ 不太一样。
我用桌面浏览器打开 https://v.douyin.com/emv1NeS/ 时，最后会跳转到 https://live.douyin.com/206475165936 这个 url。用最后落地的这个 url 格式可以在 v0.6.5 里添加抖音直播录制。
