### ISSUE TITLE
有计划实现自动上传功能吗？

### ISSUE THREAD

**Issue by sakurayun** [hr3lxphr6j/bililive-go#162]
比如上传到OneDrive GoogleDrive OSS COS S3之类的？

**Comment by hr3lxphr6j** [comment]
暂时没有，这些东西都是支持FUSE的，直接把输出目录设定到FUSE的挂载目录里就成了
- https://github.com/mk-fg/onedrive-fuse-fs
- https://github.com/astrada/google-drive-ocamlfuse
- https://github.com/aliyun/ossfs
- https://cloud.tencent.com/document/product/436/6883
- https://github.com/s3fs-fuse/s3fs-fuse

**Comment by sakurayun** [comment]
感谢，有空试一下
