### ISSUE TITLE
抖音直播能否支持手机分享的直播间呢

### ISSUE THREAD

**Issue by chenlu96** [hr3lxphr6j/bililive-go#163]
能否和52破解论坛里的python脚本一样 支持录制手机分享的地址呢 大佬
帖子：https://www.52pojie.cn/forum.php?mod=viewthread&tid=1439751&highlight=%B6%B6%D2%F4%D6%B1%B2%A5%C2%BC%D6%C6

他的也是基于ffmpeg的，能直接解析手机分享的直播间连接，因为抖音网页版很多直播没有收录
就是下面这种格式的直播间地址：https://v.douyin.com/ebFBG3m/

**Comment by chenlu96** [comment]
甚至有可以实时预览的封装exe：https://www.52pojie.cn/forum.php?mod=viewthread&tid=1468046&highlight=%B6%B6%D2%F4%D6%B1%B2%A5%C2%BC%D6%C6
![54545](https://user-images.githubusercontent.com/54001481/124371964-52bb5000-dcb9-11eb-929c-ff5bdf0b6f7e.png)

**Comment by sehczaa** [comment]
> 甚至有可以实时预览的封装exe：https://www.52pojie.cn/forum.php?mod=viewthread&tid=1468046&highlight=%B6%B6%D2%F4%D6%B1%B2%A5%C2%BC%D6%C6 ![54545](https://user-images.githubusercontent.com/54001481/124371964-52bb5000-dcb9-11eb-929c-ff5bdf0b6f7e.png)

你也是浙江丽水的吗

**Comment by chenlu964** [comment]
> > [甚至可以实时预览的包： https](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1468046&highlight=%B6%B6%D2%F4%D6%B1%B2%A5%C2%BC%D6%C6) ://forum.php?mod=viewthread.& highid =1468046&%D6%B6%D2%F4%C2%B1%B2%A5%C2%BC% [D6%C6](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1468046&highlight=%B6%B6%D2%F4%D6%B1%B2%A5%C2%BC%D6%C6) ![54545](https://user-images.githubusercontent.com/54001481/124371964-52bb5000-dcb9-11eb-929c-ff5bdf0b6f7e.png)
> 
> 你也是浙江丽水的吗

哈哈被抓到了，现在可以用biliup录制抖音哦

**Comment by sehczaa** [comment]
> > > [甚至可以实时预览的包： https](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1468046&highlight=%B6%B6%D2%F4%D6%B1%B2%A5%C2%BC%D6%C6) ://forum.php?mod=viewthread.& highid =1468046&%D6%B6%D2%F4%C2%B1%B2%A5%C2%BC% [D6%C6](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1468046&highlight=%B6%B6%D2%F4%D6%B1%B2%A5%C2%BC%D6%C6) ![54545](https://user-images.githubusercontent.com/54001481/124371964-52bb5000-dcb9-11eb-929c-ff5bdf0b6f7e.png)
> > 
> > 
> > 你也是浙江丽水的吗
> 
> 哈哈被抓到了，现在可以用biliup录制抖音哦

biliup是个啥

**Comment by kira1928** [comment]
原来如此，https://github.com/hr3lxphr6j/bililive-go/issues/160 这里发的是手机分享的格式啊。。
那应该可以支持。不过支持这个需要改造比较底层部分的代码，需要花一些时间。

**Comment by kira1928** [comment]
查了一下，这个手机分享页面用了很强势的加密方法，目前 github 上还没有同类工具能在不上 Selenium  之类浏览器模拟器的前提下解析手机的分享链接到直播页面的。
我觉得这个项目主要侧重于让那些已经有录制方法的直播间可以手动设置简单录制，而不是攻克被高强度加密的直播网站，所以目前不打算支持手机的分享格式。
如果有其他开源项目实现了对这个格式的支持，我们可以参考他们的视线方式补充支持。
