### ISSUE TITLE
twitch为啥在docker上添加不了，不是复制直播间网址输入进去点ok就行了吗

### ISSUE THREAD

**Issue by kkhwg** [hr3lxphr6j/bililive-go#172]

**Comment by hr3lxphr6j** [comment]
- 使用的版本？
- 直播间url？
- 日志？
-

**Comment by kkhwg** [comment]
版本就是一分钟前刚装好的6.20
直播间网址格式：https://www.twitch.tv/xxxxx
日志在哪里看呀老哥？

**Comment by hr3lxphr6j** [comment]
> 版本就是一分钟前刚装好的0.62
> 直播间网址格式：https://www.twitch.tv/xxxxx
> 日志在哪里看呀老哥？

https://docs.docker.com/engine/reference/commandline/logs/

**Comment by kkhwg** [comment]
我是看B站这位老哥的小白教程装的，然后发现录不了twith平台的主播。
【【教程】直播录制软件：bililive-go的使用方法-哔哩哔哩】https://b23.tv/tXZ53X

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/130355318-f15dcdd0-bd77-42d6-b74e-487750ca5b20.png)
!image](https://user-images.githubusercontent.com/12208550/130355325-4d98cc28-9de8-4ee2-be6f-583a0b095a81.png)
我这里没问题，需要你提供log，做进一步排查，可以先检查下是不是科学上网相关的问题，和输出目录的权限问题

**Comment by kkhwg** [comment]
斗鱼可以录，但是twitch不行是科学上网的问题吗？

**Comment by hr3lxphr6j** [comment]
> 斗鱼可以录，但是twitch不行是科学上网的问题吗？

看起来应该是的，如果你用的是SS或者V2ray这种代理的话bgo不会识别
