### ISSUE TITLE
关于6.3版本在docker端，页面显示内容。

### ISSUE THREAD

**Issue by KSOYU** [hr3lxphr6j/bililive-go#177]
6.2版本拥有直播间名称和直播间链接。
而在新版的6.3中虽然适配了页面，但是并没有直播间名称和链接。

**Comment by hr3lxphr6j** [comment]
截个图看看

**Comment by KSOYU** [comment]
![Screenshot_2021-09-18-12-23-25-367_com android browser](https://user-images.githubusercontent.com/77818832/133872312-05399865-d649-4ec1-ac70-b853fc9c6eb2.jpg)
你看他中间有直播间的名字，还有他可以点进去的链接。0.6.3版本没有。

**Comment by hr3lxphr6j** [comment]
> ![Screenshot_2021-09-18-12-23-25-367_com android browser](https://user-images.githubusercontent.com/77818832/133872312-05399865-d649-4ec1-ac70-b853fc9c6eb2.jpg)
> 你看他中间有直播间的名字，还有他可以点进去的链接。0.6.3版本没有。

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/12208550/133872389-7d9ae276-a72f-4d28-bcd7-675aa37feefe.png">
<img width="988" alt="image" src="https://user-images.githubusercontent.com/12208550/133872394-5747cc38-e1a8-40f3-8b04-c0c679328f70.png">

**Comment by KSOYU** [comment]
我去试了一下，我发现你竖屏进去页面的时候是看不到，
![Screenshot_2021-09-18-13-17-39-419_com android browser](https://user-images.githubusercontent.com/77818832/133873714-ac377038-bb13-4783-aa18-89aaf88eb717.jpg)
，当你横屏进入这个页面的时候是可以看到的，然后再切换到竖屏的时候也是能看到的。
![Screenshot_2021-09-18-13-20-39-691_com android browser](https://user-images.githubusercontent.com/77818832/133873733-1df09a52-7ff2-4fc7-ae1f-11693106f84b.jpg)
![Screenshot_2021-09-18-13-20-45-859_com android browser](https://user-images.githubusercontent.com/77818832/133873736-711fd5e1-5068-42b0-9fea-5ad57b53ff9f.jpg)
，确实是我不太会用新版本。打扰了。

**Comment by KSOYU** [comment]
抱歉了，打扰了，谢谢作者教վ'ᴗ' ի

**Comment by KSOYU** [comment]
大佬你也看海子姐。溜了溜了。

**Comment by hr3lxphr6j** [comment]
> 我去试了一下，我发现你竖屏进去页面的时候是看不到，
> ![Screenshot_2021-09-18-13-17-39-419_com android browser](https://user-images.githubusercontent.com/77818832/133873714-ac377038-bb13-4783-aa18-89aaf88eb717.jpg)
> ，当你横屏进入这个页面的时候是可以看到的，然后再切换到竖屏的时候也是能看到的。
> ![Screenshot_2021-09-18-13-20-39-691_com android browser](https://user-images.githubusercontent.com/77818832/133873733-1df09a52-7ff2-4fc7-ae1f-11693106f84b.jpg)
> ![Screenshot_2021-09-18-13-20-45-859_com android browser](https://user-images.githubusercontent.com/77818832/133873736-711fd5e1-5068-42b0-9fea-5ad57b53ff9f.jpg)
> ，确实是我不太会用新版本。打扰了。

@BJ4501 你看下，前段的问题

**Comment by BJ4501** [comment]
简化竖屏内容显示的时候有点欠考虑，我后面修复一下。
