### ISSUE TITLE
web面板访问问题

### ISSUE THREAD

**Issue by isleon** [hr3lxphr6j/bililive-go#180]
平台：Windows
版本：0.6.3

第一种情况，设置如下，本地能通过127.0.0.1:8080访问，但局域网内不能通过192.168.1.X:8080 访问
>rpc:
>  enable: true
>  bind: 127.0.0.1:8080

第二种情况，设置如下，本地不能通过127.0.0.1:8080，只能通过192.168.1.X:8080访问，局域网内能通过192.168.1.X:8080 访问
>rpc:
>  enable: true
>  bind: 192.168.1.X:8080

第三种情况，设置如下，本地能访问，局域网内能通过192.168.1.X:8080 访问
>rpc:
>  enable: true
>  bind: :8080

但是以上三种设置均不能通过nginx的proxy_pass转发，本地可以访问但通过proxy_pass却不行。
部署的其他服务都没有这种情况，感觉有点奇怪，且试过放到windows的VPS，设置127.0.0.1:8080，防火墙端口放行，也不能通过公网IP:8080的形式访问。

**Comment by hr3lxphr6j** [comment]
1. bind `127.0.0.1:8080` 绑定的是`localhost`网卡，也就是只能在本机访问，这是预期内的
2. bind `192.168.1.X:8080` 绑定的是局域网的网卡，也就是只能在局域网访问，这是预期内的
3. bind `:8080`会绑定所有网卡，任何网络均可以访问，这是预期内的

以上部分如果有其它疑问，可以翻socket相关的文。

反代的问题优先检查nginx配置、防火墙和网络等问题。
毕竟我自己用bgo一直在通过traefik反代，这部分不会有问题。

**Comment by ldsoy** [comment]
我这有同样的问题，使用Docker部署的

**Comment by ldsoy** [comment]
现在把地址改成192.168.2.1:8080,我在局域网下面板正常打开了
