### ISSUE TITLE
CC直播 能否加入录制密码房功能  绕过切频道直接获取源

### ISSUE THREAD

**Issue by lbcake** [hr3lxphr6j/bililive-go#189]
有的主播做活动 要去包厢   去到其他子频道（主页显示下播  实际在直播）   能否也加入获取源并录制

**Comment by kira1928** [comment]
不太了解包厢的概念。能给一个会使用到这个功能的主播和他使用这个功能的大概时间段吗？

**Comment by kira1928** [comment]
年久失联，issue 先关闭。
