### ISSUE TITLE
win11 无法启动

### ISSUE THREAD

**Issue by sosohungry** [hr3lxphr6j/bililive-go#197]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kira1928** [comment]
无法启动具体是怎么启动的？启动后有什么错误信息吗？

**Comment by kira1928** [comment]
年久失联，issue 先关闭。
