### ISSUE TITLE
douyin 不滋磁了哇

### ISSUE THREAD

**Issue by sosohungry** [hr3lxphr6j/bililive-go#198]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blackedxyz** [comment]
我也添加不了

**Comment by kira1928** [comment]
v0.6.5 版本已修复抖音直播录制功能。
