### ISSUE TITLE
这个软件怎么打开，小白一脸懵逼，用什么打开

### ISSUE THREAD

**Issue by xiaozhi126** [hr3lxphr6j/bililive-go#199]
**描述bug**a清楚而简明地描述bug是什么。N，n，*，n，*，去“.”N2。点击“.”N3。向下滚动至“.”N4。请参阅错误n**预期的行为**NA对您期望发生的事情的清晰而简明的描述。Nn**屏幕截图**nif适用，添加截图，以帮助解释您的问题。N n**桌面(请填写以下信息)：**n-OS：[例如IOS]n-Browser[例如铬，Safari]n-版本[例如22]n**智能手机(请填写以下信息)：**n-设备：[例如iPhone6]n-OS：[例如iOS8.1]n-Browser[例如股票浏览器，Safari]n-版本[例如22]n**附加上下文**n添加有关此问题的任何其他上下文。

**Comment by hr3lxphr6j** [comment]
https://github.com/hr3lxphr6j/bililive-go/wiki
