### ISSUE TITLE
请问能不能添加一个通过代理访问的功能

### ISSUE THREAD

**Issue by inkforest** [hr3lxphr6j/bililive-go#20]
RT，因为国内看twitch需要挂代理...
试了一下挂加速器 自己访问twitch看直播没问题 但是使用工具就无法录制

time="2019-05-18 00:31:06" level=info msg="BiliLive-go Version: 0.3.3 Link Start"
time="2019-05-18 00:31:27" level=error msg="room not exists" url="https://www.twitch.tv/godjj"
time="2019-05-18 00:31:27" level=info msg="ListenerManager Start"
time="2019-05-18 00:31:27" level=info msg="RecorderManager Start"
time="2019-05-18 00:31:27" level=info msg="Bye~"

**Comment by hr3lxphr6j** [comment]
https://github.com/hmgle/graftcp

**Comment by wwng2333** [comment]
https://github.com/rofl0r/proxychains-ng

**Comment by hr3lxphr6j** [comment]
> https://github.com/rofl0r/proxychains-ng

proxychains-ng对go没有用
