### ISSUE TITLE
请教问题 老想用这个软件了 实在不会打开程序 教程在哪 看不到 

### ISSUE THREAD

**Issue by xiaozhi126** [hr3lxphr6j/bililive-go#200]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hr3lxphr6j** [comment]
看wiki https://github.com/hr3lxphr6j/bililive-go/wiki
