### ISSUE TITLE
是否支持对bilibili直播录制的画质选择功能？

### ISSUE THREAD

**Issue by AstralMolaMola** [hr3lxphr6j/bililive-go#203]
在最近对bilibili直播的录制中出现了原画录制跳帧问题，同时自己看直播切换原画也会卡顿，但蓝光看直播并无卡顿。
想问是否有办法设置录制蓝光画质的直播录像？

**Comment by kira1928** [comment]
在网页端增加为房间选择画质的功能已经被提上日程了，预计在[这个里程碑](https://github.com/hr3lxphr6j/bililive-go/milestone/4)中完成。

**Comment by kira1928** [comment]
已在 https://github.com/hr3lxphr6j/bililive-go/pull/428 中实现。
