### ISSUE TITLE
douyu无法识别开播状态

### ISSUE THREAD

**Issue by buzhixihuan2021** [hr3lxphr6j/bililive-go#207]
当有人在此频道直播时，无法录制（实际是开播的）。
https://www.douyu.com/topic/channel11

一定要在这个频道直播时，添加当前正在直播的主播。
他会直接跳转Redirect 到其他直播间，但不是这个正在直播的直播间，导致get_response到其他直播间了。

**Comment by kira1928** [comment]
这个douyu.com/topic 页面下的内容格式各异，直接录制这个 url 不太可能。
毕竟连 https://www.douyu.com/topic/douyuZGT 这种里面完全不是直播内容的 topic 都可能存在。
建议直接录制具体的主播的直播间。。
