### ISSUE TITLE
老大能做一个最新版本的docker镜像嘛

### ISSUE THREAD

**Issue by johnnywongxy** [hr3lxphr6j/bililive-go#210]
[能做这个版本的docker镜像嘛？v0.6.4-rc.2](https://github.com/hr3lxphr6j/bililive-go/releases/tag/v0.6.4-rc.2)

**Comment by hr3lxphr6j** [comment]
> [能做这个版本的docker镜像嘛？v0.6.4-rc.2](https://github.com/hr3lxphr6j/bililive-go/releases/tag/v0.6.4-rc.2)

https://hub.docker.com/layers/192093601/chigusa/bililive-go/v0.6.4-rc.2/images/sha256-249e7e60bf54b3c11e343a097ba81b2368fa193fadf76a8321c350607b23d9bc?context=repo
