### ISSUE TITLE
抖音直播现在支持获取全部直播了，希望大佬更新

### ISSUE THREAD

**Issue by chenlu964** [hr3lxphr6j/bililive-go#211]
现在手机直播的内容也在网页能直接获取了，希望大佬更新一波。
例子：https://www.douyin.com/user/MS4wLjABAAAAjYUMtQOPa3gKziXUDteiCCHPEsMK8XFix910BmAoASI
用户主页，如果直播会显示直播中，然后就能进入直播间了

**Comment by kira1928** [comment]
v0.6.5 版本已修复抖音直播录制功能。
不过目前可以接受的是 `https://live.douyin.com/数字 ` 这个格式的 url。
