### ISSUE TITLE
大佬 运行时提示这个怎么解决呢 需要重装系统吗？（**程序“bililive-go.exe”无法运行: 指定的可执行文件不是此操作系统平台的有效应用程 序。所在位置 行:1 字符: 1）

### ISSUE THREAD

**Issue by wxwlyy** [hr3lxphr6j/bililive-go#213]
PS F:\bililive-go> bililive-go -c ./config.yml
**程序“bililive-go.exe”无法运行: 指定的可执行文件不是此操作系统平台的有效应用程
序。所在位置 行:1 字符: 1
+ bililive-go -c ./config.yml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~。
所在位置 行:1 字符: 1
+ bililive-go -c ./config.yml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedEx
   ception
    + FullyQualifiedErrorId : NativeCommandFailed**

**Comment by hr3lxphr6j** [comment]
使用的版本不对吧，用这个试试[bililive-windows-amd64.zip](https://github.com/hr3lxphr6j/bililive-go/releases/download/v0.6.3/bililive-windows-amd64.zip)

**Comment by wxwlyy** [comment]
用的就是这个版本的  第一次可以正常运行  然后重启了一下电脑 就一直这样了  删除重装好几次了 也没好 在其他电脑上装可以正常运行  我这不会要重新系统吧  哈哈哈

**Comment by kira1928** [comment]
这个错误似乎和程序无关，而是 windows 方面的问题。
或许是[权限问题](https://answers.microsoft.com/zh-hans/windows/forum/all/%E4%B8%8D%E5%B0%8F%E5%BF%83%E7%94%A8%E4%BA%86/60f63371-74bc-4203-bdf8-37c035a723cc)，或许是[真的需要重装windows](https://github.com/microsoft/winget-cli/issues/1125#issuecomment-862045693)，或许[毫无头绪](https://www.zhihu.com/question/373329532)。
总之，不是这个项目可以为你解决的。因此关闭此 issue。
