### ISSUE TITLE
mips架构无法运行在openwrt

### ISSUE THREAD

**Issue by qy116427** [hr3lxphr6j/bililive-go#214]
bililive-linux-mips 无法在 mips架构openwrt运行
![屏幕截图 2022-05-26 160809](https://user-images.githubusercontent.com/105727714/170446337-ad85b325-d543-49de-9f99-822084ef83d8.png)

**Comment by wc7086** [comment]
https://blog.csdn.net/fuyuande/article/details/86496058

**Comment by kira1928** [comment]
@qy116427 
按照 @wc7086 上面的方法，我编译了一个 softfloat 版本的 mips 的可执行文件。
[bililive-linux-mips-softfloat.zip](https://github.com/hr3lxphr6j/bililive-go/files/10337132/bililive-linux-mips-softfloat.zip)
你可以试一下这个能不能用吗？
如果可以，我就修改一下编译脚本，以后发行版本的时候都加上 mips 的 softfloat 版的可执行文件。

**Comment by kira1928** [comment]
已在最新 release 中添加了 mips-softfloat 的可执行文件。
