### ISSUE TITLE
yaml: line 13: block sequence entries are not allowed in this context

### ISSUE THREAD

**Issue by jacksparrowFF2** [hr3lxphr6j/bililive-go#22]
不知道为什么会出先这个问题，附yml文件

`rpc:
  enable: true
  port: 127.0.0.1:8080
  token: ""
  tls:
    enable: false
    cert_file: ""
    key_file: ""
debug: false
interval: 15
out_put_path: F:\funvideo\videoforlearn
feature:
  use_native_flv_parser: false
live_rooms: - https://live.bilibili.com/11057497
`

**Comment by hr3lxphr6j** [comment]
https://en.wikipedia.org/wiki/YAML

**Comment by jacksparrowFF2** [comment]
找到问题所在了，`live_rooms`的键值应该在下一行
