### ISSUE TITLE
抖音的直播均无法获取到RENDER_DATA，无法录制

### ISSUE THREAD

**Issue by marvinssky** [hr3lxphr6j/bililive-go#221]
抖音的直播均无法获取到RENDER_DATA，提示
![image](https://user-images.githubusercontent.com/37216223/173826940-eb7a0814-f777-4f31-8b5f-a5abd58992b7.png)，无法录制；麻烦看下是否有其他问题

**Comment by kira1928** [comment]
v0.6.5 版本已修复抖音直播录制功能。
