### ISSUE TITLE
抖音手机端分享的链接和网页端的地址都无法导入诶

### ISSUE THREAD

**Issue by sehczaa** [hr3lxphr6j/bililive-go#222]
![image](https://user-images.githubusercontent.com/92673198/176434748-03b2bf7e-16ad-4e35-bcf0-268110cb0e11.png)
我使用的是群晖docker版的，希望大佬能解决一下

**Comment by sehczaa** [comment]
顺便再请教一下这几个参数分别是设置哪些东西的，应该如何设置
![image](https://user-images.githubusercontent.com/92673198/176471063-59392257-b0bf-4a00-a4f6-c2e2532adf12.png)

**Comment by kira1928** [comment]
v0.6.5 版本已修复抖音直播录制功能。
