### ISSUE TITLE
虎牙录制出现问题都是这一个问题，什么都录制不到

### ISSUE THREAD

**Issue by menheng** [hr3lxphr6j/bililive-go#225]
![QQ图片20220718173549](https://user-images.githubusercontent.com/109516293/179484476-7ce75fa7-84d0-45f2-acf9-5882548ba209.png)

**Comment by jieli1990** [comment]
确实，虎牙的全都不能录制了，好像虎牙的规则改了

**Comment by TheUnknownSoldier** [comment]
原来都遇到了虎牙不能录的问题了，我还以为我自己的问题呢

**Comment by jdnxn** [comment]
也不是全不行   想这种https://www.huya.com/lpl    房间号是字母的就可以   而后面像这种https://www.huya.com/688 是房间号的不行

**Comment by jieli1990** [comment]
在源码中这一段：
var hyPlayerConfig = {
--
  | html5: 1,
  | WEBYYSWF: 'jsscene',
  | vappid: 10057,
  | stream: {"data":这里的内容就包含视频解析信息，但是具体的格式怎么解析，还希望各位大神了

**Comment by charon627** [comment]
临时修复了虎牙纯数字直播间的检测，自编译要的下面度盘链接自取
/s/1UZwizKBnHmRpIpiG5NQWWg m9mg

**Comment by menheng** [comment]
> 临时修复了虎牙纯数字直播间的检测，自编译要的下面的度盘链接自取 /s/1UZwizKBnHmRpIpiG5NQWWg m9mg

谢谢大佬

**Comment by 0cod** [comment]
老哥，0 code 非码人员也遇到了这个问题，把那个压缩包下下来之后怎么操作呢，方便的话麻烦指导一下。

**Comment by kira1928** [comment]
[这个](https://github.com/hr3lxphr6j/bililive-go/pull/231) pr 修复了上述问题。
现在使用最新版应该可以解决这个问题了。
