### ISSUE TITLE
0.6.4的windows版本不能检测到ffmpeg

### ISSUE THREAD

**Issue by oahiewuoil** [hr3lxphr6j/bililive-go#235]
ffmpeg放在根目录会提示ffmpeg binary not found

**Comment by dakzim** [comment]
ffmpeg 解压后添加 bin 目录到系统 PATH，bililive-windows-amd64 解压就能直接用了。

**Comment by 212884177** [comment]
你怎么解决的

**Comment by oahiewuoil** [comment]
> 你怎么解决的

用他编译的版本https://github.com/hr3lxphr6j/bililive-go/issues/225#issuecomment-1193047656

**Comment by jellycooker** [comment]
把 ffmpeg 加入环境变量

**Comment by hibiki222** [comment]
> 把 ffmpeg 加入环境变量

加了也没用啊 新版本换了几个ffmepg 都识别不了 环境变量设了无数遍
