### ISSUE TITLE
能否添加猫耳FM跟克拉克拉两个声音直播平台

### ISSUE THREAD

**Issue by jjaaaxx** [hr3lxphr6j/bililive-go#236]
辛苦大大~~

**Comment by kira1928** [comment]
目前现有的支持的网站中有些已经失效了。应该会优先修复那些相关issue之后再考虑新增支持的网站了。

**Comment by kira1928** [comment]
猫耳平台已于 https://github.com/hr3lxphr6j/bililive-go/pull/362 实现。
将被包含进下个版本 (0.7.4) 中。
也可以自己编译最新的 master branch 来提前使用最新功能~

**Comment by kira1928** [comment]
忘记关了。上述网站现在已经全部支持啦！
