### ISSUE TITLE
我是群晖版的但是打不开监控界面

### ISSUE THREAD

**Issue by ntd612** [hr3lxphr6j/bililive-go#237]
录播可以正常录但是打不开监控界面

**Comment by xiaobaozi233** [comment]
你是不是映射了其他端口，我映射了就无法访问了

**Comment by kira1928** [comment]
@ntd612 可以看一下你群晖的 docker 面板里 bililive-go 的容器的详细设置吗？
主要是在总览面板下的端口设置那里。

比如我的设置是映射到 10001 端口，监控界面就是访问 http://群晖的ip:10001/
![chrome_fbT9DUqaLn](https://user-images.githubusercontent.com/2352900/210226642-cf3aae11-f4cc-4b10-89fa-f40b64f5083a.png)

**Comment by ntd612** [comment]
> 

已经可以打开监控页面了，谢谢

**Comment by ntd612** [comment]
@kira1928  谢谢已经可以打开了
