### ISSUE TITLE
哔哩哔哩直播在主播pk对战的时候录出花屏

### ISSUE THREAD

**Issue by a1037674173** [hr3lxphr6j/bililive-go#238]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kira1928** [comment]
听说在配置文件里启用 use_native_flv_parser 的话可以解决 pk 时的各种录制问题。
但是 use_native_flv_parser 也有 use_native_flv_parser 的问题，你可以在 issue 里搜搜看。

**Comment by wc7086** [comment]
https://github.com/hr3lxphr6j/bililive-go/issues/191

**Comment by kira1928** [comment]
楼主失联，issue 关闭。
