### ISSUE TITLE
ffmpeg binary not found

### ISSUE THREAD

**Issue by 212884177** [hr3lxphr6j/bililive-go#239]
ffmpeg binary not found
一直识别不了

**Comment by chiwugy** [comment]
需要把ffmpeg的路径加入环境变量

**Comment by hibiki222** [comment]
> 需要把ffmpeg的路径加入环境变量
![2022-09-24_045658_看图王](https://user-images.githubusercontent.com/114181056/192057255-9d321800-8838-42a0-8055-47f80924b84b.png)

加了也没用

**Comment by hibiki222** [comment]
已经试过各种版本ffmepg 没啥用 环境变量换了几个也没啥用
