### ISSUE TITLE
什么时候修复无法添加抖音录制BUG

### ISSUE THREAD

**Issue by yyy1314** [hr3lxphr6j/bililive-go#242]
抖音直播无法添加录制

**Comment by nixingshiguang** [comment]
貌似现在还不能添加吧抖音，我今天刚装好也添加不了

**Comment by jun9100** [comment]
我也期待能录制抖音

**Comment by kira1928** [comment]
修复抖音的 pr 已经 merge 进 master，等下一个 release 出了应该就可以添加抖音平台了。（如果我顺利搞清楚怎么创建新的 release 的话。。）

**Comment by kira1928** [comment]
v0.6.5 版本已修复抖音直播录制功能。
