### ISSUE TITLE
新版本的无论怎么弄环境变量 都是显示ffmpeg binary not found

### ISSUE THREAD

**Issue by hibiki222** [hr3lxphr6j/bililive-go#248]
ffmepg版本也换了几个

**Comment by hibiki222** [comment]
无论怎么设置ffmpeg都是显示这个 怎么都用了 真的绝望了 遇到的问题有点多

**Comment by hibiki222** [comment]
![2022-09-24_045658_看图王](https://user-images.githubusercontent.com/114181056/192055407-0709f029-2db7-4b03-9e83-57df987afcb8.png)
都这样都用不了

**Comment by hibiki222** [comment]
下的版本也没错 真的就是启动不了

**Comment by snowdream1985** [comment]
ffmpeg.exe放入c:\windows\system32目录, 当前目录不要放

**Comment by kira1928** [comment]
@JaydenFish 
在这边统一回复，问题从 0.6.4 开始出现，到 0.6.5 为止全部版本都受到了影响。
现象是之前放在 exe 同目录里可以被检测到的 ffmpeg 文件在新版本中无法被检测到。
问题代码出在 [这里](https://github.com/hr3lxphr6j/bililive-go/commit/e4edab4ae6960d266da1734835f57a66edeb05a8#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR14)。
原因是这里升级了 golang 版本到 1.19，在这个版本中，golang [修改了](https://tip.golang.org/doc/go1.19#os-exec-path)从系统目录中查找特定程序是否存在的函数 exec.LookPath() 函数的效果。出于安全考虑，从 1.19 版开始，这个函数默认不再检查当前目录。
修复方法很简单，只要手动增加一次检测当前目录中是否存在 ffmpeg 就可以了。目前修改代码部分我已经完成了，但卡在编译 windows 版 exe 文件在本地测试这一步。。
我对这个项目的这些基础设施还不熟悉，以后在这方面花费的时间应该会大幅减少。这次就算是我交学费了，各位也稍微等我一下吧。

**Comment by kira1928** [comment]
ffmpeg 无法找到问题已在 0.6.6 版本中修复！

**Comment by JaydenFish** [comment]
> ffmpeg 无法找到的问题已在 0.6.6 版本中修复！

我的还是找不到ffmpeg.exe啊. 是0.6.6的版本.

**Comment by JaydenFish** [comment]
> > ffmpeg 无法找到的问题已在 0.6.6 版本中修复！
> 
> 我的还是找不到ffmpeg.exe啊. 是0.6.6的版本.

我知道了, 要把`.exe`去掉.

**Comment by kira1928** [comment]
呃，尴尬。。
这个问题在下个版本修复，现在暂时靠去掉exe凑合一下吧。。

**Comment by kira1928** [comment]
@JaydenFish 
啊这，我试了 powershell 和普通 cmd，用 0.6.6 真的都可以识别到了啊。。
![WindowsTerminal_Gx2JYW6116](https://user-images.githubusercontent.com/2352900/210472631-94a59f99-8296-49f7-bad6-f69989a4fb90.png)

**Comment by kira1928** [comment]
@JaydenFish 
再确认一下，你是在 exe 目录内执行的 `.\bililive-windows-amd64.exe`，还是在外部目录执行比如 `bin\bililive-windows-amd64.exe` 这样的呢？
如果从外部目录执行也会找不到 ffmpeg

**Comment by kira1928** [comment]
@JaydenFish 
再确认一下，你是在 exe 目录内执行的 `.\bililive-windows-amd64.exe`，还是在外部目录执行比如 `bin\bililive-windows-amd64.exe` 这样的呢？
如果从外部目录执行也会找不到 ffmpeg

**Comment by JaydenFish** [comment]
在 exe 目录内执行的 .\bililive-windows-amd64.exe

**Comment by kira1928** [comment]
你去掉 ffmpeg.exe 的 .exe 以后问题解决了吗？

**Comment by kira1928** [comment]
如果你允许的话，我想在你方便的时候远程看一下你那边是什么情况。
我这边已经无法重现这个故障了，没有可重现的环境，目前没什么修复的头绪了。。

**Comment by JaydenFish** [comment]
> 如果你允许的话，我想在你方便的时候远程看一下你那边是什么情况。 我这边已经无法重现这个故障了，没有可重现的环境，目前没什么修复的头绪了。。

加一下我QQ 3635 95575
