### ISSUE TITLE
最近录制的上传到b站显示转码失败 不知道有没有和我一样 而且还莫名其妙分段

### ISSUE THREAD

**Issue by longjiank** [hr3lxphr6j/bililive-go#249]
首先还是谢谢作者 但这么多提交了 请问能不能更新下

**Comment by LimitBreaker01** [comment]
显示转码失败

**Comment by LimitBreaker01** [comment]
显示转码失败

**Comment by LimitBreaker01** [comment]
原因：该视频文件超过32G，建议剪辑为多个稿件上传。 请检查视频文件是否可以正常播放后再重新上传视频后再进行投稿。该视频时长超过10小时，请剪辑后通过分P上传。就两个原因，自己可以看b站消息提示。
