### ISSUE TITLE
当添加房间的数目大于128条后，监听网站页面就会变成空白（显示为NO Data）

### ISSUE THREAD

**Issue by alaaflu** [hr3lxphr6j/bililive-go#251]
大佬您好！非常感谢你开发了bililive-go这个直播录制工具，目前我在使用过程中发现当添加房间的数目大于128条后，监听网站页面就会变成空白（显示为NO Data），不会在显示添加的房间条目，非常期待大佬您在有精力的情况下可以修复下这个BUG，万分感谢您！

**Comment by kira1928** [comment]
看起来是 Duplicate of #100 了。
这个未来应该可以通过扩大上限数量来解决。
