### ISSUE TITLE
求大佬支持一下抖音平台

### ISSUE THREAD

**Issue by a1037674173** [hr3lxphr6j/bililive-go#253]
求大佬支持一下抖音平台

**Comment by kira1928** [comment]
修复抖音的 pr 已经 merge 进 master，等下一个 release 出了应该就可以添加抖音平台了。（如果我顺利搞清楚怎么创建新的 release 的话。。）

**Comment by kira1928** [comment]
Duplicate of #242

**Comment by kira1928** [comment]
v0.6.5 版本已修复抖音直播录制功能。
