### ISSUE TITLE
能不能添加自动投稿功能

### ISSUE THREAD

**Issue by SouLXH** [hr3lxphr6j/bililive-go#254]
如题 自动投稿b站

**Comment by LimitBreaker01** [comment]
https://github.com/ForgQi/bilibiliupload    支持自动录制各大直播平台，上传直播录像到bilibili

**Comment by kira1928** [comment]
自动投稿和这个项目的目标区别有点大。
现在有好几个比较主流且成熟的b站自动投稿工具，可以试试那边。
