### ISSUE TITLE
斗鱼录制，一直分段，很难受，不能自动合并

### ISSUE THREAD

**Issue by LimitBreaker01** [hr3lxphr6j/bililive-go#256]
主播地址：https://www.douyu.com/5415816
已经录制分段了651视频了，这还是一个月的分量。需要自己后期ffmpeg合并，很麻烦，有好点的 建议吗？
<img width="625" alt="2022-10-13_103524" src="https://user-images.githubusercontent.com/65392605/195491167-986755e3-47a9-4a6d-8cbe-f00164afada3.png">

**Comment by kira1928** [comment]
Duplicated of #241
