### ISSUE TITLE
花椒直播无发录制

### ISSUE THREAD

**Issue by jinchunyou** [hr3lxphr6j/bililive-go#261]
添加花椒直播之后系统并未出现监控名单，例如https://www.huajiao.com/l/336208905，所以也无法录制，麻烦有空的话看一下，谢谢

**Comment by kira1928** [comment]
这个直播 https://www.huajiao.com/l/336208905 似乎不存在，或者已经无法访问了。
我试了其他类似格式的直播间，比如 https://www.huajiao.com/l/337351335 ，确实无法添加。但改成这个直播间的用户首页的 url https://www.huajiao.com/user/261927574 的话就可以添加了。
我试了一下，也可以支持 `域名/l/数字` 的格式，但这可能导致同一个直播间被用两种不同 url 添加两次，这会引入一些未知问题，比如开播后被以相同文件名重复录制。
看代码似乎现有结构不太好实现让指向同一直播的不同 url 被识别为重复添加。想增加这个功能需要动一些现有代码的底层设计，比如[这里](https://github.com/hr3lxphr6j/bililive-go/blob/6717c91251b2b2b25d81b0ee5651b598c817e103/src/live/internal/base_live.go#L19-L29)的 liveId 如果能在各个网站的具体实现代码内部自己决定就好了。
总之这一块需要跟 @hr3lxphr6j 联系上以后商量一下再决定。

话说，[据说](https://github.com/hr3lxphr6j/bililive-go/issues/281)作者目前联系不上了，我有点担心。。

**Comment by kira1928** [comment]
https://github.com/hr3lxphr6j/bililive-go/issues/163 这个 issue 好像也是涉及从不同 url 添加相同直播间的问题。

**Comment by jinchunyou** [comment]
感谢，按您说的已解决，希望能联系上作者，让项目持续下去

**Comment by kira1928** [comment]
解决了就好^_^
如果没有其他问题的话，你那边可以把 issue 关闭吗？我没有这个权限。
