### ISSUE TITLE
centos无法录制生成回放

### ISSUE THREAD

**Issue by youxiage** [hr3lxphr6j/bililive-go#263]
有没有大佬帮忙看看是啥情况，之前用mac都是可以生成的。现在不管是编译运行还是下载release的二进制包都无法录制生成文件
[root@centos bin]# ./bililive-linux-amd64  -i https://live.bilibili.com/23197314
time="2022-10-26 21:09:49" level=info msg="BiliLive-go Version: v0.6.4-1-g6717c91 Link Start"
time="2022-10-26 21:09:50" level=info msg="Live Start" host="飞天狙想要努力变胖" room="18点训练赛"
time="2022-10-26 21:09:50" level=info msg="Record Start" host="飞天狙想要努力变胖" room="18点训练赛"

^Ctime="2022-10-26 21:12:39" level=info msg="Record End" host="飞天狙想要努力变胖" room="18点训练赛"
time="2022-10-26 21:12:39" level=info msg="Bye~"
[root@centos bin]# ll 哔哩哔哩/飞天狙想要努力变胖/
总用量 0
[root@centos bin]#

下面这个是系统信息
[root@centos bin]# cat /proc/version
Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020
[root@centos bin]# uname -a
Linux centos 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kira1928** [comment]
录其他直播也没有生成回放文件吗？
我试了一下其他 b 站直播间 （这个 https://live.bilibili.com/22943211），在我的 docker  环境里用网页管理界面添加后是可以正常录制生成文件的。

另外有一点就是这个 bin 目录的访问权限有没有问题？
可以 ls -l 看一下吗？
我看默认输出目录是当前目录，有没有可能目录没有写权限？

个人环境不好调试，要不要换用 docker 试试？

**Comment by wc7086** [comment]
先检查一下 ffmpeg 能否正常录制

**Comment by kira1928** [comment]
年久失联，issue 先关闭。
