### ISSUE TITLE
输入斗鱼URL无法录制一直显示监控中

### ISSUE THREAD

**Issue by waiguoren001** [hr3lxphr6j/bililive-go#264]
斗鱼用0.64版本  输入https://www.douyu.com/topic/LYDB2022_ZJ?rid=5234836 这种链接无法进行录制 一直显示监控中

**Comment by kira1928** [comment]
这个问题现在还可以重现吗？
我用的 docker 版，在网页管理界面加入这个 url 是可以录制的，停止录制之后打开生成的视频也可以正常播放。

**Comment by kira1928** [comment]
年久失联，issue 先关闭。
