### ISSUE TITLE
能否添加一个ffmpeg的web页面来处理下载的直播

### ISSUE THREAD

**Issue by zheyiyuezhuo** [hr3lxphr6j/bililive-go#265]
首先谢谢作者大大开发的这么好用的工具！

我用的是docker版，看这个是基于ffmpeg的，能否在监控列表下面增加一个利用ffmoeg简单处理视频的页面：
比如建立一个定时执行的脚本，定时用ffmpeg将*.flv转为*.mp4，可以内置些简单的命令，也可以让我们自己写

**Comment by Wittoy** [comment]
#159 
可以借鉴一下

**Comment by kira1928** [comment]
这个需求实际上是为了满足录制结束后把flv转为mp4的话，这个功能在 v0.6.5 里已经添加了启用对应功能的配置项。
这边的 issue 就先关掉了。如果还有其他理由想添加这个页面的话，可以继续评论，我会再开这个 issue。
