### ISSUE TITLE
斗鱼录制，电脑和手机PK，PK结束后就花屏+声音变电音了

### ISSUE THREAD

**Issue by mfjl1212** [hr3lxphr6j/bililive-go#266]
斗鱼录制，电脑和手机PK，PK结束后就花屏+声音变电音了

**Comment by kira1928** [comment]
听说在配置文件里启用 use_native_flv_parser 的话可以解决 pk 时的各种录制问题。
但是 use_native_flv_parser 也有 use_native_flv_parser 的问题，你可以在 issue 里搜搜看。

**Comment by kira1928** [comment]
楼主失联，issue 关闭。
