### ISSUE TITLE
关于猫耳平台 【猫耳FM】的直播录制

### ISSUE THREAD

**Issue by bizzld** [hr3lxphr6j/bililive-go#268]
最近在用obs 手动录制猫耳fm上面的直播，不知道大佬能不能支持下
https://fm.missevan.com/

**Comment by kira1928** [comment]
目前现有的支持的网站中有些已经失效了。应该会优先修复那些相关issue之后再考虑新增支持的网站了。

**Comment by kira1928** [comment]
于 https://github.com/hr3lxphr6j/bililive-go/pull/362 实现。
将被包含进下个版本 (0.7.4) 中。
也可以自己编译最新的 master branch 来提前使用最新功能~
