### ISSUE TITLE
虎牙似乎又不行了

### ISSUE THREAD

**Issue by avrileader** [hr3lxphr6j/bililive-go#269]
docker 镜像
![image](https://user-images.githubusercontent.com/28498445/202947845-f0ebea6a-1ef4-4092-8733-1fcafacf1b11.png)
日志
![image](https://user-images.githubusercontent.com/28498445/202948229-c999069e-bf43-4172-8656-e0c5d3d7a44b.png)
想问各位大佬有没有临时解决办法？

**Comment by kira1928** [comment]
现在还能重现这个问题吗？
我录虎牙现在完全没问题，不能重现这个 bug 的话有点难入手调查。

**Comment by kira1928** [comment]
原来如此！重新获取最新的docker镜像使用的话能解决就好。
这边的 issue 我就关闭啦。
