### ISSUE TITLE
Twitch录制显示Commercial break in progress

### ISSUE THREAD

**Issue by Tyler-Rabbit** [hr3lxphr6j/bililive-go#279]
<img width="960" alt="bugs" src="https://user-images.githubusercontent.com/48662489/206046208-13f82596-a6ec-4297-aa3b-ca98502a920b.png">

**Comment by kira1928** [comment]
这应该是因为在你的所在地没有合适的广告填充，只能给你看这个空白页面来填充广告时间的意思。
关于目前 twitch 无法添加录制的问题会在其他 issue 下对应。
