### ISSUE TITLE
作者去哪里了有人有联系方式吗，flv使不使用都会开始乱分段，看了直播全程并没有卡，本地有些分段有些不分段

### ISSUE THREAD

**Issue by yibingchaoyue** [hr3lxphr6j/bililive-go#281]
如题，我就搞不清为什么抽风乱分段，一没pk而没卡，我都不用flv解析了，还一直分段，受不了了

**Comment by kira1928** [comment]
我用 docker 版默认的 ffmpeg 录制虎牙和斗鱼目前没遇到过乱分段的问题，经常能录出几 G 甚至十几 G 的录像文件。
