### ISSUE TITLE
看大家都在说flv分段的事 现在觉得可能是斗鱼虎牙录制线路的问题 

### ISSUE THREAD

**Issue by 212884177** [hr3lxphr6j/bililive-go#282]

**Comment by kira1928** [comment]
我用 docker 版默认的 ffmpeg 录制虎牙和斗鱼目前没遇到过乱分段的问题，经常能录出几 G 甚至十几 G 的录像文件。
能提供一下你录的会乱分段的直播间地址吗？
最好是什么时候录都稳定乱分段的直播间。如果问题很容易重现的话，我想试试修复看看。
