### ISSUE TITLE
无法添加twitch直播间

### ISSUE THREAD

**Issue by suyeonku** [hr3lxphr6j/bililive-go#283]
**Describe the bug**
【win版】今天看一下录播状态，发现无法加载twitch直播间状态，重启之后发现配置的twitch直播间全部消失，添加的话也是无法添加。
【docker版】群晖nas使用docker打开后，无法加载webUI或者是过了很久才能加载出来。
希望作者大大可以修复一下，拜托了

**Comment by q405812306** [comment]
看来不是我一个人有这种情况

**Comment by kira1928** [comment]
Dublicate of #188
