### ISSUE TITLE
四个问题  感觉还是问题还是挺多的

### ISSUE THREAD

**Issue by hibiki222** [hr3lxphr6j/bililive-go#285]
新问题其实也是老问题 ffmpeg下载无论是不是flv解析 偶尔会出现进度条是0;00:00 拖不动进度条 转码成MP4会恢复进度条上的时间戳  

但是不管转码前的flv 还是转码后的MP4 都是声音是静音 用potplayer右键查看属性会出现音频未解码状态 估计是ffmpeg下载出问题了
前面的flv解析和其他分段问题  估计都是ffmepg下载  作者更新看能不能换个下载器啥的  
最开始以为这是主播的问题  后来发现只有虎牙主播这样  斗鱼也会出现进度条是0;00;00 但是音频解码  有声音
虎牙大部分时候出现0;00;00 都是没声音的 只有小部分才有声音

第二个问题  网易cc直播可能解析失效了  主播无论开没开播 都是一直检测输出在命令行  主播一但开播 就是live star 下一秒就又是live end
一直循环很多次    但不是全天都输出这个报错   

第三个问题  就是flv解析和不用flv解析 我同时录一个主播   flv解析的是20g  不用flv解析的是15g     确实不太懂 15g那个有一段文件全程都是0;00;00    录一个音频主播时  如果音频主播开视频  则会出现只录到音频流  没有录到视频流

第四个问题  虎牙主播下播后 虽然会检测究竟下没下播  但出一直输出最后几秒的画面然后生成文件    但斗鱼检测下播  就不会生成最后几秒的文件   但又怕录不全

**Comment by kira1928** [comment]
可以提供一个虎牙录制出来没声音的直播间吗？

**Comment by hibiki222** [comment]
> 可以提供一个虎牙录制出来没声音的直播间吗？

我一共录制了25个房间  大约每5天 会有2到3个文件是这个音频未解码 没声音的情况   而且是不同主播都会出现 无论斗鱼虎牙
但录斗鱼的文件如果进度条是0：00:00 是必有声音的  但虎牙则可能有声音 可能没有声音

我用其他项目的录制同样5个房间没有问题   我在修复这种文件时候发现  大部分无声音的第一个音频解码在第3秒出现   所以说怀疑是ffmepg下载器的问题  还是请大佬看看啥问题

主要是非一个直播间的问题 是很多直播间的问题  且时间轴经常错乱  ffmpeg我之前看一篇文章 好像就是默认＋1 啥的
看有没有机会不依赖ffmpeg 换个下载器啥的  不过这样工程量可能就大了  

上次我转封装一个录下来进度条0：00；00  这个文件该是5个小时 转下来缺只有2个小时

**Comment by kira1928** [comment]
那可以上传一个没声音的flv文件吗？
太大的话可以用网盘之类的方式上传，这边发网盘链接。

**Comment by hibiki222** [comment]
> 那可以上传一个没声音的flv文件吗？ 太大的话可以用网盘之类的方式上传，这边发网盘链接。

最近这几天又没有这个情况了 12月我录的文件 发生几率很大  之前录的文件都修了 没源文件了 等着看着几天有没有这种文件
主要是这个文件得手动修
我是用了 use_native_flv_parser 的解析   之前没用这个 录下来的虎牙 虽然进度条0:00;00 但是有声音的
这个问题可以先不管 太复杂了  又难以重现这个错误

**Comment by hibiki222** [comment]
> 那可以上传一个没声音的flv文件吗？ 太大的话可以用网盘之类的方式上传，这边发网盘链接。

大佬可以先看下这个虎牙直播分段的问题  大佬在另一条issue回复的 和 #241 和  #182 
虎牙cdn的问题  导致分段


还有就是新版本那个抖音录制能否能在配置或者web端添加cookie来录制抖音直播
感觉添加cookie录制会稳一点 防止漏录

还有就是我这条issue的第4个问题  虎牙主播下播后 虽然会检测究竟下没下播 但出一直输出最后几秒的画面然后生成文件 但斗鱼检测下播 就不会生成最后几秒的文件 但又怕录不全

**Comment by hibiki222** [comment]
> 那可以上传一个没声音的flv文件吗？ 太大的话可以用网盘之类的方式上传，这边发网盘链接。
![Uploading 2023-01-07_123717_看图王.png…]()
这就是那个虎牙下播后会不断生成最后几秒画面的文件 有时候不确定是分段还是最后几秒  
斗鱼就不会这样生成最后几秒的文件
就怕不生成最后几秒画面的文件 会导致漏录

**Comment by kira1928** [comment]
前几个问题好像挺大的，最好能分成单个的 issue，我一个一个解决。

>还有就是我这条issue的第4个问题 虎牙主播下播后 虽然会检测究竟下没下播 但出一直输出最后几秒的画面然后生成文件 但斗鱼检测下播 就不会生成最后几秒的文件 但又怕录不全

这个有重现条件吗？我一直路虎牙主播，一直没遇到过这个问题。
是不是要用 flv parser？我一直用的是ffmpeg。
还有，是不是要从主播开播开始录，一直录到下播之后才会发生这个一直输出最后几秒的画面的问题？

**Comment by hibiki222** [comment]
> Collaborator
对 我一直用的是flv parse  防止花屏  不是从开始录  一直录到下播才会发生 一样是有几率发生 但大部分时候都发生了这个不断输出文件
你这么一说  可能我这些问题都来自这个flv parse吧 包括那个网易cc检测输出在命令行程序框上
大佬可以试试用flv parse 录几个虎牙主播

**Comment by hibiki222** [comment]
> > Collaborator
> 
> 对 我一直用的是flv parse 防止花屏 不是从开始录 一直录到下播才会发生 一样是有几率发生 但大部分时候都发生了这个不断输出文件 你这么一说 可能我这些问题都来自这个flv parse吧 包括那个网易cc检测输出在命令行程序框上 大佬可以试试用flv parse 录几个虎牙主播

这条issues话没说清楚  就是不断输出最后几秒文件是随便多久开录 不管主播开没开播之前监控   用flv parse多录几个虎牙主播大佬应该能发现 网易cc这个不断检测输出在命令行程序框上也是这个flv parse  可能那个没声音的问题也是这个导致的

这样 我这所有问题 其实都是一个问题了 就是这个flv parse

**Comment by kira1928** [comment]
flv parser 的问题难度比较大，我可能需要学习 flv 直播流的格式标准之后，才有能力修改原作者的代码。
这个部分可能会留到 0.8.0 中去实现。
目前我的目标是全力实现 [0.7.0](https://github.com/hr3lxphr6j/bililive-go/milestone/1) 中收录的所有问题，这也是一个大版本更新，需要一些时间来测试。
等到我能着手flv parser这里也许要几周以后了。
如果中途我的热情也燃烧殆尽了，那就得再等下一个志愿者了。。

**Comment by hibiki222** [comment]
> flv parser 的问题难度比较大，我可能需要学习 flv 直播流的格式标准之后，才有能力修改原作者的代码。 这个部分可能会留到 0.8.0 中去实现。 目前我的目标是全力实现 [0.7.0](https://github.com/hr3lxphr6j/bililive-go/milestone/1) 中收录的所有问题，这也是一个大版本更新，需要一些时间来测试。 等到我能着手flv parser这里也许要几周以后了。 如果中途我的热情也燃烧殆尽了，那就得再等下一个志愿者了。。

感谢大佬 大佬辛苦了  那我这条issue是关闭还是开着

**Comment by kira1928** [comment]
开着开着，修复这个bug是计划之内的事，以后要做的。

**Comment by hibiki222** [comment]
> flv parser 的问题难度比较大，我可能需要学习 flv 直播流的格式标准之后，才有能力修改原作者的代码。 这个部分可能会留到 0.8.0 中去实现。 目前我的目标是全力实现 [0.7.0](https://github.com/hr3lxphr6j/bililive-go/milestone/1) 中收录的所有问题，这也是一个大版本更新，需要一些时间来测试。 等到我能着手flv parser这里也许要几周以后了。 如果中途我的热情也燃烧殆尽了，那就得再等下一个志愿者了。。

大佬其实可以把2018到2020年部分的issues关闭了 我看了下 好多和我差不多的问题

比如 #150 这个之前应该已经修复了虎牙纯数字房间录制失败的问题   
#29 类似这个 其实回复一条用ffmepg提取音频就行了  纯录制音频 会出很多问题 
#11 #190 #238 这个和我的问题差不多

**Comment by kira1928** [comment]
确实有些 issue 年代太久远联系不到人，而且症状可以被现在的 issue 包含，我就关闭了。
剩下的比较新的 issue 和提供了测试 flv 文件的 issue 我留下了，接下来会继续调查。

**Comment by hibiki222** [comment]
> 确实有些 issue 年代太久远联系不到人，而且症状可以被现在的 issue 包含，我就关闭了。 剩下的比较新的 issue 和提供了测试 flv 文件的 issue 我留下了，接下来会继续调查。

大佬 抖音只支持录flv流吗 能否支持录ts 

还有就是我发现 #266 这个电脑和手机pk 如果不开flv parse的话 是肯定花屏的 

但如果开了前面电脑正常直播的与后面电脑和手机pk分段再合并 就会导致pk那段没声音 然后导致后面一大截没声音 

我以为是pk直播本来就不能合并有声音

我又去官方找了下录播 发现是这段是有声音的 不知道是数据处理问题还是本来就不能合并这个pk文件

我又用了下其他程序录下来的文件 发现转封装之后再合并是没有问题的      也许又是flv parse的问题吧

**Comment by kira1928** [comment]
从哪里获取 ts 直播地址？有其他开源项目的实现可以参考吗？
后面是想做针对各个直播平台让用户自己选直播源的。

pk的录制问题预计在 0.8.0 中修复。如果我能搞定的话= =

**Comment by hibiki222** [comment]
> 从哪里获取 ts 直播地址？有其他开源项目的实现可以参考吗？ 后面是想做针对各个直播平台让用户自己选直播源的。
> 
> pk的录制问题预计在 0.8.0 中修复。如果我能搞定的话= =

ts地址是m3u8吧 这我搜了下倒是没有能获取的开源程序  我之前用idm下载出来的就是ts

还有抖音cookies:   live.douyin.com: name1=qwer;name2=asdf

这个qwer asdf不知道啥意思  是指_ac_nonce 和__ac_signature 这两项？

**Comment by kira1928** [comment]
抖音的 m3u8 直播源我好像看到了，想做是可以支持的。
我想问一下 flv 和 m3u8 直播源录下来有什么区别吗？我的理解是他们最后被拼接成一个完整的视频之后清晰度是没有区别的。

抖音 cookie 那个 asdf qwer 是我随举的例子，意思是填入任何你取得到的 cookie 值。。
如果你取到了 cookie 就能理解了，cookie 的内容就是一堆 `key=value` 格式的字符串。
关于用户怎么取得直播网站的 cookie 这里我是有些担心的。你平时都是用什么导出网站的 cookie 值的呢？

**Comment by hibiki222** [comment]
> 抖音的 m3u8 直播源我好像看到了，想做是可以支持的。 我想问一下 flv 和 m3u8 直播源录下来有什么区别吗？我的理解是他们最后被拼接成一个完整的视频之后清晰度是没有区别的。
> 
> 抖音 cookie 那个 asdf qwer 是我随举的例子，意思是填入任何你取得到的 cookie 值。。 如果你取到了 cookie 就能理解了，cookie 的内容就是一堆 `key=value` 格式的字符串。 关于用户怎么取得直播网站的 cookie 这里我是有些担心的。你平时都是用什么导出网站的 cookie 值的呢？


flv源录下来就是flv格式  时长不会出错  （我是一直用flv pares的 ffmepg我不知道时长会不会出错）
m3u8录下来就是ts格式  时长会有很大概率出错  得转一下mp4才正常  然后比flv唯一优势就是能拖进度条 我知道直播录下来的flv不能拖是因为没有关键帧 我几天测试才发现flv源或许更好一点


我是看其他项目（biliup olive）的抖音cookie是这两项  _ac_nonce     _ac_signature
这两个项目都是必须填cookie才能录抖音    但bililive-go没cookie也能录制好 我就是怕漏录制抖音  所以之前问能否增加cookie 录制抖音

取得这个cookie 要在浏览器登录抖音 在浏览器就能取得  但是cookie是会过期的 我测试下来至少能有1个多月 每个人应该都差不多吧 

另外抖音最好录制房间不要过多 请求频率减少一点  抖音对这个比b站虎牙这些限制要大一点  很容易就被ban了

**Comment by kira1928** [comment]
请求频率的问题我看下来有的网站比较敏感，有的就无所谓。
后面我打算把cookie呀、输出文件名模板呀、访问间隔时间等等设置都做成可以按域名甚至按直播间设置的形式。
各个层级都设置了的话，设置的优先级就是 直播间设置 > 直播网站设置 > 全局设置 这样的顺序。

bililive-go 不需要 cookie 可以录抖音是因为我随便写了个 _ac_nonce 的 cookie 值在用。用户如果设置了自己的 cookie 就可以覆盖我写的这个随便的值。
我不知道什么情况下一定要用真实的抖音 cookie 才能录直播，至少目前我这里是用我随便写的 cookie 就能录了的。

每过一个月去设置一次 cookie 挺折磨的，也不符合这个项目无人值守的特点。实在需要的话，就用现在的在网页上改配置的界面，定期写入自己的 cookie 吧。

**Comment by kira1928** [comment]
我发现在设置里打开 debug: true 会输出很多有用的关于录制问题的错误信息。你后面如果有机会重启程序的话，可以打开这个配置，然后设法保存输出的log吗？
打开之后输出的 log 量挺大的，要小心。

**Comment by hibiki222** [comment]
> 我发现在设置里打开 debug: true 会输出很多有用的关于录制问题的错误信息。你后面如果有机会重启程序的话，可以打开这个配置，然后设法保存输出的log吗？ 打开之后输出的 log 量挺大的，要小心。

我一直没弄这个debug配置文件  后面试试
我今天又发现了抖音录制的文件的问题 会导致文件时间不对  修改时间减去创建时间应该是视频时长
但视频时长错误了 第一个截图是录下来的原视频  第二个截图是我用录播姬的修复功能修复出来的 时长就正常了
![2023-01-26_031512_看图王](https:/
![2023-01-26_031523_看图王](https://user-images.githubusercontent.com/114181056/214959952-3f43eda8-14d3-4aa7-884a-df96c572e255.png)
/user-images.githubusercontent.com/114181056/214959751-4b92bf3a-9468-4f76-ab4b-d629e734075a.png)

**Comment by hibiki222** [comment]
> > 我发现在设置里打开 debug: true 会输出很多有用的关于录制问题的错误信息。你后面如果有机会重启程序的话，可以打开这个配置，然后设法保存输出的log吗？ 打开之后输出的 log 量挺大的，要小心。
> 
> 我一直没弄这个debug配置文件 后面试试 我今天又发现了抖音录制的文件的问题 会导致文件时间不对 修改时间减去创建时间应该是视频时长 但视频时长错误了 第一个截图是录下来的原视频 第二个截图是我用录播姬的修复功能修复出来的 时长就正常了 ! 包括之前音频未解码也是用录播姬修复修的
![2023-01-26_031512_看图王](https://user-images.githubusercontent.com/114181056/214960107-54ab08fe-aca4-4d97-a575-279d4b39e50c.png)
![2023-01-26_031523_看图王](https://user-images.githubusercontent.com/114181056/214960136-a385c5d7-72cb-4479-93ba-559c97789fc3.png)

**Comment by kira1928** [comment]
这和一直以来发生的直播录制完之后不转换成 mp4 的话进度条就有问题的bug是不是一回事啊？
在设置里把录制完之后自动转换成 mp4 设成 true 的话，转换完的 mp4 的播放时长有问题吗？

**Comment by hibiki222** [comment]
> 这和一直以来发生的直播录制完之后不转换成 mp4 的话进度条就有问题的bug是不是一回事啊？ 在设置里把录制完之后自动转换成 mp4 设成 true 的话，转换完的 mp4 的播放时长有问题吗？

没有 我这个文件都是flv文件 不敢转mp4 mp4很难修好 
之前有一个文件转了mp4 和错误的时长一样 再修就修不好了

**Comment by hibiki222** [comment]
> > 这和一直以来发生的直播录制完之后不转换成 mp4 的话进度条就有问题的bug是不是一回事啊？ 在设置里把录制完之后自动转换成 mp4 设成 true 的话，转换完的 mp4 的播放时长有问题吗？
> 
> 没有 我这个文件都是flv文件 不敢转mp4 mp4很难修好 之前有一个文件转了mp4 和错误的时长一样 再修就修不好了

**Comment by hibiki222** [comment]
> 这和一直以来发生的直播录制完之后不转换成 mp4 的话进度条就有问题的bug是不是一回事啊？ 在设置里把录制完之后自动转换成 mp4 设成 true 的话，转换完的 mp4 的播放时长有问题吗？

这是之前说的虎牙进度条0:00:00  音频未解码的图 这次录到了
![2023-01-27_065507_看图王(3)](https://user-images.githubusercontent.com/114181056/215057718-531b39d1-88bb-422c-bd11-f46b2d676aa0.png)
![2023-01-27_065507_看图王(1)](https://user-images.githubusercontent.com/114181056/215057894-bf9740f2-0a09-4ad1-b741-b10cd89aa76a.png)

**Comment by hibiki222** [comment]
> > 这和一直以来发生的直播录制完之后不转换成 mp4 的话进度条就有问题的bug是不是一回事啊？ 在设置里把录制完之后自动转换成 mp4 设成 true 的话，转换完的 mp4 的播放时长有问题吗？
> 
> 没有 我这个修复前 修复后的文件都是flv文件 不敢转mp4 mp4很难修好 之前有一个文件转了mp4 和错误的时长一样 再修就修不好了

**Comment by kira1928** [comment]
>没有 我这个修复前 修复后的文件都是flv文件 不敢转mp4 mp4很难修好
之前有一个文件转了mp4 和错误的时长一样 再修就修不好了

嗯，那可以只选中转换成 mp4，不选中转换后删除 flv。到时候看看mp4不对头还有flv这条退路。

那个进度条00，音频未解码的文件可以发我吗？我想分析一下。。

**Comment by kira1928** [comment]
录播姬的修复具体是怎么操作的可以说明一下吗？如果是那个开源项目的话，我想学一下他的代码。

**Comment by hibiki222** [comment]
> > 没有 我这个修复前 修复后的文件都是flv文件 不敢转mp4 mp4很难修好
> > 之前有一个文件转了mp4 和错误的时长一样 再修就修不好了
> 
> 嗯，那可以只选中转换成 mp4，不选中转换后删除 flv。到时候看看mp4不对头还有flv这条退路。
> 
> 那个进度条00，音频未解码的文件可以发我吗？我想分析一下。。

我这次没留那个文件 因为太大了 20多个g 所以就修好 再转mp4了 
录播姬修复只修flv 所以我说只留flv 具体其实很复杂   录播姬修复我不知道开不开源哇 我可以去问问作者   
包括之前说的电脑和手机pk 合并没声音  也都可能是下载直播流出错了 
我看那个flv parse确实很难搞

**Comment by Qixingchen** [comment]
https://rec.danmuji.org/dev/repair/  
这里有开发者写的说明和示例代码

**Comment by kira1928** [comment]
谢谢提供具体链接！
我很喜欢做这种比较底层的功能。只要我对这个项目的热情还在，后面一定会把这个功能加进来的！

**Comment by hibiki222** [comment]
> 谢谢提供具体链接！ 我很喜欢做这种比较底层的功能。只要我对这个项目的热情还在，后面一定会把这个功能加进来的！

大佬我看 今天#366 包括之前说的 如果真要修flv parse    这是原作者在 #191 说的


花屏的原因是avc的 SPS 和 PPS 变了，ffmpeg（use_native_flv_parser=faLse）不处理这个变化，导致花屏，use_native_flv_parser=true时候是我自己实现的flv解析器，在遇到第二个SPS和PPS回重新录制。
flv这个格式正常情况没有索引所以总时长不正确，也无法索引，重新封装成mp4的时候会创建索引，就能正常播放了


感觉真的修是不行的 我用其他录制程序录的同一主播 斗鱼电脑和手机pk的话是不会分屏的  且手机pk那段有声音
 bililive-go录的会分屏
但是转mp4合并完之后  进度条拖到手机电脑pk那段照样没声音  我去看斗鱼官方录播 那段也是有声音的

我估计就是下载直播流的问题了

**Comment by hibiki222** [comment]
> 谢谢提供具体链接！ 我很喜欢做这种比较底层的功能。只要我对这个项目的热情还在，后面一定会把这个功能加进来的！

正好 我刚才复刻了网易cc直播的问题 昨天遇到了忘截图
![2023-01-31_212204_看图王](https://user-images.githubusercontent.com/114181056/215771963-953671cb-492f-4308-988d-4fbc57b6ab01.png)
具体表现为随便那个直播间 无论在没在直不直播都会有这个输出  但他输出是随机的 不是马上加上这个直播间就输出这个
我等了半个小时左右就输出了  这次复刻我没开debug  不知道需不需要开一下

这个网易cc的问题之前发过 不过当时没注意 以为是flv parse的问题 现在看来不是 估计网易cc官方更新了啥吧

**Comment by kira1928** [comment]
> 我用其他录制程序录的同一主播 斗鱼电脑和手机pk的话是不会分屏的 且手机pk那段有声音

这个其他录制程序可以介绍一下吗？
还有不会分屏是指什么情况？只会录到自己这边的屏幕？
另外能问一下一般哪些直播间pk比较多吗？我需要去蹲一个pk，收集一些调查材料。

**Comment by hibiki222** [comment]
> > 我用其他录制程序录的同一主播 斗鱼电脑和手机pk的话是不会分屏的 且手机pk那段有声音
> 
> 这个其他录制程序可以介绍一下吗？ 还有不会分屏是指什么情况？只会录到自己这边的屏幕？ 另外能问一下一般哪些直播间pk比较多吗？我需要去蹲一个pk，收集一些调查材料。

打错字了 不是分屏 是分段  手机pk必分段 我看斗鱼官方和别人录的都没分断 其他录制程序就是biliup 直播间的话我找找 我是偶尔看见手机pk的

**Comment by hibiki222** [comment]
> > > 我用其他录制程序录的同一主播 斗鱼电脑和手机pk的话是不会分屏的 且手机pk那段有声音
> > 
> > 
> > 这个其他录制程序可以介绍一下吗？ 还有不会分屏是指什么情况？只会录到自己这边的屏幕？ 另外能问一下一般哪些直播间pk比较多吗？我需要去蹲一个pk，收集一些调查材料。
> 
> 打错字了 不是分屏 是分段 手机pk必分段 我看斗鱼官方和别人录的都没分断 其他录制程序就是biliup 直播间的话我找找 我是偶尔看见手机pk的  找到了 这个正在手机直播 https://www.douyu.com/688928

**Comment by kira1928** [comment]
> 不太好提名字吧

啊这，为什么不太好呃。。。
github有好多好多，很多可能也有这个问题，我想直接参考你用过好用的那一款，可以直接告知吗？
如果是开源项目的话，我想那些作者也不会介意你帮他们推广吧。

**Comment by hibiki222** [comment]
> > 不太好提名字吧
> 
> 啊这，为什么不太好呃。。。 github有好多好多，很多可能也有这个问题，我想直接参考你用过好用的那一款，可以直接告知吗？ 如果是开源项目的话，我想那些作者也不会介意你帮他们推广吧。

就是StreamerHelper和biliup吧

**Comment by hibiki222** [comment]
> > > 不太好提名字吧
> > 
> > 
> > 啊这，为什么不太好呃。。。 github有好多好多，很多可能也有这个问题，我想直接参考你用过好用的那一款，可以直接告知吗？ 如果是开源项目的话，我想那些作者也不会介意你帮他们推广吧。
> 
> 就是StreamerHelper和biliup吧  其实github录播程序 没几个
