### ISSUE TITLE
求支持 -ov 仅支持 视频  -om 仅音频

### ISSUE THREAD

**Issue by willshion** [hr3lxphr6j/bililive-go#29]

**Comment by hr3lxphr6j** [comment]
这个不会减少流量，只能减少磁盘占用

**Comment by frostrain** [comment]
> 这个不会减少流量，只能减少磁盘占用

b站的直播是有 **仅播放音频** 选项的, 应该可以只下载音频吧...

然后我自己录制直播的时候时不时会碰到时间戳异常的问题....可能是b站流中断造成的...
就是视频前面播放正常, 但是后面就不能正常播放了(变成了快进一样的画面, 声音也没了, 但是用ffmpeg单独提取声音出来看起来又比较完整....)
试过一些时间戳修复的工具也没用, 感觉应该还是 ffmpeg 录制的问题, 没啥解决办法...

**Comment by kira1928** [comment]
@frostrain 
>然后我自己录制直播的时候时不时会碰到时间戳异常的问题....可能是b站流中断造成的...
就是视频前面播放正常, 但是后面就不能正常播放了(变成了快进一样的画面, 声音也没了, 但是用ffmpeg单独提取声音出来看起来又比较完整....)
试过一些时间戳修复的工具也没用, 感觉应该还是 ffmpeg 录制的问题, 没啥解决办法...

现在还有类似问题吗？

**Comment by kira1928** [comment]
需要的话可以用ffmepg提取音频。
issue 年代久远，就此关闭了。
