### ISSUE TITLE
虎牙主播在房间被封后  会一直检测 这倒是没啥  但重启之后 

### ISSUE THREAD

**Issue by hibiki222** [hr3lxphr6j/bililive-go#291]
被封房间会掉配置 而不会一直检测  从而导致漏录制  除非一直不重启

**Comment by kira1928** [comment]
和 #262 应该是同一个问题。

**Comment by hibiki222** [comment]
> 和#262应该是同一个问题。

大佬能看下网易cc直播啥问题吗 我这边出现网易cc直播 无论主播是否开播 都会不断检测输出在命令行的指令框中  然后主播开播 就不停地live start    live end

**Comment by kira1928** [comment]
@hibiki222 
我无法重现你的问题。
我用 https://cc.163.com/241659392/ 这个直播间试了一下，在我这里是可以正常录制的。
然后用 https://cc.163.com/241659113/ 这个直播间试了一下没有开播的情况，也是正确显示监控中。

如果你只在添加特定 url 的时候遇到了这个问题，能把你遇到问题的直播间的 url 发出来吗？

**Comment by hibiki222** [comment]
> @hibiki222 我无法重现你的问题。 我用 https://cc.163.com/241659392/ 这个直播间试了一下，在我这里是可以正常录制的。 然后用 https://cc.163.com/241659113/ 这个直播间试了一下没有开播的情况，也是正确显示监控中。
> 
> 如果你只在添加特定 url 的时候遇到了这个问题，能把你遇到问题的直播间的 url 发出来吗？

我试了几个直播间都是如此  大佬可以先挂着 这个网易cc不是百分之百会出现这个问题  挂几天  也许会出现
我也有几天没出现 有几天出现了 很迷

**Comment by wc7086** [comment]
> 大佬能看下网易cc直播啥问题吗 我这边出现网易cc直播 无论主播是否开播 都会不断检测输出在命令行的指令框中 然后主播开播 就不停地live start live end

输出的是什么内容，用的是不是最新版本，请提供更多信息

**Comment by hibiki222** [comment]
> @hibiki222 我无法重新发现你的问题。 我用https://cc.163.com/241659392/这个直播间试了下，在我这里是可以正常录制的。 然后用[https://cc.163.com/ 241659113/](https://cc.163.com/241659113/)这个直播间试了一次没有开播的情况，也是正确显示监控中。
> 
> 如果你只是在添加特定url的时候遇到了这个问题，能把你遇到问题的直播间的url发出来吗？

我刚才叫我两个朋友把他们的issuse关闭了 问题汇总到我这来  要不两位大佬创个群聊 我感觉我的问题还是挺多的了

**Comment by hibiki222** [comment]
> > 大佬能看下网易cc直播啥问题吗 我这边出现网易cc直播 无论主播是否开播 都会不停检测输出在指令行的指令柜中 然后live直播不结束live
> 
> 输出的是什么内容，用的不是最新版本，请提供更多信息
我刚才叫我两个朋友把他们的issuse关闭了 问题汇总到我这来  要不两位大佬创个群聊 我感觉我的问题还是挺多的了

**Comment by kira1928** [comment]
@hibiki222 
我刚刚收到原作者的授权，可以管理 issue 和代码了。
接下来我会陆续处理目前积压的 issue 和 pr。
创建群聊的问题，是需要开项目的 discussions 分区吗？我还没用过 discussions，不太清楚它和 issue 有什么区别。。

**Comment by hibiki222** [comment]
> @hibiki222 我刚授权授权授权授权授权授权授权授权可以和和了。 接下来我会处理处理目前目前积压的的的的的的的的的和和 和和issue有什么区别。。
![2022-12-30_045810_看图王](https://user-images.githubusercontent.com/114181056/210230808-2399da10-bee3-442f-94bc-f55ba40efec8.png)
这是那个网易cc在命令行程序框的内容 主播在那个时间并没有开播或者下播   大概是在11月份开始的 我用其他工具录制网易cc也是录不了 也行网易cc官方更新了个什么东西  非码人员也看不懂代码 
但是一但开播就会不断重复live strart 和 live end
这几天还没开播 所以还没有live star和live end的截图
