### ISSUE TITLE
请清理 issues

### ISSUE THREAD

**Issue by wc7086** [hr3lxphr6j/bililive-go#292]
我发现这个项目的 issues 区域非常杂乱。很多问题都已经解决，但它们仍然留在了 issues 列表中。

我建议清理 issues 区域，将已解决的问题标记为“已关闭”。这样可以更轻松地找到未解决的问题，并且 issues 区域也会变得更整洁。

**Comment by kira1928** [comment]
作者可能已经对维护项目失去兴趣了。我发邮件都联系不到他。
如果还能联系到作者，现在增加新的维护者来处理积压的 issue 和 pr 更现实一些。
如果一直联系不到人，但又有一定的用户量（issue 量），那 fork 一个新的仓库，在那边继续开发和处理这边的 issue，等作者有回应了再尝试 merge 回来比较可行。

**Comment by q405812306** [comment]
你们twitch能正常录制吗

**Comment by kira1928** [comment]
> 你们twitch能正常录制吗

不能。twitch录制功能目前是坏的。详情见[这里](https://github.com/hr3lxphr6j/bililive-go/pull/289#issuecomment-1365186440)。

**Comment by hr3lxphr6j** [comment]
> 作者可能已经对维护项目失去兴趣了。我发邮件都联系不到他。 如果还能联系到作者，现在增加新的维护者来处理积压的 issue 和 pr 更现实一些。 如果一直联系不到人，但又有一定的用户量（issue 量），那 fork 一个新的仓库，在那边继续开发和处理这边的 issue，等作者有回应了再尝试 merge 回来比较可行。

人去考研了，确实没有时间再维护项目了，给您发了个管理邀请，如果您有兴趣的话可以维护下这个项目

**Comment by kira1928** [comment]
@hr3lxphr6j 
收到，感谢授权。
预祝考研顺利！

**Comment by kira1928** [comment]
粗略整理了一遍 issue 区，剩下的 issue 慢慢处理吧。
