### ISSUE TITLE
【功能请求】使 HTML 可以修改所有设置

### ISSUE THREAD

**Issue by wc7086** [hr3lxphr6j/bililive-go#293]
更好的方法是使用中后台框架写一个完整的后台前端。

**Comment by kira1928** [comment]
换框架工程量有点大，得看有没有勇士接手了。
目前看来只是在现有界面上增加 html 修改所有设置的可能性比较高。

**Comment by kira1928** [comment]
已在最新版中实现在 web UI 界面中修改配置文件原文。
