### ISSUE TITLE
群晖使用配置文件就报错

### ISSUE THREAD

**Issue by Xiaofan0331** [hr3lxphr6j/bililive-go#296]
群晖使用配置文件就报错 不使用就能正常录制

**Comment by kira1928** [comment]
群晖docker吗？那配置文件你应该没法不使用吧，是默认用配置文件启动的。

报错是什么错误信息可以复制或截图发上来吗？

配置文件的内容也发一下吧

**Comment by Xiaofan0331** [comment]
不好意思 映射文件路径搞错了

**Comment by kira1928** [comment]
解决了就好，那issue我就关闭啦
