### ISSUE TITLE
0.6.5的windows版本找不到ffmpeg.

### ISSUE THREAD

**Issue by JaydenFish** [hr3lxphr6j/bililive-go#297]
一运行就报错`FFmpeg binary not found, Please Check.`
0.6.3是正常的. 升级到0.6.5就报错了.

**Comment by kira1928** [comment]
看了一下 https://github.com/hr3lxphr6j/bililive-go/wiki/Install-Windows ，上面说要把 ffmpeg 复制进 bililive-go 目录里。
你那边有没有把 0.6.3 里的 ffmpeg 程序复制进 0.6.5 的目录里？

**Comment by JaydenFish** [comment]
> 看了一下 https://github.com/hr3lxphr6j/bililive-go/wiki/Install-Windows ，上面说要把 ffmpeg 复制进 bililive-go 目录里。 你那边有没有把 0.6.3 里的 ffmpeg 程序复制进 0.6.5 的目录里？

有的. ffmpeg.exe和bililive-windows-amd64.exe在同一个目录下. 一直是这样. 这样对吗?

**Comment by kira1928** [comment]
对的。你的问题我这里也重现了。用 0.6.3 可以找到 ffmpeg，用 0.6.5 就不行，很邪门。。
我调查一下。

**Comment by kira1928** [comment]
Duplicate of #248
