### ISSUE TITLE
直播录制的时候，将文件上传的云存储 UPYUN，QINIU，阿里云，腾讯云

### ISSUE THREAD

**Issue by StringKe** [hr3lxphr6j/bililive-go#3]

**Comment by StringKe** [comment]
不影响任何功能，命令提示符在Windows下显示不全
![image](https://user-images.githubusercontent.com/31089228/43124179-ed525746-8f58-11e8-9141-c8009e8cf4d1.png)

**Comment by hr3lxphr6j** [comment]
试试msys2
