### ISSUE TITLE
可以支持录制直接转码成h265吗

### ISSUE THREAD

**Issue by ghoslin01** [hr3lxphr6j/bililive-go#30]
因为现在录制完成后再通过脚本来转换 时间太长 可以支持ffmpeg直接就输出成h265的编码的吗？

**Comment by hr3lxphr6j** [comment]
https://gist.github.com/hr3lxphr6j/827060b7f0ceedad829da11694dcbccc

写成cron，实时转码太吃CPU

**Comment by ghoslin01** [comment]
好吧。。。不过主要直播都是好多个小时的 转码又花好几个小时
