### ISSUE TITLE
解决使用不同 url 录制同一直播间会导致重复订阅的问题

### ISSUE THREAD

**Issue by kira1928** [hr3lxphr6j/bililive-go#300]
- [x] https://github.com/hr3lxphr6j/bililive-go/issues/78
- [x] https://github.com/hr3lxphr6j/bililive-go/issues/261

**Comment by caileisir** [comment]
大佬你好，我想请教一下，docker安装的录播结束后，录播文件在哪里，网页端保存设置点击无反应。

**Comment by kira1928** [comment]
@caileisir 
见使用 docker 方面的说明 https://github.com/hr3lxphr6j/bililive-go/wiki/docker-&-k8s 。

你是怎么设置和启动 docker 的呢？
如果你有映射 `/srv/bililive` 目录的话，录播文件就在逆映射到的本地目录里。

网页端保存设置点了应该不至于无反应。不过保存的配置文件在 docker 的 container 内，位置是 /etc/bililive-go/config.yml 。
你可以把这个配置文件也映射到你的宿主机上，这样可以直接访问到保存后的配置文件，也可以手动修改了。

**Comment by caileisir** [comment]
l

> @caileisir 见使用 docker 方面的说明 https://github.com/hr3lxphr6j/bililive-go/wiki/docker-&-k8s 。
> 
> 你是怎么设置和启动 docker 的呢？ 如果你有映射 `/srv/bililive` 目录的话，录播文件就在逆映射到的本地目录里。
> 
> 网页端保存设置点了应该不至于无反应。不过保存的配置文件在 docker 的 container 内，位置是 /etc/bililive-go/config.yml 。 你可以把这个配置文件也映射到你的宿主机上，这样可以直接访问到保存后的配置文件，也可以手动修改了。

@kira1928 
/srv/bililive 里面空白完蛋

**Comment by kira1928** [comment]
那可能是程序 bug 了。能发一下你的程序 log 吗？
曾经有过[这种](https://github.com/hr3lxphr6j/bililive-go/issues/38)bug，你可以试试里面的方法。

**Comment by kira1928** [comment]
为了后续沟通，你最好能新建一个 issue，我们在那边聊吧。

**Comment by caileisir** [comment]
> 为了后续沟通，你最好能新建一个 issue，我们在那边聊吧。

@kira1928 好的，服务器重装了，我重新试试看。谢谢

**Comment by kira1928** [comment]
于 https://github.com/hr3lxphr6j/bililive-go/pull/304 实现。
