### ISSUE TITLE
新的版本會出現 FFmpeg binary not found

### ISSUE THREAD

**Issue by helloonix** [hr3lxphr6j/bililive-go#301]
發現新的版本會出現
FFmpeg binary not found, Please Check.
但是已經有FFmpeg.exe在同folder中

**Comment by kira1928** [comment]
最新的 0.6.6 本来就是为了解决这个问题而发布的，详见 https://github.com/hr3lxphr6j/bililive-go/issues/248 。
不过看起来没有奏效呢。

如果你用的就是 0.6.6 的话，能不能提供一下你的 os 版本，安装方式，执行方法，最好有截图的。

**Comment by kira1928** [comment]
再确认一下，你是在 exe 目录内执行的 `.\bililive-windows-amd64.exe`，还是在外部目录执行比如 `bin\bililive-windows-amd64.exe` 这样的呢？
如果从外部目录执行也会找不到 ffmpeg

**Comment by helloonix** [comment]
> 再确认一下，你是在 exe 目录内执行的 `.\bililive-windows-amd64.exe`，还是在外部目录执行比如 `bin\bililive-windows-amd64.exe` 这样的呢？ 如果从外部目录执行也会找不到 ffmpeg
![capture](https://user-images.githubusercontent.com/121936109/210665799-1da2e6ee-5250-42bc-b563-688d5505a8c6.PNG)
我用cmd run exe
如图
Windows 10

**Comment by kira1928** [comment]
刚刚发布了 v0.6.7，现在两个 exe 放在同一目录下，在 exe 目录内执行 `.\bililive-windows-amd64.exe` 就可以识别到 ffmpeg 啦！

**Comment by kira1928** [comment]
Duplicate of #248
