### ISSUE TITLE
网页端保存设置的返回值格式，服务器端和前端的预期不同，导致前端命令行报错

### ISSUE THREAD

**Issue by kira1928** [hr3lxphr6j/bililive-go#303]
目前服务器端返回的是 `"OK"` 之类的字符串，前端期待的是 json。
爬了一下历史，应该是前端[提交代码](https://github.com/hr3lxphr6j/bililive-go/pull/47)的时候服务器端返回的[还是 json](https://github.com/hr3lxphr6j/bililive-go/blob/d68d3b544133cfb16cbf067fcb8ddeadc07fe7ec/src/servers/handler.go#L174)，在前端提交之后服务器端[修改了](https://github.com/hr3lxphr6j/bililive-go/commit/0fe9111d8e0b84b3dfd6e7e48dc872afd5bcc4f1#diff-3f0fe088da5b01ac8a52c35f0a13499c6981680ea8160f12dbe3a73ea79f6e54R127)返回值的格式。

原作者近期比较忙，所以这里想问一下 @BJ4501 大佬了解当时服务器端为什么要修改返回值格式吗？
从易用性角度来讲，我是想把返回值改回 json 的。

**Comment by kira1928** [comment]
已在最新版中统一为返回 json 了。

**Comment by BJ4501** [comment]
这个返回值太久不记得了，我看了下应该没什么问题。
@hr3lxphr6j
