### ISSUE TITLE
out-of-rang

### ISSUE THREAD

**Issue by willshion** [hr3lxphr6j/bililive-go#31]
ime="2019-07-18 14:59:46" level=info msg="BiliLive-go Version: 0.3.7 Link Start"
time="2019-07-18 14:59:48" level=info msg="ListenerManager Start"
time="2019-07-18 14:59:48" level=info msg="RecorderManager Start"
time="2019-07-18 14:59:48" level=info msg="Listener Start" host_name="艺笙yo" id=16ebc4650b689e8f7ec2c0cb475053ff room_name="【直播】陪你度过漫长岁月" status=true url="https://www.douyu.com/4043952"
time="2019-07-18 14:59:48" level=info msg="Live Start" host_name="艺笙yo" id=16ebc4650b689e8f7ec2c0cb475053ff room_name="【直播】陪你度过漫长岁月" status=true url="https://www.douyu.com/4043952"
time="2019-07-18 14:59:48" level=info msg="Listener Start" host_name="御姐李莎" id=d7599620e44002e80b537df039455381 room_name="多晚我都等你回家" status=false url="https://www.douyu.com/66969"
time="2019-07-18 14:59:48" level=info msg="Recorde Start" host_name="艺笙yo" id=16ebc4650b689e8f7ec2c0cb475053ff room_name="【直播】陪你度过漫长岁月" status=true url="https://www.douyu.com/4043952"
time="2019-07-18 14:59:49" level=info msg="Listener Start" host_name="小温妤baby" id=464842ff62795928544f00fab75a5f68 room_name="你的情感治愈女友" status=false url="https://www.douyu.com/4650531"
panic: runtime error: index out of range

goroutine 63 [running]:
github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).getSignParams(0xc00016a410, 0x0, 0x0, 0x0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:181 +0x1244
github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).GetStreamUrls(0xc00016a410, 0xc0000285a0, 0x0, 0x0, 0x0, 0x0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:239 +0x5b
github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).run(0xc0000b2000)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:56 +0x7b
created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Start.func1
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:86 +0x4e

**Comment by ghoslin01** [comment]
同样出现这种情况 目测斗鱼更新了

**Comment by ghoslin01** [comment]
time="2019-07-18 23:03:02" level=info msg="Live Start" host_name=Nearly1 id=0f587a978b07918dbe5e1e42500fb869 room_name="QYQX的直播间" status=true url="https://www.douyu.com/7"


time="2019-07-18 23:03:02" level=info msg="Recorde Start" host_name=Nearly1 id=0f587a978b07918dbe5e1e42500fb869 room_name="QYQX的直播间" status=true url="https://www.douyu.com/7"


panic: runtime error: index out of range




goroutine 79 [running]:


github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).getSignParams(0xc0001ee0a0, 0x0, 0x0, 0x0)


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:181 +0x123d


github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).GetStreamUrls(0xc0001ee0a0, 0xc000231bc0, 0x0, 0x0, 0xc000470300, 0xc0004703c0)


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:239 +0x54


github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).run(0xc0000216c0)


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:56 +0x74


created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Start.func1


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:86 +0x47


time="2019-07-18 23:04:03" level=info msg="BiliLive-go Version: 0.3.5 Link Start"


time="2019-07-18 23:04:05" level=info msg="Server start at :8080"


time="2019-07-18 23:04:05" level=info msg="ListenerManager Start"


time="2019-07-18 23:04:05" level=info msg="RecorderManager Start"


time="2019-07-18 23:04:05" level=info msg="Listener Start" host_name="鲨鱼熊" id=32dafd75257c60c9280545097174b1d6 room_name="随便看看" status=true url="https://live.bilibili.com/144"


time="2019-07-18 23:04:05" level=info msg="Live Start" host_name="鲨鱼熊" id=32dafd75257c60c9280545097174b1d6 room_name="随便看看" status=true url="https://live.bilibili.com/144"


time="2019-07-18 23:04:05" level=info msg="Listener Start" host_name="小燚不吃仓鼠" id=48c906f9b922e5f922ddae2a8d506660 room_name="温柔暖萌酥语偶凶，姐姐和你闲聊玩过家家哦" status=true url="https://live.bilibili.com/82429"


time="2019-07-18 23:04:05" level=info msg="Recorde Start" host_name="鲨鱼熊" id=32dafd75257c60c9280545097174b1d6 room_name="随便看看" status=true url="https://live.bilibili.com/144"


time="2019-07-18 23:04:05" level=info msg="Live Start" host_name="小燚不吃仓鼠" id=48c906f9b922e5f922ddae2a8d506660 room_name="温柔暖萌酥语偶凶，姐姐和你闲聊玩过家家哦" status=true url="https://live.bilibili.com/82429"


time="2019-07-18 23:04:05" level=info msg="Listener Start" host_name="空空之火" id=42972631fde4b3e82b4d9979e44d1a8b room_name="【超御小姐姐】我可以成为你的好朋友吗" status=false url="https://live.bilibili.com/351232"


time="2019-07-18 23:04:05" level=info msg="Recorde Start" host_name="小燚不吃仓鼠" id=48c906f9b922e5f922ddae2a8d506660 room_name="温柔暖萌酥语偶凶，姐姐和你闲聊玩过家家哦" status=true url="https://live.bilibili.com/82429"


time="2019-07-18 23:04:05" level=info msg="Listener Start" host_name="10是拖延症晚期" id=53fafbd371988287617faea77e051438 room_name="不来点歌的都是猪" status=true url="https://live.bilibili.com/95342"


time="2019-07-18 23:04:06" level=info msg="Live Start" host_name="10是拖延症晚期" id=53fafbd371988287617faea77e051438 room_name="不来点歌的都是猪" status=true url="https://live.bilibili.com/95342"


time="2019-07-18 23:04:06" level=info msg="Listener Start" host_name=Nearly1 id=0f587a978b07918dbe5e1e42500fb869 room_name="QYQX的直播间" status=true url="https://www.douyu.com/7"


time="2019-07-18 23:04:06" level=info msg="Recorde Start" host_name="10是拖延症晚期" id=53fafbd371988287617faea77e051438 room_name="不来点歌的都是猪" status=true url="https://live.bilibili.com/95342"


time="2019-07-18 23:04:06" level=info msg="Live Start" host_name=Nearly1 id=0f587a978b07918dbe5e1e42500fb869 room_name="QYQX的直播间" status=true url="https://www.douyu.com/7"


time="2019-07-18 23:04:06" level=info msg="Listener Start" host_name=tsukasalol id=a4c3d9ebbc76f51070bdae59782d6044 room_name="TT的直播间~" status=false url="https://www.douyu.com/1188"


time="2019-07-18 23:04:06" level=info msg="Recorde Start" host_name=Nearly1 id=0f587a978b07918dbe5e1e42500fb869 room_name="QYQX的直播间" status=true url="https://www.douyu.com/7"


panic: runtime error: index out of range




goroutine 85 [running]:


github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).getSignParams(0xc0000aa050, 0x23ec8d47a400df44, 0x3e91ace37d62bab7, 0xa264140afe11aa05)


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:181 +0x123d


github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).GetStreamUrls(0xc0000aa050, 0xc00007ca20, 0x9827b5cad50e7d00, 0xf2de4c13aa204ac1, 0x86029b37876f5e35, 0xfcb35a5590b9be8d)


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:239 +0x54


github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).run(0xc00010a2a0)


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:56 +0x74


created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Start.func1


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:86 +0x47

**Comment by ghoslin01** [comment]
time="2019-07-18 23:03:02" level=info msg="Live Start" host_name=Nearly1 id=0f587a978b07918dbe5e1e42500fb869 room_name="QYQX的直播间" status=true url="https://www.douyu.com/7"


time="2019-07-18 23:03:02" level=info msg="Recorde Start" host_name=Nearly1 id=0f587a978b07918dbe5e1e42500fb869 room_name="QYQX的直播间" status=true url="https://www.douyu.com/7"


panic: runtime error: index out of range




goroutine 79 [running]:


github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).getSignParams(0xc0001ee0a0, 0x0, 0x0, 0x0)


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:181 +0x123d


github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).GetStreamUrls(0xc0001ee0a0, 0xc000231bc0, 0x0, 0x0, 0xc000470300, 0xc0004703c0)


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:239 +0x54


github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).run(0xc0000216c0)


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:56 +0x74


created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Start.func1


	/home/ghos/go/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:86 +0x47

**Comment by liwufan** [comment]
Jul 22 19:53:13 x220 systemd[30447]: Started Live Stream Saver.
Jul 22 19:53:13 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:13" level=info msg="BiliLive-go Version: 0.3.7 Link Start"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="ListenerManager Start"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="RecorderManager Start"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Listener Start" host_name="机智的肯尼" id=c75eb2db607fd2929a7dc86309e0a831 room_name="【肯尼】大哥哥又来玩啦" status=true url="http://cc.163.com/239802416"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Live Start" host_name="机智的肯尼" id=c75eb2db607fd2929a7dc86309e0a831 room_name="【肯尼】大哥哥又来玩啦" status=true url="http://cc.163.com/239802416"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Listener Start" host_name="羽毛" id=3c4003885a7c5e23c763a88ee5118e73 room_name="[喂狗组] 走，打碟" status=false url="http://www.huya.com/virgoo"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Recorde Start" host_name="机智的肯尼" id=c75eb2db607fd2929a7dc86309e0a831 room_name="【肯尼】大哥哥又来玩啦" status=true url="http://cc.163.com/239802416"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Listener Start" host_name="楼座" id=430a3bb66e944d9c2dde4af35200d6e2 room_name="[喂狗组]走，打碟！" status=false url="https://www.huya.com/431087"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Listener Start" host_name="伯爵" id=d38ace3ebe72b48d6b71176b23a8d7f3 room_name="[喂狗组]请给我更多银河城" status=true url="https://www.huya.com/diriya"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Live Start" host_name="伯爵" id=d38ace3ebe72b48d6b71176b23a8d7f3 room_name="[喂狗组]请给我更多银河城" status=true url="https://www.huya.com/diriya"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Listener Start" host_name="门房大爷" id=d37d23a69e80c98d4bfd1f31f1b22403 room_name="开心也是一天不开心也是一天" status=false url="https://www.douyu.com/564824"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Recorde Start" host_name="伯爵" id=d38ace3ebe72b48d6b71176b23a8d7f3 room_name="[喂狗组]请给我更多银河城" status=true url="https://www.huya.com/diriya"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Listener Start" host_name=ywwuyi id=780c675e3e39fbeff6c10344b6c164e0 room_name="[透明系无声vtuber]钢之魂！！！" status=false url="https://www.douyu.com/6655"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Listener Start" host_name="谜之声还是被抢注了" id=be7b1b988c19ee42a9e9c0cd65c596df room_name="谜之空间：周一至周五晚8点前开播~" status=true url="https://www.douyu.com/51233"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Live Start" host_name="谜之声还是被抢注了" id=be7b1b988c19ee42a9e9c0cd65c596df room_name="谜之空间：周一至周五晚8点前开播~" status=true url="https://www.douyu.com/51233"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Listener Start" host_name=Quin33 id=9a9eee786de8b493cfca57033993db00 room_name="【Quin】漫威终极联盟3" status=false url="https://cc.163.com/361433"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: time="2019-07-22 19:53:15" level=info msg="Recorde Start" host_name="谜之声还是被抢注了" id=be7b1b988c19ee42a9e9c0cd65c596df room_name="谜之空间：周一至周五晚8点前开播~" status=true url="https://www.douyu.com/51233"
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: panic: runtime error: index out of range
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: goroutine 117 [running]:
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).getSignParams(0xc0002d2dc0, 0x616c63207669643c, 0x656d6167223d7373, 0x6f702d6d6574692d)
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]:         /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:181 +0x123d
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).GetStreamUrls(0xc0002d2dc0, 0xc0000804e0, 0x35223d676f6c2000, 0x3232613436333364, 0x3264343330633462, 0x3a33353562666334)
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]:         /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:239 +0x54
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).run(0xc00010fd50)
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]:         /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:56 +0x74
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]: created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Start.func1
Jul 22 19:53:15 x220 bililive-go-linux-amd64[18084]:         /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:86 +0x47
Jul 22 19:53:15 x220 systemd[30447]: bililive-go.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 22 19:53:15 x220 systemd[30447]: bililive-go.service: Failed with result 'exit-code'.
Jul 22 19:53:15 x220 systemd[30447]: bililive-go.service: Service RestartSec=100ms expired, scheduling restart.
Jul 22 19:53:15 x220 systemd[30447]: bililive-go.service: Scheduled restart job, restart counter is at 15.
Jul 22 19:53:15 x220 systemd[30447]: Stopped Live Stream Saver.

斗鱼会闪退

**Comment by keyingfu0** [comment]
同样出现这种情况, 提示  index out of range
