### ISSUE TITLE
twitch直播间显示room not exists

### ISSUE THREAD

**Issue by plrvib** [hr3lxphr6j/bililive-go#314]
我是在mac上用docker运行的
`docker run -v ~/Movies:/srv/bililive --rm chigusa/bililive-go -o /srv/bililive -i https://www.twitch.tv/restiafps`
执行命令之后显示
```
time="2023-01-07 02:54:08" level=error msg="room not exists" url="https://www.twitch.tv/restiafps"
time="2023-01-07 02:54:08" level=info msg="Bye~"
```

之前都可以正常运行，顺利下载直播。
但是从12月中开始，twitch所有直播间都会显示room not exists

**Comment by kira1928** [comment]
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/188
