### ISSUE TITLE
希望抖音能够支持自定义cookie

### ISSUE THREAD

**Issue by yyll2233** [hr3lxphr6j/bililive-go#316]
先谢谢！
希望抖音能够支持！

**Comment by kira1928** [comment]
你好！说明文档没改，但是网页版抖音直播已经可以录制啦！

**Comment by yyll2233** [comment]
好的，谢谢！
不知道后期能否传递cookie？抖音已经有一些会员专属直播了。

**Comment by kira1928** [comment]
你好，目前 cookie 功能还在开发中，原作者已经把大部分开发完了！
后面我看看收尾不困难的话预计 0.7.0 的大版本更新的时候一起放出。

**Comment by yyll2233** [comment]
好的，期待大版本更新！
祝新年快乐，开发顺利！

**Comment by kira1928** [comment]
已在最新版中实现。

**Comment by yyll2233** [comment]
好的！感谢，我现在去更新！
