### ISSUE TITLE
命令行参数不足导致程序自动退出时应增加提示

### ISSUE THREAD

**Issue by TheDDF6** [hr3lxphr6j/bililive-go#319]
<img width="570" alt="WeChata924fdfe5f2bfde11351b74664f118bb" src="https://user-images.githubusercontent.com/100023488/211227358-85d1f244-ac05-400c-bde2-89ba37946334.png">

研究了很久才发现我不能运行的原因是程序刚运行就自动关闭（msg="Bye～"），不懂如何解决
还有感觉wiki中对mac端的教程可能不够清晰？

**Comment by kira1928** [comment]
这个确实是 wiki 对用法的解释不充分造成的误会。。

这个程序接收应该录哪些直播间的指令有两种途径，一个是从 config 文件中读取，第二个是通过网页管理界面接收命令。
使用 config 需要使用像 `-c config.yml` 这样的启动参数。
启动网页端需要使用 `--enable-rpc` 这个启动参数。
如果两个参数都没有设置，那程序就没有途径接收应该录制哪些直播间的命令，未来也没有机会从外界接收新的命令，只好关闭自己了。
这算是一种启动参数配置错误，应该在程序输出中对用户发出提醒的。
这个 issue 作为操作提醒不明确的问题暂时保留，会在后面进行修复。
不过我最近你在全力开发 [0.7.0](https://github.com/hr3lxphr6j/bililive-go/milestone/1) 的大版本更新，这个 issue 的优先级要排在那之后了。

**Comment by TheDDF6** [comment]
那么我应该在何处配置启动参数？
在终端中直接使用以上两个命令是不行的，`-c config.yml`的完整语句应该是`ffmpeg -c config.yml`?
`--enable-rpc`的使用我还在研究
我能理解作者大大可能不会注意这些小细节，可对于我这样代码基础相对薄弱的、想学习做切片的用户经常遇到这样的难题（捂脸）
还有这样算成功配置了使用config需要的参数了吗
![WechatIMG265](https://user-images.githubusercontent.com/100023488/211256643-eb02d5a9-769c-44ab-91ad-7ceba383c19a.jpeg)

**Comment by kira1928** [comment]
啊不好意思，我还是没说清楚。

这两个命令都是加在 bililive-go 上的。
比如 `/Users/theddf/Downloads/bililive-darwin-amd64 --enable-rpc`， 
或者 `/Users/theddf/Downloads/bililive-darwin-amd64 -c config.yml`，这里的 `config.yml` 应该在你执行这个命令时所在的目录中。
如果是代码计出相对薄弱的用户，我这里推荐用项目目录里自带的 config.yml 文件作为初始设置。
在你的环境下使用这个设置的命令应该是 `/Users/theddf/Downloads/bililive-darwin-amd64 -c /Users/theddf/Downloads/config.yml` 吧，如果你是把 zip 文件直接解压到 Downloads 目录了的话。

ffmpeg 是 bililive-go 启动后，由程序内部自动调用的，用户（也就是你）不需要特意去执行它。
aria2 应该不是这个项目的必须组件，只是碰巧我们和他们都选择了同一个参数名 `--enable-rpc` 而已，实际上只是两个人家的孩子起名起重名了的关系，实际上这两家互相并不认识^_^

这个项目最初可能是面向有一定技术能力的用户而开发的（嗯，我不是原作者，只是近期加入协助维护项目的路人），所以有些地方的提示并不充分，说明也比较简洁。基本上是不懂的地方自己看代码。不过绝不是为了刻意为难非程序员用户的。
后面我会丰富一下说明文档，以及程序执行时出现各种问题时的错误提醒信息。
还有不懂的地方也欢迎来提 issue ~

**Comment by TheDDF6** [comment]
谢谢帮助，目前我已经能够成功进入bililive-go的网页端界面了，是否能够正常使用还需要我进一步的尝试。
同时我发现一个问题，我好像每次开启bililive-go都需要通过`/Users/theddf/Downloads/bililive-darwin-amd64/bililive-darwin-amd64 --enable-rpc`这一指令来实现，因为当我成功打开过一次网络接口后再尝试直接打开bililive-darwin-amd64又出现了自动关闭的现象，虽然目前还不影响我的使用，但应该属于一个需要优化的部分。

**Comment by TheDDF6** [comment]
通过我短暂地尝试，发现问题应该在程序不能自动读取config，导致我每次都要手动让它读取，我在config里面调整了rpc中的`enable:false`为`enable:true`，即使这样每次直接打开程序还是会自动关闭。

**Comment by TheDDF6** [comment]
还有一个有疑问的点，不知道在这个issue下提出合不合适
录制的片源的画质是可调的吗？还是说默认就是最高画质？
虽然我本人只需要最高画质，但是有关画质问题方面应该在wiki中指明？即使指明目前仅支持监视最高画质，也能起到不使人疑惑的作用

**Comment by kira1928** [comment]
>我在config里面调整了rpc中的enable:false为enable:true，即使这样每次直接打开程序还是会自动关闭。

这可能是你打开程序的时候没有指定这个你调整了设置的 config 文件。
config 确实不是自动读取的，每次执行都需要明确指定 -c 某个 config.yml

**Comment by kira1928** [comment]
>录制的片源的画质是可调的吗？还是说默认就是最高画质？  

调目前是不可调的，至于具体选了哪个画质我也不太清楚。目前看来没人抱怨过画质，估计是默认选最高画质了。

>虽然我本人只需要最高画质，但是有关画质问题方面应该在wiki中指明？即使指明目前仅支持监视最高画质，也能起到不使人疑惑的作用

是的，wiki这方面目前缺少维护，后面会慢慢补上。
大概，0.7.0 版本发布之后，0.8.0 版本发布之前吧。

**Comment by kira1928** [comment]
已加入了以下功能
>双击执行时尝试使用可执行文件旁边的配置文件，当命令行参数不足且可执行文件旁边没有默认的配置文件时，程序自动退出时会提示退出原因。

将在下个版本 (0.7.4) 中发布。
也可以自己在本地编译最新的 master branch 提前体验新功能~
