### ISSUE TITLE
哥们支持一下twitch，我这边添加不进去，还有afreecatv

### ISSUE THREAD

**Issue by carryyourself** [hr3lxphr6j/bililive-go#334]
https://github.com/nilaoda/N_m3u8DL-CLI/releases
可以直接拿上面的源码，上面可以直接下载m3u8可以直接去检测下载m3u8即可

**Comment by carryyourself** [comment]
还有微博直播可以支持吗

**Comment by BearChu** [comment]
建议不要理会此人提出的af，不良直播内容不适合支持，需过滤该类平台，不让特定用户持续要求更多，大多数作者都不采纳该类平台

**Comment by hibiki222** [comment]
这条issue在 #294 你已经发过了

**Comment by hibiki222** [comment]
> 建议不要理会此人提出的af，不良直播内容不适合支持，需过滤该类平台，不让特定用户持续要求更多，大多数作者都不采纳该类平台

确实 太小众的平台和类似affactv的平台 不仅耗时也没多少人用  现在这个大佬也是为爱发电的  修好现在几个平台感觉也很不容易了

**Comment by kira1928** [comment]
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/188
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/294

**Comment by kira1928** [comment]
@hibiki222
确实是为爱发电。
原作者的热情耗尽了，我是最近休息比较闲所以更新很频繁。
等下周我也要去上班了，可能不会像这两周这样疯狂处理 issue 了。

**Comment by hibiki222** [comment]
> @hibiki222 确实是为爱发电。 原作者的热情耗尽了，我是最近休息比较闲所以更新很频繁。 等下周我也要去上班了，可能不会像这两周这样疯狂处理 issue 了。
我的意思就是比较小众的平台或许可以不添加了 维护这几个平台感觉也是耗费精力很多了  

确实是辛苦大佬了 祝大佬小年快乐！
