### ISSUE TITLE
已经确认自动分段时长为1h，但录出来的视频会变成很多小块，而且之间不正常连接

### ISSUE THREAD

**Issue by TheDDF6** [hr3lxphr6j/bililive-go#335]
在正常使用了数日后出现的bug，先上报错（我看不懂）
![WechatIMG278](https://user-images.githubusercontent.com/100023488/212504409-733fd3fd-0370-4a82-8c4c-2b8da959f106.jpeg)
![WechatIMG279](https://user-images.githubusercontent.com/100023488/212504411-86aa9e4f-92e8-464c-a811-d452cba2b45b.jpeg)
根据文件名称可以看到相邻片段的时间间隔不是一小时（我确认了config里面是1h），同时这些小片段的间隔也不是固定值，相邻片段同容也不是无缝。
![WechatIMG280](https://user-images.githubusercontent.com/100023488/212504486-04b2965c-26cf-426d-9d5b-94ef3d6c7fe0.jpeg)
期间尝试在控制网站中删除直播间再重新添加房间，然后正常录制了几个片段就又不正常了。

**Comment by kira1928** [comment]
可以发一下你的 config 文件和命令行启动参数吗？
这个录制断断续续的问题很多其他人也提出来过了。目前因为输出的错误信息不够详细，还不能断定大家遇到的是不是同一类问题，也不知道应该怎么解决。
现在的一个思路是大家可能都是用了 use_native_flv_parser 这个 flag，然后这个 parser 里可能有些什么问题。
关于录出来的视频断断续续的问题我是想在下一个大版本更新 (0.8.0) 时尽可能修复的，期间可能要麻烦你帮忙提供几次反馈。

**Comment by TheDDF6** [comment]
`rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 15
out_put_path: /Users/theddf/Movies/bgo
feature:
  use_native_flv_parser: false
live_rooms:
- https://live.bilibili.com/65726
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: true
  max_duration: 1h0m0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
`

**Comment by TheDDF6** [comment]
`rpc:`
`  enable: true`
`  bind: 127.0.0.1:8080`
`debug: false`
`interval: 15`
`out_put_path: /Users/theddf/Movies/bgo`
`feature:`
`  use_native_flv_parser: false`
`live_rooms:`
`- https://live.bilibili.com/65726`
`out_put_tmpl: ""`
`video_split_strategies:`
`  on_room_name_changed: true`
`  max_duration: 1h0m0s`
`cookies: {}`
`on_record_finished:`
`  convert_to_mp4: true`
`  delete_flv_after_convert: true`

**Comment by kira1928** [comment]
没用 flv parser 也会这么严重啊。。
有一种说法是我们访问b站频率太高，ip 被限制了。
你要不要试试把 `interval` 这个设置调大一点，比如 300 秒一次？
不过这样的坏处是主播开播后最晚要等 300 秒才会开始录制。

如果这样也不能缓解频繁分段的问题，那就要等软件这边后面升级，增加详细的错误信息之后再看 log 分析对策了。

**Comment by TheDDF6** [comment]
好的，我试试

**Comment by hibiki222** [comment]
这可能不是工具的问题 是b站直播服务器的问题

**Comment by Qixingchen** [comment]
ip 限制只会导致无法监控到新开播,不会录出一堆小文件  
要是你在本地录的,用浏览器打开看看录制断开时直播间是不是也卡了
