### ISSUE TITLE
可以在页面中添加一个每个直播间保存文件夹命名的功能吗

### ISSUE THREAD

**Issue by limoer1** [hr3lxphr6j/bililive-go#337]
### 新功能

因为在抖音的录播过程中，添加了一个主播名字最后带有 ..  这两个符号的，在录制完成后win10系统在本地打不开这个录制的文件夹，应该是命名上的冲突，但是我又不想只为了这一个主播把所有直播间的命名方式更改！

请求加一个在页面中更改直播间命名的功能，感谢大大！

**Comment by kira1928** [comment]
在windows下因为含有特殊字符的直播间名导致无法正常保存或访问文件和目录，类似 https://github.com/hr3lxphr6j/bililive-go/issues/62 这个问题。
你说需要单个直播间的输出文件和文件夹命名功能，这个可以做。不过最好也有一些保障措施，在主播突然换成使用特殊字符直播间名时也能正常保存为一个在windows下可用的文件名，而且这个通用的保护功能的优先级比给单个直播间创建自定义输出文件名模板的优先级要高一些。

**Comment by limoer1** [comment]
期待新版本能更新上这个功能，非常感谢！

**Comment by kira1928** [comment]
在 20 分钟后即将发布的 0.7.8 版本中修复了允许生成以英文句号 `.` 或空格 ` ` 结尾的文件或文件名的 bug。
