### ISSUE TITLE
无法录制twitch

### ISSUE THREAD

**Issue by kingsey** [hr3lxphr6j/bililive-go#34]
录制过程中生成的flv文件无法打开，录制时间短的话是个黑屏的220KB，时间长也只有一帧的画面。国内直播则正常。
网络环境的话是路由器翻墙，同样环境使用Github的其他项目比如streamlink能够正常录制。
系统是win10 LTSC

**Comment by hr3lxphr6j** [comment]
麻烦提供下使用的版本和出现问题的直播间地址

**Comment by kingsey** [comment]
很迷啊...之前连这好几天试了几次都不行。刚刚看到你回复了去试了一下结果没问题了......
版本没换，配置文件也没改的....
总之现在正常了。
