### ISSUE TITLE
关于之前说的虎牙房间封禁 导致重开命令行掉配置  不知道有没有解决办法

### ISSUE THREAD

**Issue by hibiki222** [hr3lxphr6j/bililive-go#341]
不重开命令行的话 是会一直检测主播直到解封的 这也没啥
重开 就会掉配置了  一直都是挂着换盘录 有时候不知道啥时候解封 导致漏录制

**Comment by kira1928** [comment]
掉配置是指哪个房间监控，哪个暂时不监控是吗？那个设定在最新版里已经可以保存进配置文件了，重开也不会掉这个配置的。
不过虎牙房间被封还会继续检测确实烦。你能给一个现在被封了的虎牙主播吗？我想拿来测试看看怎么改善这部分的逻辑。

**Comment by kira1928** [comment]
想起来了，是重开会掉整个被封的房间的配置的问题。
现在在 master branch 中已经修复。相关修正会包含进下一次 release （大概是 0.7.2）中。

**Comment by kira1928** [comment]
0.7.2 在打包了，过25分钟左右就会自动发布，请注意查收。
