### ISSUE TITLE
请求添加快手直播网站

### ISSUE THREAD

**Issue by limoer1** [hr3lxphr6j/bililive-go#342]
### 目标网站任意直播间的示例 url，精确到具体直播间

https://live.kuaishou.com/u/3xegciduu57zbzk

### 列举其他已支持上述网站的开源工具

https://www.52pojie.cn/thread-1648686-1-1.html

### 自由描述

因为家中老人和小孩都用快手，我也不知道为什么，他们说一些直播很容易错过
我用了某站的录制工具，不靠谱，所以还是跑这来请求添加快手直播！

**Comment by limoer1** [comment]
https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder
这位大佬的好像也是，但是我没弄Java环境，不知道怎么用~

**Comment by kira1928** [comment]
新网站请求积攒了有一些了，确实应该处理下的。
不过我现在比较关注那些说录播断断续续的人，想先解决那个大问题。
新增网站如果有参考的话，是比较简单的。等有其他新人想参加项目的时候让他们来试着实现一下也不错。
实在没人的话，就等我修复了上面那个大问题以后再来增加这些新网站吧。
快手直播我看了一下，对我这里有一些限制，需要登陆一个cookie才能正常获取到直播地址，其他的似乎不是很复杂。

**Comment by Blackmaginitaimei** [comment]
同求快手，快手这样用户基数大的需求应该比较大的说，希望作者有时间可以加一个。爱你

**Comment by kira1928** [comment]
忘记关闭了。
现在录快手没有cookie好像有点问题，但至少可以录了。
