### ISSUE TITLE
请求增加录播文件浏览和在线播放功能,谢谢

### ISSUE THREAD

**Issue by guardiora** [hr3lxphr6j/bililive-go#343]
### 新功能

麻烦增加侧边栏录播文件浏览和在线播放功能,谢谢

**Comment by kira1928** [comment]
我也需要这个功能！

**Comment by zsinba** [comment]
控制文件权限；
播放列表 ；
播放及下载记录；
格式转换。
这是一个大的方向，还需要进一步从长远考虑

**Comment by kira1928** [comment]
大概会和 https://github.com/BililiveRecorder/BililiveRecorder-WebUI 一样，提供文件列表，点击打开一个类似b站网页端的播放器播放。
播放记录，播放列表之类需要保存设置，没有数据库比较不方便。
格式转换应该不用，现有 flv.js 可以在除 ios 以外几乎所有设备的浏览器上播放，够用了。
真要实时转换格式直播，有些没有浮点运算能力的低配设备未必跑得动。

**Comment by kira1928** [comment]
已在 0.7.10 版本中实现！
