### ISSUE TITLE
m1 mac和docker均有问题，无法正常使用

### ISSUE THREAD

**Issue by sirlioniva** [hr3lxphr6j/bililive-go#347]
docker，我使用的就是chigusa/bililive-go镜像，但是部署后，只能添加b站的直播间，而且可以正常录制，其他任何直播间都加不进去，不管是网页添加，还是直接修改配置文件，如果是修改配置文件加入斗鱼直播间，直接docker就连不上启动失败了
配置文件也是很正常的
```
rpc:
  enable: true
  bind: :8080
debug: true
interval: 20
out_put_path: /srv/bililive
feature:
  use_native_flv_parser: false
live_rooms:
- url: https://live.bilibili.com/2807295
  is_listening: true
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 10m0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000
```

mac我使用的bililive-darwin-arm64和bililive-windows-arm64（在虚拟机中使用），均出现一个问题，就是有时斗鱼候录制出来的视频会卡顿，看视频容量比其他的小就知道下载过程中出现了断连，但是出现几率比较高，我甚至同时开启两个进程一起下载，都会随机出现某个视频断链容量变小（而且不是不分割文件就不会断链，基本上容量只要变小的，多多少少都卡顿了一部分画面，有的会每隔xx秒就卡一次，容量就特别小，有的随机几个画面突发卡顿，容量就小一点，我的配置和docker的这个一模一样）

<img width="594" alt="截屏2023-01-21 12 36 21" src="https://user-images.githubusercontent.com/123224923/213843619-e5ec0435-fa1b-4c72-926d-66ed43881944.png">

因为我只有录制斗鱼的需求，所以docker完全没法用，然后arm的两个版本都录出来的视频不行，win本我手头没有，无法测试了，而且我在用这个录制的同时，直接把推流放在浏览器里面录制，是没有任何问题和卡顿断链的，哪怕这文件到20g都不会卡顿，而且同时下载几个同一个直播间的推流也不会出现卡顿，所以应该是软件下载的时候出现了问题才对（难道这个app被斗鱼风控了？）

**Comment by kira1928** [comment]
你用的是 0.7.1 的版本吗？
录制不了的直播间可以发任意一个出来吗？
录制不了的时候命令行有没有输出错误信息？可以提供一下吗？

**Comment by sirlioniva** [comment]
> 你用的是 0.7.2 的版本吗？
> 录制不了的直播间可以发任意一个出来吗？
> 录制不了的时候命令行有没有输出错误信息？可以提供一下吗？

是最新版，docker也更新过了，0.7.2
比如周淑怡直播间https://www.douyu.com/290935，我还在douyin，huya都找过随机直播间，都加不进去，只有b站能加进去
docker我不知道在哪里看错误信息，会存在哪个地址呢？（我对这些都是一知半解，勉强能用的状态，望见谅）

**Comment by kira1928** [comment]
不是 docker 的时候，比如 m1 命令行执行的话是可以看到错误信息的。这时候添加房间失败的错误信息有吗？

**Comment by sirlioniva** [comment]
> 不是 docker 的时候，比如 m1 命令行执行的话是可以看到错误信息的。这时候添加房间失败的错误信息有吗？

mac只有录制的视频卡顿，容量偏小的问题，没有加不进去的问题，和docker是不同的问题

**Comment by kira1928** [comment]
在 mac 上你是如何启动 docker 的？可以发一下启动参数吗？

**Comment by sirlioniva** [comment]
> 在 mac 上你是如何启动 docker 的？可以发一下启动参数吗？

坏了，我忘说了，docker不是在mac上的，是在我的路由器里的，路由器用的simpledocker，这个界面里面没有可以看命令行的地方
<img width="701" alt="截屏2023-01-21 13 18 17" src="https://user-images.githubusercontent.com/123224923/213844848-e53f9283-e9fc-4254-b4a7-37fc5070a8d1.png">

**Comment by kira1928** [comment]
嗯，能透漏一下路由器的型号吗？我看看他docker怎么个跑法。
还有 0.7.2 的话，可以在网页版左侧打开系统信息面板，下面有一个复制信息到剪贴板的按钮，按一下，然后把那个剪贴板内的信息也发上来好吗？

**Comment by sirlioniva** [comment]
> 在 mac 上你是如何启动 docker 的？可以发一下启动参数吗？

我是在路由器上部署的docker，simpledocker，我刚才重新启动docker，添加了一下斗鱼直播间，没任何反应，这是我找到的日志
`time="2023-01-21 13:22:13" level=info msg="BiliLive-go Version: v0.7.2 Link Start"
time="2023-01-21 13:22:13" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.2 BuildTime:2023-01-20_14:52:54 GitHash:4e708fc4a523e3736eb9a6fe91c94604635f182e Pid:7 Platform:linux/arm64 GoVersion:go1.19.5}"
time="2023-01-21 13:22:13" level=debug msg="&{File:/etc/bililive-go/config.yml RPC:{Enable:true Bind::8080} Debug:true Interval:20 OutPutPath:/srv/bililive Feature:{UseNativeFlvParser:false} LiveRooms:[] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:10m0s} Cookies:map[] OnRecordFinished:{ConvertToMp4:false DeleteFlvAfterConvert:false} TimeoutInUs:60000000 liveRoomIndexCache:map[]}"
time="2023-01-21 13:22:13" level=info msg="Server start at :8080"
time="2023-01-21 13:22:14" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:22:14" level=debug msg="Http Request" Method=GET Path=/static/js/main.154d97ce.chunk.js RemoteAddr="192.168.0.2:53701"
time="2023-01-21 13:22:14" level=debug msg="Http Request" Method=GET Path=/static/css/2.5b1f1a89.chunk.css RemoteAddr="192.168.0.2:53699"
time="2023-01-21 13:22:14" level=debug msg="Http Request" Method=GET Path=/static/css/main.2a98fe54.chunk.css RemoteAddr="192.168.0.2:53698"
time="2023-01-21 13:22:14" level=debug msg="Http Request" Method=GET Path=/static/js/2.9f0f35e8.chunk.js RemoteAddr="192.168.0.2:53700"
time="2023-01-21 13:22:14" level=debug msg="Http Request" Method=GET Path=/manifest.json RemoteAddr="192.168.0.2:53697"
time="2023-01-21 13:22:15" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:22:16" level=debug msg="Http Request" Method=GET Path=/api/raw-config RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:22:18" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:22:30" level=debug msg="Http Request" Method=GET Path=/api/raw-config RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:22:57" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:22:59" level=debug msg="Http Request" Method=POST Path=/api/lives RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:23:33" level=debug msg="Http Request" Method=PUT Path=/api/config RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:23:33" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:23:34" level=debug msg="Http Request" Method=GET Path=/api/info RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:23:35" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="192.168.0.2:53696"
`

**Comment by kira1928** [comment]
感谢详细的介绍！
```
time="2023-01-21 13:22:59" level=debug msg="Http Request" Method=POST Path=/api/lives RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:23:33" level=debug msg="Http Request" Method=PUT Path=/api/config RemoteAddr="192.168.0.2:53696"
time="2023-01-21 13:23:33" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="192.168.0.2:53696"
```
看这段通信记录应该是添加房间时的通信内容。最后没添加成功但也没有错误信息呢。我本地试了一下，确实添加失败也不会有任何提示，这不太好。
关于错误信息不足的问题，我们这里是有一个 issue 的：https://github.com/hr3lxphr6j/bililive-go/issues/299 。
如果你不急的话，我这两天看看能不能完善一下 log，然后你之后用 0.7.3 之类的新版本再启动看看？
到时候应该会比较容易排查问题。

**Comment by sirlioniva** [comment]
好的，我会第一时间更新，

还有mac上斗鱼的视频会卡顿容量变小丢失一部分视频帧，这个问题可以帮忙看一下嘛

**Comment by kira1928** [comment]
斗鱼录制问题，嗯，有很多这类问题。
我感觉这个修复比较困难， 所以把修复它们作为下一个大版本更新的目标了。
你可以看一下我预计在 0.8.0 中修复的[其他 issue](https://github.com/hr3lxphr6j/bililive-go/milestone/3)，有些和你的情况是比较相似的。
这个说实话修不修的好我也不是很有信心。不过有一点你可以先试一下，就是把配置的 `use_native_flv_parser` 改为 `true`。有人反映这样录制的效果比用默认ffmpeg的要好。
不过这个 flv parser 也有它特有的问题。反正先等 0.8.0 吧。。

**Comment by sirlioniva** [comment]
好的，期待更新，谢谢啦

**Comment by kira1928** [comment]
另外我想问一下你用的是什么浏览器？我写的复制到剪贴板按钮在你那里为什么不支持呢orz

**Comment by sirlioniva** [comment]
> 另外我想问一下你用的是什么浏览器？我写的复制到剪贴板按钮在你那里为什么不支持呢orz

safari，mac下的是支持的，路由docker的不行

**Comment by kira1928** [comment]
那就有点奇怪了。这个功能是一个前端的 javascript 函数，按理说 mac 和 docker 的网页前端代码应该是一样的。
嗯，很多问题。
我可能得买一台你那个路由器试试看了。正好过年，我考虑考虑。

**Comment by kira1928** [comment]
你的路由器固件版本是多少呀？我查了一下，有人说这个路由器本身有频繁断流的问题：https://www.bilibili.com/video/BV1kZ4y147tf
但是你的 mac 没有断流问题，是不是你的 mac 不是连这台路由器上的网呢？

**Comment by sirlioniva** [comment]
> 你的路由器固件版本是多少呀？我查了一下，有人说这个路由器本身有频繁断流的问题：https://www.bilibili.com/video/BV1kZ4y147tf ，https://www.bilibili.com/video/BV1y94y1S7hN ， https://www.bilibili.com/video/BV1Gt4y137bw

已经是最新版1.0.22了，断流问题我从来没遇到过，而且我如果直接用浏览器下载推流，全程是不会有任何卡顿和丢帧的，我即便是同一个直播间下载2 3个，下下来的都不会卡顿丢帧，但是全部需要我自己手动，所以我才想找个专门的软件，但现在就是似乎这个软件会随机卡顿丢帧，导致视频不完整了

那个flv的选项我开了，录制斗鱼的视频全部变成1分钟一小段，设置的时间分段不生效，而且每一段1分钟的视频彼此也不是100%连续，会有几秒的重复，很奇怪

**Comment by kira1928** [comment]
我这里重现不了，好痛苦 ><

> 而且我如果直接用浏览器下载推流，全程是不会有任何卡顿和丢帧的

你这里说的用浏览器下载推流，下载的是在哪里取得的 url 呀？

**Comment by sirlioniva** [comment]
> 我这里重现不了，好痛苦 ><
> 
> > 而且我如果直接用浏览器下载推流，全程是不会有任何卡顿和丢帧的
> 
> 你这里说的用浏览器下载推流，下载的是在哪里取得的 url 呀？

其他的斗鱼插件，可以复制推流地址，放入本地播放器播放

**Comment by kira1928** [comment]
啊啊！那个插件连接可以发一下吗？我看看我们用的链接一不一样。

**Comment by sirlioniva** [comment]
douyuex，github就有

**Comment by kira1928** [comment]
谢谢，我有台m1 mac，我试试

**Comment by kira1928** [comment]
啊对了再问一下，你m1 mac用的ffmpeg是怎么安装的，还有安装的版本可以告知一下吗

**Comment by sirlioniva** [comment]
就是homebrew安装的
ffmpeg -version
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.202)

**Comment by kira1928** [comment]
我发现在设置里打开 debug: true 会输出很多有用的关于录制问题的错误信息。你有时间的话，可以在 mac 上打开这个配置路一段发生卡顿的直播，然后设法保存输出的log吗？
打开之后输出的 log 量挺大的，要小心。

**Comment by sirlioniva** [comment]
> 我发现在设置里打开 debug: true 会输出很多有用的关于录制问题的错误信息。你有时间的话，可以在 mac 上打开这个配置路一段发生卡顿的直播，然后设法保存输出的log吗？
> 打开之后输出的 log 量挺大的，要小心。

刚好录了一段，倒数第二个视频出现卡顿，最后一个视频是正常的，但视频我删了，只有命令行里的记录了，你看看是不是你需要的
[终端存储的输出.txt](https://github.com/hr3lxphr6j/bililive-go/files/10472646/default.txt)

**Comment by sirlioniva** [comment]
> 我发现在设置里打开 debug: true 会输出很多有用的关于录制问题的错误信息。你有时间的话，可以在 mac 上打开这个配置路一段发生卡顿的直播，然后设法保存输出的log吗？
> 打开之后输出的 log 量挺大的，要小心。

今天也录制了一遍，也出现了很多次视频卡顿容量偏小的情况，做一下参考
<img width="644" alt="截屏2023-01-22 22 35 35" src="https://user-images.githubusercontent.com/123224923/213921556-9a4d9bb7-bacb-4ef8-b0b9-346a70958ecb.png">
[终端存储的输出.txt](https://github.com/hr3lxphr6j/bililive-go/files/10474634/default.txt)

**Comment by kira1928** [comment]
感谢提供log！
这周末没做出输出详细log的功能。。
周一到周五上班时间比较忙（刚入职要好好表现），可能要拖到下周末或以后了。

**Comment by kira1928** [comment]
请看一下这位大佬的回答：https://github.com/hr3lxphr6j/bililive-go/issues/351#issuecomment-1400720052
也许能帮助解决 docker 内无法添加直播间的问题。

**Comment by sirlioniva** [comment]
m1 mac使用最新的0.7.3，使用use_native_flv_parser: true后，录制卡顿情况大幅度减少，但是路由器docker依然无法录制非b站以外的直播间，6088的docker暂未找到+dns命令的办法，有个命令行输入的地方但是加入命令后，docker启动失败，不会折腾，没法确认到底什么问题

**Comment by kira1928** [comment]
我在 master branch 里加入了输出更多 debug 信息的代码，等一会儿应该会发布一个 0.7.4 版本的 release。之后你用 docker 安装 0.7.4 ，然后看一下 debug: true 设置下的 log 好吗？
这个只有 b 站可以录制的情况如果真的是 dns 问题，新增加的 debug log 也许能帮我缩小可能出问题的范围。

**Comment by sirlioniva** [comment]
> 我在 master branch 里加入了输出更多 debug 信息的代码，等一会儿应该会发布一个 0.7.4 版本的 release。之后你用 docker 安装 0.7.4 ，然后看一下 debug: true 设置下的 log 好吗？
> 这个只有 b 站可以录制的情况如果真的是 dns 问题，新增加的 debug log 也许能帮我缩小可能出问题的范围。

用0.7.4有debug了，依然是斗鱼无法添加，b站可以
[c6225ee6cf3a-all.log](https://github.com/hr3lxphr6j/bililive-go/files/10555990/c6225ee6cf3a-all.log)

**Comment by kira1928** [comment]
@sirlioniva 
这个周末有空吗？可以加qq群交流吗？
我想看一下你那边的docker的情况，然后让你敲几个命令试试看。

群名称：非官方bililive-go交流群
群号：765848211

**Comment by hanmingpan** [comment]
这个问题解决了吗？我也遇到同样的问题

**Comment by hanmingpan** [comment]
@sirlioniva @kira1928 
这个问题解决了吗？我也遇到同样的问题
