### ISSUE TITLE
录制的flv文件无法快进或拖动到特定的时间点播放

### ISSUE THREAD

**Issue by ykjyhmj** [hr3lxphr6j/bililive-go#35]
你好，

我发现录制的flv文件无法快进，这正常吗，还是我使用的播放器的问题。 我现在在手机上尝试过infuse， Vidon，playerXtreme等多个播放器，均不可拖拽播放。

谢谢

**Comment by hr3lxphr6j** [comment]
需要自己重新封装到mp4

[reformat2mp4.sh](https://gist.github.com/hr3lxphr6j/827060b7f0ceedad829da11694dcbccc)

**Comment by Lase75** [comment]
可以修改源码，使用ffmpeg封装的格式为mp4
