### ISSUE TITLE
[Bug]: 在网页上无法添加直播间 点击添加后无反应 

### ISSUE THREAD

**Issue by muyun5** [hr3lxphr6j/bililive-go#350]
### 程序版本

0.7.2

### 自由描述

使用的是树莓派 armv7 docker 最新0.7.2版 在网页上无法添加直播间  点击添加后无反应 查看日志 只用启动运行那两行 日志。

**Comment by sirlioniva** [comment]
也是docker无法添加直播间？你试试是不是只能添加b站的，其他站都不行

**Comment by muyun5** [comment]
> 也是docker无法添加直播间？你试试是不是只能添加b站的，其他站都不行

我试了抖音 跟b站都不行 感觉是网页无法传递    点击添加直播间  无反应 日志没有任何信息

**Comment by kira1928** [comment]
@sirlioniva 我在想是不是 arm 的问题了。
毕竟你们的设备和路由器都是 arm 的。

**Comment by muyun5** [comment]
> 可以提供一个你添加失败的直播间的 url 吗？我这边试一下。我也是在 docker 里跑的 0.7.2，我是群晖，intel 的 cpu。

https://live.bilibili.com/23584459   我添加的直播间都是随机找的测试用的  我感觉可能也是arm问题  我之前黑裙可以正常使用

**Comment by kira1928** [comment]
我这里添加成功了。看来确实是其他原因。
你在树莓派上安装黑群晖以前能用的版本试试看如何？这样可以排除是后续版本引入的 bug 的可能。

**Comment by muyun5** [comment]
> 我这里添加成功了。看来确实是其他原因。 你在树莓派上安装黑群晖以前能用的版本试试看如何？这样可以排除是后续版本引入的 bug 的可能。

我之前黑裙不是在树莓派上运行的  之前的黑裙是j1900

**Comment by kira1928** [comment]
嗯，不是说在树莓派上安装黑群，是安装你以前在黑裙上安的 blilive-go 的版本。
比如你这次在树莓派用了 0.7.2， 以前在 j1900 的黑裙上跑的 0.6.4 的话，现在用树莓派也跑一下 0.6.4 看看能不能正常添加直播间。

**Comment by muyun5** [comment]
> 嗯，不是说在树莓派上安装黑群，是安装你以前在黑裙上安的 blilive-go 的版本。 比如你这次在树莓派用了 0.7.2， 以前在 j1900 的黑裙上跑的 0.6.4 的话，现在用树莓派也跑一下 0.6.4 看看能不能正常添加直播间。

我的黑裙硬盘丢失了 忘记之前下的版本了  但我在树莓派上试了0.6.4-0.6.5  情况跟最新版本的一样 无反应无日志

**Comment by kira1928** [comment]
请看一下这位大佬的回答：https://github.com/hr3lxphr6j/bililive-go/issues/351#issuecomment-1400720052
也许能帮助解决 docker 内无法添加直播间的问题。

**Comment by sirlioniva** [comment]
> 请看一下这位大佬的回答：[#351 (comment)](https://github.com/hr3lxphr6j/bililive-go/issues/351#issuecomment-1400720052)
> 也许能帮助解决 docker 内无法添加直播间的问题。

我的simpledocker没研究明白怎么加dns命令，让这位兄弟试试吧
但那个贴里面的四个直播间，我都是可以直接添加的，不像他只有一个不行，b站我就没找到添加不了的，除非直播间不存在

但是斗鱼是一个都不行

**Comment by kira1928** [comment]
@sirlioniva 
具体症状可能不同，但是你那边成功和失败都是整个域名都成功或都失败，看起来确实有点像 dns 问题。

**Comment by insoxin** [comment]
如果会抓包,建议抓包看一下 能精确到具体原因

**Comment by kira1928** [comment]
提问者失联，issue关闭。
