### ISSUE TITLE
配置文件里的第一个直播间识别不到

### ISSUE THREAD

**Issue by OXYG4TE** [hr3lxphr6j/bililive-go#351]
0.7.2   Docker版  linux/AMD64
配置文件里的第一个直播间识别不到报了个Error。
此时用网页端编辑配置文件，浏览器会弹框Server Error。
其他直播间与其他功能一切正常。

Config：
rpc:
  enable: true
  bind: :8080
debug: true
interval: 30
out_put_path: /srv/bililive
feature:
  use_native_flv_parser: false
live_rooms:
- url: https://live.bilibili.com/3917826
  is_listening: false
- url: https://live.bilibili.com/8035609
  is_listening: true
- url: https://live.bilibili.com/41056
  is_listening: true
- url: https://live.bilibili.com/23387936
  is_listening: true
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 2h0m0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

Log：
time="2023-01-24 00:56:33" level=info msg="BiliLive-go Version: v0.7.2 Link Start"
time="2023-01-24 00:56:33" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.2 BuildTime:2023-01-20_14:52:18 GitHash:4e708fc4a523e3736eb9a6fe91c94604635f182e Pid:1 Platform:linux/amd64 GoVersion:go1.19.5}"
time="2023-01-24 00:56:33" level=debug msg="&{File:/etc/bililive-go/config.yml RPC:{Enable:true Bind::8080} Debug:true Interval:20 OutPutPath:/srv/bililive Feature:{UseNativeFlvParser:false} LiveRooms:[{Url:https://live.bilibili.com/3917826 IsListening:true LiveId:} {Url:https://live.bilibili.com/8035609 IsListening:true LiveId:}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:2h0m0s} Cookies:map[] OnRecordFinished:{ConvertToMp4:false DeleteFlvAfterConvert:false} TimeoutInUs:60000000 liveRoomIndexCache:map[https://live.bilibili.com/3917826:0 https://live.bilibili.com/8035609:1]}"
time="2023-01-24 00:57:06" level=error msg="Get \"https://api.live.bilibili.com/room/v1/Room/room_init?id=3917826\": dial tcp: lookup api.live.bilibili.com on 127.0.0.11:53: read udp 127.0.0.1:32894->127.0.0.11:53: i/o timeout" url="&{https://live.bilibili.com/3917826 true }"
time="2023-01-24 00:57:07" level=info msg="Server start at :8080"
time="2023-01-24 00:57:23" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="10.0.0.233:41942"
time="2023-01-24 00:57:31" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="10.0.0.233:41990"
time="2023-01-24 00:57:39" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="10.0.0.2:58411"

**Comment by Qixingchen** [comment]
docker 的 DNS 不可用，参考 https://docs.docker.com/config/containers/container-networking/#dns-services docker 命令加个 --dns 119.29.29.29 （国外加 --dns 8.8.8.8 ）

**Comment by OXYG4TE** [comment]
> docker 的 DNS 不可用，参考 https://docs.docker.com/config/containers/container-networking/#dns-services docker 命令加个 --dns 119.29.29.29 （国外加 --dns 8.8.8.8 ）

感谢  已解决  作者辛苦了！

**Comment by Qixingchen** [comment]
#350  可能也是这个同样的问题
