### ISSUE TITLE
[Bug]: 虎牙一分钟一段.恢复了旧版本v0.6.4 正常了 抖音也是一分钟一段

### ISSUE THREAD

**Issue by insoxin** [hr3lxphr6j/bililive-go#354]
### 程序版本

v0.7.2

### 所使用的 config 文件的内容

out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 1h0m0s
cookies:
  live.douyin.com: name1=qwer;name2=asdf
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

### 自由描述

@kira1928 大佬,发现这两天发现虎牙一分钟一段.恢复了旧版本v0.6.4 正常了 抖音也是一分钟一段
新版蛮多未适配,手机测试menu和直播平台不显示

> @insoxin 大佬可以单独发 issue 吗？你写这儿我不太好统计 issue 呃...
> 虎牙频繁分段的问题我是听说过，但我从 0.6.4 以来改过的唯一一个和录制有关的地方就是把 timeout 给提到配置文件里了。
> 你看看你的配置文件里 timeout_in_us 设置的是多少？默认应该是 60000000 左右。太小有可能导致网络稍微卡顿就自动分段了。
> 
> 网页端适配手机我是一点儿没碰，我以前用的时候也发现用手机会有些列不显示，或者横屏刷新显示，这时候竖过来就没事。一开始就竖屏刷新就会有些列一直不显示。
> 反正前端是有些问题的。我计划在 [这个里程碑](https://github.com/hr3lxphr6j/bililive-go/milestone/4) 中大幅翻新维修网页UI，可以麻烦你另外新建一个 issue，然后把你这里的提问复制过去吗？最好把我的这段回复也复制过去，然后我把你的新 issue 包括进里程碑里，以防遗漏。

**Comment by insoxin** [comment]
timeout_in_us 是默认.我测试一下
 
 rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 15
out_put_path: ./
feature:
  use_native_flv_parser: true
live_rooms:
- url: https://www.huya.com/863725
  is_listening: true
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000


全新配置,依旧

![image](https://user-images.githubusercontent.com/19371836/214523558-7ba9a514-648d-4fe7-95a8-bb67ba8a0a95.png)

**Comment by kira1928** [comment]
看文件修改时间，除了整60秒的以外，还有整30秒的是吗？还是最后那个是正在录制的文件？

**Comment by kira1928** [comment]
这个 60 秒切割的如此完美，很难想象这是网络波动造成的。
看来我的追加 error log 的 issue 需要加速了。

目前暂时还有一个获得详细 log 方法，是把配置的 `debug: false` 改成 `true`。这样会额外输出大量调试信息。
你可以打开那个 flag 然后看看分段的时候有没有输出什么有用的错误信息吗？

**Comment by insoxin** [comment]
time="2023-01-25 17:17:37" level=info msg="BiliLive-go Version: v0.7.2 Link Start"
time="2023-01-25 17:17:37" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.2 BuildTime:2023-01-20_14:52:18 GitHash:4e708fc4a523e3736eb9a6fe91c94604635f182e Pid:12886 Platform:linux/amd64 GoVersion:go1.19.5}"
time="2023-01-25 17:17:37" level=debug msg="&{File:/www/tool/bililive/lu/config.yml RPC:{Enable:true Bind:127.0.0.1:8080} Debug:true Interval:15 OutPutPath:./ Feature:{UseNativeFlvParser:true} LiveRooms:[{Url:https://www.huya.com/863725 IsListening:true LiveId:}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s} Cookies:map[] OnRecordFinished:{ConvertToMp4:false DeleteFlvAfterConvert:false} TimeoutInUs:600000000 liveRoomIndexCache:map[https://www.huya.com/863725:0]}"
time="2023-01-25 17:17:38" level=info msg="Server start at 127.0.0.1:8080"
time="2023-01-25 17:17:38" level=error msg="listen tcp 127.0.0.1:8080: bind: address already in use"
time="2023-01-25 17:17:38" level=info msg="Live Start" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"
time="2023-01-25 17:17:38" level=info msg="Record Start" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"

> 这个 60 秒切割的如此完美，很难想象这是网络波动造成的。 看来我的追加 error log 的 issue 需要加速了。
> 
> 目前暂时还有一个获得详细 log 方法，是把配置的 `debug: false` 改成 `true`。这样会额外输出大量调试信息。 你可以打开那个 flag 然后看看分段的时候有没有输出什么有用的错误信息吗？

**Comment by insoxin** [comment]
> 哦哦哦！没有 ffmpeg 进程是因为 ` use_native_flv_parser: true` 这个配置。 改成 false 就有 ffmpeg 了。 这两种录制方法各有利弊。未来尽量想放弃 ffmpeg，改为优化那个 flv parser。这个目标预计在[ 0.8.0 的里程碑](https://github.com/hr3lxphr6j/bililive-go/milestone/3)中完成。 没完成就当我没说吧= =

feature:
  use_native_flv_parser: true这个配置我从使用这个工具就下意识开启了,因为之前b站不开这个花屏,养成习惯后,我就一直开了

**Comment by kira1928** [comment]
是的，毕竟它解决的问题比较关键。
后面我会专门强化它的。
flv parser，已有也许会有 hls/m3u8 parser，都会有的！

**Comment by insoxin** [comment]
> 嗯，就是这个，打开之后放一会儿，放到视频分段的时候看看有没有什么log输出。

打开这个[开始](debug:true),竟然不分段了,神奇 我关闭再试下

**Comment by insoxin** [comment]
卧槽,复现不了了,我再重装

**Comment by kira1928** [comment]
也许真是网络波动呢

**Comment by insoxin** [comment]
> 也许真是网络波动呢

这两天出现多次了,虎牙每一个都是,斗鱼没出现 然后我今天恢复旧版本了

![image](https://user-images.githubusercontent.com/19371836/214528570-5ea4eb2b-a2ce-4ff0-9b77-6cd0a690d012.png)

**Comment by insoxin** [comment]
![image](https://user-images.githubusercontent.com/19371836/214529353-b44f49b8-38b2-4943-8da6-c9ba7b921f86.png)
![image](https://user-images.githubusercontent.com/19371836/214529393-f42a444d-20f3-42a5-8ee4-00937a38e8f8.png)
time="2023-01-25 17:37:49" level=info msg="BiliLive-go Version: v0.7.2 Link Start"
time="2023-01-25 17:37:49" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.2 BuildTime:2023-01-20_14:52:18 GitHash:4e708fc4a523e3736eb9a6fe91c94604635f182e Pid:14904 Platform:linux/amd64 GoVersion:go1.19.5}"
time="2023-01-25 17:37:49" level=debug msg="&{File:/www/tool/bililive/lu/config.yml RPC:{Enable:true Bind:127.0.0.1:8080} Debug:true Interval:15 OutPutPath:./ Feature:{UseNativeFlvParser:true} LiveRooms:[{Url:https://www.huya.com/863725 IsListening:true LiveId:}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s} Cookies:map[] OnRecordFinished:{ConvertToMp4:false DeleteFlvAfterConvert:false} TimeoutInUs:60000000 liveRoomIndexCache:map[https://www.huya.com/863725:0]}"
time="2023-01-25 17:37:51" level=info msg="Server start at 127.0.0.1:8080"
time="2023-01-25 17:37:51" level=info msg="Live Start" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"
time="2023-01-25 17:37:51" level=info msg="Record Start" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"
time="2023-01-25 17:38:51" level=debug msg="context deadline exceeded (Client.Timeout or context cancellation while reading body)" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"



复现了

**Comment by insoxin** [comment]
time="2023-01-25 17:37:51" level=info msg="Record Start" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"
time="2023-01-25 17:38:51" level=debug msg="context deadline exceeded (Client.Timeout or context cancellation while reading body)" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"
time="2023-01-25 17:39:51" level=debug msg="context deadline exceeded (Client.Timeout or context cancellation while reading body)" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"
time="2023-01-25 17:40:51" level=debug msg="context deadline exceeded (Client.Timeout or context cancellation while reading body)" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"
time="2023-01-25 17:41:51" level=debug msg="context deadline exceeded (Client.Timeout or context cancellation while reading body)" host="剑雪封喉9527" room="DPC东南亚:Black - SMG"
后面都是如此

**Comment by kira1928** [comment]
应该是和我设的 60 秒超时设置有关了。
这个错误信息 一搜，网上有很多相关文章，我研究一下。
谢谢提供线索！

**Comment by kira1928** [comment]
调查结果是我实现配置文件的 timeout 时错误地把 flv-parser 可以录制的时长搞错成只能录 timeout 那么长的视频了。。
现在我已经紧急修复，准备发布 0.7.3 了。预计 20 分钟之后打包结束，就会自动发布 0.7.3 ，到时候请换用最新版吧。

**Comment by insoxin** [comment]
OK,大佬辛苦

**Comment by insoxin** [comment]
测试了五天,还是会十分钟以内的不规律分段,我把超时时间加了个0改成了一小时希望有效果

**Comment by kira1928** [comment]
10分钟以内断流看起来就比较像[这里](https://github.com/hr3lxphr6j/bililive-go/milestone/3)的那些 issue 的共有问题了。
我要把在这之前想做的 web UI 翻新的里程碑做完之后才会去挑战修理 flv parser。要你等一阵了。。

**Comment by insoxin** [comment]
> 10分钟以内断流看起来就比较像[这里](https://github.com/hr3lxphr6j/bililive-go/milestone/3)的那些 issue 的共有问题了。
> 我要把在这之前想做的 web UI 翻新的里程碑做完之后才会去挑战修理 flv parser。要你等一阵了。。

因为不是所有平台这样,比如B站,斗鱼,都是完整一小时.像虎牙抖音,十分钟以内

**Comment by kira1928** [comment]
抖音也有这个问题好像是第一次听人提到。
这个问题和这个 issue 原本提出的一分钟一段已经是两个不同的 bug 了。
你可以单独创建一个新的 bug issue 吗？我们在那边继续讨论，这边这个 issue 原本的问题已经修复了，就不继续在这边聊了。
