### ISSUE TITLE
douyin  显示该直播只能手机看

### ISSUE THREAD

**Issue by buzhixihuan2021** [hr3lxphr6j/bililive-go#355]
ID  738073130230
在直播，网页打开显示只能手机看，无法获取下载。我看有好多主播都这样设置只能手机看。

**Comment by kira1928** [comment]
能发一下直播间 url 吗？

**Comment by kira1928** [comment]
另外如果有其他开源工具能录制这类直播间，可以提供一下吗？我们可以参考他们的方法添加支持。

**Comment by insoxin** [comment]
> 738073130230

直接提交链接,不能下吗?我还没遇到过这种,我刚打开,提示直播结束

**Comment by kira1928** [comment]
是的，我也是看到直播结束，所以没有看到你说的仅限手机的那个说明。

**Comment by buzhixihuan2021** [comment]
> 

晚上播，网页打开显示只能手机看，手机看是在直播的。

**Comment by Qixingchen** [comment]
聊天室只能手机观看 目前没看到有能录的项目

**Comment by kira1928** [comment]
其他项目都不能录的话，我们也很难做出突破。这个 issue 先关闭了。
如果找到有人有解决办法的话，我们可以跟进修改。
