### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xiatiantiantian** [hr3lxphr6j/bililive-go#36]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x90065b]

goroutine 471 [running]:
github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Close.func1()
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:96 +0x4b
sync.(*Once).Do(0xc000910130, 0xc000cf5f18)
        /usr/local/Cellar/go/1.12.7/libexec/src/sync/once.go:44 +0xba
github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Close(0xc000182000)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:94 +0x59
github.com/hr3lxphr6j/bililive-go/src/recorders.(*RecorderManager).RemoveRecorder(0xc0002115f0, 0xb5d480, 0xc00014a840, 0xc00019eac0, 0x20, 0x0, 0x0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder_manager.go:94 +0xb9
github.com/hr3lxphr6j/bililive-go/src/recorders.(*RecorderManager).Start.func2(0xc000ec6040)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder_manager.go:49 +0xb4
created by github.com/hr3lxphr6j/bililive-go/src/lib/events.(*EventDispatcher).DispatchEvent
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/lib/events/event_dispatcher.go:56 +0xdb

版本v0.3.8 
系统 win10  1903         ffmpeg-4.2-win64-static

（随意选了多个测试都是这样的）长时间一直挂着就会出现上面的错误，意外中断，然后导致视频部分画面丢失，但是音频完整。

**Comment by xiatiantiantian** [comment]
panic: Get https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js: net/http: TLS handshake timeout

goroutine 42 [running]:
github.com/hr3lxphr6j/bililive-go/src/api.loadCryptoJS(...)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:95
github.com/hr3lxphr6j/bililive-go/src/api.getEngineWithCryptoJS(0xc0003c6000, 0xccfb, 0xc000020ea0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:102 +0x165
github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).getSignParams(0xc000190230, 0xa8aa08, 0xc0002abd70, 0x45f4e0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:203 +0x73a
github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).GetStreamUrls(0xc000190230, 0xc000151b60, 0xc0002abe00, 0x4052b3, 0xc000120780, 0x4)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:244 +0x5b
github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).run(0xc0001841c0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:56 +0x7b
created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Start.func1
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:86 +0x4e

有时候还会出现上面的错误

**Comment by AndersonBY** [comment]
第一个错误我也遇到了，长时间就会这样

**Comment by keyingfu0** [comment]
+1,稍微久一点就会这样

**Comment by kira1928** [comment]
issue 年代久远，之后没再看到类似报告，也许已经修复了。这里就先关闭了。
