### ISSUE TITLE
如何在本地代码启动？ windows 系统如何打包？

### ISSUE THREAD

**Issue by kcxg** [hr3lxphr6j/bililive-go#363]
### 新功能

想在本地开发，不知如何操作

**Comment by insoxin** [comment]
跑题了


https://www.runoob.com/go/go-tutorial.html

**Comment by kcxg** [comment]
我会一些基础的语法，但是不知道怎么运行咱的项目

**Comment by kira1928** [comment]
噢噢噢！欢迎！

我刚加入的时候也发现这个项目没有介绍开发环境设置方法的 wiki，着实苦恼了一阵子呢。后面应该会添加这类文档。

这个项目的编译过程包含了一些 linux 的 shell 脚本，所以在 windows 的 cmd 里是很难完成编译的。
我现在是用 windows 的 wsl 创建一个 ubuntu 虚拟机，在里面安装各种需要的工具。
印象中要安装的工具有 ffmpeg，node.js (我安的是 18.12.1)，golang (我安的是 1.19)。别的还有需要的话就按提示安装吧。
全安好之后再按照 [这里](https://github.com/hr3lxphr6j/bililive-go#%E8%8E%B7%E5%8F%96%E7%BC%96%E8%AF%91) 说的步骤执行，应该就能编译了吧。
有一点需要注意的是，如果是想在本地开发调试，最后的 `make` 命令请改成 `make dev`。用 `make` 编译的可执行文件没有单步调试所需的符号等信息，可以执行但不能调试。
编译的时候如果遇到 `go:embed build` 相关的编译错误的话，大概是因为网页端没有被编译，这时候用 `make build-web` 命令先编译一个网页端，然后再执行 make 什么的，应该就能通过了。（我最开始就被这一步卡住了。。）

我刚加入这个项目的时候是连 golang 的语法都不了解，怎么声明变量都要去查的程度。参与过一段时间以后，现在读写 golang 代码已经有一些自信了。参与实际项目开发真的对学习很有帮助，期待你的 PR！

**Comment by kcxg** [comment]
我在  linux  机器上成功啦！ 但不知道如何 给window 机器 编译可执行文件，我在makefile 文件修改了几个参数但是编译出来不可用。
![image](https://user-images.githubusercontent.com/31840413/215729605-fb146987-381f-4965-b77b-94130310a5ad.png)
