### ISSUE TITLE
如何马上应用程序更新？

### ISSUE THREAD

**Issue by sgfadf43** [hr3lxphr6j/bililive-go#369]
使用过程中遇到了一些bug，再来这个项目发现code界面有开发人员说相关bug已经修复了，但是我不知道如何将马上更新到我的windows程序上，该怎么做？还是说应该等待Releases的新发布？纯小白，没有编程相关知识。

**Comment by Qixingchen** [comment]
编译可以参考 #363 ,如果看不懂就等新的 Release

**Comment by kira1928** [comment]
就像楼上说的，目前确实没有更好的办法。。
后续如果有余力，我也许会尝试增加 nightly build，让用户有一个可以直接下载到最新开发版可执行文件的地方。
暂时的话，正好昨天有大佬发了新的 pr，我跟他商量说想给他新增的内容发一个新 release 呢，现在我就把最新版内容整理到 0.7.4 发出来。
自动打包预计20多分钟之后就可以在 release 里看到 0.7.4 了。

**Comment by bulai0408** [comment]
我的做法是使用docker，然后再使用docker的一个镜像，watchtower，拥有当镜像更新自动升级的能力

**Comment by kira1928** [comment]
0.7.4 已经发布，issue 就关闭了。
