### ISSUE TITLE
建了一个 tg 群，方便快速交流问题

### ISSUE THREAD

**Issue by kira1928** [hr3lxphr6j/bililive-go#375]
<del>群名称：非官方bililive-go交流群
群号：765848211
因为不是和原作者商量后建的群，所以暂称"非官方群"。</del>

<del>update:
QQ 炸号，群亡了= =</del>

update:
@paomian 大佬建了一个 telegram 群 性质和 QQ 群一样
https://t.me/+JWHWnxEWsigzMDc1

**Comment by hibiki222** [comment]
> ### 新功能
> 群名称：非官方bililive-go交流群 群号：765848211
> 
> 因为不是和原作者商量后建的群，所以暂称"非官方群"。 我平日不太有精力开发这边，目前是只在周末集中开发一下，所以周末会有比较多进展发在群里（也可能没有进展）。

早就想叫大佬创群了

**Comment by kira1928** [comment]
QQ 炸号，群亡了= =

**Comment by paomian** [comment]
建了一个 telegram 群 性质和 QQ 群一样
https://t.me/+JWHWnxEWsigzMDc1

**Comment by a1007182533** [comment]
Q群能加下我吗？

**Comment by ColorfulDick** [comment]
> Q群能加下我吗？

群都无了咋加，找老哥建个新的吧，正好工作原因最近在搞多模态模型的音视频集成和视频爬取，可以贡献一些小功能

**Comment by alibabacn** [comment]
求作者加个web网页密码，我在服务器着了，被人把直播间都删了，过了几天我才发现 我直接当场气吐血
