### ISSUE TITLE
[Bug]: 貌似是抖音直播的紧急BUG

### ISSUE THREAD

**Issue by limoer1** [hr3lxphr6j/bililive-go#376]
### 程序版本

0.7.0   0.7.4

### 程序 log

![微信图片_20230206180008](https://user-images.githubusercontent.com/122724907/216942964-8531d27a-8edf-42fe-a993-ca47913190e5.png)

### 自由描述

从今天下午开始程序突然报错
我以为是我添加的直播间链接的问题
但我清空所有直播间链接
重新从0开始添加时，还是添加不了抖音的直播间
并且只要一添加抖音的直播间，就会疯狂报错！！

**Comment by limoer1** [comment]
一直显示  403行的代码错误~

**Comment by limoer1** [comment]
![image](https://user-images.githubusercontent.com/122724907/216944115-4f9004b7-8d4d-4097-8d9a-66f12cce49ab.png)

**Comment by kcxg** [comment]
我也有相同的问题

**Comment by limoer1** [comment]
有没有进了Q群的，和大佬说一下这个紧急BUG！

**Comment by menheng** [comment]
用cookie也这样吗？

**Comment by kira1928** [comment]
我好像发现了一个 cookie 相关的 bug。
就是 config 里设置的cookie只对在程序启动的瞬间就存在的直播间才有效，后面添加的直播间会无视config里的cookie。

暂时可以试试手动把抖音房间写进config，然后抖音的cookie也设置好，再重启一次程序，这样写进去的抖音就可以录制了，大概。。

今天有点忙，我得继续工作了。这个问题可能周末修。。
或者有没有好心人可以帮忙看一下 ><

启动时设置cookie的代码是这里：https://github.com/hr3lxphr6j/bililive-go/blob/master/src/cmd/bililive/bililive.go#L109
运行中添加直播间的代码大致在这个范围里：https://github.com/hr3lxphr6j/bililive-go/blob/master/src/servers/handler.go#L133-L190

然后就是等一个好心人了。。

**Comment by kira1928** [comment]
0.7.5 修复了 添加直播间时不使用 cookie 的 bug。
抖音直播间现在需要用户填入 cookie 才能录制。
我写了一个随机生成抖音 cookie 的功能 merge 进 master branch 了，会在下一个版本中发布。
这边的 issue 基本对应完了，就关掉啦。
