### ISSUE TITLE
无法添加抖音直播间

### ISSUE THREAD

**Issue by Loong0201** [hr3lxphr6j/bililive-go#381]
![IMG_20230207_012132.jpg](https://user-images.githubusercontent.com/123194940/217061395-7ed0759c-3d65-4007-8212-a41f6f86d3dd.jpg)

**Comment by Loong0201** [comment]
![Uploading IMG_20230207_012132.jpg …

**Comment by joyyes1203** [comment]
我添加了cookie就能添加和录制了

**Comment by kira1928** [comment]
似乎从昨天开始，抖音需要添加cookie才能录制了。

**Comment by Loong0201** [comment]
> 似乎从昨天开始，抖音需要添加cookie才能录制了。

怎么弄呢

**Comment by kira1928** [comment]
参考这里：https://github.com/hr3lxphr6j/bililive-go#cookie-%E5%9C%A8-configyml-%E4%B8%AD%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95

**Comment by Loong0201** [comment]
> 参考这里：https://github.com/hr3lxphr6j/bililive-go#cookie-%E5%9C%A8-configyml-%E4%B8%AD%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95

在cmd里弄是吧

**Comment by kira1928** [comment]
在 config.yml 里写。你打开那个文件看到格式就大概理解了。

**Comment by Loong0201** [comment]
> 在 config.yml 里写。你打开那个文件看到格式就大概理解了。


![IMG_20230207_143703.jpg](https://user-images.githubusercontent.com/123194940/217167337-a1206175-f5da-4c9c-aa72-1b2151130514.jpg)

**Comment by kira1928** [comment]
在网页上修改设置的功能在抖音出问题以后好像就不能用了，会一直弹server error的警告吧？
最好直接打开那个文件加入上面的内容。
另外cookie的内容属于隐私，图片最好打上马赛克再发上来。。
最后，cookies下面那行字前面需要有两个空格，这个挺重要的，不能省略（也许可以，没试过，印象中不能省略）。

**Comment by Loong0201** [comment]
> 在网页上修改设置的功能在抖音出问题以后好像就不能用了，会一直弹server error的警告吧？
> 最好直接打开那个文件加入上面的内容。
> 另外cookie的内容属于隐私，图片最好打上马赛克再发上来。。
> 最后，cookies下面那行字前面需要有两个空格，这个挺重要的，不能省略（也许可以，没试过，印象中不能省略）。


用什么打开呢，我按了跳出让我上微软商店找

**Comment by kira1928** [comment]
应该说任何文本编辑器都可以，记事本也可以。

**Comment by Loong0201** [comment]
> 应该说任何文本编辑器都可以，记事本也可以

试过了还是不行

**Comment by kira1928** [comment]
不行具体指什么症状？
用记事本打不开 config.yml 文件吗？还是打开编辑后无法保存？还是保存后依然无法录制抖音？

**Comment by Loong0201** [comment]
> 不行具体指什么症状？
> 用记事本打不开 config.yml 文件吗？还是打开编辑后无法保存？还是保存后依然无法录制抖音？

还是不能录制

**Comment by kira1928** [comment]
修改保存配置文件后需要重启一次程序才能生效。

**Comment by nixingshiguang** [comment]
请教下这个cookie怎么获取，获取之后是啊一段？

**Comment by Loong0201** [comment]
> 修改保存配置文件后需要重启一次程序才能生效。

成功了

**Comment by kira1928** [comment]
近期有很多人录制抖音遇到问题，这个 issue 就先不关闭，保留一段时间给别人做参考了。

**Comment by xboylegend** [comment]
请问一下，我使用的是Docker镜像运行的，请问怎么在config.yml里添加cookie呢？，我通过网页控制台的设置功能，在设置文件里，添加了抖音的cookie，依旧无法添加抖音的直播间。我尝试编辑镜像里的/etc/bililive-go/config.yml文件，在文件里添加抖音的cookie，结果保存以后重启Docker容器就无法启动了。显示config.yml的内容错误。
请问这两个修改config.yml的方式，哪个是对的呢？我无法启动，是不是我填写的cookie填的不对。

**Comment by xboylegend** [comment]
搞不明白怎么才能顺利添加抖音直播间，哪位好心人能给出个教程吗？

**Comment by kira1928** [comment]
@xboylegend 
你好，改docker里的设置文件，网页版现在在（抖音）直播间有问题的时候保存设置有问题。
我推荐的方式是直接改 docker 里的文件。
如果你会登陆进 docker，可以在容器的 /etc/bililive-go/config.yml 处修改它。
如果不方便登陆 docker 的话，可以把那个文件映射到容器外面，然后手动修改那个文件。
像这样：
![W452GEX VTB3}PT8$Y(B(A](https://user-images.githubusercontent.com/2352900/217471708-00701cff-dc77-4c27-87bb-46307b9ec783.png)

**Comment by kira1928** [comment]
你修改以后显示 config.yml 的内容错误，可以把你修改后的 config.yml 的内容发出来我看一下吗？cookie信息注意打码或者替换。

**Comment by xboylegend** [comment]
> 你修改以后显示 config.yml 的内容错误，可以把你修改后的 config.yml 的内容发出来我看一下吗？cookie信息注意打码或者替换。

可能是我用镜像新建的容器，直接进去修改/etc/bililive-go/config.yml的原因。我添加的cookie格式可能不太对。我刚才看了一下，我在网页端保存设置以后。网页端保存的cookie值保存到了/etc/bililive-go/config.yml文件里。我看了半天，感觉我文档里不太一致的地方就是结尾多了两个双引号。请问是这个双引号造成的问题吗？
![image](https://user-images.githubusercontent.com/17827830/217473859-3dd57831-2713-4057-a838-dd96b4c28814.png)

**Comment by xboylegend** [comment]
经过群里qiudaoyu5788的提醒，终于弄明白了。

**Comment by kira1928** [comment]
不一定要用网页版修改配置，有时候网页版修改配置之后保存会失败，这种情况下直接打开 config.yml 文件修改保存比较好。
其他项都没问题~

**Comment by joyyes1203** [comment]
> 不一定要用网页版修改配置，有时候网页版修改配置之后保存会失败，这种情况下直接打开 config.yml 文件修改保存比较好。 其他项都没问题~

测试了两天下来，发现个大问题：我是docker配置的，添加cookies后，能正常添加和录制，但是过段时间就会出现一个问题：大概十二个小时左右会出现，之后开播的，无法检测到开播状态并且不录制；前面已经开播录制的，在下播后也不会切换状态的情况。并且chrome正常模式打开直播网页live.douyin.com/xxx页面直接是空白页，无法再打开直播网页，貌似cookies有被封禁的意味儿，只能每次手动隐身模式打开窗口更换cookies

**Comment by kira1928** [comment]
刚刚发布了最新的 0.7.6 版本，会在用户没有设置抖音 cookie 的时候随机生成一个 cookie 使用。
这边的 issue 可以关闭了。
