### ISSUE TITLE
[Bug]: 闪退命令行

### ISSUE THREAD

**Issue by menheng** [hr3lxphr6j/bililive-go#383]
### 程序版本

0.7.3之后

### 自由描述

![1675810246027 jpg](https://user-images.githubusercontent.com/109516293/217386296-12234a5a-c557-475e-b8f6-18263c9d0c35.jpg)
现在每天几乎到了0点后就会闪退命令行报这个错，每天早上起来都是这样。

**Comment by menheng** [comment]
很早的版本没有这闪退问题

**Comment by kira1928** [comment]
运行的平台是什么？windows？linux？是不是docker？
闪退后命令行有没有留下log？可以贴一下吗？

**Comment by menheng** [comment]
windows，闪退后命令行整个都没有了 ，所以没有报错的错误 ，只留下网页的这个报错，很奇怪都是0点20分之前就闪退，测试了好几天都这样，应该不是windows的锅，不知道为什么进程会没有了，我的内存是够的。

**Comment by kira1928** [comment]
可能是某种程序错误。
你会用windows命令行吗？CMD或者PowerShell。
在里面启动 exe 的话，执行结束后 log 也会保留在命令行里可以看到退出前最后时刻发生了什么。
如果你不熟悉这方面的东西的话，可以等一下我接下来要发的下一个小版本，大概是 0.7.6。我会在里面加入把 log 输出到指定目录的功能，这样双击执行 exe 也可以保留到 log 文件。

**Comment by menheng** [comment]
整个程序都掉了， 早上起来都没看见这个命令行，直接给我闪退关闭了 。文本输出log可以，最好每次打开会保存到每一次打开的log，不然文字多打开的很慢，总之谢谢大佬。（我这个bug很烦恼）

**Comment by kira1928** [comment]
>整个程序都掉了， 早上起来都没看见这个命令行，直接给我闪退关闭了 。

你是怎么启动程序的？是不是双击 exe 启动的？那样启动看到的命令行确实程序关闭就会消失。如果是自己打开的 CMD 里敲命令执行的 exe 的话，程序闪退应该 CMD 也还会保留的，在 CMD 里可以看到最后的 log。
不过看你的描述你应该不是很熟悉这些工具。那就等我下一个可以输出 log 的版本吧~
我目前的想法是有一个默认 log，每次启动都删除 log 里的内容，然后重新写，这样每次里面都只记录最后一次执行程序时的 log，也不会生成太多 log 文件。
如果想每次执行的 log 都保留，可以在 config 里指定一个 log 输出目录，每次启动都会生成一个当前时间日期为文件名的 log 文件保存在输出目录里，用户不删除 log 就一直增加这样的。

**Comment by menheng** [comment]
双击的，难道是双击的问题？我明天再试试敲命令的。

**Comment by kira1928** [comment]
我觉得闪退应该不是双击导致的，但是双击确实会在程序退出后没地方去看 log。
你可以试试敲命令启动，再闪退的话就把闪退时的 log 贴上来吧。

**Comment by menheng** [comment]
问题出来了
![KE{C4(I4OLZDG5~H8CRKN$2](https://user-images.githubusercontent.com/109516293/217911929-652b8878-3a85-474a-8734-c35ae7879118.png)

**Comment by menheng** [comment]
![QLDY~`SJ8OK6$(W2JK8T5}C](https://user-images.githubusercontent.com/109516293/217955243-5c35d692-f7ec-42a4-978f-9baff170b441.png)

**Comment by kira1928** [comment]
我懂了，这是一个[现有的](https://github.com/hr3lxphr6j/bililive-go/issues/204)多线程 bug，在录制结束时有一定几率发生，导致程序崩溃。
因为发生几率比较小，而且修改难度比较大，所以一直推迟没有去修复它。没想到你能这么准确地触发它……
我会把这个 bug 排进我下一步准备解决的工作清单，有进展以后会在这个 issue 下面回复你的。

**Comment by kira1928** [comment]
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/204

**Comment by kira1928** [comment]
整理 issue，同类 issue 只留一个。
今后相关问题的进展请关注最早提出同类问题的 issue https://github.com/hr3lxphr6j/bililive-go/issues/204。
