### ISSUE TITLE
[Bug]: 有些录制的视频没声音，前面是没事的后面就突然没了

### ISSUE THREAD

**Issue by Loong0201** [hr3lxphr6j/bililive-go#384]
### 程序版本

0.7.5

### 自由描述

录着录着就自动暂停了出现以下代码
ime="2023-02-08 20:09:23" level=warning msg="failed to get stream url, will retry after 5s..." error="<nil>" host

**Comment by kira1928** [comment]
录制没声音的flv，可以发给我吗？

**Comment by kira1928** [comment]
我想调查这个bug。以前也有别人遇到过，但我无法重现所以没法查。

**Comment by Loong0201** [comment]
> 录制没声音的flv，可以发给我吗？

后面再遇到发给你，已经

**Comment by kira1928** [comment]
嗯嗯，感谢！
有的视频录下来可能很大不方便传。暂时是希望你下次遇到以后暂时别删，我这边想办法做个工具抽取出那个视频文件中我需要的内容，这样你只需要发一个比较小的抽取后的文件给我就可以了。
当然如果flv不是特别大的话，我还是特别想直接收到原始文件哒~

**Comment by Loong0201** [comment]
> 嗯嗯，感谢！
> 有的视频录下来可能很大不方便传。暂时是希望你下次遇到以后暂时别删，我这边想办法做个工具抽取出那个视频文件中我需要的内容，这样你只需要发一个比较小的抽取后的文件给我就可以了。
> 当然如果flv不是特别大的话，我还是特别想直接收到原始文件哒~

今天录到一段出现绿屏的需要发给你吗

**Comment by kira1928** [comment]
你的录播操作系统是windows？mac？linux？
用的docker还是下载release本地录制？
cpu是x64架构还是arm架构？（可以选网页端左侧第二个tab，然后点击右侧的复制按钮复制这些信息粘贴过来。）

出问题的那个视频文件多大？如果能直接上传的尺寸的话最好直接传完整文件（我用不了阿里云盘，要注意）
出问题的文件是一开始就绿了还是中途绿的？
如果一开始就绿了而且文件非常大，可以想办法只切下文件最开始的10MB大小发给我。

**Comment by Loong0201** [comment]
> 你的录播操作系统是windows？mac？linux？
> 用的docker还是下载release本地录制？
> cpu是x64架构还是arm架构？（可以选网页端左侧第二个tab，然后点击右侧的复制按钮复制这些信息粘贴过来。）
> 
> 出问题的那个视频文件多大？如果能直接上传的尺寸的话最好直接传完整文件（我用不了阿里云盘，要注意）
> 出问题的文件是一开始就绿了还是中途绿的？
> 如果一开始就绿了而且文件非常大，可以想办法只切下文件最开始的10MB大小发给我。

windows 
x64

中途绿了文件200mb

**Comment by kira1928** [comment]
中途的话就想要全文件了。不知道你有没有网盘，或者方便进qq群传到群文件吗？

**Comment by Loong0201** [comment]
> 中途的话就想要全文件了。不知道你有没有网盘，或者方便进qq群传到群文件吗？

谷歌网盘你用吗或则其他途径，QQ忘了密码进不去

**Comment by kira1928** [comment]
谷歌好哎！我还买了他家200G容量呢，喜欢！

**Comment by Loong0201** [comment]
> 谷歌好哎！我还买了他家200G容量呢，喜欢！

我装进drive待会发链接给你

**Comment by Loong0201** [comment]
这里打开就是了


https://drive.google.com/drive/folders/1n2DKNUgltqbTsdtjZOWP30_SPVf6kYPb

**Comment by kira1928** [comment]
访问权限申请已发送～

**Comment by kira1928** [comment]
下到了，感谢~
这个原因大概是主播直播途中参加了 pk 或者切换了直播分辨率导致的。ffmpeg无法处理flv直播途中变更分辨率，变过一次以后后面就会花屏但是有声音。
目前已经有一个临时对策是把程序的 config.yml 配置文件里的 
```
  use_native_flv_parser: false
```
这里改成
```
  use_native_flv_parser: true
```

这样做的效果是录制时不用ffmpeg，而改用程序作者自制的 flv 录制代码。
使用这个 flv 录制代码时每当遇到主播参与pk或调整参数等行为导致直播流途中切换分辨率时，都会分割一次视频，保证输出的每个视频都有一个唯一的分辨率。
主播刚切换分辨率时程序有点不稳定，可能会生成几个1MB左右的视频碎片，之后等直播流稳定了就会稳定录制了。
不过这个 flv parser 似乎也有各种各样的小问题，有兴趣的话可以看看[这里](https://github.com/hr3lxphr6j/bililive-go/milestone/3)的相关 issue。

**Comment by kira1928** [comment]
最后推荐一个 flv 视频修复工具，就是隔壁的 [B站录播姬](https://github.com/BililiveRecorder/BililiveRecorder) 的程序里自带的工具箱。
说来惭愧，我就是用他的工具箱尝试分析和修复了一下你给我的视频之后，才能够很快得出调查结果的。
后续我们会逐渐学习他们修复视频的方法，把这些功能集成进我们的录制过程中。敬请期待~

**Comment by Loong0201** [comment]
![IMG_20230217_013918.jpg](https://user-images.githubusercontent.com/123194940/219445385-7a8eb673-a9cc-4a38-940b-fd458d7625b4.jpg)

**Comment by kira1928** [comment]
当时的log可以发一下吗？
