### ISSUE TITLE
2023-2-9尝试录制虎牙的主播，录制出来的文件都很卡，别的平台好像不卡[Bug]: 

### ISSUE THREAD

**Issue by itgoyo** [hr3lxphr6j/bililive-go#385]
### 程序版本

docker最新

### 自由描述

2023-2-9尝试录制虎牙的主播，录制出来的文件都很卡，别的平台好像不卡

**Comment by kira1928** [comment]
估计还是虎牙 cdn 的问题。现在很多用户反应虎牙录制时如果随机使用到阿里的cdn线路，录播质量就非常差，经常断线重连。默认设置下表现出来应该就是录播断断续续，使用flv-parser的话就会变成露出来频繁分断成好多短视频。
