### ISSUE TITLE
能不能添加一个配置选项，录制真正的直播，而不录制播放的视频。

### ISSUE THREAD

**Issue by MaiXiaochai** [hr3lxphr6j/bililive-go#388]
大佬好，有的主播习惯直播完之后一直放之前的直播视频（估计是为了水时长），但是放的视频画质普遍不高，不想录，主要是我的硬盘撑不住啊，还得人肉检测去删除那些，实在是费劲。
我不太会Go语言（虽然之前看过一遍，但是一直不用，忘得差不多了），要不我就提PR了。感谢大佬！

**Comment by kira1928** [comment]
主播手动放视频，录播软件也不知道啊。。

**Comment by MaiXiaochai** [comment]
大一点的平台，跳舞时候banner图左上角会显示“热舞中”，不知道数据中有没有，不过这个也不是很重要。

**Comment by kira1928** [comment]
如果能给出具体平台，也许我可以研究一下这些标签。不过这个需求实在是很小众，做他的优先级不会很高。

**Comment by MaiXiaochai** [comment]
sorry，我回答串了，这个应该是那个跳舞检测的，哈哈哈~。用这个标志检测有没有在跳舞也挺好，应该是平台有自己的AI，能识别是不是在跳舞，然后自己打了个标。
比如[斗鱼舞蹈区](https://www.douyu.com/g_dance)，“跳舞中”是一个小图片。
要不这个问题关了吧，感觉暂时确实有些不好弄，不是刚需~

**Comment by kira1928** [comment]
好的，这边先关了。在那边聊吧。
