### ISSUE TITLE
腾讯云Windows平台可以检测但是不会下载了==

### ISSUE THREAD

**Issue by iac-cai** [hr3lxphr6j/bililive-go#39]
Windows Server 2016 数据中心版 64位中文版
Windows Server 2008 数据中心版 64位中文版
都是可以检测直播状态，但是无法下载TnT

**Comment by hr3lxphr6j** [comment]
提供下使用版本，完整的log输出和配置文件

**Comment by iac-cai** [comment]
> 提供下使用版本，完整的log输出和配置文件

time="2019-11-12 11:29:40" level=info msg="BiliLive-go Version: 0.4.0-rc.2 Link Start"
time="2019-11-12 11:29:40" level=debug msg="{AppName:BiliLive-go AppVersion:0.4.0-rc.2 BuildTime:2019-09-10_15:20:10 GitHash:bdc555ad287209a138f4cbfade4f573bee21a6db Pid:1584 Platform:windows/amd64 GoVersion:go1.13}"
time="2019-11-12 11:29:40" level=debug msg="&{RPC:{Enable:false Bind::8080 Token: TLS:{Enable:false CertFile: KeyFile:}} Debug:true Interval:20 OutPutPath:./ Feature:{UseNativeFlvParser:false} LiveRooms:[https://live.bilibili.com/275561] file:}"
time="2019-11-12 11:29:41" level=info msg="Live Start" host="永夜的星指引" room="想看ADC的请进，上船帮上分"
time="2019-11-12 11:29:41" level=info msg="Record Start" host="永夜的星指引" room="想看ADC的请进，上船帮上分"
time="2019-11-12 11:29:41" level=warning msg="failed to get stream url, will retry after 5s..." error="<nil>" host="永夜的星指引" room="想看ADC的请进，上船帮上分"

**Comment by kira1928** [comment]
issue 年代久远，而且之后没有遇到过同类提问，这里就先关闭了。
