### ISSUE TITLE
抖音的主播名可能会带有表情，文件名存在表情无法上传到网盘

### ISSUE THREAD

**Issue by wwkk2580** [hr3lxphr6j/bililive-go#392]
### 新功能

希望在读取直播信息的时候去除表情和特殊符号，其他平台的主播名也可能会有这个情况
不要把表情或符号保存到视频文件名
![image](https://user-images.githubusercontent.com/76099203/219070161-694a25ae-089a-480c-9937-eca7c667b6f5.png)

**Comment by wwkk2580** [comment]
![image](https://user-images.githubusercontent.com/76099203/219070915-f045be5c-a6ff-4b56-b6b2-0d38d9323a9a.png)

**Comment by kira1928** [comment]
文件名确实需要一些规则。包括有些文件名是windows不支持的等等问题。

**Comment by chenlu964** [comment]
是的，我这也有一个主播叫《小咸鱼不下饭🐟》，最好能自定义主播名称

**Comment by insoxin** [comment]
@wwkk2580  这自己都能完成.[\p{So}\p{Sk}]
![image](https://user-images.githubusercontent.com/19371836/219296992-fe335c4b-547d-49e6-aea4-212d74e7c4d9.png)

**Comment by coffee798** [comment]
> 是的，我这也有一个主播叫《小咸鱼不下饭🐟》，最好能自定义主播名称

你好问一下，小咸鱼这几天有播吗，一直没录到过

**Comment by kira1928** [comment]
在 20 分钟后即将发布的 0.7.8 版本中加入了一个新的配置选项。
```yaml
feature:
  remove_symbol_other_character: true
```
向上面这样把 `remove_symbol_other_character` 设置为 `true` 的话，可以把输出文件和文件夹名称中的小鱼之类特殊字符替换为下划线 `_` 。
