### ISSUE TITLE
希望能快点出个能选择清晰度的功能

### ISSUE THREAD

**Issue by poblm** [hr3lxphr6j/bililive-go#394]
### 新功能

现在需要录制的直播对清晰度要求不高，如果同时录几个直播间，而且录的时间长，硬盘不够用~~希望能出个清晰度选择的功能，或者简单搞个低清/高清可以选都够了，谢谢

**Comment by kira1928** [comment]
Duplicated of https://github.com/hr3lxphr6j/bililive-go/issues/352
