### ISSUE TITLE
Hope to support 

### ISSUE THREAD

**Issue by BearChu** [hr3lxphr6j/bililive-go#4]
希望能增加FB及油管了录制,这2平台自动化有难度,目前还没看到可行的
因为没直播间,都是个人主页显示直播才有直播地址,且1080P以上视频音频分离

也希望增加新指令 txt列表方案 
如-i txt (txt只需输入一行一个地址即可) 
原本的-i 网址 -i 网址 比较杂乱 且须连着输入 非常长 不好整理及查看
也可能有方便的方法 我没发现 麻烦指教提点 感谢

**Comment by hr3lxphr6j** [comment]
1. u2b我记得会自带直播录像，所以就没做，FB抽空看看
2. 可以通过`-c`参数指定配置文件，在配置文件写直播间地址，配置文件就是releases压缩包里提供的`config.yml`，配置文件格式参考Readme

**Comment by BearChu** [comment]
对 u2b自带 但是经常因为各种版权内容被屏蔽 就会消失 了解 感谢解答
