### ISSUE TITLE
panic: Get https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js: dial tcp 104.19.195.151:443: i/o timeout

### ISSUE THREAD

**Issue by xiatiantiantian** [hr3lxphr6j/bililive-go#40]
panic: Get https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js: dial tcp 104.19.195.151:443: i/o timeout

goroutine 56 [running]:
github.com/hr3lxphr6j/bililive-go/src/api.loadCryptoJS(...)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:95
github.com/hr3lxphr6j/bililive-go/src/api.getEngineWithCryptoJS(0xc0003ec000, 0xb110, 0xc00006c9a0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:102 +0x165
github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).getSignParams(0xc0001bc230, 0xa8aa08, 0xc0000a3d70, 0x45f4e0)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:203 +0x73a
github.com/hr3lxphr6j/bililive-go/src/api.(*DouyuLive).GetStreamUrls(0xc0001bc230, 0xc0002f4420, 0xc0000a3e00, 0x4052b3, 0xc000054780, 0x4)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/api/douyu_live.go:244 +0x5b
github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).run(0xc00038c000)
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:56 +0x7b
created by github.com/hr3lxphr6j/bililive-go/src/recorders.(*Recorder).Start.func1
        /Users/chigusa/Documents/Dev/golang/src/github.com/hr3lxphr6j/bililive-go/src/recorders/recorder.go:86 +0x4e

**Comment by xiatiantiantian** [comment]
好吧，GG了 
![image](https://user-images.githubusercontent.com/51699978/65961534-63f27f80-e489-11e9-9476-a09217265529.png)

**Comment by xiatiantiantian** [comment]
@hr3lxphr6j 
可以弄个本地加载嘛， 今天整个cdnjs.cloudflare.com    ajax.cloudflare.com  都被强了


http://www.17ce.com/site/http/20191001_e26b7d60e42c11e9a461dfdb56d25986:1.html

**Comment by cxumol** [comment]
Closed by #91
