### ISSUE TITLE
[提问]: docker版无法添加抖音直播的房间

### ISSUE THREAD

**Issue by shinwa** [hr3lxphr6j/bililive-go#400]
### 程序版本

0.6.3 go1.17

### 自由描述

例如地址为：
https://live.douyin.com/86786934718
添加后页面仍然是空白的， docker 的log里面没有变化

但是
bilibili的直播没有问题

**Comment by anlo1220** [comment]
我的能 你有加COOKIE?

**Comment by shinwa** [comment]
> 我的能 你有加COOKIE?

哦，没有加cookie....

config.toml 放在那个位置？

**Comment by shinwa** [comment]
> > > 我的能 你有加COOKIE?
> > 
> > 
> > 哦，没有加cookie....
> > config.toml 放在那个位置？
> 
> https://github.com/hr3lxphr6j/bililive-go#cookie-%E5%9C%A8-configyml-%E4%B8%AD%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95

找到了， 在docker里面， 是在/etc/bililive-go/config.yml 这里
然后...

关于cookies
chrome F12里面找到一堆， 但是要填写哪个？

**Comment by kira1928** [comment]
0.6.3 本身不支持抖音直播呀。。
建议升级到最新版。

**Comment by shinwa** [comment]
> 0.6.3 本身不支持抖音直播呀。。 建议升级到最新版。

我拉的是docker的镜像哦 是不是docker没更新?

**Comment by kira1928** [comment]
https://hub.docker.com/r/chigusa/bililive-go/tags
docker 镜像最新版是 0.7.8 哦，latest 也指向 0.7.8 哦。

**Comment by rootwhois** [comment]
> https://hub.docker.com/r/chigusa/bililive-go/tags
> docker 镜像最新版是 0.7.8 哦，latest 也指向 0.7.8 哦。

我遇到了相同的问题，当docker的镜像源设置是阿里云的时候，拉取的不是最新版，用官方的就ok了。

**Comment by kira1928** [comment]
楼主长期未回复，大概问题已经解决了。这边就关闭了。
