### ISSUE TITLE
make build-web报错

### ISSUE THREAD

**Issue by ciihom** [hr3lxphr6j/bililive-go#405]
### 程序版本

0.7.8

### 自由描述

root@localhost:~/bililive-go# make build-web
cd ./src/webapp && yarn install && yarn build && cd ../../
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
make: *** [Makefile:46: build-web] Error 1

**Comment by kira1928** [comment]
https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

**Comment by ciihom** [comment]
谢谢，按照你的提示找到对应的解决方法了。
