### ISSUE TITLE
抖音直播似乎没有使用最高码率的源

### ISSUE THREAD

**Issue by kira1928** [hr3lxphr6j/bililive-go#411]
### 程序版本

0.7.8

### 自由描述

用biliup录有10M码率60fps，bgo只有6M不到码率45fps。

**Comment by a554233472** [comment]
app.initialState.roomStore.roomInfo.room.stream_url.flv_pull_url
这句代码的问题，这下面的链接没有最高清晰度的
可以去app.initialState.roomStore.roomInfo.room.stream_url.live_core_sdk_data.pull_data.stream_data里面找
参考
r5 = room_info['stream_url']['live_core_sdk_data']['pull_data']['stream_data']
self.raw_stream_url = json.loads(r5)['data']['origin']['main']['flv']

**Comment by kira1928** [comment]
已在 master branch 中修复。预计于下次 release 中发布。
