### ISSUE TITLE
[提问]: 请问一下bililive能转mp3嘛

### ISSUE THREAD

**Issue by kratkin1997** [hr3lxphr6j/bililive-go#412]
### 程序版本

0.7.8

### 自由描述

如题，看到有个能转mp4的功能，请问一下这个能转mp3嘛

**Comment by kira1928** [comment]
目前不能。
以后可能会提供一个配置项让用户自行决定录制结束之后执行什么命令，到时候你可以在哪里写一段代码，用 ffmpeg 之类的工具从录下来的 flv 中抽取出 mp3.
https://github.com/hr3lxphr6j/bililive-go/issues/339#issuecomment-1385728481

**Comment by kira1928** [comment]
合并到 https://github.com/hr3lxphr6j/bililive-go/issues/414
