### ISSUE TITLE
可以添加一个自定义设置录制完毕后的动作吗

### ISSUE THREAD

**Issue by novohit** [hr3lxphr6j/bililive-go#414]
### 新功能

比如录制完毕后执行一段command，可以自动上传到网盘

**Comment by kira1928** [comment]
可以，想做！

**Comment by pencilqaq** [comment]
感觉也可以对接一下biup-rs

**Comment by kira1928** [comment]
@pencilqaq 不太了解，这个应该可以靠用户设置来实现吧。
这边目前只想做好录制功能。

**Comment by 1136623363** [comment]
> 可以，想做！

请问大佬这个功能有做了吗，期待+1

**Comment by kira1928** [comment]
> 请问大佬这个功能有做了吗，期待+1

只能说，后面会做的T_T
这样比较简单的功能，应该会比较早推出。

**Comment by longjiank** [comment]
+1  也想要这个上传网盘这个功能

**Comment by Crazy-FuQing** [comment]
> 自动上传到网盘

如果只是想自动上传到网盘的话为什么不把网盘挂载到本地，直接录到里面不就行了 😁

**Comment by 1136623363** [comment]
> > 自动上传到网盘
> 
> 如果只是想自动上传到网盘的话为什么不把网盘挂载到本地，直接录到里面不就行了 😁

你去试一下看行不行吧，反正我觉得太不稳定了，这种要保持文件实时更新的，挂载的网盘做不到。目前我用的比较舒服的方案[](https://github.com/tickstep/aliyunpan)

**Comment by Crazy-FuQing** [comment]
> > > 自动上传到网盘
> > 
> > 
> > 如果只是想自动上传到网盘的话为什么不把网盘挂载到本地，直接录到里面不就行了 😁
> 
> 你去试一下看行不行吧，反正我觉得太不稳定了，这种要保持文件实时更新的，挂载的网盘做不到。目前我用的比较舒服的方案https://github.com/tickstep/aliyunpan

sync也行

**Comment by kira1928** [comment]
忘了回复这边了。这个功能现在已经实现啦！ https://github.com/hr3lxphr6j/bililive-go/pull/524
