### ISSUE TITLE
重开直播间就不见了

### ISSUE THREAD

**Issue by Loong0201** [hr3lxphr6j/bililive-go#415]
每次重开已经一些添加的直播间都会不见需要重新加

**Comment by kira1928** [comment]
完全清空吗？那你的启动方式是怎样的呢？docker？命令行参数？

如果是部分消失，可以举几个每次都会消失的直播间的例子吗？如果直播间被封，程序检测不到可能会以为url失效，这是会丢失直播间的一种可能，但你每次都能添加上，大概不是这种情况。

**Comment by Loong0201** [comment]
部分消失但能重新加上，就在我每次关电脑后再开就不见了几个直播间

**Comment by kira1928** [comment]
是不是在网页端添加了之后没点保存配置按钮？

**Comment by kohakox** [comment]
我也遇到了这个情况 配置好了后可以使用  网页端两个位置的保存配置都点了  但是重启docker config直接恢复默认的   环境是TrueNAS-SCALE-22.02.4 下的k8s

**Comment by kira1928** [comment]
@kohakox
按完保存按钮之后看看 docker 里的配置文件有没有实际改变？
配置文件在 docker 里的位置参见[这里](https://github.com/hr3lxphr6j/bililive-go/wiki/docker-%26-k8s#docker)。
如果保存配置之后文件有改变，重启 docker 之后 config 恢复默认值，那就是你的 docker 环境有问题了。
如果保存配置之后文件内容没变，那就要看看你的 docker 是不是有什么特殊的权限设置了。需要贴一下你的容器创建时设置的全部参数之类的。

**Comment by kohakox** [comment]
谢谢  我试了下docker运行的时候 更改是有变化的 重启docker配置就恢复了    我试着把/etc/bililive-go挂载出来  保存后重启就没问题了     另外有个问题  可不可以设置转码的mp4自定义输出目录呢

**Comment by kira1928** [comment]
> 可不可以设置转码的mp4自定义输出目录呢
目前不可以，有需求的话可以另外写一个新 issue 正式提出这个需求。

**Comment by kohakox** [comment]
> 目前不可以，有需求的话可以另外写一个新 issue 正式提出这个需求。

好的谢谢 暂时不是刚需  我本地运行个脚本也能实现

**Comment by kira1928** [comment]
现在配置应该不会掉了
