### ISSUE TITLE
[提问]: 使用ffmpeg导出的mp4视频画面隔几秒会卡几帧，声音正常

### ISSUE THREAD

**Issue by ybm2020** [hr3lxphr6j/bililive-go#417]
### 程序版本

0.7.8

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 15
out_put_path: ./
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.panda.tv/10300
  is_listening: true
- url: https://www.huya.com/27195669
  is_listening: true
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 1h0m0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
timeout_in_us: 60000000

### 自由描述

使用ffmpeg导出的mp4视频画面隔几秒会卡几帧，声音正常

**Comment by ybm2020** [comment]
谢谢你的回复，现在有个新的问题，我添加的虎牙直播间，主播没有在播，但是运行状态显示的是录制中而不是监控中，导致终端一直在尝试录制，最后程序停止运行了。

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa8 pc=0xd96ffb]

goroutine 2180 [running]:
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop.func1()
        /home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:163 +0x1b
sync.(*Once).doSlow(0xc00030b6e0?, 0xd9c0e0?)
        /opt/hostedtoolcache/go/1.19.5/x64/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.19.5/x64/src/sync/once.go:65
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop(0xc00060e000?)
        /home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:162 +0x45
github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).Close(0xe68a40?)
        /home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:222 +0x62
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).RemoveRecorder(0xc00039c720, {0xc0004c7f78?, 0x8?}, {0xc000135ae0, 0x20})
        /home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:148 +0xa2
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).registryListener.func3(0xc0004b4120?)
        /home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:69 +0xb7
github.com/hr3lxphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent.func1()
        /home/runner/work/bililive-go/bililive-go/src/pkg/events/dispatcher.go:96 +0x47
created by github.com/hr3lxphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent
        /home/runner/work/bililive-go/bililive-go/src/pkg/events/dispatcher.go:94 +0x235

**Comment by kira1928** [comment]
主播没在播画面但是直播间是不是显示在直播？比如在你的关注列表里显示正在直播了。
最后那个错误是一个[已知错误](https://github.com/hr3lxphr6j/bililive-go/issues/204)，比较难修。

**Comment by ybm2020** [comment]
不晓得哦，当时进直播间显示没在播，没看关注列表，不过那次后重启就好了，整体来说还是很好用的，谢谢你
