### ISSUE TITLE
[提问]: 打算试着添加快手直播录制，需要完成哪些步骤？

### ISSUE THREAD

**Issue by TeslaLyon** [hr3lxphr6j/bililive-go#421]
### 程序版本

0.7.8

### 程序 log

~/code/go-dev/bililive-go$make
building bililive (Platform: darwin, Arch: amd64, GoVersion: 1.19.5)
src/webapp/webapp.go:11:12: pattern build: no matching files found
make: *** [bililive] Error 1

### 自由描述

go: 1.19.5
打算试着添加快手直播录制，是不是完成 douyin.go 中的 GetStreamUrls 方法即可？

参考：https://github.com/nICEnnnnnnnLee/LiveRecorder/blob/master/live_recorder/you_live/kuaishou_recorder.py
看了一下 python 的代码，大致思路是获取直播pc页面的 html，提取 json 数据，在json中提取到直播地址。

**Comment by kira1928** [comment]
我没有添加过新的直播平台，所以不是很了解。
你可以参考[这个](https://github.com/hr3lxphr6j/bililive-go/pull/362/files)新增猫耳fm直播录制的PR里修改和增加的内容来尝试实现添加快手平台。
我的印象是除了 GetStreamUrls  以外 应该还有个 GetInfo 还是什么的函数需要实现。另外还有其他你继承的 interface 要求实现的函数。
反正最好是参考上面的添加其他平台的成功 PR 来开发。
祝开发顺利，希望早日看到你的PR！

**Comment by TeslaLyon** [comment]
> 

OK，我需要恶补一下 golang 的相关知识，目前还不知道怎么调试。。。 没有找到 main.go 。。

**Comment by kira1928** [comment]
我也是花了好大功夫才找到一个比较稳定的调试 golang 的方法。
主要我印象中一般调试都是语言或 IDE 自带的功能，我用过的语言里只有 php 和 golang 是要额外安装个东西才能调试的。
golang 我是在 windows 的 wsl ubuntu 上安装了 delve，然后用 `dlv --listen=":50000" --headless=true --log --api-version=2 exec bin/bililive-linux-amd64 -- -c config.yml` 这个命令启动程序开始在 vscode 上调试的。
vscode 那边的调试用 launch.json 我用的是
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Connect to server",
      "type": "go",
      "debugAdapter": "dlv-dap",
      "request": "attach",
      "mode": "remote",
      "remotePath": "${workspaceFolder}",
      "port": 50000,
      "host": "localhost"
    }
  ]
}
```
希望能让你少走一些弯路。

**Comment by TeslaLyon** [comment]
> 我也是花了好大功夫才找到一个比较稳定的调试 golang 的方法。 主要我印象中一般调试都是语言或 IDE 自带的功能，我用过的语言里只有 php 和 golang 是要额外安装个东西才能调试的。 golang 我是在 windows 的 wsl ubuntu 上安装了 delve，然后用 `dlv --listen=":50000" --headless=true --log --api-version=2 exec bin/bililive-linux-amd64 -- -c config.yml` 这个命令启动程序开始在 vscode 上调试的。 vscode 那边的调试用 launch.json 我用的是
> 
> ```json
> {
>   "version": "0.2.0",
>   "configurations": [
>     {
>       "name": "Connect to server",
>       "type": "go",
>       "debugAdapter": "dlv-dap",
>       "request": "attach",
>       "mode": "remote",
>       "remotePath": "${workspaceFolder}",
>       "port": 50000,
>       "host": "localhost"
>     }
>   ]
> }
> ```
> 
> 希望能让你少走一些弯路。

感谢大佬指引
