### ISSUE TITLE
希望能新增指定ffmpeg路径的配置

### ISSUE THREAD

**Issue by xiers819** [hr3lxphr6j/bililive-go#424]
### 新功能

ffmpeg版本更新速度很快，部分其他软件支持自定义ffmpeg路径，所以本人会将各种ffmpeg构建版本集中保存在一个固定的路径，若bililive-go能够支持在配置文件中自定义ffmpeg路径，使用起来会方便很多，希望开发大佬采纳！

**Comment by kira1928** [comment]
合理！

**Comment by kira1928** [comment]
已在 0.7.13 版中实现
