### ISSUE TITLE
添加不了直播

### ISSUE THREAD

**Issue by cosylxc** [hr3lxphr6j/bililive-go#429]
作者你好，我主要是想录制抖音的直播，搜到了你这个项目，前天电脑win版本下好后，一直在添加主播。

但可能想要录制的人太多？我添加到一定数量后，再点击添加就没有什么用了，无论是直接添加，还是设置添加。

好像配置文件添加还是可以的，但有一个问题，就是这样的话，新增主播，就只能重启biligo吗？🥹

因为添加的主播很多，重启也要好久才能恢复过来。

直接关闭的话，现在正在录制的主播会怎样。

所以想请问一下，监控的人数上限多少好呢，好调整一下，因为我虽然监控的人多，但大部分都不经常直播的。

非常感谢楼主的项目🥹

**Comment by cosylxc** [comment]
今天直接打不开了🥹

**Comment by kira1928** [comment]
抖音直播听说限制很严格，家的房间多了访问抖音就会很频繁，容易被暂时ban ip。
建议是监控的房间越多，在配置里设置的检测房间的时间间隔 （`interval`） 就要设置的越大。具体设置多少就靠你实际试错了。

直接关闭就是录制到一半，录下来的 flv 文件没有转录成 mp4 也没有修复文件头，所以放在远程访问的话会有无法拖动视频进度条到后面这样的问题。这些可以用b站录播姬的工具箱来修复视频。
