### ISSUE TITLE
windows桌面版

### ISSUE THREAD

**Issue by SkyTine** [hr3lxphr6j/bililive-go#445]
### 新功能

希望出一个优雅的windows桌面版，可以挂在系统托盘里，支持开启自启啥的。目前还是命令行+web的形式，关闭cmd窗口程序就关闭了。

**Comment by kira1928** [comment]
以项目目前未知的方向性来看，应该不会做 web GUI 以外的图形界面了。毕竟这本来就是一个跑在服务器上7x24小时运行的命令行程序。
