### ISSUE TITLE
[提问]: 快手无法录制

### ISSUE THREAD

**Issue by leo57209259** [hr3lxphr6j/bililive-go#447]
### 程序版本

0.7.10

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 60
out_put_path: /srv/bililive
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: true
live_rooms: []
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: false
timeout_in_us: 60000000

### 自由描述

我用的是Nas里的Docker搭的  刚开始快手是可以录制的  就算没直播的房间也会显示主播名称   等我添加了几个房间后就录不了了  主播名称和房间名称全不显示  就算添加正在直播的房间也是显示监控中  输出文档里也没有录像文件  我试了下其他平台是可以正常录制的   是不是因为我添加快手房间太快了  IP被ban了？  可我改了Nas的本地IP  电脑挂上全局梯子  各种方法试了还是不行  请问怎么解决   谢谢

**Comment by kira1928** [comment]
看添加快手支持的大佬的[意思](https://github.com/hr3lxphr6j/bililive-go/commit/099965a3dd39f8611b6f62931e441d0ab2d4fd77#commitcomment-110152406)，录快手现在必须在配置里带上自己的 cookie 信息。
cookie 格式如上面链接内文所示，cookie 的获取方式可以查阅网络，有很多这方面的教程。

**Comment by leo57209259** [comment]
> 看添加快手支持的大佬的[意思](https://github.com/hr3lxphr6j/bililive-go/commit/099965a3dd39f8611b6f62931e441d0ab2d4fd77#commitcomment-110152406)，录快手现在必须在配置里带上自己的 cookie 信息。 cookie 格式如上面链接内文所示，cookie 的获取方式可以查阅网络，有很多这方面的教程。

感谢  我去试试

**Comment by luosite1** [comment]
> > 看添加快手支持的大佬的[意思](https://github.com/hr3lxphr6j/bililive-go/commit/099965a3dd39f8611b6f62931e441d0ab2d4fd77#commitcomment-110152406)，录快手现在必须在配置里带上自己的 cookie 信息。 cookie 格式如上面链接内文所示，cookie 的获取方式可以查阅网络，有很多这方面的教程。
> 
> 感谢 我去试试

请问解决了吗

**Comment by jun9100** [comment]
请问快手cooke怎么获取呢？

**Comment by RiverChu0** [comment]
我印象中快手反扒很厉害

**Comment by kira1928** [comment]
已更新 readme 说明快手确实不能用了。
