### ISSUE TITLE
在flv parser录制下 会有几率出现主播下播或封禁后出现最后几秒的分段

### ISSUE THREAD

**Issue by hibiki222** [hr3lxphr6j/bililive-go#448]
### 程序版本

有flv parser的版本

### 自由描述

如果所示 下播或封禁后就会出现文件大小一模一样的分段  就是第一个大文件的最后几秒  几个视频文件都是重复最后几秒
开始flv parser有几率出现 然后分段文件大小不一定每一个一样大 有几率出现不一样大 但仍然是最后几秒的直播
![QQ截图20230423175623](https://user-images.githubusercontent.com/114181056/233833116-2159100a-d15a-4a84-bdf6-8f86e87e4007.png)
![QQ截图20230423175606](https://user-images.githubusercontent.com/114181056/233833119-9324f5f3-5e68-4eee-92b3-b8a9a8764102.png)

**Comment by hibiki222** [comment]
最开始只有虎牙出现   现在斗鱼也出现下播重复分段了

**Comment by kira1928** [comment]
等一个好心人帮我们调查一下

**Comment by kira1928** [comment]
我因为一直不用 flv parser 在录，平时遇不到，所以没有特别大的动力去修这个问题。希望有其他好心人来看一看这个bug >_<

**Comment by hibiki222** [comment]
证实了是cdn问题
