### ISSUE TITLE
斗鱼主播在重启时掉配置如下图

### ISSUE THREAD

**Issue by hibiki222** [hr3lxphr6j/bililive-go#450]
### 程序版本

所有

### 自由描述

例如该直播间https://www.douyu.com/52004
斗鱼主播网页端显示
![QQ截图20230423183822](https://user-images.githubusercontent.com/114181056/233834967-76689fed-daaf-42c1-932b-dcefb1d6b89c.png)
如果启动含有该主播的配置文件
则输出如下图
![QQ截图20230423183746](https://user-images.githubusercontent.com/114181056/233835009-84d49f52-d71c-4bbf-a31f-59ce30d24c9f.png)
webui不会出现
![QQ截图20230423183943](https://user-images.githubusercontent.com/114181056/233835051-52388252-81d0-4779-838c-36659201f4fe.png)

**Comment by LightWind1** [comment]
能发一份你的config.yml吗，这个没显示就是因为没获取到房间信息，判定无效

**Comment by hibiki222** [comment]
> 能发一份你的config.yml吗，这个没显示就是因为没获取到房间信息，判定无效

抱歉，今天才看到消息，请问还需要配置文件吗

**Comment by LightWind1** [comment]
> > 能发一份你的config.yml吗，这个没显示就是因为没获取到房间信息，判定无效
> 
> 抱歉，今天才看到消息，请问还需要配置文件吗

暂时不需要了，如果可以，麻烦根据我的改动帮忙测试下？

**Comment by hibiki222** [comment]
> > > 能发一份你的config.yml吗，这个没显示就是因为没获取到房间信息，判定无效
> > 
> > 
> > 抱歉，今天才看到消息，请问还需要配置文件吗
> 
> 暂时不需要了，如果可以，麻烦根据我的改动帮忙测试下？

俺不会打包测试，只有等项目的大佬来测试了

**Comment by hibiki222** [comment]
> > > 能发一份你的config.yml吗，这个没显示就是因为没获取到房间信息，判定无效
> > 
> > 
> > 抱歉，今天才看到消息，请问还需要配置文件吗
> 
> 暂时不需要了，如果可以，麻烦根据我的改动帮忙测试下？

请问你在tg讨论群里吗，如果方便可以加tg群聊

**Comment by kira1928** [comment]
已在 https://github.com/hr3lxphr6j/bililive-go/pull/459 中修复
