### ISSUE TITLE
有没有可能加个电脑开播就让use_native_flv_parser为false，手机开播就让use_native_flv_parser为true的功能

### ISSUE THREAD

**Issue by qsje** [hr3lxphr6j/bililive-go#452]
### 新功能

录制斗鱼的时候，如果让use_native_flv_parserr为false，主播假使某天用手机开播并打了PK，这天的录制大概率就GG了，但是如果一直让use_native_flv_parserr为true，它的分段并不是很省心，有时候会分段成一堆碎片，感觉可以偶尔用，不适合一直用。
我实践下来，如果想让每天的录制都正常，那么在主播手机开播的时候，就得手动去修改配置文件，然后主播要用电脑直播了再把配置文件修改回去，很麻烦。
能不能尝试加一个检测，如果主播是用电脑开播的，就自动让use_native_flv_parser为false；如果主播是用手机开播的，就自动让use_native_flv_parser为true

**Comment by userzzzq** [comment]
我用的是use_native_flv_parser: false，录抖音也会产生一堆碎片，只有几秒的那种。

**Comment by kira1928** [comment]
>这天的录制大概率就GG了

GG的视频不要扔，用b站录播姬的工具箱功能可以修复视频，在GG的部分进行视频分段，然后调整分辨率把录播视频切割成几个可以正常播放的分段。

**Comment by kira1928** [comment]
录播程序应该没法知道对方是用什么设备开播的，支持这个功能不太现实。
理想情况是未来继续优化 flv parser，最终完全脱离对 ffmpeg 的依赖，这也是这个项目原作者当初的目标。

**Comment by qsje** [comment]
@kira1928  关于斗鱼上录播程序检测使用什么开播的，好像可以从https://www.douyu.com/betard/{roomid}中找到"ver"字段，如果是手机开播的，"ver"的值就是"android|v7.x"或者"ios|v7.x"；如果是电脑开播的，"ver"的值就是"|5.x"

**Comment by kira1928** [comment]
@qsje 哇！确实可以，学到了！
不过这就成了斗鱼特供功能了。。
另外pk导致ffmpeg录播花屏的的原理是pk的时候直播的分辨率会发生变化。这样就算pc开播的主播如果和手机开播的人pk的话也会发生花屏问题，并不能彻底解决问题。
即使你录的主播很稳定地pc开播就不pk，手机开播pk就会花屏，那也是属于定制化需求了，不太可能专门为这非常少数的用户受益而专门编写一个定制化功能。
