### ISSUE TITLE
[提问]: 请问如何添加快手cookies

### ISSUE THREAD

**Issue by leo57209259** [hr3lxphr6j/bililive-go#453]
### 程序版本

0.7.10

### 自由描述

我想录快手   根据网上的方法找到的cookies是一大串   包括userId在内的很多东西  不太懂   大佬的格式是  live.douyin.com: __ac_nonce=123456789012345678903;name=value    以域名为单位   我倒是在抖音cookies里找到 __ac_nonce 了  快手的cookies里没有   而且我用谷歌和edge两个浏览器获取的cookies还不一样   也不知道是怎么回事    快手的应该怎么填有人解答下吗     谢谢

**Comment by kira1928** [comment]
操作 cookie 是有一定安全危险性的。如果不是很了解 cookie，建议不要使用这类功能。
快手录制功能本身并不稳定，已经有很多人反馈录制只能持续几分钟，之后就会被中断录制了。添加这个功能的作者本人也[没有很好的办法](https://github.com/hr3lxphr6j/bililive-go/commit/099965a3dd39f8611b6f62931e441d0ab2d4fd77#commitcomment-110152406)。
目前可以认为快手功能是不完备的。可能会在下次更新时注明功能不完备。

**Comment by leo57209259** [comment]
> 操作cookie是有一定安全危险性的。如果不是很了解cookie，建议不要使用这种功能。快手记录制作功能本身并不稳定，已经有很多人反喷录制只能持续几分钟，之后就会被 中断录制了。添加这个功能的作者本人也[没有很好的办法](https://github.com/hr3lxphr6j/bililive-go/commit/099965a3dd39f8611b6f62931e441d0ab2d4fd77#commitcomment-110152406)。 目前可以认为是快手功能是不齐全的。可能会在下次更新时注明功能不齐全。

感谢回答   我才发现上个版本才支持的快手  可能功能还不完备  其他平台不需要cookies都能稳定录制  快手大部分时间不能录  但是有时候突然一打开能录一会就又断了  还是等作者大大更新吧
