### ISSUE TITLE
疑似直播标题导致文件路径录入问题

### ISSUE THREAD

**Issue by 976481642** [hr3lxphr6j/bililive-go#456]
### 程序版本

v0.7.9

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 15
out_put_path: ./
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: true
  remove_symbol_other_character: false
live_rooms:
- url: https://www.panda.tv/10300
  is_listening: true
  quality: 0
- url: https://www.douyu.com/5684726
  is_listening: false
  quality: 0
- url: https://www.douyu.com/10722927
  is_listening: false
  quality: 0
- url: https://www.douyu.com/1667826
  is_listening: false
  quality: 0
- url: https://www.douyu.com/651133
  is_listening: false
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 30m0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
timeout_in_us: 60000000

### 程序 log

time="2023-05-05 14:50:00" level=info msg="open 斗鱼\\一口三明治3Mz\\[2023-05-05 14-50-00][一口三明治3Mz][骚瑞 累了睡过
头了>_<].flv: The filename, directory name, or volume label syntax is incorrect." host="一口三明治3Mz" room="骚瑞 累了睡过头了&gt;_&lt;"

### 自由描述

目前看下来是疑似是标题的问题导致的无法录入 之前是可以的

**Comment by kira1928** [comment]
1. 我试着录了一下这个房间，没看到房间标题中有 >< 符号，可以正常录制。
2. 程序本身已经[剔除了](https://github.com/hr3lxphr6j/bililive-go/blob/master/src/pkg/utils/strings.go#L59)主播名和直播间名中的特殊字符，至今为止也从没有人提过因为存在 >< 字符导致上述错误信息的 issue，所以个人认为这个原因的可能性很低。
3. 我需要看前后的更多 log 来推测可能的问题原因。
4. 还有用网页版UI的`系统状态` tab 页面里的`复制到剪贴板`按钮复制一下系统信息发出来可以吗？

**Comment by 976481642** [comment]
之后可以录制 是因为联系主播改了标题后 可以进行录制了&nbsp; &nbsp;没有跟主播沟通前 都是这个&nbsp; &nbsp;重新启动都会有这个bug
&nbsp;


[淘宝网]
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月5日(星期五) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hr3lxphr6j/bililive-go] 疑似直播标题导致文件路径录入问题 (Issue #456)





  
我试着录了一下这个房间，没看到房间标题中有 &gt;< 符号，可以正常录制。
 
程序本身已经剔除了主播名和直播间名中的特殊字符，至今为止也从没有人提过因为存在 &gt;< 字符导致上述错误信息的 issue，所以个人认为这个原因的可能性很低。
 
我需要看前后的更多 log 来推测可能的问题原因。
 
还有用网页版UI的系统状态 tab 页面里的复制到剪贴板按钮复制一下系统信息发出来可以吗？

**Comment by kira1928** [comment]
等你有空发一下上面需求的一些附加信息之后，我再调查看看吧。
目前是比较怀疑你的执行平台比较特别。看错误信息应该是windows，不知道是不是特殊架构的windows。

**Comment by 976481642** [comment]
最近有点事没有回复&nbsp; 我的是win11系统
&nbsp;


[淘宝网]
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月6日(星期六) 凌晨0:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hr3lxphr6j/bililive-go] 疑似直播标题导致文件路径录入问题 (Issue #456)





 
等你有空发一下上面需求的一些附加信息之后，我再调查看看吧。
 目前是比较怀疑你的执行平台比较特别。看错误信息应该是windows，不知道是不是特殊架构的windows。

**Comment by kira1928** [comment]
我又做了各种测试，都无法重现你遇到的问题，真的很奇怪。

说一下我掌握到的情况。
首先出现这个 `The filename, directory name, or volume label syntax is incorrect.` 错误是因为最终生成的文件名中包含了 "><" 这个不合法的文件名字符。
但是因为你的配置文件里使用的是默认的输出文件名模板 `out_put_tmpl: ""`，所以会使用[这个](https://github.com/hr3lxphr6j/bililive-go/blob/master/src/recorders/recorder.go#L61-L64)默认文件名模板。
其中的`[{{ .RoomName | filenameFilter }}].flv`就是 `[骚瑞 累了睡过头了><].flv`部分。
但是因为模板中使用了过滤特殊字符的[这个函数](https://github.com/hr3lxphr6j/bililive-go/blob/master/src/pkg/utils/strings.go#L58-L64)进行过滤，所以一定会把`><`替换成`__`，也就是错误信息不应该是
```
open 斗鱼\一口三明治3Mz\[2023-05-05 14-50-00][一口三明治3Mz][骚瑞 累了睡过头了><].flv: The filename, directory name, or volume label syntax is incorrect.
```
而应该是
```
open 斗鱼\一口三明治3Mz\[2023-05-05 14-50-00][一口三明治3Mz][骚瑞 累了睡过头了__].flv: The filename, directory name, or volume label syntax is incorrect.
```
不过这样的话也就不会报错了。

到这里就进入了我无法理解的执行过程了。我能想象的只有你实际使用的 config 和你发上来的不同。而且你实际使用的 config 里修改了输出文件名模板，去掉了那个过滤函数。
话说，之后你还遇到过这个问题吗？

**Comment by 976481642** [comment]
后边换回win10系统后&nbsp; 截止到现在主播也没有用特殊的标题&nbsp; 也就没出现这个情况了&nbsp;&nbsp;&nbsp;


[淘宝网]
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月5日(星期六) 晚上6:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hr3lxphr6j/bililive-go] 疑似直播标题导致文件路径录入问题 (Issue #456)





 
我又做了各种测试，都无法重现你遇到的问题，真的很奇怪。
 
说一下我掌握到的情况。
 首先出现这个 The filename, directory name, or volume label syntax is incorrect. 错误是因为最终生成的文件名中包含了 "&gt;<" 这个不合法的文件名字符。
 但是因为你的配置文件里使用的是默认的输出文件名模板 out_put_tmpl: ""，所以会使用这个默认文件名模板。
 其中的[{{ .RoomName | filenameFilter }}].flv就是 [骚瑞 累了睡过头了&gt;<].flv部分。
 但是因为模板中使用了过滤特殊字符的这个函数进行过滤，所以一定会把&gt;<替换成__，也就是错误信息不应该是
 open 斗鱼\一口三明治3Mz\[2023-05-05 14-50-00][一口三明治3Mz][骚瑞 累了睡过头了&gt;<].flv: The filename, directory name, or volume label syntax is incorrect.  
而应该是
 open 斗鱼\一口三明治3Mz\[2023-05-05 14-50-00][一口三明治3Mz][骚瑞 累了睡过头了__].flv: The filename, directory name, or volume label syntax is incorrect.  
不过这样的话也就不会报错了。
 
到这里就进入了我无法理解的执行过程了。我能想象的只有你实际使用的 config 和你发上来的不同。而且你实际使用的 config 里修改了输出文件名模板，去掉了那个过滤函数。
 话说，之后你还遇到过这个问题吗？

**Comment by kira1928** [comment]
我的开发环境也是 win11，无法重现这个问题。
无法重现的问题对我来说等于无法修复的问题。这边的 issue 我就先关掉了。如果再遇到的话可以重新打开这个 issue。
