### ISSUE TITLE
偶尔会出现只有音频（无视频），或者 只有视频（无音频）的文件。

### ISSUE THREAD

**Issue by xiatiantiantian** [hr3lxphr6j/bililive-go#46]
win10 64  ffmpeg 4.2.1 
一直挂着。偶尔会出现3个FLV文件或者更多。（排除我网络原因，录了很多个，没有断流，只生成一个文件.）

第一个FLV文件：  完整视频有声音画面。
第二个FLV文件：   10几KB 左右的文件。
第三个FLV文件：   出现只有音频 或者 只有视频 的文件。

**Comment by raydoom** [comment]
我也遇到了，b站我录了好几个视频，2个没音频，另外的都正常

**Comment by raydoom** [comment]
同一个房间的，不同时间段，当时直播我看了，直播本身是有声音的

> 我也遇到了，b站我录了好几个视频，2个没音频，另外的都正常

**Comment by kira1928** [comment]
@raydoom 能提供一下出问题的直播间吗？

**Comment by kira1928** [comment]
年代久远，issue 关闭了。
