### ISSUE TITLE
关于猫耳直播录制无法播放或用某些音乐播放软件才行

### ISSUE THREAD

**Issue by AngelMacoto** [hr3lxphr6j/bililive-go#461]
### 程序版本

最新版本

### 所使用的 config 文件的内容

用了自带的config

### 程序 log

不知道呀

### 自由描述

录制文件是全部出来了，但是打开有问题，[https://s2.loli.net/2023/05/24/hD8FyCPYfA3HEV7.png](url)
如图，打卡一直卡死在00：00，但是后缀改成MP3拖进某云音乐后，可以听，只是进度条和看直播一样，没有时长范围。 也不能快进后退。
我猜测是普通直播有画面，而猫耳没有画面，仅仅一个背景图。可能改成截取背景图与MP3合成就能解决了。求教解决方法

**Comment by AngelMacoto** [comment]
补充：log：

time="2023-05-24 19:28:17" level=info msg="BiliLive-go Version: v0.7.10 Link Start"
time="2023-05-24 19:28:18" level=info msg="Server start at 127.0.0.1:8080"
time="2023-05-24 19:42:02" level=info msg="Live Start" host="北酱c" room="弹琴丨唱歌丨混一会"
time="2023-05-24 19:42:02" level=info msg="Record Start" host="北酱c" room="弹琴丨唱歌丨混一会"
time="2023-05-24 20:15:10" level=info msg="Record End" host="北酱c" room="弹琴丨唱歌丨混一会"
time="2023-05-24 20:15:10" level=info msg="<nil>" host="北酱c" room="弹琴丨唱歌丨混一会"
time="2023-05-24 22:00:09" level=info msg="Live Start" host="汀宝敲可爱" room="3D 甜甜的~"
time="2023-05-24 22:00:09" level=info msg="Record Start" host="汀宝敲可爱" room="3D 甜甜的~"
time="2023-05-24 22:00:15" level=info msg="Live Start" host="筱安安_是胖次鸭冠" room="3D放松  前方睡意来袭~"
time="2023-05-24 22:00:15" level=info msg="Record Start" host="筱安安_是胖次鸭冠" room="3D放松  前方睡意来袭~"
time="2023-05-24 22:05:32" level=info msg="Live Start" host="蜜桃_糖果の" room="[3D]技术流~秒睡~~晚安❤"
time="2023-05-24 22:05:32" level=info msg="Record Start" host="蜜桃_糖果の" room="[3D]技术流~秒睡~~晚安❤"

config：

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 20
out_put_path: ./
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://fm.missevan.com/live/868862339
  is_listening: true
  quality: 0
- url: https://fm.missevan.com/live/129826663
  is_listening: true
  quality: 0
- url: https://fm.missevan.com/live/140216322
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

**Comment by murphysking** [comment]
猫耳直播录制的是flv格式的视频文件，用视频播放器打开看看进度条是否正常

**Comment by AngelMacoto** [comment]
> 猫耳直播录制的是flv格式的视频文件，用视频播放器打开看看进度条是否正常

附图了，不正常的。属于是一直卡着播放不出来

**Comment by AngelMacoto** [comment]
算是解决了，potplayer和系统自带的视频播放软件播放FLV有问题。。转换成MP4就行了。
