### ISSUE TITLE
希望增加直接录制视频直播流的功能

### ISSUE THREAD

**Issue by blackusagi** [hr3lxphr6j/bililive-go#462]
### 新功能

如题，希望可以直接添加在网站上找到的m3u8流进行录制，现在似乎没有好用简洁的服务器端录制m3u8流方案

**Comment by kira1928** [comment]
已经找到 m3u8 地址，只是要下载的话，现在应该有很多这类工具了。
这个项目主要是用来24小时监控指定直播间，等主播开播了开始录制用的，暂时不打算增加单独的 m3u8 链接下载功能。。
