### ISSUE TITLE
抖音录制报错

### ISSUE THREAD

**Issue by kcxg** [hr3lxphr6j/bililive-go#463]
### 程序版本

0.7.10

### 程序 log

time-"2023-06-02 16:55:18"level=error msg="failed to get page, code: 403, internal error"url="& https://live.douyin.cm/42279048403 falsetime=“2023-06-02 16:55:18”lewel=info msg=Server start at 127.0.0.1:8080time=”2023-06-02 16:56:16level=error msg="https://live.douyin.com/789875745592: failed to get page,code: 403.interna
errortime="2023-06-02 16:56:25”level=error msg-"https://1ive. douyin. com/789875745592: failed to get page,code: 403，internaerrortime="2023-06-02 16:57:07”level=error msg-"https://live.douyin. com/789875745592: failed to get page,code: 403,internaerror

### 自由描述

应该是抖音改版啦。直接打开网页也需要登录才行

**Comment by kira1928** [comment]
最怕他改版了。。之后我研究一下

**Comment by hucaloof** [comment]
> 最怕他改版了。。之后我研究一下

抖音流地址需要验证了

**Comment by kira1928** [comment]
针对这个问题，已经发布新版本 0.7.11，应该可以缓解你的问题。
