### ISSUE TITLE
无法添加抖音直播

### ISSUE THREAD

**Issue by WhenAwake** [hr3lxphr6j/bililive-go#464]
### 程序版本

0.7.10

### 自由描述

群晖docker 监控列表无法添加上抖音直播

**Comment by kira1928** [comment]
1. 看一下出问题时的 log
2. 是之前可以录，今天突然开始不能录制的吗？

**Comment by WhenAwake** [comment]
> * 看一下出问题时的 log
> * 是之前可以录，今天突然开始不能录制的
@kira1928

**Comment by WhenAwake** [comment]
> * 看一下出问题时的 log 吗？
time="2023-06-02 16:39:56" level=error msg="https://live.douyin.com/45262571827: failed to get page, code: 403, internal error"
> * 是之前可以录，今天突然开始不能录制的吗？
之前都是可以添加并录制的今天下午就突然添加不上了 可能就是前面那个兄弟说的改版了的原因
@kira1928

**Comment by sehczaa** [comment]
我也出现了同样问题

**Comment by trader7z** [comment]
出现同样问题

**Comment by kira1928** [comment]
针对这个问题，已经发布新版本 0.7.11，应该可以缓解你的问题。
