### ISSUE TITLE
抖音无法录制

### ISSUE THREAD

**Issue by L134139** [hr3lxphr6j/bililive-go#465]
### 程序版本

0.7.1

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: true
interval: 20
out_put_path: ./
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/5893162289
  is_listening: true
  quality: 0
- url: https://live.douyin.com/40461216038
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

### 程序 log

time="2023-06-02 22:44:33" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:44:54" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:45:10" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:45:32" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:45:33" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="127.0.0.1:8058"
time="2023-06-02 22:45:51" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:46:10" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:46:27" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:46:44" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:47:00" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:47:21" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:47:47" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:48:04" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="127.0.0.1:8058"
time="2023-06-02 22:48:04" level=debug msg="Http Request" Method=GET Path=/static/css/2.5b1f1a89.chunk.css RemoteAddr="127.0.0.1:8058"
time="2023-06-02 22:48:04" level=debug msg="Http Request" Method=GET Path=/static/css/main.6220e936.chunk.css RemoteAddr="127.0.0.1:9268"
time="2023-06-02 22:48:04" level=debug msg="Http Request" Method=GET Path=/static/js/2.09e56847.chunk.js RemoteAddr="127.0.0.1:9269"
time="2023-06-02 22:48:04" level=debug msg="Http Request" Method=GET Path=/static/js/main.8591cfea.chunk.js RemoteAddr="127.0.0.1:9270"
time="2023-06-02 22:48:04" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="127.0.0.1:9269"
time="2023-06-02 22:48:05" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:48:05" level=debug msg="Http Request" Method=GET Path=/manifest.json RemoteAddr="127.0.0.1:9271"
time="2023-06-02 22:48:24" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:48:44" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:49:02" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:49:24" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:49:49" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:50:08" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:50:24" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:50:41" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:51:04" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:51:05" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="127.0.0.1:9269"
time="2023-06-02 22:51:30" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:51:49" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:52:06" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:52:27" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:52:49" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:53:12" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:53:33" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:53:54" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:54:05" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="127.0.0.1:9269"
time="2023-06-02 22:54:06" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:54:20" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:54:41" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:54:58" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:55:23" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"
time="2023-06-02 22:55:38" level=error msg="failed to load room info" error="failed to get page, code: 403, internal error" url="https://live.douyin.com/40461216038"

**Comment by kira1928** [comment]
0.7.1 版本已经不能录制抖音了，需要升级到最新版本。
不过最近有人提出之前一直可用的修复后的抖音录制功能也失效了，这个还在确认中。

**Comment by L134139** [comment]
最新版不是0.7.1吗？怎么升级版本




许多
***@***.***







                       
Original Email
                       
                     

Sender:"kira1928"< ***@***.*** &gt;;

Sent Time:2023/6/2 15:31

To:"hr3lxphr6j/bililive-go"< ***@***.*** &gt;;

Cc recipient:"L134139"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [hr3lxphr6j/bililive-go] 抖音无法录制 (Issue #465)




 
0.7.1 版本已经不能录制抖音了，需要升级到最新版本。
 不过最近有人提出之前一直可用的修复后的抖音录制功能也失效了，这个还在确认中。
 
&mdash;

**Comment by kira1928** [comment]
如果是 docker，可能你用了国内的缓存镜像，不是最新版，要从 docker hub 官网下载最新版。
如果是直接运行程序的，那看一下这个项目的 release 项目，最新目前是 0.7.10 我记得。
