### ISSUE TITLE
更新0.7.11后抖音还是无法录制

### ISSUE THREAD

**Issue by WhenAwake** [hr3lxphr6j/bililive-go#467]
### 程序版本

0.7.11

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /srv/bililive
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/662688155778
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

### 自由描述

更新0.7.11后 虽然可以添加抖音 但是依然无法录制
![image](https://github.com/hr3lxphr6j/bililive-go/assets/106490099/024a60c3-0ce8-49cf-9b2d-e876a2ef9da0)
@kira1928

**Comment by WhenAwake** [comment]
并且监控列表上主播名字和标题无法正常显示，即使在直播中的也显示监控中

**Comment by kcxg** [comment]
同样的问题

**Comment by kira1928** [comment]
是的。这次是因为有人反映添加到配置里的直播间在网页上的监控列表里不显示。所以我让无论能不能加上的房间都先显示出来了。
本以为加入监控列表里，慢慢的他就能连上，不过看来这并不能解决问题。现在正在尝试其他方法，应该很快会再出一个版本。

**Comment by kira1928** [comment]
根据群内用户反馈，又更新了一版抖音修复策略。可以试一下 0.7.12 版本吗？

**Comment by WhenAwake** [comment]
> 根据群内用户反馈，又更新了一版抖音修复策略。可以试一下 0.7.12 版本吗？

我试试看

**Comment by WhenAwake** [comment]
> 根据群内用户反馈，又更新了一版抖音修复策略。可以试一下 0.7.12 版本吗？

更新0.7.12后 可以正常录制了  感谢大佬
