### ISSUE TITLE
0.7.12版本录制有问题，抖音斗鱼虎牙都有一直产生碎片
显示“<nil>” host

### ISSUE THREAD

**Issue by Loong0201** [hr3lxphr6j/bililive-go#471]

**Comment by kira1928** [comment]
可以贴一下 log 吗？

最近的两次 release 都没有动过斗鱼虎牙相关的内容。硬要说的话就是现在添加一个不存在或不支持的直播间也不会直接告诉你添加失败了，而是会先存进 config 里，然后按照其他直播间一样的频率不停的尝试连接用户添加的这个 url，如果一直不成功，那个直播间就一直显示为初始化中的状态。

**Comment by Loong0201** [comment]
time="2023-06-06 19:07:19" level=info msg="<nil>" host="
time="2023-06-06 19:20:06" level=info msg="<nil>" host="
time="2023-06-06 19:24:50" level=info msg="<nil>" host="

**Comment by hibiki222** [comment]
并非0.71.2才有的，0.7.10（更早之前）版本就有了，你是不是flv par录制的

**Comment by buzhixihuan2021** [comment]
莫妮卡  是抖音，  不是斗鱼虎牙的。

**Comment by Loong0201** [comment]
> 莫妮卡  是抖音，  不是斗鱼虎牙的。

都有遇到

**Comment by hibiki222** [comment]
> > 并非0.7.12才有的，0.7.10（更早之前）版本就有了，你是不是flv par录制的
> 
> 应该不是吧

是，每个版本我留有日志，很久之前就有了，只是你现在才发现而已

**Comment by Loong0201** [comment]
抖音虎牙斗鱼都有这问题，不知道是不是网络问题但在前面的0.7.10版本很少出现，我尝试退回去看看
