### ISSUE TITLE
[提问]: 老哥，这个可以自己填代理地址不，我在config.yml和bililive-go里修改地址都会出现tocol/network address/port) is normally permitted.

### ISSUE THREAD

**Issue by mshjz** [hr3lxphr6j/bililive-go#473]
### 程序版本

0.7.12

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:10808
debug: false
interval: 20
out_put_path: ./
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms: []
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

**Comment by kira1928** [comment]
你改成什么地址后遇到这个报错的？
报错前后的 log 可以一起发上来我看一下吗？
代理现在没有这个功能，不过要添加应该也不难。主要分成检测直播是否开播时的代理，和实际下载时的代理。应该是都可以在程序里修改。
如果看完你的 log 确实是只能用代理解决的话，可以考虑保留这个 issue 等后面看有没有人愿意贡献一个添加代理的 PR。
