### ISSUE TITLE
猫耳直播没有声音

### ISSUE THREAD

**Issue by supercell532** [hr3lxphr6j/bililive-go#474]
### 程序版本

latest

### 自由描述

rt，录制下来的文件没有声音

**Comment by kira1928** [comment]
贴一下

程序版本
所使用的 config 文件的内容
程序 log

**Comment by supercell532** [comment]
版本 v0.7.12

config
rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 10
out_put_path: ./
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/349284730993
  is_listening: true
  quality: 0
- url: https://live.douyin.com/940031487128
  is_listening: true
  quality: 0
- url: https://fm.missevan.com/live/128351929
  is_listening: true
  quality: 0
- url: https://fm.missevan.com/live/868868512
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

log文件内容：
time="2023-06-14 17:15:59" level=info msg="BiliLive-go Version: v0.7.12 Link Start"
time="2023-06-14 17:16:00" level=info msg="Server start at 127.0.0.1:8080"
time="2023-06-14 17:16:11" level=error msg="this live has a listener" url="https://fm.missevan.com/live/128351929"
time="2023-06-14 17:16:16" level=error msg="this live has a listener" url="https://fm.missevan.com/live/868868512"
time="2023-06-14 20:04:32" level=error msg="failed to load room info" error="http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=\"\"" url="https://live.douyin.com/940031487128"
time="2023-06-14 22:57:56" level=info msg="Live Start" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:56" level=info msg="Record Start" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:57" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:57" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:57" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:58" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:58" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:59" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:59" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:59" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:57:59" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:58:00" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 22:58:00" level=info msg="exit status 1" host="桥桥oo" room="3D 温柔乡"
time="2023-06-14 23:10:19" level=info msg="Live Start" host="仙仙い" room="【3D】姐姐の温柔治愈"
time="2023-06-14 23:10:19" level=info msg="Record Start" host="仙仙い" room="【3D】姐姐の温柔治愈"
time="2023-06-14 23:39:22" level=info msg="Live Start" host="奶橘尢🍊（声控助眠💤）" room="3D没有技术全是感情"
time="2023-06-14 23:39:22" level=info msg="Record Start" host="奶橘尢🍊（声控助眠💤）" room="3D没有技术全是感情"
time="2023-06-14 23:46:23" level=error msg="failed to load room info" error="stream error: stream ID 1375; INTERNAL_ERROR; received from peer" url="https://live.douyin.com/349284730993"
time="2023-06-15 01:24:08" level=info msg="Live Start" host="声控女友-水水" room="声控轻语"
time="2023-06-15 01:24:08" level=info msg="Record Start" host="声控女友-水水" room="声控轻语"
time="2023-06-15 01:27:46" level=info msg="Live end" host="声控女友-水水" room="声控轻语"
time="2023-06-15 01:27:46" level=info msg="Record End" host="声控女友-水水" room="声控轻语"
time="2023-06-15 01:27:46" level=info msg="<nil>" host="声控女友-水水" room="声控轻语"
time="2023-06-15 01:32:11" level=info msg="Live end" host="桥桥oo" room="3D 温柔乡"
time="2023-06-15 01:32:11" level=info msg="Record End" host="桥桥oo" room="3D 温柔乡"
time="2023-06-15 01:32:17" level=info msg="<nil>" host="桥桥oo" room="3D 温柔乡"
time="2023-06-15 01:38:06" level=info msg="Live Start" host="声控女友-水水" room="声控轻语"
time="2023-06-15 01:38:06" level=info msg="Record Start" host="声控女友-水水" room="声控轻语"
time="2023-06-15 02:00:50" level=info msg="Live end" host="仙仙い" room="【3D】姐姐の温柔治愈"
time="2023-06-15 02:00:50" level=info msg="Record End" host="仙仙い" room="【3D】姐姐の温柔治愈"
time="2023-06-15 02:00:56" level=info msg="<nil>" host="仙仙い" room="【3D】姐姐の温柔治愈"
time="2023-06-15 02:08:57" level=info msg="Live end" host="声控女友-水水" room="声控轻语"
time="2023-06-15 02:08:57" level=info msg="Record End" host="声控女友-水水" room="声控轻语"
time="2023-06-15 02:09:03" level=info msg="<nil>" host="声控女友-水水" room="声控轻语"
time="2023-06-15 02:31:30" level=info msg="Live end" host="奶橘尢🍊（声控助眠💤）" room="3D没有技术全是感情"
time="2023-06-15 02:31:30" level=info msg="Record End" host="奶橘尢🍊（声控助眠💤）" room="3D没有技术全是感情"
time="2023-06-15 02:32:27" level=info msg="<nil>" host="奶橘尢🍊（声控助眠💤）" room="3D没有技术全是感情"
time="2023-06-15 02:58:30" level=error msg="failed to load room info" error="http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=\"\"" url="https://live.douyin.com/349284730993"
time="2023-06-15 07:01:54" level=error msg="failed to load room info" error="stream error: stream ID 1847; INTERNAL_ERROR; received from peer" url="https://live.douyin.com/349284730993"
time="2023-06-15 10:27:57" level=error msg="failed to load room info" error="stream error: stream ID 749; INTERNAL_ERROR; received from peer" url="https://live.douyin.com/349284730993"
time="2023-06-15 12:05:39" level=error msg="failed to load room info" error="http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=\"\"" url="https://live.douyin.com/940031487128"

**Comment by supercell532** [comment]
更正，录制的文件是flv格式。使用potplayer不能正常播放

**Comment by supercell532** [comment]
使用ffmpeg -i 可以提取出mp3格式的音频

**Comment by kira1928** [comment]
[这个](https://github.com/hr3lxphr6j/bililive-go/pull/455)PR修复了这个问题，但目前修复后的版本还没有发布 release 版。
预计会在下一个版本的 0.7.13 中修复这个问题。修复方式为以后录制的文件格式为 *.aac，只录制声音。我印象中测试的时候录制下来的 aac 是可以在 potplayer 中播放的。
新版本可能在这周末发布。

**Comment by kira1928** [comment]
cc @DUYA112233

**Comment by DUYA112233** [comment]
potplayer自带的解码器无法处理现在此程序录制的仅有音轨的flv，若使用LAV作为解码器可正常播放，下一版程序将会把猫耳输出文件格式改为aac
另外，flv中音轨为aac，若转换为mp3是有损质量的，请使用此命令进行flv->aac的手动转换：
`ffmpeg -i {input_file.flv} -vn -acodec copy {output_file.aac}`
也可以尝试我的自用python脚本：
```
import os
import fnmatch
import subprocess

# 遍历指定目录及其子目录中的所有flv文件
for root, dirnames, filenames in os.walk('.'):
    for filename in fnmatch.filter(filenames, '*.flv'):
        # 提取 AAC
        input_file = os.path.join(root, filename)
        print(input_file)
        output_file = os.path.join(root, os.path.splitext(filename)[0] + '.aac')
        subprocess.call(['ffmpeg', '-i', input_file, '-vn', '-acodec', 'copy', '-y', output_file])
        # 删除源文件
        os.remove(input_file)
```
将此脚本放在“猫耳”文件夹下，运行后将自动遍历所有子文件夹中的flv并转换为aac

**Comment by kira1928** [comment]
0.7.13版本发布了。
你可以更新到最新版试试看。
