### ISSUE TITLE
可以增加一个视频号直播监控视频吗？

### ISSUE THREAD

**Issue by talway** [hr3lxphr6j/bililive-go#475]
### 新功能

可以增加一个视频号直播监控视频吗？

**Comment by kira1928** [comment]
有其他有类似功能的开源工具吗？
有的话我们可以参考他们的实现在增加，没有的话就不想挑战这个全网第一了。。

**Comment by kira1928** [comment]
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/438

**Comment by talway** [comment]
https://voipfinderliveplay.wxqcloud.qq.com/trtc_1400419933/111583_edc7f052c8ff905c23a33c433ff57564.flv?extbuf=VYNWWtvyFuUjMviDBaLOw0wmWkA0xbnD6O%2BWKDsWp10Qk8fEtWIMoT3CONF0oWtybaGLwfbxppkt%2Ffi9V0a4Y%2Fo2oLdW77RXU%2B0yLFusbAJha7FMY44lZXr9r97JwJooI4sCSjDIvrj2YzsqAtT6vpDvA8a6&openid=189c25e723a9c8efd099888e0b9a4b4a&txSecret=bef1de1c719a6877a12aeea561089a49&txTime=62216E57&wxtoken=2c188b78f1ae1c4d1418eb8767e2955b&combuf=PkV1lA4nxAULwhM3csUz9VpcetPQb7HVvSUgD%2BJ1mcKVXnPkphgMDxhqvkOnbuSK7GmzD5GQIRJdYHqNJl%2B%2Fb3i3%2BlDQnUlXJhAMHtnrxs05COd7OMhExz4mwl7l3xQDbUzl0p%2FkIhs4yPh7g0sT

**Comment by Eyion** [comment]
有款付费的非开源工具小绿点支持视频号，一直在找开源的都无果，TX会议也是
