### ISSUE TITLE
录制问题

### ISSUE THREAD

**Issue by Loong0201** [hr3lxphr6j/bililive-go#477]
录制了3小时可是录制结束点开只有40分钟，文件大小却是三小时的大小目前只在抖音发现
用了bilibili也无法修复

**Comment by kira1928** [comment]
原始flv就有这个问题还是转换成mp4才发现有这个问题呢？
你在tg群里吗？如果有原始flv文件的话方便把录制的flv视频发到群文件里么？
如果文件太大不方便就算了。。

**Comment by kira1928** [comment]
怀疑和这个问题一样：https://github.com/hr3lxphr6j/bililive-go/issues/476
