### ISSUE TITLE
希望支持docker容器修改文件和目录的权限

### ISSUE THREAD

**Issue by ghost** [hr3lxphr6j/bililive-go#479]
### 新功能

目前docker run -e PUID=1000 -e PGID=1000无法指定生成文件和目录的所有者
而 -u 1000:1000 参数则会无法启动容器（Failed to open default log file bililive-go.log for output: open bililive-go.log: permission denied）

**Comment by kira1928** [comment]
呃，这个应该怎么改呢？有什么建议吗？或者如果能直接提一个PR就最好啦。

**Comment by Luckyz-0** [comment]
我不会go语言，问了下chatgpt，大概是：容器启动时-e传入环境变量，程序通过os.Getenv获取环境变量，然后在创建目录和写入文件后用os.Chown设置文件所有者，如果要在创建文件时就修改所有者，则要修改运行程序（ffmpeg）的用户。
注意：容器内运行的用户和宿主机是相同的，即使容器内不存在UID为1000的用户程序仍然可以以1000用户运行。如果容器内存在UID为1000的a用户，容器外存在UID为1000的b用户，创建文件时在容器内看所有者是a，在宿主机看所有者是b，实际上这两个是一个用户，用户名只是一个标识。

**Comment by yingfeng-i** [comment]
> 呃，这个应该怎么改呢？有什么建议吗？或者如果能直接提一个PR就最好啦。

其实是否可以通过一些骚操作实现？
当开始录制的之后，执行下 chmod 777 -R  /src/bililivego

**Comment by yingfeng-i** [comment]
![图片](https://github.com/hr3lxphr6j/bililive-go/assets/18555737/e29263ce-a90b-4ae5-9062-681d71396d43)
我是这样操做的，但是好像如果是监控的某个直播间，之前没有直播（没有建立文件夹），现在开播了（新建了文件夹），就得重新执行下，不然文件权限存在问题
