### ISSUE TITLE
[提问]: 想咨询下修改抖音视频源获取方法

### ISSUE THREAD

**Issue by poblm** [hr3lxphr6j/bililive-go#480]
### 程序版本

最新

### 自由描述

你好，想请教一下录制清晰度怎样 修改，因为录出来的文件太大，我只需要最低清晰度的录像，应该怎样修改？谢谢

**Comment by kira1928** [comment]
目前还没有手动选择清晰度的功能。。
希望后面有人愿意贡献这方面的代码吧。

**Comment by kira1928** [comment]
Duplicate of #352
