### ISSUE TITLE
快手不能用

### ISSUE THREAD

**Issue by shanshui4731csy** [hr3lxphr6j/bililive-go#483]
刚开始添加能够，后来加到第四个房间突然间不录制了，主播名称也不显示，太奇怪了

**Comment by kira1928** [comment]
快手有很多限制，现在只能说勉强能用。

**Comment by hibiki222** [comment]
> > 快手有很多限制，现在只能说勉强能用。
> 
> cookies设置成为用户id好像也没用，现在就看到有个小软件小绿点可以比较好录制，不知道它是怎么搞的？

付费软件参考不了的，快手限制大，很容易就被ban了的

**Comment by kira1928** [comment]
已更新 readme 说明快手确实不能用了。
