### ISSUE TITLE
大家有遇到过127.0.0.1:8080无法显示内容，必须在bililive-go.exe里输入一下字母，然后重新刷新网页才可以的情况吗？

### ISSUE THREAD

**Issue by jack981122** [hr3lxphr6j/bililive-go#486]
### 程序版本

0.7.13

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
timeout_in_us: 60000000

### 自由描述

不知道是不是我添加太多直播间的关系，目前我添加了33个直播间，大概一天会遇到四五次

**Comment by jack981122** [comment]
通常出现在有人开播时，例如A直播间开播，那么我刷新网页就会显示失败

**Comment by jack981122** [comment]
time="2023-06-29 08:19:56" level=error msg="failed to load room info" error="failed to get page, code: 502, internal error" url="https://live.douyin.com/33510294475"

**Comment by kira1928** [comment]
听说在exe执行时打开的cmd窗口上鼠标点击选中一个格子就会卡住在那个cmd窗口中正在执行的程序。
之前也有人问过类似问题，最后解决方案就是不要在cmd窗口里点击选取，不小心选中了就再点一下好像就恢复了？

**Comment by kira1928** [comment]
类似情况：https://blog.csdn.net/weixin_39858881/article/details/106935616
