### ISSUE TITLE
[提问]: 抖音cookie相关

### ISSUE THREAD

**Issue by 32bit384kHZ** [hr3lxphr6j/bililive-go#488]
### 程序版本

0.7.13

### 因为没有在wiki里找到相关内容，想咨询一下录制时需要的抖音cookie的获取方式、填写内容以及格式是什么？

1. 我使用的是EditThisCookie，应该从**个人主页**导出还是从**某个主播的抖音直播间**导出cookie？
2. 导出后项目很多（如图），是需要将所有内容全部复制进配置文件，还是选择其中某一项填写即可？格式是怎样的？
![网页捕获_2-7-2023_224721_fngmhnnpilhplaeedifhccceomclgfbg](https://github.com/hr3lxphr6j/bililive-go/assets/27114434/d734ae3e-2115-45ec-905c-46a044518fcb)

**感谢解答！**

**Comment by kira1928** [comment]
首先，不添加cookie应该也是可以录抖音的。程序会生成一个随机cookie，推荐用这个，这样即使后面官方突然改变政策要惩罚用录制软件的人也不会牵连你的个人账号。

然后是回答你的问题。
> 我使用的是EditThisCookie，应该从个人主页导出还是从某个主播的抖音直播间导出cookie？

只要能导出 live.douyin.com 的 cookie，在任何地方导出结果应该都是一样的。

> 导出后项目很多（如图），是需要将所有内容全部复制进配置文件，还是选择其中某一项填写即可？格式是怎样的？

就像 [README](https://github.com/hr3lxphr6j/bililive-go#cookie-%E5%9C%A8-configyml-%E4%B8%AD%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95) 中所写的那样，我的经验是抖音只需要 `__ac_nonce` 这一个 cookie 就够了，程序的随机 cookie 也是只生成了这一个 cookie。
但也有用户表示需要同时填 `__ac_nonce` 和 `__ac_signature` 两个 cookie。你可以两种方法都试试看。

**Comment by 32bit384kHZ** [comment]
> 首先，不添加cookie应该也是可以录抖音的。程序会生成一个随机cookie，推荐用这个，这样即使后面官方突然改变政策要惩罚用录制软件的人也不会牵连你的个人账号。
> 
> 然后是回答你的问题。
> 
> > 我使用的是EditThisCookie，应该从个人主页导出还是从某个主播的抖音直播间导出cookie？
> 
> 只要能导出 live.douyin.com 的 cookie，在任何地方导出结果应该都是一样的。
> 
> > 导出后项目很多（如图），是需要将所有内容全部复制进配置文件，还是选择其中某一项填写即可？格式是怎样的？
> 
> 就像 [README](https://github.com/hr3lxphr6j/bililive-go#cookie-%E5%9C%A8-configyml-%E4%B8%AD%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95) 中所写的那样，我的经验是抖音只需要 `__ac_nonce` 这一个 cookie 就够了，程序的随机 cookie 也是只生成了这一个 cookie。 但也有用户表示需要同时填 `__ac_nonce` 和 `__ac_signature` 两个 cookie。你可以两种方法都试试看。 格式就按上面 README 里的格式写。

那我明白了，也就是说是否填写cookie并不会影响画质，可以这么理解吗？但是以防万一，关于格式还有点小问题

    "domain": "live.douyin.com",
    "expirationDate": 1688364641.344488,
    "hostOnly": true,
    "httpOnly": false,
    "name": "__ac_nonce",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "**************",
    "id": 42
这是我导出的cookie，`__ac_nonce=123456789012345678903;name=value`这里`__ac_nonce=`后的数字应该写什么，如果是写value那一行的数字的话，那么`name=value`这里的`value`需要修改为cookie当中value的值吗，还是说保持`name=value`这样的内容就可以了
