### ISSUE TITLE
斗鱼录制报错

### ISSUE THREAD

**Issue by redstone1994** [hr3lxphr6j/bililive-go#489]
### 程序版本

v0.7.13

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /srv/bililive
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.huya.com/89106
  is_listening: true
  quality: 0
- url: https://www.douyu.com/22619
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

### 程序 log

bili-go-cache-1  | time="2023-07-05 20:41:51" level=warning msg="failed to get stream url, will retry after 5s..." error="room not exists" host="Minana呀" room="今天是坏姐姐~~~~~~~~"

### 自由描述

使用docker运行
今天开始遇到的之前还可以是不是斗鱼更新了

**Comment by kira1928** [comment]
我也是用 docker，刚试了一下斗鱼还是可以录的。
你看那个直播在网页上能看吗？
还有这一行前后的log可以多贴一些嘛？还是说和这个直播间相关的 log 只有这一行呀？

**Comment by redstone1994** [comment]
![image](https://github.com/hr3lxphr6j/bililive-go/assets/26979634/2d142588-6367-4347-a7fd-e6ec856336e5)
只有斗鱼的不行 别的平台都可以，日志全是一样的

**Comment by kira1928** [comment]
你方便把 config 里的 `debug: false` 的`false`改成 `true`，再重启试试吗？
应该会输出更多的相关 log，对调查问题也许有帮助。

**Comment by redstone1994** [comment]
![image](https://github.com/hr3lxphr6j/bililive-go/assets/26979634/ae9ef020-f20a-4985-bf09-bf644079dbdd)
我用了一个之前的版本，也不好使了

**Comment by kira1928** [comment]
我也试着录了一下呆妹，用这个 url：https://www.douyu.com/t/2947432
结果就录上了。。。

**Comment by kira1928** [comment]
我看了一下，斗鱼出现这个错误信息可能有 4 种可能。现在的代码没有区分这四种情况时的 log 文字，全写一样的了，所以没法一下子发现你的问题。
我会建一个斗鱼错误信息重复，无法区分错误位置的 issue 来修复它（在未来某一天= =）。
在那之前，你这边的问题很难继续调查了。
如果很急的话，可以加 tg 群，看看群里有没有人有类似症状，也许有人可以提供一些改善意见。

**Comment by redstone1994** [comment]
非常尴尬 ，我刚又重启试了下，正常了。。。。。。
感谢回复

**Comment by kira1928** [comment]
我刚发现呆妹直播间录下来的不是flv，而是ts文件！ts文件尺寸来看似乎是都录上了，但我这边不能正常播放。
我录的其他斗鱼直播间还是flv。不知道呆妹这边有什么特殊设置还是怎样。总之斗鱼目前可能会有些问题。你也看一下你那边录下来的视频能否正常播放吧。。

**Comment by redstone1994** [comment]
本地是可以播放的，但是用咱们的网页播放器播放失败，有可能是html播放器解码的问题

**Comment by kira1928** [comment]
你录下来的也是 ts 文件是吗？

**Comment by redstone1994** [comment]
是的，我看有的主播是ts，有的是flv，好像人气大的主播是ts
