### ISSUE TITLE
编译提示GOPATH: unbound variable

### ISSUE THREAD

**Issue by binxy123** [hr3lxphr6j/bililive-go#49]
make编译提示GOPATH: unbound variable，请问是哪里的问题？
![image](https://user-images.githubusercontent.com/41134766/73804891-1bb0e880-4800-11ea-98b0-bbf5f18b79df.png)

**Comment by hr3lxphr6j** [comment]
设置GOPATH https://github.com/golang/go/wiki/SettingGOPATH

**Comment by binxy123** [comment]
@hr3lxphr6j  感谢大佬 解决了，但是我又遇到了一个问题，请问怎么处理？
undefined: strings.ReplaceAll
![image](https://user-images.githubusercontent.com/41134766/73822330-cb9e4a00-4830-11ea-950c-4aca00ebcaf2.png)

**Comment by hr3lxphr6j** [comment]
go版本太老，更新到1.13或以上
