### ISSUE TITLE
希望支持新浪微博直播

### ISSUE THREAD

**Issue by zhaochuyang929** [hr3lxphr6j/bililive-go#492]
### 新功能

希望大佬能增加支持新浪微博直播

**Comment by kira1928** [comment]
现在是不支持的。如果有其他开源项目支持的话，可以在这里提供一下，我们可以参考他们的实现移植过来。

**Comment by kira1928** [comment]
刚刚发布了 v0.7.14 版，已经支持微博直播了！
感谢 @murphysking 大佬提供 PR！
