### ISSUE TITLE
Linux平台似乎无法录制快手直播

### ISSUE THREAD

**Issue by Naboti** [hr3lxphr6j/bililive-go#497]
### 程序版本

0.7.13

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 5
out_put_path: /srv/bililive
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.kuaishou.com/u/3x9rk9ixksxqnk6
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: true
  max_duration: 30m0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
timeout_in_us: 60000000

### 自由描述

Windows版本可以正常录制快手直播，docker环境中运行的版本添加快手直播间后，主播名称和直播间名称为空白，状态一直是监控中。
![1](https://github.com/hr3lxphr6j/bililive-go/assets/122435589/590e0c2a-53a8-4358-9c19-0e562bcb50a8)

**Comment by kira1928** [comment]
快手录制需要填 cookies，然后就算填了好像也只能录几分钟的样子。
目前快手录制应该不是一个很完美的状态。

**Comment by Naboti** [comment]
> 快手录制需要填 cookies，然后就算填了好像也只能录几分钟的样子。 目前快手录制应该不是一个很完美的状态。

请问cookies怎么使用呢，我在快手直播的网页上获取到的cookies有一大段，不知道怎么在bililive go里使用

**Comment by kira1928** [comment]
怎么使用cookie可以参考README中的示例。怎么取快手cookie的话网上搜一下应该有。

**Comment by Naboti** [comment]
> 怎么使用cookie可以参考README中的示例。怎么取快手cookie的话网上搜一下应该有。

我把直播间   .kuaishou.com   .live.kuaishou.com     live.kuaishou.com的所有cookies都加了，但是监控列表里还是没有，不是很明白哎

**Comment by kira1928** [comment]
印象中只加 live.kuaishou.com 的 cookie 就可以了。
```yaml
cookies:
  live.kuaishou.com: xxx=yyy;aaa=bbb...
```

**Comment by RiverChu0** [comment]
我也是。linux下快手名字空白，只显示监控中

**Comment by kira1928** [comment]
快手录制有很多问题，我计划在下次更新时去掉本程序支持快手录制的说明。。
