### ISSUE TITLE
[提问]: 添加微博直播应该用怎么样的链接

### ISSUE THREAD

**Issue by Fengbujue2783** [hr3lxphr6j/bililive-go#499]
### 程序版本

0.7.13

### 自由描述

尝试了微博直播间链接、直播间所在动态链接和博主首页链接均无法成功添加
想问一下添加微博直播应该用怎么样的链接，谢谢

**Comment by murphysking** [comment]
https://weibo.com/l/wblive/p/show/1022:2321324925888210010576

**Comment by kira1928** [comment]
啊，微博直播最近刚刚merge进主branch，还没有发布包含它的新 release，抱歉！
这周末争取发布 0.7.14，之后就可以用上面 @murphysking 大佬发的那种格式的 url 添加了。

**Comment by kira1928** [comment]
刚刚发布了 v0.7.14 版，已经支持微博直播了！
感谢 @murphysking 大佬提供 PR！
