### ISSUE TITLE
Linux版B站直播无法获得stream url

### ISSUE THREAD

**Issue by carpenter42** [hr3lxphr6j/bililive-go#50]
版本0.5.0-rc.1，在DititalOcean和Vultr提供的VPS都出现了一样的问题，服务器所在地为新加坡，美国和印度。VPS均为Ubuntu 19.04
用央视直播当测试的log：
time="2020-02-05 20:54:13" level=info msg="BiliLive-go Version: 0.5.0-rc.1 Link Start"
time="2020-02-05 20:54:13" level=info msg="Live Start" host="哔哩哔哩直播" room="【央视新闻】【长镜头直播：武汉此时此刻】"
time="2020-02-05 20:54:13" level=info msg="Record Start" host="哔哩哔哩直播" room="【央视新闻】【长镜头直播：武汉此时此刻】"
time="2020-02-05 20:54:14" level=warning msg="failed to get stream url, will retry after 5s..." error="<nil>" host="哔哩哔哩直播" room="【央视新闻】【长镜头直播：武汉此时此刻】"
time="2020-02-05 20:54:19" level=warning msg="failed to get stream url, will retry after 5s..." error="<nil>" host="哔哩哔哩直播" room="【央视新闻】【长镜头直播：武汉此时此刻】"

本来以为是B站又换API了，但测试了一下API没问题，而且0.5.0-rc.1 Windows版也可以正常下载（美国IP），只有Linux有这个问题。

**Comment by carpenter42** [comment]
在DititalOcean的节点测试了0.4.0也是一样的问题

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/73900042-72cec000-48c9-11ea-9024-fb1fdb246c8b.png)
![image](https://user-images.githubusercontent.com/12208550/73900054-7b26fb00-48c9-11ea-9958-7ff6d8644fbc.png)
我这是正常的

**Comment by carpenter42** [comment]
> ![image](https://user-images.githubusercontent.com/12208550/73900042-72cec000-48c9-11ea-9024-fb1fdb246c8b.png)
> ![image](https://user-images.githubusercontent.com/12208550/73900054-7b26fb00-48c9-11ea-9958-7ff6d8644fbc.png)
> 我这是正常的

好奇怪... 我明天再试下，到时候反馈

**Comment by WQ-Peng** [comment]
请问最后解决了吗，遇到了同样的问题。。。

**Comment by WQ-Peng** [comment]
请问最后解决了吗，遇到了同样的问题。。。
版本0.5.5 上海阿里云服务器
time="2020-06-30 21:33:06" level=info msg="BiliLive-go Version: 0.5.5 Link Start"
time="2020-06-30 21:33:06" level=info msg="Server start at 127.0.0.1:8080"
time="2020-06-30 21:33:06" level=info msg="Live Start" host="央视新闻" room="《相对论》“七一”特辑“青春flag”之：白衣飘飘，仍是少年"
time="2020-06-30 21:33:06" level=info msg="Record Start" host="央视新闻" room="《相对论》“七一”特辑“青春flag”之：白衣飘飘，仍是少年"
time="2020-06-30 21:33:06" level=warning msg="failed to get stream url, will retry after 5s..." error="<nil>" host="央视新闻" room="《相对论》“七一”特辑“青春flag”之：白衣飘飘，仍是少年"
time="2020-06-30 21:33:11" level=warning msg="failed to get stream url, will retry after 5s..." error="<nil>" host="央视新闻" room="《相对论》“七一”特辑“青春flag”之：白衣飘飘，仍是少年"
time="2020-06-30 21:33:16" level=warning msg="failed to get stream url, will retry after 5s..." error="<nil>" host="央视新闻" room="《相对论》“七一”特辑“青春flag”之：白衣飘飘，仍是少年"
