### ISSUE TITLE
建议增加按文件大小，比如1800M 分段；建议录制成ts格式。

### ISSUE THREAD

**Issue by HarlockHomes** [hr3lxphr6j/bililive-go#504]
### 新功能

试过很多录制程序，只要是 FLV、或者转 Mp4，各种故障包括花屏，音画不同步，分辨率。
一直以前来自51pj的那个程序录制的ts文件是故障最少的，目前那作者已经不见了程序还有限制。
建议采用录制 ts。
建议按文件大小分段功能；
建议增加对douyin的直播录制时，能够为单一直播间，设定录制的清晰度，如蓝光，超清，高清，标准等。
建议浏览器中的直播列表中，增加一个可以拖动的控制点，使列表中的每一行可以上下拖动排序。
建议添加一个自定义名称，优先级高于主播自己设定的名字，有些人经常改名时就用的着。

**Comment by kira1928** [comment]
>建议采用录制 ts。

录ts一般需要hls流，这是近期几个同类项目都在尝试实现的功能。我也想做，不过进展缓慢。

>建议按文件大小分段功能；

理论上可以做到，ffmpeg可以用 -fs 参数，flv parser 可以自己计算文件尺寸。不过这个需求从没见别人提过，如果很多人需要的话可以考虑单独开issue追踪记录。

>建议增加对douyin的直播录制时，能够为单一直播间，设定录制的清晰度，如蓝光，超清，高清，标准等。

这个是我们一直想做但还没做的，印象中有专门的 issue 追踪这个需求了。期待大佬发 PR 实现它 ><

>建议浏览器中的直播列表中，增加一个可以拖动的控制点，使列表中的每一行可以上下拖动排序。

这个我也在考虑了，不过目前没看到有其他人有这个需求。如果很多人需要的话可以考虑单独开 issue 追踪记录。

>建议添加一个自定义名称，优先级高于主播自己设定的名字，有些人经常改名时就用的着。

这个我也觉得比较有意义，不过目前没看到有其他人有这个需求。如果很多人需要的话可以考虑单独开 issue 追踪记录。

**Comment by BugKun** [comment]
建议按文件大小分段功能+1

**Comment by redstone1994** [comment]
想知道大家有什么需求要分段啊，我还要自己把片段合并:joy:

**Comment by BugKun** [comment]
> 想知道大家有什么需求要分段啊，我还要自己把片段合并😂

最好加个自动合并功能。在推流视频的参数没变，并且未达到分段要求时，如果出现网络中断等原因导致分段提前结束的话，那么就自动续写文件或者自动合并。等待恢复的时间最好可配置，一般默认为10s比较好。

**Comment by kira1928** [comment]
合并的话，确实可以考虑片段之间时间间隔小于一定时间的话自动合并。不过如果是大量碎片的话合并后视频会一跳一跳的，播放起来也不连续了，接近废片。
最好还是从根本上解决cdn网络不好的问题，也就是允许用户手动指定cdn，或者频繁断线的话程序自动尝试其他可用cdn，甚至尝试降低画质录制？

**Comment by BugKun** [comment]
> 合并的话，确实可以考虑片段之间时间间隔小于一定时间的话自动合并。不过如果是大量碎片的话合并后视频会一跳一跳的，播放起来也不连续了，接近废片。 最好还是从根本上解决cdn网络不好的问题，也就是允许用户手动指定cdn，或者频繁断线的话程序自动尝试其他可用cdn，甚至尝试降低画质录制？

如果是聊天电台的话，合并碎片的跳帧问题影响不大。如果是游戏直播的话，只能通过更换更稳定的cdn处理了。尝试降低画质录制也还是会可能产生碎片，而且影响体验，感觉不太可取。

**Comment by BugKun** [comment]
自己做了一下分片功能，修改的代码不多，由于不会GO语言，如有不完善的地方，请各位大佬帮忙修改一下。
https://github.com/hr3lxphr6j/bililive-go/pull/545#issue-1889901979
