### ISSUE TITLE
[提问]: huya直播会生成好多录制文件

### ISSUE THREAD

**Issue by hailongwu123** [hr3lxphr6j/bililive-go#509]
### 程序版本

v0.7.14

### 程序 log

<!DOCTYPE html>
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style>body{font-family:"Lucida Console",Consola,Monaco,Monospace,"Courier New",Courier,Serif;}h2{text-align:center;}table{width:95%;border-collapse:collapse;}table,th,td{border:1px solid black;}td{white-space:nowrap;text-align:left;}</style>
</head>
<body>
<h2>bililive-go</h2>
<table>
<tr><th>date</th><th>stream</th><th>content</th></tr>
<tr><td>2023-07-28T08:52:08.101229410Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:52:08"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:52:08.083894792Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:52:08"&nbsp;level=info&nbsp;msg="Record&nbsp;End"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:52:07.823564683Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:52:07"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:52:07.498170243Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:52:07"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:52:05.123436143Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:52:05"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:52:04.798024816Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:52:04"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:52:01.360902441Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:52:01"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:52:01.082435576Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:52:01"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:52:00.754264544Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:52:00"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:59.025508849Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:59"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:58.743500093Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:58"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:58.468511194Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:58"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:58.131790067Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:58"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:56.462842622Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:56"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:53.565031367Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:53"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:53.270171987Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:53"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:52.940379430Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:52"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:50.008475424Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:50"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:46.535055828Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:46"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:46.130144498Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:46"&nbsp;level=info&nbsp;msg="Record&nbsp;Start"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:51:46.129334623Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:51:46"&nbsp;level=info&nbsp;msg="Live&nbsp;Start"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:45:01.959752789Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:45:01"&nbsp;level=error&nbsp;msg="https://al.flv.huya.com/src/1430972471-1430972471-6145979964421308416-2862068398-10057-A-0-1-imgplus.flv?ratio=500&amp;wsSecret=330f6dbc0be43ebd0535504c5f8b183f&amp;wsTime=64c4d130&amp;fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&amp;ctype=tars_mobile&amp;fs=bgct&amp;sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&amp;sphdDC=huya&amp;sphd=264_*-265_*&amp;exsphd=264_500,264_2000,264_4000,264_8000,&amp;t=103:&nbsp;not&nbsp;support&nbsp;this&nbsp;url"
</td></tr>
<tr><td>2023-07-28T08:44:58.817859905Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:44:58"&nbsp;level=error&nbsp;msg="https://al.flv.huya.com/src/1430972471-1430972471-6145979964421308416-2862068398-10057-A-0-1-imgplus.flv?ratio=500&amp;wsSecret=330f6dbc0be43ebd0535504c5f8b183f&amp;wsTime=64c4d130&amp;fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&amp;ctype=tars_mobile&amp;fs=bgct&amp;sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&amp;sphdDC=huya&amp;sphd=264_*-265_*&amp;exsphd=264_500,264_2000,264_4000,264_8000,&amp;t=103:&nbsp;not&nbsp;support&nbsp;this&nbsp;url"
</td></tr>
<tr><td>2023-07-28T08:44:29.381644677Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:44:29"&nbsp;level=error&nbsp;msg="https://al.flv.huya.com/src/1430972471-1430972471-6145979964421308416-2862068398-10057-A-0-1-imgplus.flv?ratio=500&amp;wsSecret=330f6dbc0be43ebd0535504c5f8b183f&amp;wsTime=64c4d130&amp;fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&amp;ctype=tars_mobile&amp;fs=bgct&amp;sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&amp;sphdDC=huya&amp;sphd=264_*-265_*&amp;exsphd=264_500,264_2000,264_4000,264_8000,&amp;t=103:&nbsp;not&nbsp;support&nbsp;this&nbsp;url"
</td></tr>
<tr><td>2023-07-28T08:32:29.722115730Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:29"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:29.647796224Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:29"&nbsp;level=info&nbsp;msg="Record&nbsp;End"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:27.852063412Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:27"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:25.409927356Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:25"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:25.073728809Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:25"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:23.546448502Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:23"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:23.220571752Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:23"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:22.141730631Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:22"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:21.806966143Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:21"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:20.331345132Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:20"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:19.953577745Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:19"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:18.158333279Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:18"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:16.647942395Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:16"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:16.302741210Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:16"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:14.652243871Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:14"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:13.090609112Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:13"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:12.799333681Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:12"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:12.459079672Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:12"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:10.117580742Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:10"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:09.754443669Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:09"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:08.274340714Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:08"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:07.998155178Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:07"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:07.721759789Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:07"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:07.387236193Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:07"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:05.897450752Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:05"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:04.423042023Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:04"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:04.023029320Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:04"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:03.725176976Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:03"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:03.380545200Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:03"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:01.944160768Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:01"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:00.436097972Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:00"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:32:00.116482430Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:32:00"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:31:59.748586959Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:31:59"&nbsp;level=info&nbsp;msg="&lt;nil&gt;"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:31:58.517168693Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:31:58"&nbsp;level=info&nbsp;msg="exit&nbsp;status&nbsp;1"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:31:57.075266764Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:31:57"&nbsp;level=info&nbsp;msg="Record&nbsp;Start"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:31:57.074485452Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:31:57"&nbsp;level=info&nbsp;msg="Live&nbsp;Start"&nbsp;host="Letme严君泽"&nbsp;room="今天先上个大师！"
</td></tr>
<tr><td>2023-07-28T08:28:52.645883585Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:28:52"&nbsp;level=info&nbsp;msg="Server&nbsp;start&nbsp;at&nbsp;:8080"
</td></tr>
<tr><td>2023-07-28T08:28:52.644897844Z</td><td>stdout</td><td>time="2023-07-28&nbsp;16:28:52"&nbsp;level=info&nbsp;msg="BiliLive-go&nbsp;Version:&nbsp;v0.7.14&nbsp;Link&nbsp;Start"
</td></tr>
</table></body></html>

### 自由描述

![11](https://github.com/hr3lxphr6j/bililive-go/assets/123808849/baf9c991-8132-4c56-a0cb-e23353a8e295)
会生成大量文件，问题从7月27号开始出现这个问题，之前录制都正常~

**Comment by kira1928** [comment]
虎牙阿里云cdn断流问题太严重了。我可能会在下一个版本中硬编码避免使用这个cdn来解决这类问题。

**Comment by hailongwu123** [comment]
> 虎牙阿里云cdn断流问题太严重了。我可能会在下一个版本中硬编码避免使用这个cdn来解决此类问题。

我发现有些主播不会这样，比如王者荣耀的就录制正常，但是LOL的就会出现问题，

嗯，那我只能等下个版本了，谢谢辛苦了

**Comment by Parting2-Plated-Cleat** [comment]
一样的问题，我好几天没管了，今天一看才发现有50000多个文件，吓我一跳。

**Comment by kira1928** [comment]
刚刚发布的 v0.7.15 版本已经修复这个问题啦！
感谢 @yaobiao131 大佬提供的 [PR](https://github.com/hr3lxphr6j/bililive-go/pull/511)！

**Comment by hailongwu123** [comment]
> 刚刚发布的 v0.7.15 版本已经修复这个问题啦！ 谢谢@yaobiao131大佬提供[公关](https://github.com/hr3lxphr6j/bililive-go/pull/511)！

哇，那我赶快升级
