### ISSUE TITLE
[提问]: 请问如何在config文件中，设置保存的文件名模板？

### ISSUE THREAD

**Issue by HarlockHomes** [hr3lxphr6j/bililive-go#510]
### 程序版本

0.7.13

### 自由描述

请问如何在config文件中，设置保存的文件名模板？

首页帮助里话完全不知道要怎么用。示例文件里面也没有文件名保存模板这一项。

**Comment by zxr10-ha** [comment]
同问

**Comment by kira1928** [comment]
https://github.com/hr3lxphr6j/bililive-go/wiki/More-Tips#%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E5%90%8D%E6%A8%A1%E6%9D%BF

**Comment by kira1928** [comment]
如果这个wiki看不懂的话，也可以说一下你想改成什么样，也许其他人可以帮你写一个模板

**Comment by zxr10-ha** [comment]
想要的格式：主播名字 日期.flv
示例：“刘德华 2023.07.30 00:00:00.flv”

有大神可以帮忙写一个模板格式吗？先谢了。

**Comment by waitsaber** [comment]
{{ .HostName | filenameFilter }}-[{{ now | date "2006-01-02 15-04-05"}}].flv
这个应该就是你要的，可以填到out_put_tmpl试试

**Comment by zxr10-ha** [comment]
不行，之前这样写过，应用闪退，以下是配置文件：
out_put_tmpl: "{{ .HostName | filenameFilter }}-[{{ now | date "2006-01-02 15-04-05"}}].flv"
# out_put_tmpl: {{ .HostName | filenameFilter }}-[{{ now | date "2006-01-02 15-04-05"}}].flv
video_split_strategies:
  on_room_name_changed: false
  max_duration: 5h0m0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
timeout_in_us: 60000000

**Comment by kira1928** [comment]
解决了的话这边的 issue 我就关掉啦？

**Comment by zxr10-ha** [comment]
已解决。
wiki页面，out_put_tmpl后面是双信号，如果自定义文件名模板的话，要改成单引号，否则程序会闪退。
