### ISSUE TITLE
能否监控抖音up主，发布视频就下载下来，时刻监控

### ISSUE THREAD

**Issue by talway** [hr3lxphr6j/bililive-go#513]
### 新功能

能否监控抖音up主，发布视频就下载下来，时刻监控。
下载无水印视频
下载图文
这些都有开源的
能否集成到这里来的

**Comment by kira1928** [comment]
我觉得加这些功能不太好。这些功能有些脱离这个项目原本的目的，也就是24小时监控直播间录直播视频这件事了。。

**Comment by justdoiting** [comment]
江湖工具箱  有这个功能
![image](https://github.com/hr3lxphr6j/bililive-go/assets/109136320/3cfd16a9-af19-40dc-b893-c39fd737f707)

**Comment by kira1928** [comment]
搞定了的话这边 issue 我就关闭啦。
