### ISSUE TITLE
微博直播清晰度问题

### ISSUE THREAD

**Issue by Fengbujue2783** [hr3lxphr6j/bililive-go#518]
### 新功能

某些微博直播间虽然有720p的推流 但是网页端给出的是540p的流 可以通过把链接里的540替换成720来获取更高的清晰度 不知道程序是否能支持这一操作

**Comment by kira1928** [comment]
@murphysking 大佬有兴趣么？

**Comment by murphysking** [comment]
有具体的直播间链接吗？

**Comment by Fengbujue2783** [comment]
https://weibo.com/l/wblive/p/show/1022:2321324925299250037602
https://weibo.com/l/pc/anchor/live?live_id=1022:2321324925299250037602

**Comment by Fengbujue2783** [comment]
> 有具体的直播间链接吗？

tps://weibo.com/l/wblive/p/show/1022:2321324925299250037602
https://weibo.com/l/pc/anchor/live?live_id=1022:2321324925299250037602

**Comment by Fengbujue2783** [comment]
> 有具体的直播间链接吗？

https://weibo.com/l/wblive/p/show/1022:2321324925299250037602
https://weibo.com/l/pc/anchor/live?live_id=1022:2321324925299250037602

**Comment by murphysking** [comment]
我试了下确实可以这么操作，但是这种操作不一定通用，程序目前没有好办法处理。我考虑在链接上增加参数，手动指定视频分辨率

**Comment by BugKun** [comment]
已PR(https://github.com/hr3lxphr6j/bililive-go/pull/706)，待 @kira1928 合并。

**Comment by kira1928** [comment]
已合并
