### ISSUE TITLE
bilibili直播无法获得stream url 

### ISSUE THREAD

**Issue by anlo1220** [hr3lxphr6j/bililive-go#52]
bilibili直播无法获得stream url 不知是否是ban ip 
本地是都為正常
用不同 vps 測試  目前用两天
virmach 紐約 為正常
contabo 德國 昨日正常今日一直 failed to get stream url 不同直播间都一样
time="2020-02-16 00:42:34" level=info msg="Live Start" host="3号直播间" room="哔哩哔哩音悦台"
time="2020-02-16 00:42:34" level=info msg="Record Start" host="3号直播间" room="哔哩哔哩音悦台"
time="2020-02-16 00:42:35" level=warning msg="failed to get stream url, will retry after 5s..." error="412 Precondition Failed" host="3号直播间" room="哔哩哔哩音悦台"
time="2020-02-16 00:42:40" level=warning msg="failed to get stream url, will retry after 5s..." error="412 Precondition Failed" host="3号直播间" room="哔哩哔哩音悦台"
time="2020-02-16 00:42:45" level=warning msg="failed to get stream url, will retry after 5s..." error="412 Precondition Failed" host="3号直播间" room="哔哩哔哩音悦台"
time="2020-02-16 00:42:51" level=warning msg="failed to get stream url, will retry after 5s..." error="412 Precondition Failed" host="3号直播间" room="哔哩哔哩音悦台"
time="2020-02-16 00:42:56" level=warning msg="failed to get stream url, will retry after 5s..." error="412 Precondition Failed" host="3号直播间" room="哔哩哔哩音悦台"
time="2020-02-16 00:43:01" level=warning msg="failed to get stream url, will retry after 5s..." error="412 Precondition Failed" host="3号直播间" room="哔哩哔哩音悦台"

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/74597969-846f4f00-50a3-11ea-80bb-3d4c6cb94a51.png)
上海电信没问题，我没这几个地方的机器没法测试，不过大概率是ban ip，这种我也没啥办法。

**Comment by anlo1220** [comment]
可能国外有限制都会ban
我国内用没被ban流量也比国外大
