### ISSUE TITLE
录制bilibili直播时，有时使用flv格式，有时使用ts格式

### ISSUE THREAD

**Issue by javayxw** [hr3lxphr6j/bililive-go#521]
### 程序版本

docker版本

### 自由描述

程序版本：暂时不清楚，目前采用的是项目中给的docker命令直接部署的

问题描述：录制的平台为：哔哩哔哩 ，目前开了两个直播间监控，第一个直播间录制的视频格式没有出现过任何问题，一直是flv格式，音画正常同步，画质高清。第二个直播间是后来加入的，当初第一次加入的时候，发现录制的视频格式为ts，音画同步有问题，画质也不清晰，但确实视频格式较小。后来第二次和第三次录制时，格式变成了flv。昨天第四次录制，又变成了ts格式。

不晓得程序对于录制这块儿的逻辑是如何判断的，请教大佬可以解决这个问题吗？

**Comment by kira1928** [comment]
录成 ts 可能是当时直播间有 hevc 格式的直播流，config 文件里又默认选择了优先使用 hevc 直播流导致的。
可以看一下这段注释：https://github.com/hr3lxphr6j/bililive-go/blob/master/config.yml#L15-L18

**Comment by javayxw** [comment]
感谢大佬的指导，已经明白原因了，下次我会多看看注释的，再次感谢
