### ISSUE TITLE
录制的视频播放不了

### ISSUE THREAD

**Issue by Hertz221** [hr3lxphr6j/bililive-go#526]
### 程序版本

0.7.15

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 50
out_put_path: D:\录制
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: false
  save_every_log: false
feature:
  use_native_flv_parser: true
  remove_symbol_other_character: false
live_rooms:

out_put_tmpl: '{{ .HostName | filenameFilter }}/{{ .HostName | filenameFilter }} {{ now | date "2006-01-02 15-04-05"}}'
video_split_strategies:
  on_room_name_changed: false
  max_duration: 1h0m0s
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
timeout_in_us: 60000000

### 自由描述

配置文件的url我省略了，是抖音的直播间，主播被封禁后的文件打不开
<img src="https://tu.wnflb2023.com/i/2023/08/19/215604.png" alt="屏幕截图 2023-08-19 215545" />
显示是这样的

**Comment by kira1928** [comment]
用什么程序打不开？试试 potplayer？

**Comment by kira1928** [comment]
可不可以用[这个](https://kira1928.github.io/web-tools/#/file-split)网页工具切割下来那个 mp4 文件的前 10MB 发上来我研究一下？

**Comment by Hertz221** [comment]
> 用什么程序打不开？试试 potplayer？

我用的mpv播放器打开就闪退，画面都没有，系统自带的也打不开，vlc也不行，后来我用一个工具给修复了

**Comment by kira1928** [comment]
已经修复了？修复工具有没有说是什么问题？

**Comment by Hertz221** [comment]
> 已经修复了？修复工具有没有说是什么问题？

一开始想用录播姬修复，结果提示mp4文件不行，我就试试ffmpeg能不能转flv（这个我不知道能不能mp4转flv）结果是不行的，搜了下vlc也可以修复视频，我就试着结果也不行，后来用digital video repair这个工具给修复了，貌似这个工具没啥提示，它检测完提示有没有同一相机录制的文件我就选择了其他录制视频就给修复成功了，没有提示什么错误

**Comment by kira1928** [comment]
解决了就好。那issue我关掉啦。
