### ISSUE TITLE
作者好，快手直播的回放作品有办法批量下载吗？

### ISSUE THREAD

**Issue by xueli12** [hr3lxphr6j/bililive-go#528]
### 新功能

![image](https://github.com/hr3lxphr6j/bililive-go/assets/51438016/f2b0e8af-1104-47ee-9dee-ded53bc6313d)
打开直播间，有一些直播回看，想下载下来，量还不少，一个一个用猫爪解析m3再下载太慢。

**Comment by daWxiaow** [comment]
我有现成的程序可以用

**Comment by Naboti** [comment]
用m3u8下载器就好啦，你可以在回放页面获取m3u8文件的地址，然后丢下载器里，很方便也很快
