### ISSUE TITLE
抖音出现-failed to get RENDER_DATA from page, internal error

### ISSUE THREAD

**Issue by antonio65421** [hr3lxphr6j/bililive-go#533]
### 程序版本

0.7.15

### 程序 log

level=error msg="failed to load room info" error="failed to get RENDER_DATA from page, internal error"

### 自由描述

这几天才出现这总情况

**Comment by kira1928** [comment]
可以把 config.yml 里的 debug 的值设为 true 然后再看看 log 里有什么吗？

**Comment by kira1928** [comment]
可能需要重启一次程序

**Comment by antonio65421** [comment]
time="2023-09-03 00:04:52" level=debug msg="other flags have been ignored."
time="2023-09-03 00:04:52" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.15 Build
Time:2023-07-30_08:24:00 GitHash:346816ab8d409e51f3b61326c5692eac1ee437c8 Pid:10560 Platform:windows/amd64 GoVersion:go1.19.11}"
time="2023-09-03 00:04:52" level=debug msg="&{File:D:\\bililive-go\\config.yml RPC:{Enable:true Bind:127.0.0.1:8080} Debug:true Interval:36 OutPutPath:D:\\bililive-go斗鱼录制 FfmpegPath: Log:{OutPutFolder:./ SaveLastLog:true SaveEveryLog:false} Feature:{UseNativeFlvParser:false RemoveSymbolOtherCharacter:false}

**Comment by kira1928** [comment]
需要看 failed to get RENDER_DATA from page, internal error 这个 log 前后的 log

**Comment by antonio65421** [comment]
不太懂

**Comment by kira1928** [comment]
就是先把设置里的 debug 打开，这个你已经做完了。
之后程序再输出 log 的时候会输出相对比较多的信息。
在这样的状态下，等到你下次再遇到抖音出现 failed to get RENDER_DATA from page, internal error 这个 log 的时候，你再把那时候的这个 log 前后的 log 一起发上来，我看看有没有有用的线索可以用来解决这个问题。

**Comment by antonio65421** [comment]
Press [q] to stop, [?] for help
time="2023-09-03 00:29:46" level=info msg="Live Start" host="妤味泡芙" room="素颜、演员界的潜水教练"
time="2023-09-03 00:29:46" level=info msg="Record Start" host="妤味泡芙" room="素颜、演员界的潜水教练"
time="2023-09-03 00:29:47" level=debug msg="Start ParseLiveStream(http://pull-flv-f1.douyincdn.com/stage/stream-690120646922863274_or4.flv?keeptime=00093a80&wsSecret=6030b860d92ba9aaf0a5d13b91feab78&wsTime=64f362fe, D:\\bililive-go斗鱼录制\\抖音\\妤味泡芙\\[2023-09-03 00-29-47][妤味泡芙][素颜、演员界的潜水教练].flv)" host="妤味泡芙" room="素颜、演员界的潜水教练"
ffmpeg version 2023-05-25-git-944243477b-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  9.100 / 58.  9.100
  libavcodec     60. 14.101 / 60. 14.101
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, flv, from 'http://pull-flv-f1.douyincdn.com/stage/stream-690120646922863274_or4.flv?keeptime=00093a80&wsSecret=6030b860d92ba9aaf0a5d13b91feab78&wsTime=64f362fe':
  Metadata:
    model           : iPhone13,4
    fp_vmode        : 1
    start_time      : 1693671730353
    min_bitrate     : 1000
    is_hardware_encode: 1
    s_id            : 8
    publish_time_stamp: 1693671730
    stream_id       : push-rtmp-hs-f5.douyincdn.com:stage:stream-690120646922863274_or4
    e_id            : 0
    max_bitrate     : 2490
    link_info       : n.cn-56uylx.lz5o_3767814,n.cn-56uylx.2w8t_3953140
    p_id            : 6
    fp_coderate     : 2549760
    fp_amode        : 0
    qId             : {"ios_1080p_fps_22":true,"ios_denoise_v3dot1":true}
    platform        : iOS
    os_version      : 15.5
    default_bitrate : 2024
    fp_nb           : 0
    ab              : 0
    encoder         : Lavf58.45.100
    h_id            : 0
    interval        : 2
    push_protocol   : rtmp
    sdk_version     : 14.7.0.10-aweme
    hit_node_optimize: 1
  Duration: 00:00:00.00, start: 457.565000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1088x1920, 2549 kb/s, 20 fps, 100 tbr, 1k tbn
  Stream #0:1: Audio: aac (HE-AAC), 44100 Hz, stereo, fltp, 64 kb/s
Output #0, flv, to 'D:\bililive-go斗鱼录制\抖音\妤味泡芙\[2023-09-03 00-29-47][妤味泡芙][素颜、演员界的潜水教练].flv':
  Metadata:
    model           : iPhone13,4
    fp_vmode        : 1
    start_time      : 1693671730353
    min_bitrate     : 1000
    is_hardware_encode: 1
    s_id            : 8
    publish_time_stamp: 1693671730
    stream_id       : push-rtmp-hs-f5.douyincdn.com:stage:stream-690120646922863274_or4
    e_id            : 0
    max_bitrate     : 2490
    link_info       : n.cn-56uylx.lz5o_3767814,n.cn-56uylx.2w8t_3953140
    p_id            : 6
    fp_coderate     : 2549760
    fp_amode        : 0
    qId             : {"ios_1080p_fps_22":true,"ios_denoise_v3dot1":true}
    platform        : iOS
    os_version      : 15.5
    default_bitrate : 2024
    fp_nb           : 0
    ab              : 0
    hit_node_optimize: 1
    h_id            : 0
    interval        : 2
    push_protocol   : rtmp
    sdk_version     : 14.7.0.10-aweme
    encoder         : Lavf60.5.100
  Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1088x1920, q=2-31, 2549 kb/s, 20 fps, 100 tbr, 1k tbn
  Stream #0:1: Audio: aac (HE-AAC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
time="2023-09-03 00:29:59" level=error msg="failed to load room info" error="failed to get RENDER_DATA from page, internal error" url=https://live.douyin.com/

**Comment by antonio65421** [comment]
Press [q] to stop, [?] for help
time="2023-09-03 00:29:46" level=info msg="Live Start" host="妤味泡芙" room="素颜、演员界的潜水教练"
time="2023-09-03 00:29:46" level=info msg="Record Start" host="妤味泡芙" room="素颜、演员界的潜水教练"
time="2023-09-03 00:29:47" level=debug msg="Start ParseLiveStream(http://pull-flv-f1.douyincdn.com/stage/stream-690120646922863274_or4.flv?keeptime=00093a80&wsSecret=6030b860d92ba9aaf0a5d13b91feab78&wsTime=64f362fe, D:\\bililive-go斗鱼录制\\抖音\\妤味泡芙\\[2023-09-03 00-29-47][妤味泡芙][素颜、演员界的潜水教练].flv)" host="妤味泡芙" room="素颜、演员界的潜水教练"
ffmpeg version 2023-05-25-git-944243477b-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  9.100 / 58.  9.100
  libavcodec     60. 14.101 / 60. 14.101
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, flv, from 'http://pull-flv-f1.douyincdn.com/stage/stream-690120646922863274_or4.flv?keeptime=00093a80&wsSecret=6030b860d92ba9aaf0a5d13b91feab78&wsTime=64f362fe':
  Metadata:
    model           : iPhone13,4
    fp_vmode        : 1
    start_time      : 1693671730353
    min_bitrate     : 1000
    is_hardware_encode: 1
    s_id            : 8
    publish_time_stamp: 1693671730
    stream_id       : push-rtmp-hs-f5.douyincdn.com:stage:stream-690120646922863274_or4
    e_id            : 0
    max_bitrate     : 2490
    link_info       : n.cn-56uylx.lz5o_3767814,n.cn-56uylx.2w8t_3953140
    p_id            : 6
    fp_coderate     : 2549760
    fp_amode        : 0
    qId             : {"ios_1080p_fps_22":true,"ios_denoise_v3dot1":true}
    platform        : iOS
    os_version      : 15.5
    default_bitrate : 2024
    fp_nb           : 0
    ab              : 0
    encoder         : Lavf58.45.100
    h_id            : 0
    interval        : 2
    push_protocol   : rtmp
    sdk_version     : 14.7.0.10-aweme
    hit_node_optimize: 1
  Duration: 00:00:00.00, start: 457.565000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1088x1920, 2549 kb/s, 20 fps, 100 tbr, 1k tbn
  Stream #0:1: Audio: aac (HE-AAC), 44100 Hz, stereo, fltp, 64 kb/s
Output #0, flv, to 'D:\bililive-go斗鱼录制\抖音\妤味泡芙\[2023-09-03 00-29-47][妤味泡芙][素颜、演员界的潜水教练].flv':
  Metadata:
    model           : iPhone13,4
    fp_vmode        : 1
    start_time      : 1693671730353
    min_bitrate     : 1000
    is_hardware_encode: 1
    s_id            : 8
    publish_time_stamp: 1693671730
    stream_id       : push-rtmp-hs-f5.douyincdn.com:stage:stream-690120646922863274_or4
    e_id            : 0
    max_bitrate     : 2490
    link_info       : n.cn-56uylx.lz5o_3767814,n.cn-56uylx.2w8t_3953140
    p_id            : 6
    fp_coderate     : 2549760
    fp_amode        : 0
    qId             : {"ios_1080p_fps_22":true,"ios_denoise_v3dot1":true}
    platform        : iOS
    os_version      : 15.5
    default_bitrate : 2024
    fp_nb           : 0
    ab              : 0
    hit_node_optimize: 1
    h_id            : 0
    interval        : 2
    push_protocol   : rtmp
    sdk_version     : 14.7.0.10-aweme
    encoder         : Lavf60.5.100
  Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1088x1920, q=2-31, 2549 kb/s, 20 fps, 100 tbr, 1k tbn
  Stream #0:1: Audio: aac (HE-AAC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
time="2023-09-03 00:29:59" level=error msg="failed to load room info" error="failed to get RENDER_DATA from page, internal error" url=https://live.douyin.com/

**Comment by antonio65421** [comment]
不知道.對你有沒有幫助.前後沒顯示.能錄.就是一直跑那個代碼

**Comment by jack981122** [comment]
> 就是先把设置里的 debug 打开，这个你已经做完了。 之后程序再输出 log 的时候会输出相对比较多的信息。 在这样的状态下，等到你下次再遇到抖音出现 无法从页面获取RENDER_DATA，内部错误 这个 log 的时候，你再把那时候的这个 log 前后的 log 一起发上来，我看看有没有有用的线索可以用来解决这个问题。

time="2023-09-03 06:16:51" level=info msg="BiliLive-go Version: v0.7.15 Link Start"
time="2023-09-03 06:16:51" level=debug msg="config path: H:\\bililive\\config.yml."
time="2023-09-03 06:16:51" level=debug msg="other flags have been ignored."
time="2023-09-03 06:16:51" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.15 BuildTime:2023-07-30_08:24:00 GitHash:346816ab8d409e51f3b61326c5692eac1ee437c8 Pid:10956 Platform:windows/amd64 GoVersion:go1.19.11}"
time="2023-09-03 06:16:51" level=debug msg="&{File:H:\\bililive\\config.yml RPC:{Enable:true Bind:127.0.0.1:8080} Debug:true Interval:60 OutPutPath:./ FfmpegPath: Log:{OutPutFolder:./ SaveLastLog:true SaveEveryLog:false} Feature:{UseNativeFlvParser:false RemoveSymbolOtherCharacter:false} LiveRooms:[{Url:https://live.douyin.com/101149621029 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/141005260784 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/201131942769 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/232456778140 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/284168683445 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/350737633233 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/357479258526 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/630131081341 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/81929881042 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/841936067471 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/878663493540 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/905410035851 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/947468024686 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/47785908478 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/dymo8yhreivu IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/47230362998 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/cttttc IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/32981901870 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/172866001543 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/947760858533 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/874129894926 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/dy8mubx68rzk IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/523736611397 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/167505046050?video_id=7261277637719427875 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/53771052444 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/11111781608 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/377190243758 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/55102971785 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/718538287860 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/uki0114 IsListening:true LiveId: Quality:0} {Url:https://www.douyu.com/22619 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/50142002958 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/67815124553 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/S888821 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/640355136243 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/424208106660 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/374956500935 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/904445332387 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/467623961784 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/891557979486 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/Evenbaeee IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/971288847253 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/e22v66e88n IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/19535174192 IsListening:true LiveId: Quality:0} {Url:https://live.douyin.com/986850154361 IsListening:true LiveId: Quality:0}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s} Cookies:map[] OnRecordFinished:{ConvertToMp4:true DeleteFlvAfterConvert:true} TimeoutInUs:60000000 liveRoomIndexCache:map[https://live.douyin.com/101149621029:0 https://live.douyin.com/11111781608:25 https://live.douyin.com/141005260784:1 https://live.douyin.com/167505046050?video_id=7261277637719427875:23 https://live.douyin.com/172866001543:18 https://live.douyin.com/19535174192:43 https://live.douyin.com/201131942769:2 https://live.douyin.com/232456778140:3 https://live.douyin.com/284168683445:4 https://live.douyin.com/32981901870:17 https://live.douyin.com/350737633233:5 https://live.douyin.com/357479258526:6 https://live.douyin.com/374956500935:36 https://live.douyin.com/377190243758:26 https://live.douyin.com/424208106660:35 https://live.douyin.com/467623961784:38 https://live.douyin.com/47230362998:15 https://live.douyin.com/47785908478:13 https://live.douyin.com/50142002958:31 https://live.douyin.com/523736611397:22 https://live.douyin.com/53771052444:24 https://live.douyin.com/55102971785:27 https://live.douyin.com/630131081341:7 https://live.douyin.com/640355136243:34 https://live.douyin.com/67815124553:32 https://live.douyin.com/718538287860:28 https://live.douyin.com/81929881042:8 https://live.douyin.com/841936067471:9 https://live.douyin.com/874129894926:20 https://live.douyin.com/878663493540:10 https://live.douyin.com/891557979486:39 https://live.douyin.com/904445332387:37 https://live.douyin.com/905410035851:11 https://live.douyin.com/947468024686:12 https://live.douyin.com/947760858533:19 https://live.douyin.com/971288847253:41 https://live.douyin.com/986850154361:44 https://live.douyin.com/Evenbaeee:40 https://live.douyin.com/S888821:33 https://live.douyin.com/cttttc:16 https://live.douyin.com/dy8mubx68rzk:21 https://live.douyin.com/dymo8yhreivu:14 https://live.douyin.com/e22v66e88n:42 https://live.douyin.com/uki0114:29 https://www.douyu.com/22619:30]}"
time="2023-09-03 06:17:16" level=info msg="Server start at 127.0.0.1:8080"
time="2023-09-03 06:17:50" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="127.0.0.1:10693"
time="2023-09-03 06:17:50" level=debug msg="Http Request" Method=GET Path=/static/css/2.5b1f1a89.chunk.css RemoteAddr="127.0.0.1:10693"
time="2023-09-03 06:17:50" level=debug msg="Http Request" Method=GET Path=/static/css/main.6220e936.chunk.css RemoteAddr="127.0.0.1:10694"
time="2023-09-03 06:17:50" level=debug msg="Http Request" Method=GET Path=/static/js/main.c077553f.chunk.js RemoteAddr="127.0.0.1:10696"
time="2023-09-03 06:17:50" level=debug msg="Http Request" Method=GET Path=/static/js/2.09e56847.chunk.js RemoteAddr="127.0.0.1:10697"
time="2023-09-03 06:17:50" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="127.0.0.1:10697"
time="2023-09-03 06:17:50" level=debug msg="Http Request" Method=GET Path=/manifest.json RemoteAddr="127.0.0.1:10698"
time="2023-09-03 06:18:34" level=error msg="failed to load room info" error="failed to get RENDER_DATA from page, internal error" url="https://live.douyin.com/904445332387"
是这个日志吗

**Comment by kira1928** [comment]
感谢！
等我晚上回家看一下

**Comment by kira1928** [comment]
感觉是被抖音暂时屏蔽了？如果被屏蔽之前录制已经开始了就不影响继续录制。

**Comment by jack981122** [comment]
> 感觉是被抖音暂时屏蔽了？如果被屏蔽之前录制已经开始了就不影响继续录制。

好像是，早上还是可以正常录制的，今天就全部显示初始化中
