### ISSUE TITLE
抖音直播录制 “主播名称” “直播间名称” 显示空白，无法录制

### ISSUE THREAD

**Issue by nc1192** [hr3lxphr6j/bililive-go#537]
### 程序版本

v0.7.16

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: true
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.lang.live/room/5664344
  is_listening: false
  quality: 0
- url: https://live.bilibili.com/22603245
  is_listening: false
  quality: 0
- url: https://live.douyin.com/562956577855
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

time="2023-09-06 00:07:26" level=info msg="BiliLive-go Version: v0.7.16 Link Start"
time="2023-09-06 00:07:26" level=debug msg="config path: ./config.yml."
time="2023-09-06 00:07:26" level=debug msg="other flags have been ignored."
time="2023-09-06 00:07:26" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.16 BuildTime:2023-09-05_07:27:52 GitHash:2f55c7125ca65c94f62bbf98e7da84295a89a9a2 Pid:17972 Platform:windows/amd64 GoVersion:go1.19.12}"
time="2023-09-06 00:07:26" level=debug msg="&{File:./config.yml RPC:{Enable:true Bind:127.0.0.1:8080} Debug:true Interval:20 OutPutPath:./ FfmpegPath: Log:{OutPutFolder:./ SaveLastLog:true SaveEveryLog:false} Feature:{UseNativeFlvParser:false RemoveSymbolOtherCharacter:false} LiveRooms:[{Url:https://www.lang.live/room/5664344 IsListening:false LiveId: Quality:0} {Url:https://live.bilibili.com/22603245 IsListening:false LiveId: Quality:0} {Url:https://live.douyin.com/562956577855 IsListening:true LiveId: Quality:0}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s} Cookies:map[] OnRecordFinished:{ConvertToMp4:false DeleteFlvAfterConvert:false CustomCommandline:} TimeoutInUs:60000000 liveRoomIndexCache:map[https://live.bilibili.com/22603245:1 https://live.douyin.com/562956577855:2 https://www.lang.live/room/5664344:0]}"
time="2023-09-06 00:07:28" level=info msg="Server start at 127.0.0.1:8080"
time="2023-09-06 00:07:59" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="127.0.0.1:9631"
time="2023-09-06 00:07:59" level=debug msg="Http Request" Method=GET Path=/static/css/2.5b1f1a89.chunk.css RemoteAddr="127.0.0.1:9631"
time="2023-09-06 00:07:59" level=debug msg="Http Request" Method=GET Path=/static/css/main.6220e936.chunk.css RemoteAddr="127.0.0.1:9632"
time="2023-09-06 00:07:59" level=debug msg="Http Request" Method=GET Path=/static/js/2.09e56847.chunk.js RemoteAddr="127.0.0.1:9633"
time="2023-09-06 00:07:59" level=debug msg="Http Request" Method=GET Path=/static/js/main.c077553f.chunk.js RemoteAddr="127.0.0.1:9633"
time="2023-09-06 00:07:59" level=debug msg="Http Request" Method=GET Path=/manifest.json RemoteAddr="127.0.0.1:9634"
time="2023-09-06 00:07:59" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="127.0.0.1:9633"
time="2023-09-06 00:07:59" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="127.0.0.1:9633"

### 自由描述

您好作者大大，更新到新版本后，抖音的直播录制出现的问题，看到之前closed的issue说可能ip问题，试着关闭过一段时间重启好像还是不行诶。请问该怎么办呢~
![11111](https://github.com/hr3lxphr6j/bililive-go/assets/144151339/73171f07-f059-48ab-994b-0f9fd1187eee)

**Comment by kira1928** [comment]
我打算之后给抖音增加更多debug log，希望对查出这些问题有帮助吧。。

**Comment by Brian0924** [comment]
我也是这个问题，昨天晚上开始发现不能录制了，看了下有紧急修复版本V0.7.16，docker更新到latest、重新部署都试过了，同样不能显示对应直播间的ID

**Comment by hejiaonju** [comment]
我怀疑是抖音平台做了某些改变导致用不了了。与此类似的还有https://github.com/ihmily/DouyinLiveRecorder也用不了了。

**Comment by Brian0924** [comment]
> 我怀疑是抖音平台做了某些改变导致用不了了。与此类似的还有https://github.com/ihmily/DouyinLiveRecorder 也用不了了。

但是部分人，更新到V0.7.16后可以正常使用

**Comment by hejiaonju** [comment]
> > 我怀疑是抖音平台做了某些改变导致用不了了。与此类似的还有https://github.com/ihmily/DouyinLiveRecorder 也用不了了。
> 
> 但是部分人，更新到V0.7.16后可以正常使用

我刚才测试了一下，确实如你所说，更新到V0.7.16后可以正常使用。

**Comment by cosylxc** [comment]
我测试了一下，是ip问题，更新版本，还是会错误，但如果重新拨号，ip变了，就可以了。

**Comment by cosylxc** [comment]
又不行了，只要过一段时间，就会锁ip，感觉访问太频繁了，可不可以设置成轮流访问的呢，这样虽然主播上线不能及时录制，但至少不会被封ip。> 我测试了一下，是ip问题，更新版本，还是会错误，但如果重新拨号，ip变了，就可以了。

**Comment by nc1192** [comment]
谢谢，请问如果是ip问题的话，那有什么设置访问频率降低的办法吗，config里 interval加高会有帮助吗

**Comment by kira1928** [comment]
>config里 interval加高会有帮助吗

是的，这是用户这边唯一可以设置访问频率的地方。
另外，这是每一个直播间的访问频率，关注的直播间多也会增加访问频率。

**Comment by javayxw** [comment]
请问下各位大佬，如果是使用docker部署了项目，如何更新到V0.7.16呀。。 刚入门docker，还不是太懂

**Comment by kira1928** [comment]
@javayxw 你是群晖之类NAS的网页GUI部署的docker，还是命令行登录服务器执行命令部署的docker呢？

**Comment by javayxw** [comment]
@kira1928 解决了老哥，我是命令行的服务器执行的命令，刚刚删除了镜像，重新拉了一遍搞定了，感谢

**Comment by cosylxc** [comment]
@kira1928 愁死我了，我有几百个主播要监控，他们又不是规定时间，很随意的，现在这样封ip，几乎等于我过段时间就要手动复制链接，那和idm直接下载几乎没太多区别了😭😭唉

**Comment by hejiaonju** [comment]
有人知道以什么样的频率访问不会被封IP吗？

**Comment by Brian0924** [comment]
> @javayxw 你是群晖之类NAS的网页GUI部署的docker，还是命令行登录服务器执行命令部署的docker呢？

绿联的DX4600 PRO，前几天开始V0.7.15失效后，直接docker内更新到latest V0.7.16，监控页面依然全白，试了完整删除容器、镜像重新部署，故障依旧，将检测间隔interval调整到200、300 ，依然无法解决，期间无数次重启光猫试图更换IP。

**Comment by Brian0924** [comment]
PS:监测的直播间数量大概100个左右，之前是将设置文件复制备份，重新部署容器后在设置在粘贴，保存设置进行恢复。
后有尝试逐个直播间手动重新添加，前20几个暂时正常监测并录制，但是大概在加到第30个的样子，一下子就全变空白了，包括前20几个正常的。

**Comment by cosylxc** [comment]
@Brian0924 你自己都测出结果了，biligo的检测方式是一次性发出直播间询问，你一百个，那就是短时间内一次发一百个，间隔100s后再一次发100个，不封你ip封谁。之前在52论坛的一个直播录制是，设置间隔10，那就是每隔10s，按顺序检测一个直播间是否开播，这样依次下去，这有一个问题，就是如果监测太多，比如100个，那再监测到首个，一个循环要1000s，就是16分钟，可能会漏掉很多分钟。所以算是各有优劣，无解吧。
我建议是能获取关注页的推送最好，之前网页版推送总比手机版少，比如手机有10个直播，网页只提示7个，但现在好像完善了，直播推送一样的了。但这个有点难，抖音好像加密了关注推送。希望有大神吧。没大神的话，用selenium或者plaright这种笨办法获取倒也可以试试😊

**Comment by kira1928** [comment]
v0.7.17 换了一种新的方法获取抖音直播间，大家可以试试看呀~！

**Comment by hejiaonju** [comment]
> v0.7.17 换了一种新的方法获取抖音直播间，大家可以试试看呀~！

能请教一下新的方法是怎样的思路吗？

**Comment by nc1192** [comment]
@kira1928 谢谢啦大佬，我试了下过多监测还是会出现一样的问题，不监测太多就好

**Comment by hejiaonju** [comment]
> @kira1928 谢谢啦大佬，我试了下过多监测还是会出现一样的问题，不监测太多就好

你监测多少个出现了问题？
