### ISSUE TITLE
twitch录制，一直显示检测中(初始化)，无法录制

### ISSUE THREAD

**Issue by walfan-Ikaros** [hr3lxphr6j/bililive-go#538]
### 程序版本

0.7.16

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.twitch.tv/oxo1225
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

time="2023-09-07 07:16:44" level=info msg="BiliLive-go Version: v0.7.16 Link Start"
time="2023-09-07 07:16:47" level=info msg="Server start at 127.0.0.1:8080"
time="2023-09-07 07:18:45" level=error msg="https://twitch.tv/carabeanz: not support this url"
time="2023-09-07 07:18:57" level=error msg="https://twitch.tv/carabeanz: not support this url"

### 自由描述

添加twitch网址，一直显示检测中(初始化)，无法录制

**Comment by kira1928** [comment]
因为twitch录制功能之前坏了以后一直没修。。。
你看项目readme里也写了twitch现在不能录了。
希望有大佬提供一个修复twitch录制的pr😅
