### ISSUE TITLE
Twitch 录制错误,视频片段全程错乱.

### ISSUE THREAD

**Issue by xiaocsl** [hr3lxphr6j/bililive-go#54]
测试多个主播,均无法正常录制.

**Comment by anlo1220** [comment]
windows7测试可以 centos ubuntu 测试都不能

**Comment by hr3lxphr6j** [comment]
提供下直播间

**Comment by anlo1220** [comment]
> 提供下直播间

不管什么直播间都一样

**Comment by kira1928** [comment]
twitch 录制坏了，而且不太好修。。
详情见[这里](https://github.com/hr3lxphr6j/bililive-go/pull/289#issuecomment-1365186440)。

**Comment by kira1928** [comment]
issue 作者本人亲自发 [PR](https://github.com/hr3lxphr6j/bililive-go/pull/133) 修复过这个问题了。
这边的问题在 PR 之后应该已经修复了。
