### ISSUE TITLE
[提问]: 问下你的直播源地址从哪里获取的

### ISSUE THREAD

**Issue by ghost** [hr3lxphr6j/bililive-go#540]
### 程序版本

最新

### 所使用的 config 文件的内容

xxx

### 程序 log

xxx

### 自由描述

我想知道这个从哪里获取，然后我想用这个放在本地播放器里观看直播。或者你提供一个api，能调用获取直播源地址也行，比如输入参数 roomid=2222 ，platform=douyu,这种

**Comment by kira1928** [comment]
直播源是在各自直播平台的对应源代码里计算得到的，比如斗鱼是[这里](https://github.com/hr3lxphr6j/bililive-go/blob/master/src/live/douyu/douyu.go#L310)。

api 的话现在有检查直播间是否开播的 [api](https://github.com/hr3lxphr6j/bililive-go/blob/master/docs/API.md#get-apilives-get-all-live-info) ，但确实没有你想要的获取已经开播的直播间的直播源地址的 api。
如果需要的话我可以之后新建一个用来获取指定直播间直播源地址的 api，返回 json 格式。然后你自己解析？

**Comment by unknownUser99999** [comment]
> 直播源是在各自直播平台的对应源代码里计算得到的，比如斗鱼是 [这里 ](https://github.com/hr3lxphr6j/bililive-go/blob/master/src/live/douyu/douyu.go#L310)。
> 
> api 的话现在有检查直播间是否开播的 [api ](https://github.com/hr3lxphr6j/bililive-go/blob/master/docs/API.md#get-apilives-get-all-live-info) ，但确实没有你想要的获取已经开播的直播间的直播源地址的 api。 如果需要的话我可以之后新建一个用来获取指定直播间直播源地址的 api，返回 json 格式。然后你自己解析？

可以的，json格式我自己解析，谢了

**Comment by kira1928** [comment]
不录制这点挺重要的。我说的返回 json 格式 api 只有在程序在录制的时候才会返回直播地址，但你只需要获取一个直播地址，那最好是有一个其他的 api 专门获取和返回直播源地址而不录制。
在你的使用场景里，你是打算开直播间看看开播了再来程序这边取直播地址，还是开播与否也希望只在程序这边判断呢？
因为现在的设计是如果开始监控直播间，那开播了就会自动录制。如果不开启监控直播间，那就不会去检测直播间是否开播。
比较简单的方式是你在直播间确认开播了，然后程序这边可以在网页端做一个 UI，让你能执行一次获取指定直播间的直播源，即使是没有在监控的直播间也可以点这个 UI 让程序主动去获取一次直播源。

**Comment by unknownUser99999** [comment]
> 不录制这点挺重要的。我说的返回 json 格式 api 只有在程序在录制的时候才会返回直播地址，但你只需要获取一个直播地址，那最好是有一个其他的 api 专门获取和返回直播源地址而不录制。 在你的使用场景里，你是打算开直播间看看开播了再来程序这边取直播地址，还是开播与否也希望只在程序这边判断呢？ 因为现在的设计是如果开始监控直播间，那开播了就会自动录制。如果不开启监控直播间，那就不会去检测直播间是否开播。 比较简单的方式是你在直播间确认开播了，然后程序这边可以在网页端做一个 UI，让你能执行一次获取指定直播间的直播源，即使是没有在监控的直播间也可以点这个 UI 让程序主动去获取一次直播源。

不用考虑开不开博的监控，你就提供一个api或者命令行就可以，我直接拿源地址，拿不到就代表没开播，或者拿到了显示err，我这边也可以自己处理返回结果。总之只要一个源地址就够了，不用太麻烦

**Comment by unknownUser99999** [comment]
> 不录制这点挺重要的。我说的返回 json 格式 api 只有在程序在录制的时候才会返回直播地址，但你只需要获取一个直播地址，那最好是有一个其他的 api 专门获取和返回直播源地址而不录制。 在你的使用场景里，你是打算开直播间看看开播了再来程序这边取直播地址，还是开播与否也希望只在程序这边判断呢？ 因为现在的设计是如果开始监控直播间，那开播了就会自动录制。如果不开启监控直播间，那就不会去检测直播间是否开播。 比较简单的方式是你在直播间确认开播了，然后程序这边可以在网页端做一个 UI，让你能执行一次获取指定直播间的直播源，即使是没有在监控的直播间也可以点这个 UI 让程序主动去获取一次直播源。

这个功能应该还没有吧，我找了一下没看到

**Comment by kira1928** [comment]
还没做。做好了在这边通知你～

**Comment by unknownUser99999** [comment]
> 还没做。做好了在这边通知你～

嗯嗯
