### ISSUE TITLE
docker搭建的，快手直播间无法添加

### ISSUE THREAD

**Issue by jie8545** [hr3lxphr6j/bililive-go#542]
### 程序版本

v0.7.8

### 自由描述

docker搭建的，快手直播间无法添加

**Comment by kira1928** [comment]
1. 不记得快手是什么时候加入的了，可能需要升级到最新版镜像
2. 印象中录快手需要在配置里添加 cookie，参考 readme 了解配置中写入cookie的格式。如何获取快手cookie需要你上网搜一下。
3. 目前录制快手的方式似乎只能录制几分钟，之后会断流。因为功能本身有很多不完善之处，建议仅作测试使用，不要用来长时间录制。

**Comment by kira1928** [comment]
更新 readme 声明不能稳定支持快手了。
