### ISSUE TITLE
Docker版本 CONF_DIR="/etc/bililive-go" 无效

### ISSUE THREAD

**Issue by w9315273** [hr3lxphr6j/bililive-go#547]
### 程序版本

0.7.16

### 程序 log

`cant open file: /etc/bililive-go/config.yml`
`cant open file: /etc/bililive-go/config.yml`
`cant open file: /etc/bililive-go/config.yml`
`cant open file: /etc/bililive-go/config.yml`
`cant open file: /etc/bililive-go/config.yml`
`cant open file: /etc/bililive-go/config.yml`
`cant open file: /etc/bililive-go/config.yml`
`cant open file: /etc/bililive-go/config.yml`
`cant open file: /etc/bililive-go/config.yml`

### 自由描述

`CONF_DIR="/etc/bililive-go"`
程序没使用这个变量吧 你看看吧

**Comment by richamon** [comment]
我也遇到了,请问怎么解决的
