### ISSUE TITLE
抖音录制不稳定，显示录制中其实没有录制

### ISSUE THREAD

**Issue by 791774452** [hr3lxphr6j/bililive-go#554]
### 程序版本

0.7.17

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: true
interval: 20
out_put_path: /srv/bililive
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/598442904113
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 1h0m0s
cookies:
  live.douyin.com: __ac_nonce=********************1;name=value
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

time="2023-09-26 07:34:40" level=debug msg="Start ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=info msg="exit status 1" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="End ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="exit status 1" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="Start ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=info msg="exit status 1" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="End ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="exit status 1" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="Start ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=info msg="exit status 1" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="End ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="exit status 1" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="Start ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=info msg="exit status 1" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="End ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="exit status 1" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="Start ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=info msg="exit status 1" host="众祸" room="【V车队】无畏不惧，一往无前！"
time="2023-09-26 07:34:40" level=debug msg="End ParseLiveStream(http://pull-hs-f5-hot.flive.douyincdn.com/thirdgame/stream-113794863632220938.flv&session_id=037-202309260734369A80D6FCEF51A15BD6E5, /srv/bililive/抖音/众祸/[2023-09-26 07-34-40][众祸][【V车队】无畏不惧，一往无前！].flv)" host="众祸" room="【V车队】无畏不惧，一往无前！"

### 自由描述

<img width="1140" alt="image" src="https://github.com/hr3lxphr6j/bililive-go/assets/66341817/e4541201-e4de-4f65-b260-5e2e92fd43e2">
<img width="809" alt="image" src="https://github.com/hr3lxphr6j/bililive-go/assets/66341817/b7822cef-35ad-4dee-b53b-d37d33d0fa98">

其他平台测试没有问题，可以正常录制
日志没有报错，用日志中的流去掉session后在播放器可以播放加上不可以。

**Comment by kira1928** [comment]
> 日志没有报错，用日志中的流去掉session后在播放器可以播放加上不可以。

你是指 `session_id` 那个参数吗？

**Comment by Vae0514wzq** [comment]
我也有这种情况，在抖音平台，有些主播就可以录，有些主播一开录就exit status 1，应该是没有获取到直播源

**Comment by Aric-Sun** [comment]
相同的日志，疯狂涌入

**Comment by kira1928** [comment]
正在打包 v0.7.18 版本，大约20分钟后完成。可以在[这里](https://github.com/hr3lxphr6j/bililive-go/actions/runs/6315654801)查看打包进展。

v0.7.18 版本去掉了楼主报告的有问题的 session_id 参数，希望能解决各位遇到的问题。

**Comment by 791774452** [comment]
> 正在打包 v0.7.18 版本，大约20分钟后完成。可以在[这里](https://github.com/hr3lxphr6j/bililive-go/actions/runs/6315654801)查看打包进展。
> 
> v0.7.18 版本去掉了楼主报告的有问题的 session_id 参数，希望能解决各位遇到的问题。

测试了已经可以正常录制了
