### ISSUE TITLE
斗鱼偶而會出現這個.wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### ISSUE THREAD

**Issue by antonio65421** [hr3lxphr6j/bililive-go#557]
### 程序版本

0.7.18

### 程序 log

time="2023-09-27 13:29:04" level=error msg="failed to load room info" error="Get \"https://www.douyu.com/betard/156277\": read tcp 192.168.1.104:14425->210.65.177.25:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." url="https://www.douyu.com/156277"

**Comment by kira1928** [comment]
大概什么频率？
这个像斗鱼那边或你本地环境中的dns偶尔找到了已经失效的ip的样子。

**Comment by antonio65421** [comment]
频率不高 我这没用DNS.偶而出现一下

**Comment by kira1928** [comment]
感觉是偶发的网络问题，程序这边就不对应了。
