### ISSUE TITLE
建议支持添加主播主页连接的功能

### ISSUE THREAD

**Issue by pifeifei** [hr3lxphr6j/bililive-go#560]
### 新功能

不然主播不开播就不能添加录制， 稍微有些不方便

**Comment by kira1928** [comment]
主播不开播不能添加录制是指哪个平台？
目前好像只有微博直播因为不知道怎么从主页找到直播间地址所以不能添加微博首页来录制，别的平台都没有这个问题。

**Comment by pifeifei** [comment]
> 主播不开播不能添加录制是指哪个平台？ 目前好像只有微博直播因为不知道怎么从主页找到直播间地址所以不能添加微博首页来录制，别的平台都没有这个问题。

抖音

刚才我找了下， 不直播的情况下在主播主页找不到直播连接， 无法添加到后台监控录制视频

**Comment by kira1928** [comment]
可以用 https://live.douyin.com/抖音号 添加吧。
比如 https://live.douyin.com/y1bbbbbb

**Comment by wwkk2580** [comment]
> 可以用 [https://live.douyin.com/抖音号](https://live.douyin.com/%E6%8A%96%E9%9F%B3%E5%8F%B7) 添加吧。 比如 https://live.douyin.com/y1bbbbbb

可以程序内部转一下吗，抖音手机分享的主页链接转成直播链接
