### ISSUE TITLE
[提问]: 抖音歌厅录不了

### ISSUE THREAD

**Issue by lonely67373** [hr3lxphr6j/bililive-go#568]
### 程序版本

0.7.18

### 自由描述

我有个歌厅的直播间，一直录不了，是不是api不契合？其他的正常直播的直播间是可以录出来的。

**Comment by kira1928** [comment]
url贴一下看看？

**Comment by lonely67373** [comment]
https://live.douyin.com/373828923012

**Comment by lonely67373** [comment]
> url贴一下看看？

https://live.douyin.com/373828923012

**Comment by lonely67373** [comment]
我试了一下别的类似歌厅，也都不行

**Comment by kira1928** [comment]
看起来非常不同啊。需要专门研究看看。录下来大概只有一个音频文件是吧？

**Comment by lonely67373** [comment]
> 看起来非常不同啊。需要专门研究看看。录下来大概只有一个音频文件是吧？

之前api没更新前，录得是一个黑背景加音频合成的flv，黑背景基本不占多少空间，基本是为了以一个视频形式存在服务。
不清楚能不能录到带人头的那种，不过我觉得那个可能是抖音程序里面本地拟合的，重要是能不能正常把音频录出来。
现在是直接录不了了，每次开头一下就卡死然后不录了。

**Comment by kira1928** [comment]
嗯，争取朝着能录视频的方向努力改改看

**Comment by kira1928** [comment]
试了一下现在可以录了。

**Comment by lonely67373** [comment]
是可以录了
