### ISSUE TITLE
[提问]: 抖音没直播怎么添加直播间？添加主页没用

### ISSUE THREAD

**Issue by fgo1212** [hr3lxphr6j/bililive-go#570]
### 程序版本

0.7.18

### 自由描述

抖音没直播怎么添加直播间？添加主页没用

**Comment by AvrilL161** [comment]
![2023-10-16_11-36-13](https://github.com/hr3lxphr6j/bililive-go/assets/29428522/cdf0da36-7d23-40d2-aa68-ecd9ea800149)

https://live.douyin.com/*****

**Comment by antonio65421** [comment]
你等他开播 点他进入网页版就好了～目前都是这样

**Comment by fgo1212** [comment]
> ![2023-10-16_11-36-13](https://user-images.githubusercontent.com/29428522/275443330-cdf0da36-7d23-40d2-aa68-ecd9ea800149.png)
> 
> https://live.douyin.com/*****

会了，多谢
