### ISSUE TITLE
抖音出现和原本一样空白的问题

### ISSUE THREAD

**Issue by antonio65421** [hr3lxphr6j/bililive-go#571]
### 程序版本

v0.7.18

### 自由描述

只要重起bililive-go，抖音的录制列表会随机出现空白，每次都不一样，需手动添加回去就正常了，重起就又随机出现空白了。没有错误代码～～重新添加回去能录制.就是每次重新开启要自己检查一下 在添加回去.

**Comment by kira1928** [comment]
请补充config 文件内容和程序log。
尤其是从启动开始的完整log，包括手动添加回去的时候产生的log，以便调查可能的原因。

**Comment by antonio65421** [comment]
观察一下,刚开力马打开会有几个抖音空白,需要等一小时.他就会慢慢正常不空白了.config 文件内容和程序log 这两东西都是平常输出的正常内容看不出有什么＠＠
