### ISSUE TITLE
接口返回的信息里可以再加个抖音主页的字段吗

### ISSUE THREAD

**Issue by iamobj** [hr3lxphr6j/bililive-go#572]
### 新功能

目前有返回主播的直播地址 `live_url` ，可以的话，可以再返回个抖音主页地址，值是点分享里的那个短链接（https://v.douyin.com/XXXXXX）

**Comment by kira1928** [comment]
取到这个值并返回本身很简单，但是我想知道返回之后你希望如何使用这个返回值。

在网页 UI 里增设跳转进主播首页的按钮，方便从网页版进入主播首页？
还是只在 api 里增加返回值供用户自己获取后对接自己的定制脚本？

**Comment by iamobj** [comment]
> 取到这个值并返回本身很简单，但是我想知道返回之后你希望如何使用这个返回值。
> 
> 在网页 UI 里增设跳转进主播首页的按钮，方便从网页版进入主播首页？ 还是只在 api 里增加返回值供用户自己获取后对接自己的定制脚本？

我是对接自己脚本使用，网页 UI 里的话没要求，如果你有时间做的话，倒是也可以加， 哈哈 :sweat_smile:
我是不会 go，不然这种小功能我倒是乐意提个PR

**Comment by kira1928** [comment]
如果是这样的定制需求的话，为了抖音自己修改公共部分的数据结构有点不美观，不太想改。

其实你有能力自己写脚本，这也确实是个小功能，最理想的情况是你 fork 这个项目之后编译自己的版本使用。
但 golang 确实是太冷门了吧，大家都不太方便修改代码，可以参与开发贡献 PR 的人就更少了，难过 T_T

**Comment by iamobj** [comment]
好的，理解，那我就先把单子关了
其实 golang 也不算太冷门吧，毕竟好多大厂都有在用，只是我不会 😅  
不过我倒是喜欢它能编译出各平台都能直接用的产物
