### ISSUE TITLE
[提问]: 直播存放路径空文件夹

### ISSUE THREAD

**Issue by tingxiangfa** [hr3lxphr6j/bililive-go#574]
### 程序版本

0.7.18

### 所使
![QQ截图20231021193619](https://github.com/hr3lxphr6j/bililive-go/assets/125777925/6ad6751e-949a-40f1-8247-f5ba347e82c2)
用的 config 文件的内容

_No response_

### 程序 log
![QQ截图20231021193935](https://github.com/hr3lxphr6j/bililive-go/assets/125777925/83636f72-0f73-467e-89d4-1aa90d137f30)

_No response_

### 自由描述

windows系统ip+端口进入控制台之后，添加直播地址保存设置显示录制中，命令行日志也在进行，但是存放路径是空文件夹，没有直播文件，请问这是什么原因呢?

**Comment by kira1928** [comment]
请补充 config 文件内容和程序 log。

**Comment by tingxiangfa** [comment]
> 请补充配置文件内容和程序日志。

已补充

**Comment by kira1928** [comment]
你的 ffmpeg 程序似乎不适合你的 windows 架构。
你可以在命令行运行一下你下载的ffmpeg看看是什么输出内容吗？

**Comment by kira1928** [comment]
顺便问一下你的 ffmpeg 是怎么安装的，或者从哪里下载的？

**Comment by tingxiangfa** [comment]
> 顺便问一下你的ffmpeg是怎么安装的，或者从哪里下载的？
![QQ截图20231022084257](https://github.com/hr3lxphr6j/bililive-go/assets/125777925/9c0490a6-8835-4fa8-af47-72c925952cf4)

![QQ截图20231022084410](https://github.com/hr3lxphr6j/bililive-go/assets/125777925/28b94e8a-97d1-4244-869e-aeba57854e28)

**Comment by tingxiangfa** [comment]
> 顺便问一下你的ffmpeg是怎么安装的，或者从哪里下载的？

找到问题了，好像是使用原生flv播放器没有改成true，改成true就能看到录制文件了，也能播放。关键现在又出现一个问题，就是录制的文件不能快进，快进就会卡死，只能让它自己播放，这是什么原因呢？

**Comment by kira1928** [comment]
> 找到问题了，好像是使用原生flv播放器没有改成true，改成true就能看到录制文件了，也能播放。

这更加说明默认的 ffmpeg 程序有问题。改成使用 native flv parser 就是录制时不使用 ffmpeg 了，所以可以录制了。
推荐按照 wiki 的说明下载指定的预编译的 ffmpeg ，放置到指定的目录下试试看。
https://github.com/hr3lxphr6j/bililive-go/wiki/Install-Windows#step-1-%E8%8E%B7%E5%8F%96ffmpeg

> 关键现在又出现一个问题，就是录制的文件不能快进，快进就会卡死，只能让它自己播放，这是什么原因呢？

直播录制下来的 flv 的头文件里没有进度信息，不处理的话就是没法拖动进度条。大部分播放器只能按顺序把中途跳过的部分全都下载下来之后才能跳到指定位置，PotPlayer 稍微厉害一点，貌似可以靠自己跳着找到指定的位置，但也比有进度信息头文件的视频进度拖拽慢很多。

解决方法目前是在配置文件里启用录制完成后把 flv 转换成 mp4 这个选项，但前提是你的 ffmpeg 必须能用。
所以还是先按照上面的 wiki 里的步骤下载一个好用的 ffmpeg 吧。
