### ISSUE TITLE
请问可以录制直播时哪个观众进入了直播间的情况吗？

### ISSUE THREAD

**Issue by zihaoxingstudy1** [hr3lxphr6j/bililive-go#576]
请问可以录制直播时哪个观众进入了直播间的情况吗？

**Comment by kira1928** [comment]
这个信息普通观众好像获取不到。我只在观众人数非常少的b站直播间里偶尔能看到。
因为无法实现，所以 issue 就直接关掉了。如果你能找到其他项目已经实现了类似功能的话，可以再打开这个 issue，到时候可以等等看有没有其他开发者有没有兴趣实现这个功能。
