### ISSUE TITLE
抖音最近改版了!出现了空白 错误代码

### ISSUE THREAD

**Issue by antonio65421** [hr3lxphr6j/bililive-go#577]
### 程序版本

v0.7.18

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 35
out_put_path: D:\bililive-go
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false

out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 41m0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log
time="2023-10-26 09:56:43" level=error msg="failed to load room info" error="stream error: stream ID 553; INTERNAL_ERROR; received from peer" 
time="2023-10-26 10:00:02" level=error msg="failed to load room info" error="stream error: stream ID 831; INTERNAL_ERROR; received from peer"
time="2023-10-26 10:19:32" level=error msg="failed to load room info" error="stream error: stream ID 469; INTERNAL_ERROR; received from peer" 
time="2023-10-26 10:20:21" level=error msg="failed to load room info" error="stream error: stream ID 533; INTERNAL_ERROR; received from peer" 
time="2023-10-26 10:24:42" level=error msg="failed to load room info" error="stream error: stream ID 889; INTERNAL_ERROR; received from peer" 
time="2023-10-26 10:37:28" level=error msg="failed to load room info" error="stream error: stream ID 1911; INTERNAL_ERROR; received from peer"
### 自由描述
会出现上述的错误stream error: stream ID 后面数字会变化

**Comment by SingleRottenChips** [comment]
昨天刚开始用，今天出现以上两位说的 UI 上ID空白的情况，而且没有自动开始录制，删除再添加不管用。

**Comment by kira1928** [comment]
@SingleRottenChips 你遇到的应该不是这个问题，是一个其他更常触发的抖音录制问题。那个问题已于 v0.7.19 中修复，你可以更新试试看。
至于楼主遇到的 http2 服务器端报错问题，目前还没什么头绪。

**Comment by kira1928** [comment]
最近没有遇到这个报错了。
按照错误代码的说法，这应该不是客户端的问题，这边就不对应了。
