### ISSUE TITLE
docker配置录取视频位置不成功

### ISSUE THREAD

**Issue by ChrisYH20** [hr3lxphr6j/bililive-go#578]
### 程序版本

	v0.7.18

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /srv/bililive
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/114798666651
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 自由描述

docker run --restart=always -v ~/config.yml:/mnt/mmcblk0p24/Docker/bililive/config -v ~/Videos:/mnt/mmcblk0p24/Download/Video/bilive -p 8080:8080 -d chigusa/bililive-go          首次拉取镜像配置如此，但是录取视频的位置却在如下图挂载卷的第3行的位置
![image](https://github.com/hr3lxphr6j/bililive-go/assets/140259582/5e4f8d49-6d09-4fa5-8785-d9b8d3524a7e)

**Comment by kira1928** [comment]
你没按指定路径挂载 volume 啊。
https://github.com/hr3lxphr6j/bililive-go#%E4%BD%BF%E7%94%A8%E4%BE%8B%E5%AD%90

**Comment by ChrisYH20** [comment]
-v ~/Videos:/mnt/mmcblk0p24/Download/Video/bilive 请问这不是我运行此docker容器时设置的视频存放位置吗？如果按照你的volum值容器运行不起来呢，貌似是因为这个目录在系统分区的原因

**Comment by kira1928** [comment]
文档里写的
```
docker run --restart=always -v ~/config.yml:/etc/bililive-go/config.yml -v ~/Videos:/srv/bililive -p 8080:8080 -d chigusa/bililive-go
```
其中 `~/Videos` 部分是你宿主机上准备用来存放视频的目录，这个可以随便改。
`/srv/bililive` 是 docker 容器内的存放视频的对应位置，这个是写在 config.yml 配置文件里的 `out_put_path` 的值。你的配置文件里用的也是这个值。
对 config.yml 文件的映射同理。

**Comment by ChrisYH20** [comment]
谢谢了，这一个乌龙，是我文件映射位置填反了
