### ISSUE TITLE
按日期分类录制文件夹功能

### ISSUE THREAD

**Issue by zxate** [hr3lxphr6j/bililive-go#581]
### 新功能

请问能不能添加一个按照日期分类文件夹的功能，比如当天是10-29-2023，录播器会自动创建新的文件夹，然后当天的所有录制的文件会自动归类到当天的文件夹内。

目前Windows自带的文件夹修改日期貌似很不稳定，如果录制的主播比较多会出现明明今天有新的录制文件，但修改日期却没有更新的情况

Ex:
10-29-2023 -> 主播1
                         主播2
                         主播3

10-30-2023 -> 主播1
                         主播5

**Comment by Qixingchen** [comment]
https://github.com/hr3lxphr6j/bililive-go/wiki/More-Tips#%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E5%90%8D%E6%A8%A1%E6%9D%BF

**Comment by kira1928** [comment]
确实利用上面的模板设置就可以比较完美地实现这个需求了。
