### ISSUE TITLE
B站增加登录功能，提高录制画质

### ISSUE THREAD

**Issue by OrangeeeeeeX** [hr3lxphr6j/bililive-go#582]
### 新功能

未登录情况下，B站画质只能到720p，只有登录才有1080p，希望能开发一下登录功能，能录更高的画质

**Comment by dingpamaoo** [comment]
我说我最近录的分辨率都那么低 :(

**Comment by kira1928** [comment]
现在b站录播支持添加cookie，但是我看录播姬那边的说法是添加了cookie以后b站方面可以很容易发现你在用程序监控b站直播间，有封号风险。
这方面的取舍就看大家自己判断了。

**Comment by kira1928** [comment]
seam 是什么？

**Comment by Hollowcontainer99** [comment]
想问一下B站添加Cookie的格式是怎样的 需要提取Cookie的哪一段呢

**Comment by kira1928** [comment]
@Hollowcontainer99 格式是
```
cookies:
  live.bilibili.com: key1=value1;key2=value2
```
这样。需要哪一段不太清楚，能取到的都写上去试试？
现阶段录B站我是比较推荐用录播姬来录的。我自己的 NAS 上也是B站直播间全用录播姬录，其他网站直播才会用 bililive-go 。
另外录播姬那边也提过的，就是如果你使用自己的真实 cookie，那直播网站方面是可以非常容易排查出发现你在24小时访问他们服务器录直播的。至于这样会不会导致未来B站对这个 cookie 的账号进行封号之类的措施，就没人可以担保了。

**Comment by fenfenyangyangmate** [comment]
cookie有个曲线救国的办法青龙面板里的b站打卡可以自动获取cookie，你可以试试
https://github.com/RayWangQvQ/BiliBiliToolPro

**Comment by dingpamaoo** [comment]
> 至于这样会不会导致未来B站对这个 cookie 的账号进行封号之类的措施，就没人可以担保了。

可以用小号的cookie，封了就换一个。
