### ISSUE TITLE
命令行录制的问题

### ISSUE THREAD

**Issue by bequiteto** [hr3lxphr6j/bililive-go#583]
### 程序版本

最新版本

### 所使用的 config 文件的内容

无指定

### 程序 log

无

### 自由描述

./bililive-go -i https://live.bilibili.com/1030 -i https://www.douyu.com/6655
这个命令行录制，然后我ctrl+c中断之后，会发现虽然录制是没问题，但是录制的flv视频是无法加载完整的进度条的，转化成mp4才正常

**Comment by kira1928** [comment]
直接录制的flv直播流里是不包含进度条信息的，所以直接录下来的原始 flv 文件确实不能拖动。
像录播姬那样用自己写的 native flv parser 录制的话可以人为给录制的 flv 实时写入进度条信息，但是我对我们的 native flv parser 还不太有信心，也没有做那样额外的修改。
目前转 mp4 是最简单的添加进度条信息的方式，最开始加入这个功能也正是为了解决进度条不能拖动的问题的。建议转 mp4。

**Comment by kira1928** [comment]
运行过程中修改配置不行。先修改配置再使用修改后的配置启动命令行可以生效。
