### ISSUE TITLE
抖音又BUG了，读取不了直播间，录制不了了

### ISSUE THREAD

**Issue by fgo1212** [hr3lxphr6j/bililive-go#586]
### 程序版本

v0.7.18

### 自由描述

抖音又BUG了，读取不了直播间，录制不了了

主播名称 | 直播间名称，这两栏目都变空白了

**Comment by kira1928** [comment]
已经注意到了，也更新置顶的关于抖音现状的 issue 了，后续进展会在那边更新。

**Comment by kira1928** [comment]
已于 v0.7.19 中修复。
