### ISSUE TITLE
B站的画质无法更改

### ISSUE THREAD

**Issue by SingleRottenChips** [hr3lxphr6j/bililive-go#587]
### 程序版本

0.7.1

### 所使用的 config 文件的内容

  is_listening: true
  quality: 1

### 自由描述

将其quality的值改为1后，会变回0. 

据个人观察，**B站上**，同一个分辨率下，hevc编码视频的画质通常远不及avc, 因此对阿B直播的hevc也不太放心。

**Comment by jack981122** [comment]
没登陆B站限制画质，加上你B站账号cookie就正常了

**Comment by SingleRottenChips** [comment]
> 没登陆B站限制画质，加上你B站账号cookie就正常了

不是... 我说的是[配置文件](https://github.com/hr3lxphr6j/bililive-go/blob/24edf57a402371fd2550807b3b89895ef4c430e0/config.yml#L16C16-L16C16)里的"quality: 0"，是专门给b站设置hevc的，跟画质没关系。

话说这个脚本录B站必须要cookies吗？之前一直用隔壁的一个脚本，没加过cookies，也能录原画。

**Comment by jack981122** [comment]
> > 没登陆B站限制画质，加上你B站账号cookie就正常了
> 
> 不是...我说的是[配置文件](https://github.com/hr3lxphr6j/bililive-go/blob/24edf57a402371fd2550807b3b89895ef4c430e0/config.yml#L16C16-L16C16)里的“quality： 0”，是专门给b站设置hevc的，跟画质没关系。
> 
> 话说这个脚本录B站必须要cookies吗？之前一直用隔壁的一个脚本，没加过cookies，也能录原画。



> > 没登陆B站限制画质，加上你B站账号cookie就正常了
> 
> 不是...我说的是[配置文件](https://github.com/hr3lxphr6j/bililive-go/blob/24edf57a402371fd2550807b3b89895ef4c430e0/config.yml#L16C16-L16C16)里的“quality： 0”，是专门给b站设置hevc的，跟画质没关系。
> 
> 话说这个脚本录B站必须要cookies吗？之前一直用隔壁的一个脚本，没加过cookies，也能录原画。

好像是这段时间B站加上的，之前确实都可以录原画

**Comment by kira1928** [comment]
B站最近的更改也很麻烦。确实需要对应一下，不能录quality 0的时候应该给个提示，或者错误信息什么的。
按顺序来吧，先解决抖音的问题。

**Comment by Hollowcontainer99** [comment]
可以问一下B站怎么加cookie吗？用的SESSDATA还是buvid3还是其他段呢...纯小白

**Comment by kira1928** [comment]
试试把获取到的所有b站直播域名下的cookie都填进去看看能不能用？
cookie方面程序本身只是提供了一个可以让用户使用cookie的配置，具体不同网站要填什么cookie还是需要用户自己去了解的。

**Comment by lupwei** [comment]
有且仅有quality这一选项无法更改，导致录下来的都是1s的ts文件
