### ISSUE TITLE
新版0.7.19出现的小问题

### ISSUE THREAD

**Issue by antonio65421** [hr3lxphr6j/bililive-go#589]
### 程序版本

v0.7.19

### 所使用的 config 文件的内容

无

### 程序 log

4
4
4
4
4
4
4
4
4
4
4
4
4
4
2
4
4
4
4
4
4
4
4
4
4
4
4
4
4
2
4
2
4
4
4
4

2
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
2
2
4
4
4
4
4
4
4
4
4
4
4
time="2023-11-04 22:23:09" level=info msg="Server start at 127.0.0.1:8080"
4
4
4
4
4
4
4
2

### 自由描述

会一直出现444444444444444444444444

**Comment by Qm520** [comment]
我也遇到了，是4和2一行行的弹出来

**Comment by kira1928** [comment]
已修复。
