### ISSUE TITLE
bililive-go启动时直接就开始录制了，能否暂停，手动执行录制功能

### ISSUE THREAD

**Issue by 7654** [hr3lxphr6j/bililive-go#59]
bililive.exe -c config.yml

> rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 15
out_put_path: ./
feature:
  use_native_flv_parser: false
live_rooms:

刚启动就开始执行录制了，希望可以手动操作，节约硬盘空间

**Comment by hr3lxphr6j** [comment]
那为什么不在需要时启动程序呢？

**Comment by 7654** [comment]
因为添加了多个直播间，如果都正在直播，启动时就会全部启动录制，占硬盘占带宽，还要挨个取消不需要的录制
所以现在未使用web面板控制，而是开启多个bililive-go -i url，单独录制

**Comment by kira1928** [comment]
您需要的是不是 https://github.com/hr3lxphr6j/bililive-go/issues/255 ？
