### ISSUE TITLE
0.7.19抖音直播录制出现断断续续的问题（概率出现）

### ISSUE THREAD

**Issue by WhenAwake** [hr3lxphr6j/bililive-go#591]
### 程序版本

0.7.19

### 程序 log

![微信图片_20231105224701](https://github.com/hr3lxphr6j/bililive-go/assets/106490099/59c0d0c6-eba3-46a4-987f-1368ae4d0a90)

### 自由描述

抖音录制持续输出30秒的文件 录制断断续续

**Comment by kira1928** [comment]
首要目标是定位到途中出现的 msg="<nil>" 部分的代码，修复它让他显示有意义的信息。

**Comment by kira1928** [comment]
抖音修复了很多版，在最新版中应该没有这个问题了。
