### ISSUE TITLE
b站pk花屏

### ISSUE THREAD

**Issue by lonely67373** [hr3lxphr6j/bililive-go#593]
### 程序版本

0.7.19

### 自由描述

录制b站进行竖屏直播的主播时，主播进行pk，录制的视频会冲原本的宽1080长1920转变成宽1920长1080，或者断续录制中从宽1920长1080转变成宽1080长1920，进而导致转变分辨率的部分会花屏。
另外就是一旦出现这种转变，进行码率压制后会被强行压缩到初始比例上，形成转变内容比例失衡。
不知道有没有办法解决这个问题？是否与b站直播源输出有关？

**Comment by kira1928** [comment]
是的，默认的录制工具 ffmpeg 无法处理 flv 直播流中途改变分辨率的情况，导致的现象就是有声音但是花屏，直到分辨率变回来为止。
解决方法是在配置里启用 native flv parser，用程序内置的简易 flv parser 来录制直播。好处是遇到 pk 之类不断流改变分辨率的情况时可以自动分段，再以新的分辨率重新录制。坏处是各种稳定性方面不如 ffmpeg。

**Comment by kira1928** [comment]
另外，目前录制b站推荐使用录播姬开源工具。他们专做 b 站录制，做得非常精致。
我个人在家也是在 NAS 上跑录播姬录b站的。

**Comment by lonely67373** [comment]
> 另外，目前录制b站推荐使用录播姬开源工具。他们专做 b 站录制，做得非常精致。 我个人在家也是在 NAS 上跑录播姬录b站的。

感谢感谢，不过我录播姬挂了cookie，不适合一下子挂太多直播间。
主要感觉还是b站设计的问题，隔壁抖音就是竖屏直接拟合成一个竖屏，除了画面内容剩下都是蓝底，就b站还非得合成一个横屏内容，不知道咋想的。另外，我看有的b站竖屏主播的回放也是存在画面压缩的情况，明显是两边设计上打架了。
