### ISSUE TITLE
[提问]: 快手直播无法录制

### ISSUE THREAD

**Issue by czcxl007** [hr3lxphr6j/bililive-go#594]
### 程序版本

0.7.19

### 自由描述

为什么添加快手录制时，没有显示主播名称和直播间名称，也无法开始录制呢？是我用法错误了吗？

**Comment by czcxl007** [comment]
![Uploading 微信图片_20231109142204.png…]()

**Comment by kira1928** [comment]
快手录制功能目前很不稳定。预计下次更新会去掉支持快手的说明，或者明确提醒快手录制处于实验性状态，不保证效果。
