### ISSUE TITLE
抖音录制中频繁出现bug导致停止录制

### ISSUE THREAD

**Issue by natgeoo** [hr3lxphr6j/bililive-go#596]
### 程序版本

0.7.19

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 20
out_put_path: F:\
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/963215036174
  is_listening: true
  quality: 0
- url: https://live.douyin.com/628227367818
  is_listening: true
  quality: 0
- url: https://live.douyin.com/70102792485
  is_listening: true
  quality: 0
- url: https://live.douyin.com/97477043184
  is_listening: true
  quality: 0
- url: https://live.douyin.com/453705346927
  is_listening: true
  quality: 0
- url: https://live.douyin.com/89681804331
  is_listening: true
  quality: 0
- url: https://live.douyin.com/952153496800
  is_listening: true
  quality: 0
- url: https://live.douyin.com/902759942573
  is_listening: true
  quality: 0
- url: https://live.douyin.com/848251257131
  is_listening: true
  quality: 0
- url: https://live.douyin.com/459062056120
  is_listening: true
  quality: 0
- url: https://live.douyin.com/890918988015
  is_listening: false
  quality: 0
- url: https://live.douyin.com/272293134066
  is_listening: true
  quality: 0
- url: https://live.douyin.com/184586332119
  is_listening: true
  quality: 0
- url: https://live.douyin.com/547392850867
  is_listening: true
  quality: 0
- url: https://live.douyin.com/84384331502
  is_listening: true
  quality: 0
- url: https://live.douyin.com/916453274230
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 40m0s
  max_file_size: 0
cookies:
  ? ttwid=1%7CT96jmi-Zij8_gon1xmLHlzVkpalB_rdV07fYlKE_b_w%7C1690676976%7C4660d986fd2405eb1448a788e632ec01bf73e04190cf0ba014cabb1d2dfcd774; odin_tt=26088c13259ef8d82b27a992da21292664cbba64d60b7bd473feea92901310f45db4d372dcb9fbcfaed03bf98102600973dd2011ad2347626aa177b8e66fb404; passport_auth_status=4665e90eed09e1e3d6c479d5238e99a8%2C; passport_auth_status_ss=4665e90eed09e1e3d6c479d5238e99a8%2C; n_mh=S9bn9gCcE7iNUrKd-nuQ4OHZsHM2XGDuQoeVtnyu0ZE; passport_assist_user=CktgyDsOYV0_Y-6qppnijTUpFJNgtOEghfNKd1Nnu3XD1O2QMgxyGljr0zER92t-h4IBhYeP6PhgK79HRRDW3eOfMhAwAZpOmQKlfsEaSgo8AeHiyYsZvZhbhVjOY3qJRrRsZKC5WSz4BEHgo3GNBpIAO2iChToDMEEY-GW1egEKwjGpmir6Vhypau5-EJrVwA0Yia_WVCABIgED4ES2-Q%3D%3D; sid_ucp_sso_v1=1.0.0-KGRjZjJjZDczMGQ0MTQ4NzcxZTliMWZmODFkNGM4NmRiMWE4ZTdmMDkKHwjDlOD2mMzqBRDNkamqBhjvMSAMMJPb46gGOAZA9AcaAmxmIiBlMzVmZThkOGFjNmJhZDk5OTQ5NzQwNzI2OTI5YjY5YQ; ssid_ucp_sso_v1=1.0.0-KGRjZjJjZDczMGQ0MTQ4NzcxZTliMWZmODFkNGM4NmRiMWE4ZTdmMDkKHwjDlOD2mMzqBRDNkamqBhjvMSAMMJPb46gGOAZA9AcaAmxmIiBlMzVmZThkOGFjNmJhZDk5OTQ5NzQwNzI2OTI5YjY5YQ; sso_uid_tt=c33f519ed06f725466f848dc65d3af91; sso_uid_tt_ss=c33f519ed06f725466f848dc65d3af91; toutiao_sso_user=e35fe8d8ac6bad99949740726929b69a; toutiao_sso_user_ss=e35fe8d8ac6bad99949740726929b69a; FORCE_LOGIN=%7B%22videoConsumedRemainSeconds%22%3A180%7D; passport_csrf_token=f14a0a5ca4a48459eb89dc2c3449a6a2; passport_csrf_token_default=f14a0a5ca4a48459eb89dc2c3449a6a2; s_v_web_id=verify_loofam3y_we3UsyZG_IZlu_4qLL_Bl5g_meBEgR4lvfzq; ttcid=1387d88b80c44f00bfea6eacac5f94f935; __live_version__=%221.1.1.5086%22; device_web_cpu_core=4; device_web_memory_size=-1; xgplayer_user_id=909133865830; __ac_nonce=0654a48a500b5aa3fea3c; __ac_signature=_02B4Z6wo00f01bz8rswAAIDBZl6OVof1xRG83KpAAAp2f6;
  : ""
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

panic: runtime error: invalid memory address or nil pointer dereference[signal 0xc0000005 code=0x0 addr=0xa8pc=0x112329b] goroutine 4323 [running]:
github.com/hr31xphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop.func1()
/home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:173 +0x1b
sync.(*0nce).doSlow(0xc00033d1a0?,0x1128f00?)
/opt/hostedtoolcache/go/1.19.13/x64/src/sync/once.go:74 +0xc2
sync.(*0nce).Do(...)
/opt/hostedtoolcache/go/1.19.13/x64/src/sync/once.go:65
github.com/hr3lxphr6j/bililive-go/src/pkg/parser/ffmpeg.(*Parser).Stop(0xc000272720?)
/home/runner/work/bililive-go/bililive-go/src/pkg/parser/ffmpeg/ffmpeg.go:172 +0x45
github.com/hr3lxphr6j/bililive-go/src/recorders.(*recorder).Close(0x11f6800?)
/home/runner/work/bililive-go/bililive-go/src/recorders/recorder.go:282 +0x62
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).RemoveRecorder(0xc0002a8de0,{0xc000210b40?,0xc0001b8388?}，{0xc000319040,0x20})
/home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:148 +0xa2
github.com/hr3lxphr6j/bililive-go/src/recorders.(*manager).registryListener.func3(0xc0001b8300?)
/home/runner/work/bililive-go/bililive-go/src/recorders/manager.go:69 +0xb7
github.com/hr3lxphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent.func1 ()
/home/runner/work/bililive-go/bililive-go/src/pkg/events/dispatcher.go:96 +0x47
created by github.com/hr31xphr6j/bililive-go/src/pkg/events.(*dispatcher).DispatchEvent
/home/runner/work/bililive-go/bililive-go/src/pkg/events/dispatcher.go:94 +0x235

### 自由描述

录制抖音大概每72小时就出现一次Bug，cmd报错如log里写的，tg群里说是超线程bug无法修复，但是现在出现频率已经影响正常录制了有没有解决办法，比如出bug自动重启，系统win10
cmd报错截图图床：https://z1.ax1x.com/2023/11/14/piYF7m6.png

**Comment by kira1928** [comment]
如果非常影响使用，那么建议把配置中的 `use_native_flv_parser` 的值设为 `true`，使用程序自带的简易 flv parser 取代 ffmpeg 进行录制。

**Comment by kira1928** [comment]
已在 https://github.com/hr3lxphr6j/bililive-go/pull/675 中修复。
