### ISSUE TITLE
[提问]: 请问下B站的265直播录制支持吗，如果支持，请问config要改什么参数。

### ISSUE THREAD

**Issue by Er0sion** [hr3lxphr6j/bililive-go#598]
### 程序版本

0.7.19

### 自由描述

请问下B站的265直播录制支持吗，如果支持，请问config要改什么参数。

**Comment by kira1928** [comment]
之前有大佬做了b站 hls 直播流的 265 编码的支持。https://github.com/hr3lxphr6j/bililive-go/pull/428
应该是添加直播间时就会默认启用的。
不过最近 b 站需要添加 cookie 才能录到最高画质的直播流了，不知道和这个有没有关系。
录播姬那边的建议是添加 cookie 就要做好账号被 b 站抓出来永封的心理准备，在已知这个条件的前提下用不用 cookie 由用户自己判断吧。
