### ISSUE TITLE
docker映射config出错

### ISSUE THREAD

**Issue by ChrisYH20** [hr3lxphr6j/bililive-go#599]
### 程序版本

	v0.7.19

### 程序 log

![image](https://github.com/hr3lxphr6j/bililive-go/assets/140259582/5e1b634d-d166-41a8-8aca-a49dd113dbba)

### 自由描述

启动时映射etc文件夹时能启动但是几秒后停止报错如图，显示打不开config文件，当我不映射该文件夹这样启动时又能正常运行docker run --restart=always -v /mnt/sda1/Download/Video:/srv/bililive -p 8080:8080 chigusa/bililive-go

**Comment by zS1m** [comment]
检查一下config文件夹下是否存在config.yml文件，如果存在，检查一下是否具有该文件的读写权限

**Comment by ChrisYH20** [comment]
我是将容器内的/etc/bililive-go/config.yaml映射到我的宿主机上，但是用docker启动时如果映射此文件就会像上图一样报错，不映射此文件能正常启动，启动后config.yaml文件也存在，文件权限为-rw-r--r--

**Comment by zS1m** [comment]
容器内默认应该是没有config.yml的，我看你的图片应该是将/mnt/sdal/Docker_data/bililive-go/config与容器内的/etc/bililive-go映射，这时候需要在宿主机的/mnt/sdal/Docker_data/bililive-go/config目录下创建config.yml文件并配置好内容才能启动。
需要注意的是文件名后缀为yml，你的回复中后缀貌似是yaml。

**Comment by ChrisYH20** [comment]
ok，后缀是yml，是我打错了，我明白了
