### ISSUE TITLE
建议：发布版仅带二进制文件

### ISSUE THREAD

**Issue by 8MiYile** [hr3lxphr6j/bililive-go#600]
### 新功能

我希望是
程序在第一次执行的时候，自动生成一次配置文件并关闭
在之后，若检测到配置文件，则直接调用配置文件

或者是发布版本的config.yml改名成config.yml.example，并默认读取config.yml

否则现在的版本不利于直接在服务器上执行升级，会直接覆盖配置文件

**Comment by kira1928** [comment]
memo:

> kira:
> 都在服务器上了，应该可以用命令行参数指定另外一个路径的配置文件，不使用默认的了。这不需要靠改程序逻辑来实现。
> 8MiYile:
> 嗯 我指的是发布stable的时候 config.yml文件名应该改成config.yml.example
> kira: 
> 现在项目大部分用户是非程序员群体。与其让不懂程序的人改配置，还不如现在这样默认配置就能启动，想要定制效果的程序员群体自己动手改一下脚本得好
> 8MiYile:
> 也是
