### ISSUE TITLE
Docker 安装版本中创建的config.yml不是文件而是一个文件夹。

### ISSUE THREAD

**Issue by Meng-Xin** [hr3lxphr6j/bililive-go#601]
### 程序版本

0.7.19

### 自由描述

Docker 安装版本中创建的config.yml不是文件而是一个文件夹，因此导致无法使用docker run 命令创建容器，请将config.yml更改为文件，而不是文件夹。

**Comment by kira1928** [comment]
没听懂这个描述。
能具体说一下你执行了什么命令，遇到了什么样的错误信息，把他们原样粘贴上来吗？

**Comment by Meng-Xin** [comment]
**执行命令**
```bash
$ docker run --restart=always -v ~/config.yml:/etc/bililive-go/config.yml -v ~/Videos:/srv/bililive -p 8080:8080 -d chigusa/bililive-go
```
**错误描述：**
> docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start >container process: error during container init: error mounting "/root/config.yml" to rootfs at "/etc/bililive-go/config.yml": >mount /root/config.yml:/etc/bililive-go/config.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying >to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
>[root@localhost ~]# docker run --restart=always -v ~/config.yml:/etc/bililive-go/config.yml -v ~/Videos:/srv/bililive -p >8080:8080 -d chigusa/bililive-go
**定位问题：**
> 查看root目录下发现创建了 config.yml 文件夹，不是预期的config.yml文件，你这里是不是错误使用了 mkdir config.yml 而不是touch config.yml ?

**Comment by kira1928** [comment]
你看的那个说明文件是 `使用例子` 小结嘛，这个 `~/config.yml` 是举个例子，让你自己创建一个 config.yml 文件用。
使用例子中的 docker 命令的前提是你理解这个命令是什么意思，或者说用过 docker，不然这个程序对非程序员来说还是挺不友好的。
