### ISSUE TITLE
最近频繁出现短时断录的情况

### ISSUE THREAD

**Issue by captain-cd** [hr3lxphr6j/bililive-go#604]
### 程序版本

v0.7.16、v0.7.19

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: false
interval: 15
out_put_path: E:\直播视频录制
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/
  is_listening: true
  quality: 0
- url: https://live.douyin.com/614685591480
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 2h0m0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000

### 自由描述

1、config中的抖音直播间录制，频繁出现40秒左右断录，然后再重新录制，又再次40秒左右的情况；
2、用别的直播间测试，似乎又没有这样的情况出现；

**Comment by xuejintaoHlu** [comment]
我的也是，但我是录制B站视频时会出现这种，换斗鱼就不会，而且是2s一次重新录制

**Comment by Clxj** [comment]
最近也会频繁出现这种问题，但是重新安装以后会好一两天。

**Comment by kira1928** [comment]
抖音修复了很多版，在最新版中应该没有这个问题了。
