### ISSUE TITLE
docker v0.7.20 BUG

### ISSUE THREAD

**Issue by XiongDemo** [hr3lxphr6j/bililive-go#607]
### 程序版本

v0.7.20

### 所使用的 config 文件的内容

未谈到

### 程序 log

未谈到

### 自由描述

```
docker run -d \
--name bililive-go \
--restart=always \
-v /media/usb/bililive-go/config1.yml:/etc/bililive-go/config.yml \
-v /media/usb/Videos:/srv/bililive \
-p 8080:8080 \
chigusa/bililive-go:v0.7.20
```

刚才 pull 了几次  都是老版本  感觉不对 直接带着版本号 pull 过来的  可以用啦

**Comment by kira1928** [comment]
可能是某处的缓存的影响吧。
看 https://hub.docker.com/r/chigusa/bililive-go/tags 上 latest 是正确指向 v0.7.20 的。
