### ISSUE TITLE
nohup挂在后台，在录制结束后就自动退出了

### ISSUE THREAD

**Issue by ashesofdream** [hr3lxphr6j/bililive-go#609]
### 程序版本

0.7.20

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8081
debug: false
interval: 20
out_put_path: /root/bililive/record
ffmpeg_path: ""
log:
  out_put_folder: /root/bililive
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://fm.missevan.com/live/xxxxxxx
  is_listening: true
  quality: 0
- url: https://live.bilibili.com/xxxxxxx
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 2147483648
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000
~                    

### 程序 log

time="2023-11-27 17:09:41" level=warning msg="failed to get stream url, will retry after 5s..." error="<nil>" host="bbbbb" room="xxxxxx"
time="2023-11-27 17:09:45" level=info msg="Live end" host="bbbbb" room="xxxxxx"
time="2023-11-27 17:09:45" level=info msg="Record End" host="bbbb" room="xxxxxx"
time="2023-11-27 17:25:54" level=info msg="Server close"
time="2023-11-27 17:25:54" level=info msg="Record End" host="aaaaa" room="xxxxxx"
time="2023-11-27 17:25:54" level=info msg="Bye~"

### 自由描述

我希望能一直循环监控，而不是一录完就退出了...是我的配置文件有什么问题吗？我挂到后台的命令为：nohup bililive -c config.yml &

**Comment by kira1928** [comment]
默认就是循环监控，应该不是程序这边的问题。
