### ISSUE TITLE
http连接不上

### ISSUE THREAD

**Issue by JaydenFish** [hr3lxphr6j/bililive-go#61]
升级了 0.5.0-rc.3 , win10 x64
升级之前还能连上。
我用postman连接http的api

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/79113535-b6efac80-7db3-11ea-862f-932899ae2353.png)
所有接口都被放到`/api`下面了，文档暂时没更新

**Comment by JaydenFish** [comment]
还有config的格式也改了。
终于连上了。

**Comment by JaydenFish** [comment]
api/lives的POST接口也改了吗？ 我怎么不能添加监听？
```
{
    "lives": [
        {
            "url": "https://www.douyu.com/4747465",
            "listen": true
        }
    ]
}
```
返回是`[]`

**Comment by hr3lxphr6j** [comment]
```json
[{"url":"https://live.bilibili.com/14917277","listen":true}]
```
