### ISSUE TITLE
docker 快手直播录制没有内容

### ISSUE THREAD

**Issue by hyh1750522171** [hr3lxphr6j/bililive-go#617]
### 程序版本

0.7.20

### 程序 log

time="2023-12-20 18:28:30" level=info msg="BiliLive-go Version: v0.7.20 Link Start"
time="2023-12-20 18:28:30" level=info msg="Server start at :8080"
time="2023-12-20 18:29:01" level=error msg="docker run --restart=always -v ~/config.yml:/etc/bililive-go/config.yml -v ~/Videos:/srv/bililive -p 8080:8080 -d chigusa/bililive-go: can't parse url: https://docker run --restart=always -v ~/config.yml:/etc/bililive-go/config.yml -v ~/Videos:/srv/bililive -p 8080:8080 -d chigusa/bililive-go"
time="2023-12-20 18:30:29" level=info msg="Server close"
time="2023-12-20 18:30:29" level=info msg="Bye~"
time="2023-12-20 18:30:30" level=info msg="BiliLive-go Version: v0.7.20 Link Start"
time="2023-12-20 18:30:31" level=info msg="BiliLive-go Version: v0.7.20 Link Start"
time="2023-12-20 18:30:33" level=info msg="BiliLive-go Version: v0.7.20 Link Start"
time="2023-12-20 18:30:34" level=info msg="Server start at :8080"
time="2023-12-20 18:31:40" level=info msg="Live Start" host="海天柚熙" room="【唱见】仙乐也不过如此"
time="2023-12-20 18:31:40" level=info msg="Record Start" host="海天柚熙" room="【唱见】仙乐也不过如此"
time="2023-12-20 18:31:44" level=info msg="Record End" host="海天柚熙" room="【唱见】仙乐也不过如此"
time="2023-12-20 18:31:45" level=info msg="<nil>" host="海天柚熙" room="【唱见】仙乐也不过如此"
time="2023-12-20 18:32:28" level=info msg="Record Start" host="狂鸟丶楚河-90327" room="新主播，第一天直播！很紧张！"
time="2023-12-20 18:32:28" level=info msg="Live Start" host="狂鸟丶楚河-90327" room="新主播，第一天直播！很紧张！"
time="2023-12-20 18:32:34" level=info msg="Record End" host="狂鸟丶楚河-90327" room="新主播，第一天直播！很紧张！"
time="2023-12-20 18:32:34" level=info msg="<nil>" host="狂鸟丶楚河-90327" room="新主播，第一天直播！很紧张！"

### 自由描述

默认添加快手无法录制

**Comment by kira1928** [comment]
快手支持不稳定，目前也不打算继续维护它了。
https://github.com/hr3lxphr6j/bililive-go?tab=readme-ov-file#%E6%94%AF%E6%8C%81%E7%BD%91%E7%AB%99
