### ISSUE TITLE
如果bililive-go支持输出文件格式设定就好了

### ISSUE THREAD

**Issue by peng233163** [hr3lxphr6j/bililive-go#62]
有些直播的标题名会包含无法命名成功的字符，会导致输出不了文件。

**Comment by hr3lxphr6j** [comment]
给下有问题主播的直播间

**Comment by peng233163** [comment]
不是指定的直播间，我使用的是windows端，如果直播间标题中存在颜文字、以及文件名中不能存在的字符，会导致重命名失败（录制正常），但是无法保存的问题。

**Comment by edmund-zhao** [comment]
Windows上文件不能用颜文字，emoji，？等特殊字符命名文件
