### ISSUE TITLE
抖音部分直播间报错

### ISSUE THREAD

**Issue by wwkk2580** [hr3lxphr6j/bililive-go#621]
### 程序版本

v0.7.20

### 所使用的 config 文件的内容

App Name: v0.7.20
App Version: v0.7.20
Build Time: 2023-11-25_09:05:31
Pid: 1
Platform: linux/amd64
Go Version: go1.19.13
Git Hash: 055765caa254695c3de56c94f66e788bc527ef36

### 自由描述

![image](https://github.com/hr3lxphr6j/bililive-go/assets/76099203/e73e73a8-77b1-44d1-910a-57d4a44630b0)

**Comment by wwkk2580** [comment]
我想问一下，这是抖音风控了吗？

**Comment by yingfeng-i** [comment]
我看了下我的后台，抖音全部都是 “[failed to get RoomId from page, internal error](https://live.douyin.com/critty258)”

**Comment by yingfeng-i** [comment]
![图片](https://github.com/hr3lxphr6j/bililive-go/assets/18555737/c952cdd9-36c5-4380-b4bf-c9f21cf83516)
添加一个正在直播的直播间，一直在初始化

**Comment by jxxl1203** [comment]
> ![图片](https://private-user-images.githubusercontent.com/18555737/292889583-c952cdd9-36c5-4380-b4bf-c9f21cf83516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjM5OTUsIm5iZiI6MTcwMzY2MzY5NSwicGF0aCI6Ii8xODU1NTczNy8yOTI4ODk1ODMtYzk1MmNkZDktMzZjNS00MzgwLWI0YmYtYzlmMjFjZjgzNTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA3NTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YzlhNGY0NjliMDI4MWY5MjEyYWY0NGQ0MzdkNTI0NWNhODZiNDdmYjQ0OTFjMjQ1ZDIyYTIwNjlkZjc0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBf7LW7388A72Hk_LTl_Sjd2TLOvIvT3VgsdziJkd54) 添加一个正在直播的直播间，一直在初始化

我也是,一直卡在初始化,直播间名称也获取不到

**Comment by kira1928** [comment]
正在修复。
https://github.com/hr3lxphr6j/bililive-go/issues/543

**Comment by kira1928** [comment]
v0.7.21 已修复抖音录制问题
