### ISSUE TITLE
抖音已经完全无法录制.求一个好心人维护更新一下.感谢

### ISSUE THREAD

**Issue by antonio65421** [hr3lxphr6j/bililive-go#625]
### 程序版本

v0.7.20

**Comment by pifeifei** [comment]
+1

**Comment by kira1928** [comment]
修复代码基本已经敲定了，还在走流程。
详情见这里 https://github.com/hr3lxphr6j/bililive-go/pull/630

**Comment by antonio65421** [comment]
＠[kira1928](https://github.com/kira1928) 感谢大哥 辛苦了

**Comment by kira1928** [comment]
Duplicate of https://github.com/hr3lxphr6j/bililive-go/issues/621
