### ISSUE TITLE
linux端录制无报错但是录制失败

### ISSUE THREAD

**Issue by M1saka10010** [hr3lxphr6j/bililive-go#63]
ffmpeg没有问题IP应该也没有被ban版本是最新版.050rc3。目录也能创建，但是就是录不到内容。系统是centos7，我另外一台debian的机子输出一样但是能录。会不会是系统问题？
```
[root@host ~]# bililive-go -i https://live.bilibili.com/719085
time="2020-04-26 22:18:50" level=info msg="BiliLive-go Version: 0.5.0-rc.3 Link Start"
time="2020-04-26 22:18:51" level=info msg="Live Start" host="萌萌哒老陈" room="【陈8点】本日赛事回顾，明日赛事前瞻"
time="2020-04-26 22:18:51" level=info msg="Record Start" host="萌萌哒老陈" room="【陈8点】本日赛事回顾，明日赛事前瞻"
```
输出就这样

**Comment by lemnrt** [comment]
一样的问题在lxc虚拟化下

**Comment by hr3lxphr6j** [comment]
我一直在archLinux上用是没问题，去看看dmesg有没有错误信息，还是不行的话试试docker吧

**Comment by JIA-Jimmy** [comment]
在feature里加上这条参数试试
feature:
  use_native_flv_parser: true

**Comment by lemnrt** [comment]
> 特点：
> use_native_flv_parser： 真实

解决了录制成功谢谢

**Comment by RealXuChe** [comment]
Archlinux同样遇到了此问题.遇到问题时,我没有开启`use_native_flv_parser`.
我现在已经开启了`use_native_flv_parser`,我会进一步观察问题是否被解决.

**Comment by RealXuChe** [comment]
开启`use_native_flv_parser`后问题解决.

**Comment by hr3lxphr6j** [comment]
> 开启`use_native_flv_parser`后问题解决.

`ffmpeg`是通过`pacman`安装的吗?

**Comment by RealXuChe** [comment]
> 
> 
> > 开启`use_native_flv_parser`后问题解决.
> 
> `ffmpeg`是通过`pacman`安装的吗?

是的.
```
➜  ~ pacman -Ss ffmpeg
extra/ffmpeg 1:4.2.3-2 [installed]
    Complete solution to record, convert and stream audio and video
```

**Comment by hr3lxphr6j** [comment]
> > > 开启`use_native_flv_parser`后问题解决.
> > 
> > 
> > `ffmpeg`是通过`pacman`安装的吗?
> 
> 是的.
> 
> ```
> ➜  ~ pacman -Ss ffmpeg
> extra/ffmpeg 1:4.2.3-2 [installed]
>     Complete solution to record, convert and stream audio and video
> ```

直播间url提供下

**Comment by RealXuChe** [comment]
> 
> 
> > > > 开启`use_native_flv_parser`后问题解决.
> > > 
> > > 
> > > `ffmpeg`是通过`pacman`安装的吗?
> > 
> > 
> > 是的.
> > ```
> > ➜  ~ pacman -Ss ffmpeg
> > extra/ffmpeg 1:4.2.3-2 [installed]
> >     Complete solution to record, convert and stream audio and video
> > ```
> 
> 直播间url提供下

不能正常录制的直播间地址: https://live.bilibili.com/92613
说来,似乎只有bilibili的直播无法录制.
我监控了3个bilibili直播,1个斗鱼直播,观察到斗鱼直播可以正常录制,有1个bilibili直播观测到不能录制 (只有这1个我确定活动过,其余的直播虽无录制文件生成,但并不清楚是否活动过) .

**Comment by hr3lxphr6j** [comment]
> > > > > 开启`use_native_flv_parser`后问题解决.
> > > > 
> > > > 
> > > > `ffmpeg`是通过`pacman`安装的吗?
> > > 
> > > 
> > > 是的.
> > > ```
> > > ➜  ~ pacman -Ss ffmpeg
> > > extra/ffmpeg 1:4.2.3-2 [installed]
> > >     Complete solution to record, convert and stream audio and video
> > > ```
> > 
> > 
> > 直播间url提供下
> 
> 不能正常录制的直播间地址: https://live.bilibili.com/92613
> 说来,似乎只有bilibili的直播无法录制.
> 我监控了3个bilibili直播,1个斗鱼直播,观察到斗鱼直播可以正常录制,有1个bilibili直播观测到不能录制 (只有这1个我确定活动过,其余的直播虽无录制文件生成,但并不清楚是否活动过) .

我这里是可以的
![image](https://user-images.githubusercontent.com/12208550/84157847-c7639100-aa9d-11ea-8ef6-3ae2c0398263.png)

**Comment by RealXuChe** [comment]
> 我这里是可以的
> ![image](https://user-images.githubusercontent.com/12208550/84157847-c7639100-aa9d-11ea-8ef6-3ae2c0398263.png)

在关闭`use_native_flv_parser`后问题复现.
控制台日志和启动参数:
![图片](https://user-images.githubusercontent.com/47659370/84158675-b9624000-aa9e-11ea-93ae-87e8e7b088de.png)

**Comment by hr3lxphr6j** [comment]
> > 我这里是可以的
> > ![image](https://user-images.githubusercontent.com/12208550/84157847-c7639100-aa9d-11ea-8ef6-3ae2c0398263.png)
> 
> 在关闭`use_native_flv_parser`后问题复现.
> 控制台日志和启动参数:
> ![图片](https://user-images.githubusercontent.com/47659370/84158675-b9624000-aa9e-11ea-93ae-87e8e7b088de.png)

输出路径有读写权限吗

**Comment by RealXuChe** [comment]
> 
> 
> > > 我这里是可以的
> > > ![image](https://user-images.githubusercontent.com/12208550/84157847-c7639100-aa9d-11ea-8ef6-3ae2c0398263.png)
> > 
> > 
> > 在关闭`use_native_flv_parser`后问题复现.
> > 控制台日志和启动参数:
> > ![图片](https://user-images.githubusercontent.com/47659370/84158675-b9624000-aa9e-11ea-93ae-87e8e7b088de.png)
> 
> 输出路径有读写权限吗

有权限.
能在只打开`use_native_flv_parser`的情况下修复,就不会是权限问题啊......

**Comment by JIA-Jimmy** [comment]
之前用docker以后可以用ffmpeg录制了，但是最两天出现了录制片段3-5s一断的问题，本来以为是网络原因，但是打开`use_native_flv_parser `以后就正常

**Comment by lightyisu** [comment]
系统:centos debian 服务器
这个我开启了原生flv解析器还是没有办法 录制 
只会出现导出目录会新建（虎牙/斗鱼/xxx主播）这样的文件目录 里面文件为空
[静默没有录制的信息]
![image](https://user-images.githubusercontent.com/45456944/99095505-2bbbeb00-2610-11eb-83ad-9045086324a1.png)

**Comment by kira1928** [comment]
issue 年代久远，最近也没看到同类问题了，这边就先关闭了。
