### ISSUE TITLE
这几天别想虎牙了..每天都在换直播源..已经两天了。

### ISSUE THREAD

**Issue by miria0** [hr3lxphr6j/bililive-go#632]
### 程序版本

0.7.1

### 所使用的 config 文件的内容

1

### 程序 log

1

### 自由描述

昨天换了一次直播源，今天中午又换了一波...
太麻烦了......凌晨我自己弄的直播源还可以录制，中午就G了...然后全部碎片化...
虎牙在打击录播...因为太耗带宽了。

**Comment by kira1928** [comment]
这个好像不是 bug。
这个项目没开论坛功能，不然发这类帖子就方便了。
现在只能麻烦你找一个讨论虎牙问题的 issue 在下面留言和别人探讨了。。

**Comment by HelloGitHubWeb** [comment]
解决了吗

**Comment by kira1928** [comment]
@HelloGitHubWeb 
没有。已经有其他 issue 在追踪这个问题了。
https://github.com/hr3lxphr6j/bililive-go/issues/627

**Comment by lgygcc** [comment]
olive可以录制虎牙啊

**Comment by lgygcc** [comment]
olive 可以录制虎牙 这个为什么不行的！

**Comment by kira1928** [comment]
@lgygcc 因为这个项目菜！

**Comment by HelloGitHubWeb** [comment]
是因为直播源的问题吗 一直更换 似乎没有有用的直播源

**Comment by miria0** [comment]
> @HelloGitHubWeb 没有。已经有其他 issue 在追踪这个问题了。 #627

olive 收费项目...而且更新贼勤快...最近更新都是今天1点28分...

**Comment by HelloGitHubWeb** [comment]
> > @HelloGitHubWeb 没有。已经有其他 issue 在追踪这个问题了。 #627
> 
> olive 收费项目...而且更新贼勤快...最近更新都是今天1点28分...

发我看看

**Comment by HelloGitHubWeb** [comment]
好了 已经成功解决了直播源问题
