### ISSUE TITLE
[提问]: max_file_size的参数单位是多少

### ISSUE THREAD

**Issue by PartialC** [hr3lxphr6j/bililive-go#634]
### 程序版本

0.7.21

### 自由描述

  max_duration: 30m0s 不生效；
  max_file_size: 的参数单位是多少，查了一圈好像并没有提到这个的具体用法

**Comment by kira1928** [comment]
这个是文档不详细，注释又会被自动删除的问题，不好意思。
单位是字节。
https://github.com/hr3lxphr6j/bililive-go/blob/master/config.yml#L29
