### ISSUE TITLE
斗鱼平台录播有没有办法选择画质增强

### ISSUE THREAD

**Issue by zhenjiulong** [hr3lxphr6j/bililive-go#648]
### 新功能

<img width="113" alt="Snipaste_2024-01-13_19-51-04" src="https://github.com/hr3lxphr6j/bililive-go/assets/136667369/6cb68d49-59c2-4064-97ec-18e6231fc001">

**Comment by Seigi-Liuling** [comment]
有没有一种可能，这个是你h5播放器的及时滤镜，要是想录播成这个效果要额外压制

**Comment by kira1928** [comment]
> 有没有一种可能，这个是你h5播放器的即时滤镜，要是想录播成这个效果要额外压制

这样的话确实和录播项目无关了。
