### ISSUE TITLE
[提问]: 使用时录制完指定大小的文件后就停止录制了，也自动停止监控了，怎么让他一直循环录制

### ISSUE THREAD

**Issue by wangzhanhei** [hr3lxphr6j/bililive-go#651]
### 程序版本

最新

### 自由描述

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.douyu.com/10012556?rid=10012556&dyshid=0-15208fb070647390ddb7d20700081701&dyshci=181
  is_listening: true
  quality: 0
- url: https://www.douyu.com/10676761?dyshid=0-15208fb070647390ddb7d20700081701&dyshci=181
  is_listening: true
  quality: 0
- url: https://www.douyu.com/10609344?dyshid=0-15208fb070647390ddb7d20700081701&dyshci=181
  is_listening: true
  quality: 0
- url: https://www.huya.com/265392
  is_listening: true
  quality: 0
- url: https://live.bilibili.com/26737864
  is_listening: true
  quality: 0
- url: https://www.huya.com/27830075
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 4080218931
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000
如上，只是更改了单个文件大小的体积尺寸为3.8G

**Comment by kira1928** [comment]
默认就是循环监控。 `自动停止监控了` 是什么现象？
