### ISSUE TITLE
建议增加 bilibili只录制音频功能

### ISSUE THREAD

**Issue by zip11** [hr3lxphr6j/bililive-go#654]
### 新功能

bilibili 手机版可以播放直播音频，不含视频部分，很多访谈类 的直播，只听录音就够了，还可以节省 使用服务器录制的流量，

**Comment by Seigi-Liuling** [comment]
??? 你确定现在手机版只播放音频的时候真的是只“拉流”音频？
我看哔哩哔哩技术的介绍，现在直播只有HLS和HTTP-FLV两种流，又没有DASH，你怎么做到只拉取音频

**Comment by zip11** [comment]
> ??? 你确定现在手机版只播放音频的时候真的是只“拉流”音频？ 我看哔哩哔哩技术的介绍，现在直播只有HLS和HTTP-FLV两种流，又没有DASH，你怎么做到只拉取音频

我手机是安卓的，有系统网速显示，如果是直播视频，直播高清挡位下载速度显示100KB/S左右,如果是打开只听声音，下载速度显示20KB/S左右

**Comment by kira1928** [comment]
有大佬已经实现了 https://github.com/hr3lxphr6j/bililive-go/pull/679
会整合进下一个 release 版本中。
