### ISSUE TITLE
希望能够支持录制Afreecatv

### ISSUE THREAD

**Issue by Denkiiiii** [hr3lxphr6j/bililive-go#656]
### 目标网站任意直播间的示例 url，精确到具体直播间

https://play.afreecatv.com/sol3712/251845403

### 自由描述

afreecatv上有很多好看的主播，奈何没什么时间看，希望可以更新支持该网站。而且也找不到合适的工具录制，所以也希望能够更新支持。

**Comment by kira1928** [comment]
Duplicate of #294
