### ISSUE TITLE
直播间一直提示初始化

### ISSUE THREAD

**Issue by Akimio521** [hr3lxphr6j/bililive-go#659]
### 程序版本

0.7.23

### 自由描述

无报错信息，但一直显示初始化，等待时间超1小时，如图
![image](https://github.com/hr3lxphr6j/bililive-go/assets/77880495/95ae050a-5cf5-4150-a4b2-f0003ee225f2)

**Comment by kira1928** [comment]
在我本地无法重现。

初始化一般是指程序无法获取这个直播间的信息，一次都获取不到。可能是因为你录了太多直播间，被网站ban ip了？
