### ISSUE TITLE
可以请求功能添加吗？浪live直播

### ISSUE THREAD

**Issue by test2g** [hr3lxphr6j/bililive-go#66]
直播间状态api：https://api-kk.lv-play.com/webapi/v1/search/global?keyword=房间号
data.users.live_status为1即开播，0则不开播
直播流地址：https://api.kingkongapp.com/webapi/v1/room/info?room_id=房间号
data.live_info.stream_items[3]，即“最佳”画质的地址

**Comment by hr3lxphr6j** [comment]
好的，有时间的话我搞下

**Comment by test2g** [comment]
感谢

**Comment by test2g** [comment]
不过实测直播流地址只有在开播后才会提供返回值
