### ISSUE TITLE
能否增加tiktok和小红书直播

### ISSUE THREAD

**Issue by Leonhardt92** [hr3lxphr6j/bililive-go#662]
### 新功能
参考案例 https://github.com/ihmily/DouyinLiveRecorder

**Comment by kira1928** [comment]
小红书录播有大佬[实现了](https://github.com/hr3lxphr6j/bililive-go/pull/680)，下一个版本会包含这一功能。

一个 issue 包含两个新增网站不方便开发者对应。
建议 tiktok 单独发一个 issue，等其他大佬来实现。
