### ISSUE TITLE
抖音又又又报错了

### ISSUE THREAD

**Issue by wwkk2580** [hr3lxphr6j/bililive-go#663]
### 程序版本

v0.7.23

### 程序 log

![image](https://github.com/hr3lxphr6j/bililive-go/assets/76099203/d82fbe48-6ab9-429a-8921-1d35a7efde00)

![image](https://github.com/hr3lxphr6j/bililive-go/assets/76099203/68a15d4c-5e0a-4b12-8f5d-40bda8a9b852)

### 自由描述

```
2024-01-26 18:34:42 time="2024-01-26 18:34:42" level=error msg="failed to load room info" error="failed to get page, code: 504, internal error" url="https://live.douyin.com/826479189963"
```
提取不到直播信息，我没有使用代理

**Comment by pengjunok** [comment]
+1

**Comment by wintopic** [comment]
崩了ToT

**Comment by Aric-Sun** [comment]
+1

**Comment by myallure0322** [comment]
+1

**Comment by kira1928** [comment]
已在 https://github.com/hr3lxphr6j/bililive-go/releases/tag/v0.7.24 中修复。

**Comment by AvrilL161** [comment]
> 已在 https://github.com/hr3lxphr6j/bililive-go/releases/tag/v0.7.24 中修复。

v.0.7.24
![2024-01-30_06-36-20](https://github.com/hr3lxphr6j/bililive-go/assets/29428522/2f042b14-da70-4ec0-a9e3-08d123ef8ce1)

![2024-01-30_06-34-29](https://github.com/hr3lxphr6j/bililive-go/assets/29428522/2cc6a4e9-2459-401e-ad11-1ec3b62bfe10)

**Comment by kira1928** [comment]
504是服务器端故障代码。我们能修复的只有程序部分的bug。
也许你遇到的是ban ip之类的其它问题。那这个issue就继续保留，暂时不关闭了。

**Comment by wwkk2580** [comment]
> 504是服务器端故障代码。我们能修复的只有程序部分的bug。 也许你遇到的是ban ip之类的其它问题。那这个issue就继续保留，暂时不关闭了。

应该不是ban ip ，我会使用无痕浏览器不登陆抖音的方式验证IP状况
