### ISSUE TITLE
🙏音又開始報錯無法錄製了。-無法從頁面取得 RoomId，內部錯誤..顫求一個好心人維護一下🙏

### ISSUE THREAD

**Issue by antonio65421** [hr3lxphr6j/bililive-go#666]
### 程序版本

v0.7.23

**Comment by zhangtiezhuang** [comment]
我的也出现该问题了

**Comment by msumdx** [comment]
up up 我也有这个问题

**Comment by wintopic** [comment]
HELP

**Comment by Jimmy-ZY** [comment]
我看见有人提交修改listener.go的文件了，但是我是用docker装的，找不到文件修改。

**Comment by xxnuo** [comment]
https://github.com/xxnuo/bililive-go/releases/tag/v0.7.24

**Comment by xxnuo** [comment]
> 我看见有人提交修改listener.go的文件了，但是我是用docker装的，找不到文件修改。

使用 GitHub 自动编译，应该稍后就能看到 docker 镜像和 release 文件了

xxnuo/bililive-go

https://github.com/xxnuo/bililive-go/releases

**Comment by kira1928** [comment]
已在 https://github.com/hr3lxphr6j/bililive-go/releases/tag/v0.7.24 中修复。

**Comment by AvrilL161** [comment]
> 已在 https://github.com/hr3lxphr6j/bililive-go/releases/tag/v0.7.24 中修复。

v.0.7.24

![2024-01-30_06-36-20](https://github.com/hr3lxphr6j/bililive-go/assets/29428522/95b64d5b-34ba-4374-84cd-4690c7ab1bfe)

![2024-01-30_06-34-29](https://github.com/hr3lxphr6j/bililive-go/assets/29428522/c15ae680-d550-4960-8a7b-ee77a6b3fca6)
