### ISSUE TITLE
抖音报错failed to get page, code: 504, internal error

### ISSUE THREAD

**Issue by chaogemars** [hr3lxphr6j/bililive-go#669]
### 程序版本

0.7.1

**Comment by chaogemars** [comment]
![屏幕截图 2024-01-28 222832](https://github.com/hr3lxphr6j/bililive-go/assets/53162634/8e2988df-bc0d-4ab7-a62f-1769389f6886)

**Comment by kele-manong** [comment]
我也有这个问题

**Comment by Aric-Sun** [comment]
名字没了一般是正在直播吧，但是又录不上

**Comment by kele-manong** [comment]
> 名字没了一般是正在直播吧，但是又录不上

我观察下来貌似不是这个现象，就算当时不在直播，后面开了直播，也录不上。最近有人fork了一个版本，紧急修复了，不过不能docker安装，我不得不linux本地安装后临时过渡一下

**Comment by Aric-Sun** [comment]
> > 名字没了一般是正在直播吧，但是又录不上
> 
> 我观察下来貌似不是这个现象，就算当时不在直播，后面开了直播，也录不上。最近有人fork了一个版本，紧急修复了，不过不能docker安装，我不得不linux本地安装后临时过渡一下

看了那个commit，心想难道两行代码就搞定了？

**Comment by xxnuo** [comment]
> > 名字没了一般是正在直播吧，但是又录不上
> 
> 我观察下来貌似不是这个现象，就算当时不在直播，后面开了直播，也录不上。最近有人fork了一个版本，紧急修复了，不过不能docker安装，我不得不linux本地安装后临时过渡一下

https://github.com/hr3lxphr6j/bililive-go/issues/666#issuecomment-1913441678

**Comment by kele-manong** [comment]
> > > 名字没了一般是正在直播吧，但是又录不上
> > 
> > 
> > 我观察下来貌似不是这个现象，就算当时不在直播，后面开了直播，也录不上。最近有人fork了一个版本，紧急修复了，不过不能docker安装，我不得不linux本地安装后临时过渡一下
> 
> [#666 (comment)](https://github.com/hr3lxphr6j/bililive-go/issues/666#issuecomment-1913441678)

没错，就这个。
原来我看帖不仔细，有docker镜像的啊……算了，已经本地安装了，先对付吧
