### ISSUE TITLE
希望支持afrecatv非洲台录制

### ISSUE THREAD

**Issue by Joftal** [hr3lxphr6j/bililive-go#674]
### 目标网站任意直播间的示例 url，精确到具体直播间

https://play.afreecatv.com/1004suna/253535709

### 列举其他已支持上述网站的开源工具

https://github.com/ihmily/DouyinLiveRecorder

### 自由描述

可以有个可视化UI管理录像

**Comment by kira1928** [comment]
Duplicate of #294
