### ISSUE TITLE
[提问]: [提问]: 请教一下，我们的程序在监控一个直播链接的时候，后端程序的处理逻辑是什么？ 每隔一段时间请求一次直播间数据嘛，这个时间周期是多久，如果一直没有等到主播直播采取的策略是一直按照该周期进行监测还是再等待一定的时间后再循环检测呢

### ISSUE THREAD

**Issue by javayxw** [hr3lxphr6j/bililive-go#677]
### 程序版本

新版本

**Comment by ccp-p** [comment]
看代码是写的轮询，20秒查一次

**Comment by 389377616** [comment]
interval

**Comment by kira1928** [comment]
> 每隔一段时间请求一次直播间数据嘛

是的

> 这个时间周期是多久

时间周期可以在配置文件中设置：https://github.com/hr3lxphr6j/bililive-go/blob/master/config.yml#L5

> 如果一直没有等到主播直播采取的策略是一直按照该周期进行监测还是再等待一定的时间后再循环检测呢

一直按照该周期进行监测
