### ISSUE TITLE
添加抖音直播房间是否能用分享链接添加

### ISSUE THREAD

**Issue by 389377616** [hr3lxphr6j/bililive-go#683]
### 新功能

我每次在抖音上看到一个想要录制的直播房间，复制了房间的分享链接https://v.douyin.com/xxxxxxxx/ ，还得用电脑浏览器打开这个链接，把链接转成https://live.douyin.com/xxxxxxxxxxxx 才能添加房间，我感觉有点慢麻烦，如果可以直接用https://v.douyin.com/xxxxxxxx/ 添加的话，我就可以直接抖音里复制了链接，然后手机上打开Bililive-go页面就行添加房间了，省去转换链接的那一步了。

**Comment by kira1928** [comment]
很难。
我试了一下，这类短链接的跳转需要滑动解锁验证，不是可以简单实现的。
