### ISSUE TITLE
[提问]: 

### ISSUE THREAD

**Issue by Taffy-Zong** [hr3lxphr6j/bililive-go#686]
### 程序版本

v0.6.3

### 自由描述

想问下大佬，为什么我这边的控制台左边没有“设置”跟“文件”这两个选项

**Comment by wwkk2580** [comment]
更到最新版试试吧，不要用国内的镜像

**Comment by kira1928** [comment]
v0.6.3 版本太老了，确实没有这些选项。

> 更到最新版试试吧，不要用国内的镜像

对的！
