### ISSUE TITLE
求助 更新之后直播间报错

### ISSUE THREAD

**Issue by knownothing20** [hr3lxphr6j/bililive-go#694]
### 程序版本

0.7.24

### 所使用的 config 文件的内容

```
rpc:
  enable: true
  bind: 127.0.0.1:1985
debug: false
interval: 20
out_put_path: I:\record
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
# qulity参数目前仅B站启用，默认为0
# (B站)0代表原画PRO(HEVC)优先, 其他数值为原画(AVC)
# 原画PRO会保存为.ts文件, 原画为.flv
# HEVC相比AVC体积更小, 减少35%体积, 画质相当, 但是B站转码有时候会崩
- url: https://live.douyin.com/862155159426
  is_listening: true
  quality: 0
- url: https://live.douyin.com/10094346511
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  # 仅在 use_native_flv_parser=false 时生效
  # 单位为字节 (byte)
  # 有效值为正数，默认值 0 为无效
  # 负数为非法值，程序会输出 log 提醒，并无视所设定的数值
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
#  当 custom_commandline 的值 不为空时，convert_to_mp4 的值会被无视，
#  而是在录制结束后直接执行 custom_commandline 中的命令。
#  在 custom_commandline 执行结束后，程序还会继续查看 delete_flv_after_convert 的值，
#  来判断是否需要删除原始 flv 文件。
#  以下是一个在录制结束后将 flv 视频转换为同名 mp4 视频的示例：
#  custom_commandline: '{{ .Ffmpeg }} -hide_banner -i "{{ .FileName }}" -c copy "{{ .FileName | trimSuffix (.FileName | ext)}}.mp4"'
  custom_commandline: ""
timeout_in_us: 60000000
```

### 程序 log

time="2024-03-21 08:04:35" level=info msg="BiliLive-go Version: v0.7.24 Link Start"
time="2024-03-21 08:04:36" level=info msg="Server start at 127.0.0.1:1985"
time="2024-03-21 13:42:13" level=error msg="failed to load room info" error="Get \"https://live.douyin.com/862155159426\": read tcp 192.168.31.23:61292->183.240.72.198:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." url="https://live.douyin.com/862155159426"
time="2024-03-21 13:42:13" level=error msg="failed to load room info" error="Get \"https://live.douyin.com/10094346511\": read tcp 192.168.31.23:61292->183.240.72.198:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." url="https://live.douyin.com/10094346511"

### 自由描述

请教以下， 更新到v0.7.24 之后报错， 之前都没问题 ， 之前好像是[0.7.19] ，没太注意， 反正是低于这个最新版的。

**Comment by hibiki222** [comment]
很早就有了，能录抖音就一直存在

**Comment by kira1928** [comment]
感觉是网络不稳定，程序这边很难改善。
