### ISSUE TITLE
抖音直播录制时画质不能为最高级别

### ISSUE THREAD

**Issue by lxr760** [hr3lxphr6j/bililive-go#695]
### 程序版本

docker chigusa/bililive-go latest

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 25
out_put_path: /srv/bililive
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: false
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/****
  is_listening: true
  quality: 0
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000

### 自由描述

quality: 0

但同一个直播间，用本项目录制时，画质分辨率为960*720
用另外一个软件录制同一个频道，画质分辨率为1920*1440

![image](https://github.com/hr3lxphr6j/bililive-go/assets/8476457/712939c6-8069-4da3-829b-736b26eec6c3)
![Snipaste_2024-03-25_18-48-54](https://github.com/hr3lxphr6j/bililive-go/assets/8476457/aebf1853-923a-4b4f-bd44-dbde53eaec41)

**Comment by lxr760** [comment]
> 另外一个软件指的是哪个软件？

https://github.com/OriX6/liveRecordAuto

**Comment by Aric-Sun** [comment]
+1，我这只剩240*432了

**Comment by kira1928** [comment]
```
docker chigusa/bililive-go latest
```
这样不确定你用的是哪个版本，是不是受到了镜像缓存的影响。抖音录不到最高画质以前在 [0.7.19](https://github.com/hr3lxphr6j/bililive-go/releases/tag/v0.7.19) 是修复过的。

@Aric-Sun 你的程序版本号和遇到问题的直播间 url 可以发一下吗？

**Comment by lxr760** [comment]
> ```
> docker chigusa/bililive-go latest
> ```
> 
> 这样不确定你用的是哪个版本，是不是受到了镜像缓存的影响。抖音录不到最高画质以前在 [0.7.19](https://github.com/hr3lxphr6j/bililive-go/releases/tag/v0.7.19) 是修复过的。
> 
> @Aric-Sun 你的程序版本号和遇到问题的直播间 url 可以发一下吗？


App Name: v0.7.24
App Version: v0.7.24
Build Time: 2024-01-29_16:38:21
Pid: 1
Platform: linux/amd64
Go Version: go1.19.13
Git Hash: e481cc406d7cf429644cb98725fc435db670ed53


直播间举例 https://live.douyin.com/685619235482


分辨率不为最高不是每次都会出现，有时候是最高分辨率+最高码率，有时候是低分辨率+低码率

**Comment by kira1928** [comment]
Duplicate of #685

**Comment by kira1928** [comment]
我们集中在一个地方讨论吧。
