### ISSUE TITLE
[提问]: 请问输出的文件名称能自己定义么

### ISSUE THREAD

**Issue by javachenla** [hr3lxphr6j/bililive-go#697]
### 程序版本

v0.7.24

### 自由描述

请问输出的文件名称能自己定义么,比如说自定义文件名+日期
起因:因许多直播间录制时,名称中都带有特殊符号,使用xftp进行下载时需要进行重命名.不知道是否有什么参数能够进行设置

**Comment by kira1928** [comment]
可以哦。
https://github.com/hr3lxphr6j/bililive-go/wiki/More-Tips#%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E5%90%8D%E6%A8%A1%E6%9D%BF
