### ISSUE TITLE
访问过于频繁导致ip封禁

### ISSUE THREAD

**Issue by learner-dhx** [hr3lxphr6j/bililive-go#699]
### 程序版本

winx64最新版release

### 所使用的 config 文件的内容

我就加了两个网易cc直播源，就把我的ip封禁了。看到程序不断log，猜测是直播源不稳定导致程序进入了某种死循环的bug(请求频率高)。建议看看源码有没有轮询相关的代码请做一下延时处理。否则只要直播不稳定就会封掉ip，这应该是程序本身的问题

**Comment by hibiki222** [comment]
错误的，网易对ban ip很敏感，检测频率放低就没事了，和程序无关

**Comment by kira1928** [comment]
> 错误的，网易对ban ip很敏感，检测频率放低就没事了，和程序无关

对的！
