### ISSUE TITLE
windows 64 bit 打开闪退

### ISSUE THREAD

**Issue by OrdinaryYZH** [hr3lxphr6j/bililive-go#70]
按照wiki的步骤都做了，但是闪退...

**Comment by hr3lxphr6j** [comment]
log上有啥

**Comment by OrdinaryYZH** [comment]
闪退了，啥都看不到

**Comment by hr3lxphr6j** [comment]
用控制台打开，参数是啥

**Comment by OrdinaryYZH** [comment]
是不是要先弄go环境的，我装了go之后也不会弄控制台打开。。这里的wiki都是好几年前的。。我找找教程吧。。

**Comment by OrdinaryYZH** [comment]
对于不会go的人来说，这成本有点高，感觉不是开箱即用呀。就算是下载完源码按照首页的提示make还是，还是没反应。。。LZ还是完善下文档先吧

**Comment by hr3lxphr6j** [comment]
1. 直接下载二进制不需要依赖go，go是静态编译
2. `make`在Windows上没有，编译脚本也是shell写的，当然用了wsl或msys2当我没说
3. Windows上你不传任何参数双击点开直接闪退是预期内的，好好看使用说明

**Comment by OrdinaryYZH** [comment]
那我就直接贴以下我怎么跑的吧：
```
D:\Downloads\bililive-windows-amd64>bililive-windows-amd64.exe -i https://www.huya.com/10300
time="2020-05-24 10:12:57" level=info msg="BiliLive-go Version: 0.5.2 Link Start"
time="2020-05-24 10:13:00" level=error msg="internal error" url="https://www.huya.com/10300"
time="2020-05-24 10:13:00" level=info msg="Bye~"

D:\Downloads\bililive-windows-amd64>bililive-go -i https://www.huya.com/10300
'bililive-go' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```
这是我看着介绍弄的了，以下是目录：
![image](https://user-images.githubusercontent.com/10287222/82744184-90a43000-9da7-11ea-81fb-396413fce5e4.png)

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/82744235-1b852a80-9da8-11ea-8729-2aa78ad3e0e1.png)

**Comment by OrdinaryYZH** [comment]
我以为后面是跟端口号。。才发现直接跟直播号..

还有个问题，项目主页的可视化界面是怎么出来的，不是在里面配置录制的东西的吗？
