### ISSUE TITLE
[提问]: 

### ISSUE THREAD

**Issue by xiaomingzzzzz** [hr3lxphr6j/bililive-go#700]
### 程序版本

idk

### 所使用的 config 文件的内容

没动过 就是用记事本打开看了一下里面的内容

### 自由描述

你好作者 我是计算机初学者 到达这里之后就卡住不动了怎么办 求解 感谢您

E:\recordtest>bililive-windows-amd64.exe -c config.yml
time="2024-04-08 16:30:44" level=info msg="BiliLive-go Version: v0.7.24 Link Start"
time="2024-04-08 16:30:45" level=info msg="Server start at :8080"
![image](https://github.com/hr3lxphr6j/bililive-go/assets/143982845/a9d47dfd-d3b2-482e-aa62-35f07194ed34)

**Comment by xiaomingzzzzz** [comment]
版本是0.7.24 sry

**Comment by murphysking** [comment]
浏览器打开127.0.0.1:8080，有webui，可以添加直播间，添加后会定时监控、录制

**Comment by kira1928** [comment]
> 浏览器打开127.0.0.1:8080，有webui，可以添加直播间，添加后会定时监控、录制

对的！
