### ISSUE TITLE
虎牙直播间标题出现<bbw>符号后, 识别为&lt;bbw&gt, 无限刷屏错误,无法录制, log文件一晚上超过1gb

### ISSUE THREAD

**Issue by sirlioniva** [hr3lxphr6j/bililive-go#701]
### 程序版本

v0.7.24

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: 127.0.0.1:8080
debug: true
interval: 2
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: true
  remove_symbol_other_character: false
live_rooms:

out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

time="2024-04-12 03:54:22" level=debug msg="Start ParseLiveStream(http://al.flv.huya.com/src/840295504-840295504-3609041708655837184-1680714464-10057-A-0-1.flv?ctype=tars_mobile&exsphd=264_500%2C264_2000%2C264_4000%2C264_8000%2C&fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&fs=bgct&ratio=0&seqid=3150820144039&sphd=264_%2A-265_%2A&sphdDC=huya&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sv=2110211124&t=103&uid=1437954882039&uuid=71743d4c-446f-420e-b41e-e9f7c6131474&ver=1&wsSecret=d8d9fc763b67539f870beecbe82f6445&wsTime=6618944e, 虎牙\\抱抱念酱\\[2024-04-12 03-54-22][抱抱念 酱][运球第一名<bbw>].flv)" host="抱抱念酱" room="运球第一名&lt;bbw&gt;"
time="2024-04-12 03:54:22" level=info msg="open 虎牙\\抱抱念酱\\[2024-04-12 03-54-22][抱抱念酱][运球第一名<bbw>].flv: The filename, directory name, or volume label syntax is incorrect." host="抱抱念酱" room=" 运球第一名&lt;bbw&gt;"
time="2024-04-12 03:54:22" level=debug msg="End ParseLiveStream(http://al.flv.huya.com/src/840295504-840295504-3609041708655837184-1680714464-10057-A-0-1.flv?ctype=tars_mobile&exsphd=264_500%2C264_2000%2C264_4000%2C264_8000%2C&fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&fs=bgct&ratio=0&seqid=3150820144039&sphd=264_%2A-265_%2A&sphdDC=huya&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sv=2110211124&t=103&uid=1437954882039&uuid=71743d4c-446f-420e-b41e-e9f7c6131474&ver=1&wsSecret=d8d9fc763b67539f870beecbe82f6445&wsTime=6618944e, 虎牙\\抱抱念酱\\[2024-04-12 03-54-22][抱抱念酱][运球第一名<bbw>].flv)" host="抱抱念酱" room="运球第 一名&lt;bbw&gt;"
time="2024-04-12 03:54:22" level=debug msg="exit status 1" host="抱抱念酱" room=" 运球第一名&lt;bbw&gt;"

### 自由描述

直播间https://www.huya.com/620520

无法录制任何视频,错误信息每秒10条, log文件一晚上超过1g了

其他虎牙直播间正常,看了下异常信息应该是标题导致?

**Comment by kira1928** [comment]
特殊字符的问题应该已经在 https://github.com/hr3lxphr6j/bililive-go/pull/757 中修复了，用最新版程序可以应对上述特殊字符。
log 累计变大的问题需要另外处理一下。
