### ISSUE TITLE
大佬请求支持afreecatv和pandalive的直播录制

### ISSUE THREAD

**Issue by xiaohaigge** [hr3lxphr6j/bililive-go#703]
### 目标网站任意直播间的示例 url，精确到具体直播间

https://www.pandalive.co.kr/live/play/yyysi1004，https://play.afreecatv.com/zpdl1313/263942368

### 列举其他已支持上述网站的开源工具

https://github.com/ihmily/DouyinLiveRecorder

### 自由描述

海外视频内容丰富，尺度大。其他工具没有本工具好用

**Comment by kira1928** [comment]
Duplicate of #294
