### ISSUE TITLE
增加定时录制功能

### ISSUE THREAD

**Issue by waifei01** [hr3lxphr6j/bililive-go#705]
### 新功能

大佬，你好。目前抖音的直播平台有些是24小时不间断或较长时间直播卖货，中间插播一些访谈，请问可否增加定时录制功能，方便只录制需要的内容，其他时间段不录制。

**Comment by hibiki222** [comment]
可以通过外置脚本，操控api来定时录制

**Comment by waifei01** [comment]
> 可以通过外置脚本，操控api来定时录制

你好，可否具体说明如何操作？定时操作这个docker录制服务也可以，就是不清楚如何操作。

**Comment by hibiki222** [comment]
> > 可以通过外置脚本，操控api来定时录制
> 
> 你好，可否具体说明如何操作？定时操作这个docker录制服务也可以，就是不清楚如何操作。
https://github.com/hr3lxphr6j/bililive-go/wiki/API
写个小脚本

**Comment by waifei01** [comment]
> > > 可以通过外置脚本，操控api来定时录制
> > 
> > 
> > 你好，可否具体说明如何操作？定时操作这个docker录制服务也可以，就是不清楚如何操作。
> > https://github.com/hr3lxphr6j/bililive-go/wiki/API
> > 写个小脚本

Thanks♪(･ω･)ﾉ

**Comment by kira1928** [comment]
似乎解决了
