### ISSUE TITLE
Cookie保存后格式会强行变更

### ISSUE THREAD

**Issue by lxr760** [hr3lxphr6j/bililive-go#715]
### 程序版本

v0.7.25

### 所使用的 config 文件的内容

cookies: {}

### 自由描述

config里默认的cookie格式为cookies: {}，但是在{}输入 live.douyin.com:****以后保存，格式会被保存成
cookies:
  ? live.douyin.com:****
  : ""

![image](https://github.com/hr3lxphr6j/bililive-go/assets/8476457/78109398-c75b-4102-9475-f72812f01610)

看起来格式被程序给强行变更了，不知道此时cookie到底生效没有

**Comment by murphysking** [comment]
在live.douyin.com和cookie值两侧加上双引号即可

**Comment by lxr760** [comment]
> 在live.douyin.com和cookie值两侧加上双引号即可

cookies:"live.douyin.com:******"


是这样的格式吗？    保存时报错
![image](https://github.com/hr3lxphr6j/bililive-go/assets/8476457/65e8f6fb-8547-4814-be7b-f29f12cbe146)

**Comment by kira1928** [comment]
https://github.com/hr3lxphr6j/bililive-go?tab=readme-ov-file#cookie-%E5%9C%A8-configyml-%E4%B8%AD%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95

**Comment by murphysking** [comment]
"live.douyin.com":"cookie值"，我测试这样可以保存

**Comment by lxr760** [comment]
> "live.douyin.com":"cookie值"，我测试这样可以保存

我这样保存还是报错

**Comment by kira1928** [comment]
你那样保存的配置文件完整内容发上来看一下

**Comment by lxr760** [comment]
> 你那样保存的配置文件完整内容发上来看一下

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /srv/bililive
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.douyin.com/63017497693
  is_listening: true
  quality: 0
  audio_only: false
- url: https://live.douyin.com/217806149950
  is_listening: true
  quality: 0
  audio_only: false
- url: https://live.douyin.com/685619235482
  is_listening: false
  quality: 0
  audio_only: false
- url: https://live.douyin.com/841669633765
  is_listening: true
  quality: 0
  audio_only: false
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies:"live.douyin.com":"~~~~~~"
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000

**Comment by kira1928** [comment]
你看我上面发的链接里有写，格式应该是
```
cookies:
  live.douyin.com: __ac_nonce=123456789012345678903;name=value
```
