### ISSUE TITLE
无法录制斗鱼轮播的直播间

### ISSUE THREAD

**Issue by zhwandzcx** [hr3lxphr6j/bililive-go#717]
### 程序版本

v0.7.25

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 100
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: true
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.bilibili.com/21934623
  is_listening: false
  quality: 0
  audio_only: false
- url: https://www.douyu.com/103493
  is_listening: true
  quality: 0
  audio_only: false
- url: https://www.douyu.com/7670275
  is_listening: true
  quality: 0
  audio_only: false
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 1h0m0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: true
  delete_flv_after_convert: true
  custom_commandline: ""
timeout_in_us: 60000000

### 自由描述

无法录制这个直播间https://www.douyu.com/103493
监控显示  监控中   从不开启录制.
作为对照, 另一个直播间可以录制,  是主播自己在直播的时候放视频, 但不是轮播性质. https://www.douyu.com/7670275.  显示正常录制.

**Comment by kira1928** [comment]
仔细看了一下，这个一起看是播放的录播内容，不是直播所以不触发录制，是正确行为。
