### ISSUE TITLE
[提问]: api 文档没有给put请求体例子 PUT /api/config Save lives info to config file

### ISSUE THREAD

**Issue by zhwandzcx** [hr3lxphr6j/bililive-go#718]
### 程序版本

v0.7.25

### 自由描述

PUT /api/config Save lives info to config file
没有请求体例子

**Comment by kira1928** [comment]
没有请求体，就是把当时程序内存中新增的直播间信息落地到配置文件里。
这个API设计之初好像 web UI 添加直播间之后需要手动点保存，不然重启程序之后网页端添加的直播间会消失。后来在 web UI 的各种功能执行后都会紧跟一个 put /api/config 请求立即保存配置，就不需要用户手动点保存了。
如果你想保存你指定的配置文件信息，那可以使用 https://github.com/hr3lxphr6j/bililive-go/blob/master/docs/API.md#put-apiraw-config-save-the-whole-config-file 这个 API.
