### ISSUE TITLE
挂在磁盘创建不了文件夹 导致写入失败

### ISSUE THREAD

**Issue by miyunwangluo** [hr3lxphr6j/bililive-go#719]
### 程序版本

0.7.25

### 程序 log

time="2024-05-09 20:50:45" level=error msg="failed to create output path[z:\\ty\\live\\YY直播\\国威✦小闪电~户外\\]" error="mkdir z:\\ty\\live\\YY直播\\国威✦小闪电~户外\\: Access is denied." host="国威✦小闪电~户外" room="户外王者小闪电"

### 自由描述

用的raidrive webdav协议 将out_dir设置为挂在的云盘 日志提示无法创建路径

**Comment by kira1928** [comment]
这听起来更像是 raidrive 的问题，录播程序创建目录并没有使用任何特殊的方法。
