### ISSUE TITLE
增加暂停，直播间数据备份和导入功能

### ISSUE THREAD

**Issue by fengxueyulu** [hr3lxphr6j/bililive-go#725]
### 新功能

暂停和恢复录制功能，有时候素材急用，需要暂停进行分段，直播间数据备份和导入，方便升级或者重建容器后迅速恢复服务
能增加这几个功能么

**Comment by kira1928** [comment]
网页可以停止录制再开始录制，手动分段。

README 里写的容器内用 volume 把配置文件映射到 host 目录上，销毁容器会保留配置。配置在容器内的位置是 `/etc/bililive-go/config.yml` 
你也可以在网页设置 tab 里复制整个配置文件文本，然后保存在别处。在新系统里粘贴这个配置后保存就等于导入配置。
