### ISSUE TITLE
[提问]: 一直初始化，没有开始录制

### ISSUE THREAD

**Issue by admin1155** [hr3lxphr6j/bililive-go#728]
### 程序版本

v0.7.25

### 程序 log

time="2024-05-26 23:17:30" level=info msg="BiliLive-go Version: v0.7.25 Link Start"
time="2024-05-26 23:17:30" level=debug msg="config path: /etc/bililive-go/config.yml."
time="2024-05-26 23:17:30" level=debug msg="other flags have been ignored."
time="2024-05-26 23:17:30" level=debug msg="{AppName:BiliLive-go AppVersion:v0.7.25 BuildTime:2024-05-06_00:30:47 GitHash:1a5576470eaee090366cc9cf8223794a04e4bb1c Pid:1 Platform:linux/arm GoVersion:go1.19.13}"
time="2024-05-26 23:17:30" level=debug msg="&{File:/etc/bililive-go/config.yml RPC:{Enable:true Bind:0.0.0.0:8080} Debug:true Interval:30 OutPutPath:./ FfmpegPath: Log:{OutPutFolder:./ SaveLastLog:true SaveEveryLog:false} Feature:{UseNativeFlvParser:false RemoveSymbolOtherCharacter:false} LiveRooms:[{Url:https://live.bilibili.com/32702380 IsListening:true LiveId: Quality:0 AudioOnly:false}] OutputTmpl: VideoSplitStrategies:{OnRoomNameChanged:false MaxDuration:0s MaxFileSize:0} Cookies:map[] OnRecordFinished:{ConvertToMp4:false DeleteFlvAfterConvert:false CustomCommandline:} TimeoutInUs:60000000 liveRoomIndexCache:map[https://live.bilibili.com/32702380:0]}"
time="2024-05-26 23:19:03" level=info msg="Server start at 0.0.0.0:8080"
time="2024-05-26 23:19:28" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:19:28" level=debug msg="Http Request" Method=GET Path=/static/css/2.5b1f1a89.chunk.css RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:19:28" level=debug msg="Http Request" Method=GET Path=/static/js/main.e34eac62.chunk.js RemoteAddr="172.17.0.1:58140"
time="2024-05-26 23:19:28" level=debug msg="Http Request" Method=GET Path=/static/css/main.6220e936.chunk.css RemoteAddr="172.17.0.1:58134"
time="2024-05-26 23:19:28" level=debug msg="Http Request" Method=GET Path=/static/js/2.09e56847.chunk.js RemoteAddr="172.17.0.1:58136"
time="2024-05-26 23:19:28" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="172.17.0.1:58136"
time="2024-05-26 23:19:28" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:19:30" level=debug msg="Http Request" Method=GET Path=/api/info RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:19:30" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58140"
time="2024-05-26 23:19:30" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58140"
time="2024-05-26 23:19:32" level=debug msg="Http Request" Method=GET Path=/api/info RemoteAddr="172.17.0.1:58140"
time="2024-05-26 23:19:32" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:19:33" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:19:33" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:19:37" level=debug msg="Http Request" Method=GET Path=/static/css/main.6220e936.chunk.css RemoteAddr="172.17.0.1:58140"
time="2024-05-26 23:19:37" level=debug msg="Http Request" Method=GET Path=/static/js/2.09e56847.chunk.js RemoteAddr="172.17.0.1:58134"
time="2024-05-26 23:19:37" level=debug msg="Http Request" Method=GET Path=/static/css/2.5b1f1a89.chunk.css RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:19:37" level=debug msg="Http Request" Method=GET Path=/static/js/main.e34eac62.chunk.js RemoteAddr="172.17.0.1:34878"
time="2024-05-26 23:19:37" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="172.17.0.1:58134"
time="2024-05-26 23:19:37" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58134"
time="2024-05-26 23:20:00" level=debug msg="Http Request" Method=GET Path=/api/file/ RemoteAddr="172.17.0.1:58134"
time="2024-05-26 23:20:00" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:20:00" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:20:00" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58134"
time="2024-05-26 23:21:13" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58134"
time="2024-05-26 23:21:22" level=debug msg="Http Request" Method=POST Path=/api/lives RemoteAddr="172.17.0.1:58134"
time="2024-05-26 23:21:22" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:21:47" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:21:49" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:22:12" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:58122"
time="2024-05-26 23:22:24" level=debug msg="Http Request" Method=POST Path=/api/lives RemoteAddr="172.17.0.1:49764"
time="2024-05-26 23:23:00" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="172.17.0.1:58366"
time="2024-05-26 23:23:59" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:24:00" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:24:01" level=debug msg="Http Request" Method=GET Path=/static/css/2.5b1f1a89.chunk.css RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:24:01" level=debug msg="Http Request" Method=GET Path=/static/css/main.6220e936.chunk.css RemoteAddr="172.17.0.1:41068"
time="2024-05-26 23:24:01" level=debug msg="Http Request" Method=GET Path=/static/js/main.e34eac62.chunk.js RemoteAddr="172.17.0.1:41082"
time="2024-05-26 23:24:01" level=debug msg="Http Request" Method=GET Path=/static/js/2.09e56847.chunk.js RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:01" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:01" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:06" level=debug msg="Http Request" Method=GET Path=/api/info RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:06" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:06" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:07" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:16" level=debug msg="Http Request" Method=DELETE Path=/api/lives/4c1624b4167addb8e68931071375b277 RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:16" level=debug msg="Http Request" Method=PUT Path=/api/config RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:16" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:24:18" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:21" level=debug msg="Http Request" Method=POST Path=/api/lives RemoteAddr="172.17.0.1:41084"
time="2024-05-26 23:24:21" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:25:15" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:25:16" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:25:21" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:25:22" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:25:45" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:41060"
time="2024-05-26 23:25:52" level=debug msg="Http Request" Method=GET Path=/ RemoteAddr="172.17.0.1:53064"
time="2024-05-26 23:25:52" level=debug msg="Http Request" Method=GET Path=/static/css/2.5b1f1a89.chunk.css RemoteAddr="172.17.0.1:53064"
time="2024-05-26 23:25:52" level=debug msg="Http Request" Method=GET Path=/static/css/main.6220e936.chunk.css RemoteAddr="172.17.0.1:53068"
time="2024-05-26 23:25:52" level=debug msg="Http Request" Method=GET Path=/static/js/main.e34eac62.chunk.js RemoteAddr="172.17.0.1:53074"
time="2024-05-26 23:25:52" level=debug msg="Http Request" Method=GET Path=/static/js/2.09e56847.chunk.js RemoteAddr="172.17.0.1:53078"
time="2024-05-26 23:25:52" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="172.17.0.1:53078"
time="2024-05-26 23:25:52" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:53078"
time="2024-05-26 23:25:55" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:53078"
time="2024-05-26 23:25:58" level=debug msg="Http Request" Method=POST Path=/api/lives RemoteAddr="172.17.0.1:53078"
time="2024-05-26 23:25:58" level=error msg="http://192.168.1.: not support this url"
time="2024-05-26 23:25:58" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:53078"
time="2024-05-26 23:25:58" level=debug msg="Http Request" Method=PUT Path=/api/config RemoteAddr="172.17.0.1:53074"
time="2024-05-26 23:25:58" level=debug msg="Http Request" Method=GET Path=/api/lives RemoteAddr="172.17.0.1:53074"
time="2024-05-26 23:26:00" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:53078"
time="2024-05-26 23:26:12" level=debug msg="Http Request" Method=POST Path=/api/lives RemoteAddr="172.17.0.1:53078"
time="2024-05-26 23:26:12" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:53068"
time="2024-05-26 23:26:23" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:53068"
time="2024-05-26 23:26:24" level=debug msg="Http Request" Method=GET Path=/favicon.ico RemoteAddr="172.17.0.1:53074"
time="2024-05-

### 自由描述

一直初始化，没有显示直播信息

**Comment by kira1928** [comment]
添加的直播间url是多少？
配置文件发一下。

**Comment by admin1155** [comment]
> 添加的直播间url是多少？ 配置文件发一下。

你好，我的配置文件是默认的，没有改任何修改。直播url已经在配置文件里面了。经过我测试在宿主机上可以正常运行，但是在docker上运行就会出现这种情况，log里面是没有错误信息，我也不知道是什么情况，docker里面的网络访问是正常的，我没有使用-p进行端口映射，直接使用了host的网络以下是我的配置文件
rpc:
  enable: true
  bind: 0.0.0.0:8080
debug: true
interval: 30
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://live.bilibili.com/32702380
  is_listening: true
  quality: 0
  audio_only: false
- url: https://live.bilibili.com/5860504
  is_listening: true
  quality: 0
  audio_only: false
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

**Comment by kira1928** [comment]
>docker里面的网络访问是正常的

这个是怎么验证的呢？
可以在docker里面 wget  https://live.bilibili.com/32702380 试试看能不能访问到b站吗？
印象中以前有人也遇到过这个问题，好像是可以添加斗鱼等其他网站，唯独b站加不进去。也是docker，最后我也没明白b站为什么那么特殊= =

**Comment by kira1928** [comment]
反了，好像是只有b站能添加。
https://github.com/hr3lxphr6j/bililive-go/issues/347

**Comment by admin1155** [comment]
> 反了，好像是只有b站能添加。 #347

已经解决了。原因：
openwrt中需要在虚拟网卡中添加dockers容器的ip，否则会被禁止流量
解决方法：
iptables -t nat -A POSTROUTING -s 172.17.0.6/16 ! -o docker0 -j MASQUERADE
其中172.17.0.6/16改成容器的ip地址然后把docker0和eth0绑定在一起
然后重启网卡/设备

**Comment by kira1928** [comment]
希望对 @sirlioniva 有帮助
