### ISSUE TITLE
建议添加登陆系统，增加安全性

### ISSUE THREAD

**Issue by admin1155** [hr3lxphr6j/bililive-go#729]
### 新功能

原因：
后台管理通过访问IP：port就可以直接访问其不够安全。
为什么提出这个tip：
我是挂载在服务器上面通过本机进行访问，最近发现端口被扫描出来然后被人登陆后台破坏了我的系统，暂时没查到他是如何攻击我服务器的

**Comment by yshtcn** [comment]
其实这个解决方法比较简单，

使用nginx或者类似的服务反代本机端口，开启http用户名密码验证。然后在防火墙上关闭进方向的端口访问。

我最近正好在搭一些服务也遇到类似的问题，所以正好解决过。

**Comment by kira1928** [comment]
Duplicated of https://github.com/hr3lxphr6j/bililive-go/issues/623
