### ISSUE TITLE
虎牙直播显示录制中，但是不会生成录制文件

### ISSUE THREAD

**Issue by huangdaguo** [hr3lxphr6j/bililive-go#730]
### 程序版本

0.7.25

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.huya.com/934372
  is_listening: false
  quality: 0
  audio_only: false
- url: https://live.douyin.com/607459133
  is_listening: false
  quality: 0
  audio_only: false
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

time="2024-05-30 18:13:34" level=info msg="BiliLive-go Version: v0.7.25 Link Start"
time="2024-05-30 18:13:35" level=info msg="Server start at :8080"
time="2024-05-30 18:14:18" level=info msg="Live Start" host="奇领顾梦汐Yomi" room="拯救噜噜脸女孩！！"
time="2024-05-30 18:14:18" level=info msg="Record Start" host="奇领顾梦汐Yomi" room="拯救噜噜脸女孩！！"
time="2024-05-30 18:14:18" level=warning msg="failed to get stream url, will retry after 5s..." error="liveInfoJsonRawString not valid" host="奇领顾梦汐Yomi" room="拯救噜噜脸女孩！！"
time="2024-05-30 18:14:23" level=warning msg="failed to get stream url, will retry after 5s..." error="liveInfoJsonRawString not valid" host="奇领顾梦汐Yomi" room="拯救噜噜脸女孩！！"
time="2024-05-30 18:14:28" level=warning msg="failed to get stream url, will retry after 5s..." error="liveInfoJsonRawString not valid" host="奇领顾梦汐Yomi" room="拯救噜噜脸女孩！！"
time="2024-05-30 18:14:33" level=warning msg="failed to get stream url, will retry after 5s..." error="liveInfoJsonRawString not valid" host="奇领顾梦汐Yomi" room="拯救噜噜脸女孩！！"
time="2024-05-30 18:14:38" level=warning msg="failed to get stream url, will retry after 5s..." error="liveInfoJsonRawString not valid" host="奇领顾梦汐Yomi" room="拯救噜噜脸女孩！！"
time="2024-05-30 18:14:43" level=warning msg="failed to get stream url, will retry after 5s..." error="liveInfoJsonRawString not valid" host="奇领顾梦汐Yomi" room="拯救噜噜脸女孩！！"

### 自由描述

突然就不能生成文件了，早上还是好的，下午就不行了，我录的虎牙和抖音两个平台，抖音可以正常生成，虎牙不可以了

**Comment by kira1928** [comment]
已在 v0.7.26 中修复
