### ISSUE TITLE
虎牙报错无法录制【最新版】

### ISSUE THREAD

**Issue by wwkk2580** [hr3lxphr6j/bililive-go#732]
### 程序版本

0.7.26

### 程序 log

`time="2024-05-30 22:09:01" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="正恒、酥芙蕾【招财】" room="喂喂这个熬了快7年的主播吧"`

**Comment by kira1928** [comment]
已在 0.7.27 版中修复，正在打包准备发布。
