### ISSUE TITLE
2024.5.30号晚上开始huya的直播间无法录制

### ISSUE THREAD

**Issue by AZeC4** [hr3lxphr6j/bililive-go#734]
### 程序版本

chigusa/bililive-go   latest 

### 程序 log

time="2024-05-30 22:56:33" level=info msg="BiliLive-go Version: v0.7.26 Link Start"
time="2024-05-30 22:56:33" level=info msg="Server start at :8080"
time="2024-05-30 23:01:41" level=info msg="Live Start" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:01:41" level=info msg="Record Start" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:01:42" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:01:47" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:01:52" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:01:57" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:03" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:08" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:13" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:18" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:23" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:29" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:34" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:39" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:44" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:49" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:02:54" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:00" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:05" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:10" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:15" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:20" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:26" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:31" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:36" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:41" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:46" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"
time="2024-05-30 23:03:51" level=warning msg="failed to get stream url, will retry after 5s..." error="stream not found" host="夜崽崽丶" room="1599包出三个新角色，开整！"

### 自由描述

之前都是正常的，今天开始就不行了，同样的biliup那边的0.4.31版本也是今天开始不行了

**Comment by kira1928** [comment]
0.7.26中有一个问题导致这类错误，更新到最新的0.7.27应该可以解决。
