### ISSUE TITLE
程序的一个小问题

### ISSUE THREAD

**Issue by antonio65421** [hr3lxphr6j/bililive-go#735]
### 程序版本

v0.7.26 v0.7.27

### 自由描述

![WeChat 截圖_20240531111629](https://github.com/hr3lxphr6j/bililive-go/assets/143862835/d617f2cf-4e87-44b0-8cdb-e14b2342dae3)
当抖音主播如果是开启会员直播.或是隐藏直播会出现这个空白情况 箭头所指 他会出现录制中然后代码就会一直跑.......有时跑著跑著就容易直接崩溃... 还有一总情况会导致他崩溃当斗鱼主播讯号不好的时候没画面显示黑屏他也会一直跑程序 直到崩溃....

**Comment by kira1928** [comment]
能给个经常做这样直播的直播间 url 方便测试吗？

**Comment by antonio65421** [comment]
> 提供一個常做這樣直播的直播間網址方便測試嗎？

https://www.douyin.com/user/MS4wLjABAAAA9I3ot_BuoqMEKDeu-5XldirHoGhMfy8R5V_cs6xV5nE?previous_page=app_code_link

这个现在就是了

**Comment by kira1928** [comment]
抖音的问题已经确认到了，在修复。斗鱼大概是完全不同的问题，可以单独另发一个 issue 吗？

**Comment by kira1928** [comment]
已经修复抖音的问题，不会错误认为直播间在直播了，而是看作没有正确获取到直播间信息。
会在下一个版本中发布。

**Comment by antonio65421** [comment]
> 抖音的問題已經確認了，正在修復。
斗鱼不太好找直播间 通常是户外直播断讯才会这样黑屏

**Comment by antonio65421** [comment]
> 抖音的問題已經確認了，正在修復。

斗鱼的是这个 刚找的问题直播间https://github.com/hr3lxphr6j/bililive-go/issues/735#issuecomment-2141345892

**Comment by blackedxyz** [comment]
> > 抖音的問題已經確認了，正在修復。
> 
> 斗鱼的是这个 刚找的问题直播间 https://www.douyu.com/11495510?dyshid=3c15f5-1C:1B:0D:65:BA:AF&dyshti=0&dyshci=124

https://www.douyu.com/topic/lijiangtuanbo?rid=11495510&dyshid=0-d398204e3c06337b0343fea400091701
