### ISSUE TITLE
录制报错

### ISSUE THREAD

**Issue by zhouzhile** [hr3lxphr6j/bililive-go#739]
### 程序版本

6.11

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: # 如果此项为空，就自动在环境变量里寻找
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
live_rooms:
# qulity参数目前仅B站启用，默认为0
# (B站)0代表原画PRO(HEVC)优先, 其他数值为原画(AVC)
# 原画PRO会保存为.ts文件, 原画为.flv
# HEVC相比AVC体积更小, 减少35%体积, 画质相当, 但是B站转码有时候会崩
- url: https://www.huya.com/333003
  is_listening: true
  quality: 0 
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  # 仅在 use_native_flv_parser=false 时生效
  # 单位为字节 (byte)
  # 有效值为正数，默认值 0 为无效
  # 负数为非法值，程序会输出 log 提醒，并无视所设定的数值
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
#  当 custom_commandline 的值 不为空时，convert_to_mp4 的值会被无视，
#  而是在录制结束后直接执行 custom_commandline 中的命令。
#  在 custom_commandline 执行结束后，程序还会继续查看 delete_flv_after_convert 的值，
#  来判断是否需要删除原始 flv 文件。
#  以下是一个在录制结束后将 flv 视频转换为同名 mp4 视频的示例：
#  custom_commandline: '{{ .Ffmpeg }} -hide_banner -i "{{ .FileName }}" -c copy "{{ .FileName | trimSuffix (.FileName | ext)}}.mp4"'
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

time="2024-05-31 23:12:37" level=info msg="BiliLive-go Version: v0.7.25 Link Start"
time="2024-05-31 23:12:38" level=info msg="Server start at :8080"
time="2024-05-31 23:12:38" level=info msg="Live Start" host="Zz1tai姿态" room="督战乐"
time="2024-05-31 23:12:38" level=info msg="Record Start" host="Zz1tai姿态" room="督战乐"
time="2024-05-31 23:12:38" level=warning msg="failed to get stream url, will retry after 5s..." error="liveInfoJsonRawString not valid" host="Zz1tai姿态" room="督战乐"
time="2024-05-31 23:12:43" level=warning msg="failed to get stream url, will retry after 5s..." error="liveInfoJsonRawString not valid" host="Zz1tai姿态" room="督战乐"
time="2024-05-31 23:12:48" level=warning msg="failed to get stream url, will retry after 5s..." error="liveInfoJsonRawString not valid" host="Zz1tai姿态" room="督战乐"

### 自由描述

您好，我的是windows版本，从30号开始出错，虎牙其他直播间都报错，斗鱼，B站没事，麻烦大佬给看看

**Comment by kira1928** [comment]
虎牙的问题我修了好几个版本，目前的0.7.28版引入了一个可能导致程序崩溃的bug，预计下一个0.7.29版本能彻底修复虎牙录制。

**Comment by kira1928** [comment]
已发布v0.7.29修复该问题。
