### ISSUE TITLE
录制twitch出现bug

### ISSUE THREAD

**Issue by mshjz** [hr3lxphr6j/bililive-go#741]
### 程序版本

0.7.29

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.twitch.tv/et_1231
  is_listening: true
  quality: 0
  audio_only: false
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

time="2024-06-01 02:34:58" level=info msg="BiliLive-go Version: v0.7.29 Link Start"
time="2024-06-01 02:35:01" level=info msg="Server start at :8080"

### 自由描述

![screenshot-1717180587945](https://github.com/hr3lxphr6j/bililive-go/assets/50423102/c929a240-6151-4024-a883-ad208d438d7e)
录制twitch直播间时，主播明明在直播，运行状态显示监控中 初始化，而不录制

**Comment by kira1928** [comment]
目前不支持录制twitch
