### ISSUE TITLE
最新的版本windows报病毒

### ISSUE THREAD

**Issue by dingody** [hr3lxphr6j/bililive-go#743]
### 程序版本

v0.7.29

### 程序 log

![屏幕截图 2024-06-01 102741](https://github.com/hr3lxphr6j/bililive-go/assets/4937340/0261f1a0-2993-4c1e-92ce-286e87c83fe4)

### 自由描述

升级了最新版本，报病毒

**Comment by kira1928** [comment]
是从github release页面下载的exe吗？
程序一直是由git action自动打包发布的，源代码和打包脚本都在repo中明文可查，应该不会有这方面的问题的

**Comment by lbcake** [comment]
> 是从github release页面下载的exe吗？ 程序一直是由git action自动打包发布的，源代码和打包脚本都在repo中明文可查，应该不会有这方面的问题的

tg群 没了吗？

**Comment by kira1928** [comment]
tg 群在的，可以在置顶 issue 里找到

**Comment by dingody** [comment]
嗯，是从github release页面下载的exe，[0.7.27]这个版本没有问题

**Comment by kira1928** [comment]
我用自己的 Microsoft Defender 扫描了从 https://github.com/hr3lxphr6j/bililive-go/releases/download/v0.7.29/bililive-windows-amd64.zip 下载后解压出来的 exe 文件，没有报毒。

我这里无法重现问题，这个 issue 就先关闭了。之后如果有可以稳定重现的方法，可以再 reopen 这个 issue 。

**Comment by kira1928** [comment]
我更新了一下链接， https://t.me/+NPduQxFf9U40MjA1 你看这个可以用吗？

**Comment by lbcake** [comment]
> 我更新了一下链接， https://t.me/+NPduQxFf9U40MjA1 你看这个可以用吗？

![image](https://github.com/hr3lxphr6j/bililive-go/assets/26319880/509e34a9-414d-4278-9a00-5012b4bd2979)
不知道什么情况

**Comment by kira1928** [comment]
最近几天有其他人加入这个tg，应该不是链接的问题。剩下的我就不了解了。
