### ISSUE TITLE
[提问]: 请问微博没开直播怎么添加链接监控？

### ISSUE THREAD

**Issue by fgo1212** [hr3lxphr6j/bililive-go#744]
### 程序版本

最新

### 自由描述

请问微博没开直播怎么添加链接监控？

**Comment by kira1928** [comment]
没开播我也不知道怎么获得直播链接提前监控。
如果有其他开源项目实现了这一点，可以提供一下对方项目的 url，我可以参考他们的实现跟进这个功能。
