### ISSUE TITLE
虎牙貌似无法正常下载了？

### ISSUE THREAD

**Issue by xyjunco** [hr3lxphr6j/bililive-go#75]
今天下午发现所有下载任务全断掉了

![image](https://user-images.githubusercontent.com/4710858/84505555-7d261e00-acf0-11ea-849f-7e63956f4c4f.png)

**Comment by capric98** [comment]
遇到同样的问题，看了下好像虎牙把网页端推流改成了wss？

**Comment by lvv787** [comment]
命令是正常挂起的，但视频没有正常录制下来，视频文件也没有。不知道是不是和你们出现的是一样情况。
