### ISSUE TITLE
斗鱼录制有问题

### ISSUE THREAD

**Issue by antonio65421** [hr3lxphr6j/bililive-go#754]
### 程序版本

v0.7.29

### 所使用的 config 文件的内容

无

### 程序 log

无

### 自由描述

所有斗鱼主播录制后的影像 都会卡顿 不知道是不是斗鱼更新了什么录制出来的视频不顺畅 ts档 
https://www.douyu.com/10461999

**Comment by kira1928** [comment]
试了一下我录到的是 flv，播放很流畅。转成 mp4 后依然很流畅。
无法重现问题，无法调查。
