### ISSUE TITLE
使用抖音ID而非房间号来做为监控地址，可能导致一直初始化

### ISSUE THREAD

**Issue by seconream** [hr3lxphr6j/bililive-go#756]
### 程序版本

0.7.29

### 所使用的 config 文件的内容

都是默认的

### 程序 log

time="2024-06-10 13:31:20" level=error msg="failed to load room info" error="failed to get room status" url="https://live.douyin.com/69031430"
time="2024-06-10 13:31:35" level=error msg="failed to load room info" error="failed to get room status" url="https://live.douyin.com/7451749"
time="2024-06-10 13:31:51" level=error msg="failed to load room info" error="failed to get room status" url="https://live.douyin.com/29079569790"

### 自由描述

大部分配置为默认。出了问题的十多个直播间都是使用的抖音ID监控，同时他们也都是‘至少从添加监控那天开始，从未直播过’的直播间，不清楚哪个是触发bug的关键问题

**Comment by kira1928** [comment]
我这边可以加上，虽然没在直播，但可以看到直播间名和主播名，没有一直初始化。
问题无法重现。

**Comment by seconream** [comment]
> 我这边可以加上，虽然没在直播，但可以看到直播间名和主播名，没有一直初始化。 问题无法重现。

初始化問題後來自己消失了，現在只剩下log裡一直提示，不影響使用了。排除法發現都是從未開播的直播間會出現這個問題，那也就沒所謂。感謝回答

**Comment by kira1928** [comment]
我测试了 https://live.douyin.com/69031430 ，也是始终没有开播，但是可以进入监控状态，不会一直初始化。
log里偶尔有问题应该不大，程序定期去获取信息，只要有一次获取到了就可以正常显示和录制。
问题解决了就好，那 issue 就关闭啦。
