### ISSUE TITLE
win平台，斗鱼直播录像录制，近些天开始出现开始连接下载失败问题，错误日志显示如图；反复尝试多次后往往是可以正常录制的

### ISSUE THREAD

**Issue by marvinssky** [hr3lxphr6j/bililive-go#77]
![image](https://user-images.githubusercontent.com/37216223/84589899-92bc5480-ae64-11ea-8845-de97fe73d29e.png)

**Comment by marvinssky** [comment]
斗鱼前几日更新后，也出现了不定时录制中断问题，（参考用斗鱼客户端的录制是完整的，应该不是直播流本身的问题）

**Comment by hr3lxphr6j** [comment]
bililive-go依赖crypto-js, 用的是cf的源，国内有墙不稳定，多刷几次就好了(应该
