### ISSUE TITLE
运行没问题，直开播录制时就崩溃退出

### ISSUE THREAD

**Issue by wen2006953** [hr3lxphr6j/bililive-go#771]
### 程序版本

0.7.32

### 所使用的 config 文件的内容

默认的

### 程序 log

![aab32d6c6eb30c4493f81b8341d140f](https://github.com/user-attachments/assets/c19ea32f-c6e2-45c6-8ce0-8bda98f51c32)
![99ae3e6bc5e468d012dff0d3e6ab543](https://github.com/user-attachments/assets/b179c571-1922-4ca9-949a-a25e54a7e351)

### 自由描述

直接双击运行刚下载解压出来的程序，配置文件默认，然后界面上添加任一抖音正在直播的地址，就崩溃闪退了。别的电脑没有问题，不知道是不是我电脑内存太小了的原因。虚拟器运行的win10，只分配了3G内存。

**Comment by kira1928** [comment]
刚下载下来没有ffmpeg，所以程序崩溃了。
不过一般程序启动时就会提醒你ffmpeg不存在，不会到这里才崩溃的。
可能你系统路径里有ffmpeg，但这个ffmpeg有问题，不能正常运行，所以到录制的时候需要执行ffmpeg才崩溃。
总之这里应该给你错误提醒而不是程序崩溃，这里我可以修一下。
但ffmpeg的问题需要你看文档自己下载。

**Comment by wen2006953** [comment]
确实是ffmpeg的问题，我有下载，并且放在了主程序目录里面，yaml配置文件里面写的是./从目前来看没有获取到正确路径，但是日志输出./又可以正确输出到主程序目录。我直接把ffmpg放环境变量里好了，配置里放空，现在正常运行没有问题了。谢谢。

**Comment by kira1928** [comment]
ffmpeg有问题时程序崩溃问题已在v0.7.33版本中修复。
