### ISSUE TITLE
主播新直播间号问题

### ISSUE THREAD

**Issue by anlo1220** [hr3lxphr6j/bililive-go#78]
主播新直播间号问题
假如主播得到新房号 旧的会跳转到新的 如果新旧房号同时放就会出现两个 但同一主播
旧:
https://www.douyu.com/5706218
新:
https://www.douyu.com/9212

**Comment by hr3lxphr6j** [comment]
emm，我处理下重定向吧

**Comment by kira1928** [comment]
已在最新版中修复。
