### ISSUE TITLE
[提问]: out_put_tmpl 是用来配置保存文件的模板的吗，要如何用

### ISSUE THREAD

**Issue by talaon2** [hr3lxphr6j/bililive-go#801]
### 程序版本

all

### 自由描述

默认的中文名目录及文件名，兼容性不强，在linux有些情况下不能正常使用，请问out_put_tmpl 是用来配置保存文件的模板的吗，要如何用？

**Comment by kira1928** [comment]
最近刚好合并了一个大佬提供的关于命名模板的用法说明，可以看这里 https://github.com/hr3lxphr6j/bililive-go/blob/master/config.yml#L24-L26

**Comment by talaon2** [comment]
> 最近正好合并了一个大佬提供的关于命名模板的用法说明，可以看这里https://github.com/hr3lxphr6j/bililive-go/blob/master/config.yml#L24-L26

不错，很及时雨
