### ISSUE TITLE
可以再传个新的docker镜像吗，现在这个是5个月前的了，无法预览ts视频

### ISSUE THREAD

**Issue by CCTV-MMM** [hr3lxphr6j/bililive-go#818]
### 程序版本

v0.7.33

### 所使用的 config 文件的内容

rpc:
  enable: true
  bind: :8080
debug: false
interval: 20
out_put_path: /srv/bililive
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms: []
out_put_tmpl: ""
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies: {}
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000

### 程序 log

![image](https://github.com/user-attachments/assets/abe108af-8d97-4f3f-84a1-258ea6207903)

### 自由描述

无法预览ts视频

**Comment by kira1928** [comment]
这个功能有点小，大概要等merge了别的什么稍微大一些的功能或修复后才会发新release了。
