### ISSUE TITLE
bilibili 直播录制问题

### ISSUE THREAD

**Issue by zronghui** [hr3lxphr6j/bililive-go#82]
从 6. 29 号开始，随便添加一个直播间都会有以下错误：
msg="exit status 1" 

[我的命令行使用：
./bililive-darwin-386 -c ./config.yml
话](url)说，bililive-darwin-386是Mac的执行文件吧，分不清楚 386 还有 AMD，之前，用 AMD 也能录制，现在都不行了

**Comment by hr3lxphr6j** [comment]
提供下系统信息

**Comment by zronghui** [comment]
> 提供下系统信息

![image](https://user-images.githubusercontent.com/15062201/86326957-05a33900-bc75-11ea-993d-d262d7d1de57.png)

**Comment by hr3lxphr6j** [comment]
> > 提供下系统信息
> 
> ![image](https://user-images.githubusercontent.com/15062201/86326957-05a33900-bc75-11ea-993d-d262d7d1de57.png)

`uname -a`

**Comment by zronghui** [comment]
> > > 提供下系统信息
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15062201/86326957-05a33900-bc75-11ea-993d-d262d7d1de57.png)
> 
> `uname -a`

Darwin zhangronghuideMacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Comment by hr3lxphr6j** [comment]
> > > > 提供下系统信息
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/15062201/86326957-05a33900-bc75-11ea-993d-d262d7d1de57.png)
> > 
> > 
> > `uname -a`
> 
> Darwin zhangronghuideMacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

用`bililive-darwin-amd64`，我是10.15.5，测试是可以的

**Comment by zronghui** [comment]
> > > > > 提供下系统信息
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/15062201/86326957-05a33900-bc75-11ea-993d-d262d7d1de57.png)
> > > 
> > > 
> > > `uname -a`
> > 
> > 
> > Darwin zhangronghuideMacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
> 
> 用`bililive-darwin-amd64`，我是10.15.5，测试是可以的

感谢！我又仔细试了一下，可以用的。只是在 tmux 里面会出现 msg="exit status 1" 。应该是我自己什么时候操作错了
