### ISSUE TITLE
你好，想录黄播

### ISSUE THREAD

**Issue by lloyd18** [hr3lxphr6j/bililive-go#89]
棒子的直播平台，www.winktv.co.kr，能支持或提供思路吗？

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/87217255-c8782e80-c379-11ea-9198-5b4b2dbac853.png)
pc web用的flash，可以拆移动端的api http://m.winktv.co.kr/，不过扫了一眼请求的API感觉不好啃，form的字段名都加密了
![image](https://user-images.githubusercontent.com/12208550/87217441-cdd67880-c37b-11ea-88cb-116632bb5695.png)

**Comment by lloyd18** [comment]
有难度吗，或者看看另一个，www.pandalive.co.kr，直播内容都一样，只是网站模板微改。测试过，直播源是可以直接ffmpeg保存的，没有加密。19+直播需要登录，如果需要账号可以提供，

**Comment by lloyd18** [comment]
另外不知道这个对你有没有用，https://github.com/akshaywebllisto/pandalive_html

**Comment by hr3lxphr6j** [comment]
> 另外不知道这个对你有没有用，https://github.com/akshaywebllisto/pandalive_html

这是啥

**Comment by lloyd18** [comment]
> > 另外不知道这个对你有没有用，https://github.com/akshaywebllisto/pandalive_html
> 
> 这是啥

这个似乎是网站源码

**Comment by hr3lxphr6j** [comment]
> > > 另外不知道这个对你有没有用，https://github.com/akshaywebllisto/pandalive_html
> > 
> > 
> > 这是啥
> 
> 这个似乎是网站源码

这种玩意不会开源的吧，翻了下这个repo，感觉就是把网页的资源down下来了，没啥卵用

**Comment by hr3lxphr6j** [comment]
> 有难度吗，或者看看另一个，www.pandalive.co.kr，直播内容都一样，只是网站模板微改。测试过，直播源是可以直接ffmpeg保存的，没有加密。19+直播需要登录，如果需要账号可以提供，

已知m3u8直接喂给ffmpeg这当然没问题，问题是怎么拿到这个m3u8，追了他的js看了会有点烦

**Comment by lloyd18** [comment]
> > 有难度吗，或者看看另一个，www.pandalive.co.kr，直播内容都一样，只是网站模板微改。测试过，直播源是可以直接ffmpeg保存的，没有加密。19+直播需要登录，如果需要账号可以提供，
> 
> 已知m3u8直接喂给ffmpeg这当然没问题，问题是怎么拿到这个m3u8，追了他的js看了会有点烦

是不是开源不知道，但相似的网站至少5家以上，就是改下主页，共享主播内容，这个算是韩国最火的19+直播网站了吧，如果能支持将会造福大众啊，大佬有空再研究一下

**Comment by lemnrt** [comment]
建议添加这个chaturbate.com
参考https://github.com/sukara1992/chaturbate-downloader

**Comment by nonoandre** [comment]
> 建议添加这个chaturbate.com
> 参考https://github.com/oliverjrose99/Recordurbate

怎么样 现在还要吗 写了个link的插件 要的话给你

> 有难度吗，或者看看另一个，www.pandalive.co.kr，直播内容都一样，只是网站模板微改。测试过，直播源是可以直接ffmpeg保存的，没有加密。19+直播需要登录，如果需要账号可以提供，

怎么样 现在能录了吗 写了个streamlink的插件 要的话发你

**Comment by lloyd18** [comment]
> > 有难度吗，或者看看另一个，www.pandalive.co.kr，直播内容都一样，只是网站模板微改。测试过，直播源是可以直接ffmpeg保存的，没有加密。19+直播需要登录，如果需要账号可以提供，
> 
> 怎么样 现在能录了吗 写了个streamlink的插件 要的话发你

太需要了，lloyd18gg@gmail.com，有个使用帮助就更好了

**Comment by nonoandre** [comment]
> > > 有难度吗，或者看看另一个，www.pandalive.co.kr，直播内容都一样，只是网站模板微改。测试过，直播源是可以直接ffmpeg保存的，没有加密。19+直播需要登录，如果需要账号可以提供，
> > 
> > 
> > 怎么样 现在能录了吗 写了个streamlink的插件 要的话发你
> 
> 太需要了，[lloyd18gg@gmail.com](mailto:lloyd18gg@gmail.com)，有个使用帮助就更好了

ok  andre_inlook 是我 注意查收

**Comment by samlq** [comment]
> > 有难度吗，或者看看另一个，www.pandalive.co.kr，直播内容都一样，只是网站模板微改。测试过，直播源是可以直接ffmpeg保存的，没有加密。19+直播需要登录，如果需要账号可以提供，
> 
> 怎么样 现在能录了吗 写了个streamlink的插件 要的话发你

大神你好，pandalive的streamlink插件能发一份给我吗？谢谢

**Comment by liangshuocj** [comment]
> > 有难度吗，或者看看另一个，www.pandalive.co.kr，直播内容都一样，只是网站模板微改。测试过，直播源是可以直接ffmpeg保存的，没有加密。19+直播需要登录，如果需要账号可以提供，
> 
> 怎么样 现在能录了吗 写了个streamlink的插件 要的话发你

同求，liangshuocj@gmail.com

**Comment by youxia2016** [comment]
https://github.com/youxia2016/WinkTvLiveRecorder 已开源

**Comment by samlq** [comment]
你好，页面不存在了，麻烦您发一份给我。
谢谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月26日 11:11
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [hr3lxphr6j/bililive-go] 你好，想录黄播 (#89)


https://github.com/youxia2016/WinkTvLiveRecorder 已开源

―
