### ISSUE TITLE
斗鱼直播有时出现下载失败问题，同一时间虎牙直播就不会出现这一情况

### ISSUE THREAD

**Issue by marvinssky** [hr3lxphr6j/bililive-go#90]
斗鱼直播最近有时会出现下载失败问题，出现概率比较高，看报错信息似乎是TLS handshake超时，但是同一时间的虎牙直播就不会出现这一情况，如图
第一个下载的直播间是虎牙的下载正常，第二个是斗鱼的，就出现了下载失败的情况，尝试了其他斗鱼的直播间也下载失败

**Comment by marvinssky** [comment]
![新版本下载工具的报错~1](https://user-images.githubusercontent.com/37216223/87249108-bdafbd80-c48f-11ea-8046-298f5bc22920.jpg)

**Comment by marvinssky** [comment]
> #77 同一个问题

”bililive-go依赖crypto-js, 用的是cf的源，国内有墙不稳定“——但是同一时间的虎牙直播间直播下载就是正常的，就是图上的第一个直播间，可以正常下载；按道理不管虎牙和斗鱼下载直播视频应该都会依赖国外源的crypto-js吧，理解如果那时下载crypto-js时下载不了，应该虎牙和斗鱼都不能下载吧。

**Comment by marvinssky** [comment]
另外，如果考虑到国内有墙导致依赖的crypto-js下载可能经常会有问题，可不可以把这个需要的文件搞一个本地的备份版本，如果下载超时就用本地的文件版本~不知道这样行不行，thanks

**Comment by hr3lxphr6j** [comment]
> crypto-js

只有斗鱼依赖crypto-js
