### ISSUE TITLE
您好，不太懂编程方面的事情，想问一下twitch直播自动录制方面有什么好的办法吗

### ISSUE THREAD

**Issue by duodongyao** [hr3lxphr6j/bililive-go#92]
因为直播录制的方面找到这个软件，大致会用ffmpeg，这个不是很懂
想问一下，自己需要录制twitch的直播，有的主播没有保存录像，有没有好的自动录制的方法或者脚本之类的也可以
感谢解答，麻烦了

**Comment by hr3lxphr6j** [comment]
twitch的话bgo是支持的，不过国内录twitch要自备梯子

**Comment by duodongyao** [comment]
> twitch的话bgo是支持的，不过国内录twitch要自备梯子

您好，有没有联系方式之类的，第一次接触不太了解，想学习一下，

**Comment by hr3lxphr6j** [comment]
> > twitch的话bgo是支持的，不过国内录twitch要自备梯子
> 
> 您好，有没有联系方式之类的，第一次接触不太了解，想学习一下，

邮箱：c02110210610204@gmail.com
