### ISSUE TITLE
windows录制一段时间会报错然后保存到新文件,Ubuntu录制过一段时间进程会自己消失

### ISSUE THREAD

**Issue by RiotGamesU** [hr3lxphr6j/bililive-go#93]
1.windows:
录制一段时间会报错然后保存之前录制的,间隔一段时间会再录制新的,录制了一下午出现了很多次

time="2020-07-14 16:04:04" level=info msg="BiliLive-go Version: 0.5.7 Link Start"
time="2020-07-14 16:04:04" level=info msg="Live Start" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 16:04:04" level=info msg="Record Start" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 18:32:24" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/3567314\": read tcp 192.168.1.109:49858->36.156.56.244:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." url="https://www.douyu.com/topic/lolylyx_2?rid=3567314"
time="2020-07-14 18:32:36" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/3567314\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/topic/lolylyx_2?rid=3567314"
time="2020-07-14 18:32:41" level=warning msg="failed to get stream url, will retry after 5s..." error="Get \"https://www.douyu.com/swf_api/homeH5Enc?rids=3567314\": dial tcp: lookup www.douyu.com: no such host" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 20:29:35" level=warning msg="failed to get stream url, will retry after 5s..." error="room not exists" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 20:29:40" level=warning msg="failed to get stream url, will retry after 5s..." error="room not exists" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 20:29:44" level=info msg="Live end" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 20:29:44" level=info msg="Record End" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 20:43:44" level=info msg="Live Start" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 20:43:44" level=info msg="Record Start" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 22:17:24" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/3567314\": read tcp 192.168.1.109:58825->36.156.96.240:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." url="https://www.douyu.com/topic/lolylyx_2?rid=3567314"
time="2020-07-14 22:17:35" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/3567314\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/topic/lolylyx_2?rid=3567314"
time="2020-07-14 22:17:37" level=warning msg="failed to get stream url, will retry after 5s..." error="Get \"https://www.douyu.com/swf_api/homeH5Enc?rids=3567314\": dial tcp: lookup www.douyu.com: no such host" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 22:17:42" level=warning msg="failed to get stream url, will retry after 5s..." error="Get \"https://www.douyu.com/swf_api/homeH5Enc?rids=3567314\": dial tcp: lookup www.douyu.com: no such host" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 22:17:55" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/3567314\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/topic/lolylyx_2?rid=3567314"
time="2020-07-14 22:17:59" level=warning msg="failed to get stream url, will retry after 5s..." error="Get \"https://www.douyu.com/swf_api/homeH5Enc?rids=3567314\": dial tcp: lookup www.douyu.com: no such host" host="王纪超666" room="峡谷之巅小号冲王者"
time="2020-07-14 22:19:23" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/3567314\": read tcp 192.168.1.109:61260->120.220.231.242:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." url="https://www.douyu.com/topic/lolylyx_2?rid=3567314"
time="2020-07-14 22:19:24" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/3567314\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/topic/lolylyx_2?rid=3567314"
time="2020-07-14 22:19:44" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/3567314\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/topic/lolylyx_2?rid=3567314"

time="2020-07-14 16:19:29" level=info msg="BiliLive-go Version: 0.5.7 Link Start"
time="2020-07-14 16:19:30" level=info msg="Live Start" host="刘小又XD" room="刘小又：峡谷之巅冲第一！"
time="2020-07-14 16:19:30" level=info msg="Record Start" host="刘小又XD" room="刘小又：峡谷之巅冲第一！"
time="2020-07-14 18:32:32" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/1719183\": read tcp 192.168.1.109:50539->36.156.56.243:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." url="https://www.douyu.com/1719183"
time="2020-07-14 18:32:36" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/1719183\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/1719183"
time="2020-07-14 18:32:41" level=warning msg="failed to get stream url, will retry after 5s..." error="Get \"https://www.douyu.com/swf_api/homeH5Enc?rids=1719183\": dial tcp: lookup www.douyu.com: no such host" host="刘小又XD" room="刘小又 ：峡谷之巅冲第一！"
time="2020-07-14 22:17:32" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/1719183\": read tcp 192.168.1.109:58836->36.156.96.240:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." url="https://www.douyu.com/1719183"
time="2020-07-14 22:17:35" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/1719183\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/1719183"
time="2020-07-14 22:17:37" level=warning msg="failed to get stream url, will retry after 5s..." error="Get \"https://www.douyu.com/swf_api/homeH5Enc?rids=1719183\": dial tcp: lookup www.douyu.com: no such host" host="刘小又XD" room="刘小又 ：峡谷之巅冲第一！"
time="2020-07-14 22:17:42" level=warning msg="failed to get stream url, will retry after 5s..." error="Get \"https://www.douyu.com/swf_api/homeH5Enc?rids=1719183\": dial tcp: lookup www.douyu.com: no such host" host="刘小又XD" room="刘小又 ：峡谷之巅冲第一！"
time="2020-07-14 22:17:59" level=warning msg="failed to get stream url, will retry after 5s..." error="Get \"https://www.douyu.com/swf_api/homeH5Enc?rids=1719183\": dial tcp: lookup www.douyu.com: no such host" host="刘小又XD" room="刘小又 ：峡谷之巅冲第一！"
time="2020-07-14 22:18:00" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/1719183\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/1719183"
time="2020-07-14 22:19:09" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/1719183\": read tcp 192.168.1.109:51887->120.220.231.242:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." url="https://www.douyu.com/1719183"
time="2020-07-14 22:19:10" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/1719183\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/1719183"
time="2020-07-14 22:19:30" level=error msg="failed to load room info" error="Get \"https://open.douyucdn.cn/api/RoomApi/room/1719183\": dial tcp: lookup open.douyucdn.cn: no such host" url="https://www.douyu.com/1719183"

2.Ubuntu:
通过不同的配置文件执行的录制任务,过一段时间进程自动消失了
至于为什么要通过不同的配置文件的方式来执行命令:
首先直接用命令录制,命令可以成功执行,但是没有录制文件,看了以前的issue之后,我尝试用api的方式,但是用api添加不了录制,看到以前也有类似的issue但是您没处理,最后我看以前的issue发现use_native_flv_parser设置为true就可以了,希望您下个版本修复一下
以及上面的两个问题,主要是Ubuntu的,谢谢(另外问一下是不是docker的比较好用)

**Comment by hr3lxphr6j** [comment]
- > dial tcp: lookup open.douyucdn.cn: no such host"

    这个你检查下网络吧。

- 用systemd或者supervisor来管理进程，就算bgo挂了也会自动重启，觉得写配置麻烦那就docker吧。

- 之前的问题我在自己的archLinux上没法复现，怀疑的ffmpeg的问题，不行的话用docker吧。

**Comment by kira1928** [comment]
长期没有更新的 issue，先关闭了。
