### ISSUE TITLE
有关斗鱼直播依赖crypto-js的问题，昨天晚上开始遇到新的如下问题

### ISSUE THREAD

**Issue by marvinssky** [hr3lxphr6j/bililive-go#94]
下载crypto-js的连接被remote host中断，这个问题有什么办法解决吗？（尝试了挂vpn现象依然一样）
![新版本下载工具的报错~3_0715](https://user-images.githubusercontent.com/37216223/87465665-a0bdea80-c647-11ea-8bb5-ca5d61ea4410.jpg)

----------------------------------
另外，有关这个依赖crypto-js可能被容易被墙的问题有没有规避的方法；或者是否可以有本地备份crypto-js后，再依赖本地的crypto-js的下载工具版本~~谢谢

**Comment by hr3lxphr6j** [comment]
更新到0.5.8版本
