### ISSUE TITLE
bilibili 录制没主播名称

### ISSUE THREAD

**Issue by anlo1220** [hr3lxphr6j/bililive-go#95]
bilibili 录制没主播名称
最近两个版本 有时候录制 会出现没主播名称 也没存到主播的资料夹
本来 /哔哩哔哩/主播名称/[2020-07-11 21-15-51][极客湾Geekerwan][每周六晚9点，和你聊科技！].flv
现在有些会 /哔哩哔哩/[2020-07-14 19-40-42][][流行国语女唱见].flv

**Comment by anlo1220** [comment]
time="2020-07-15 15:09:48" level=info msg="Live end" host="智勋勋勋勋" room="智勋：晚上7点找小姐姐打游戏"
time="2020-07-15 15:09:48" level=info msg="Record End" host="智勋勋勋勋" room="智勋：晚上7点找小姐姐打游戏"
time="2020-07-15 17:02:16" level=info msg="Live end" host= room="打游戏打游戏打游戏！"
time="2020-07-15 17:02:16" level=info msg="Record End" host= room="打游戏打游戏打游戏！"
time="2020-07-15 17:02:28" level=info msg="Live Start" host= room="流行国语女唱见"
time="2020-07-15 17:02:28" level=info msg="Record Start" host= room="流行国语女唱见"

**Comment by hr3lxphr6j** [comment]
> time="2020-07-15 15:09:48" level=info msg="Live end" host="智勋勋勋勋" room="智勋：晚上7点找小姐姐打游戏"
> time="2020-07-15 15:09:48" level=info msg="Record End" host="智勋勋勋勋" room="智勋：晚上7点找小姐姐打游戏"
> time="2020-07-15 17:02:16" level=info msg="Live end" host= room="打游戏打游戏打游戏！"
> time="2020-07-15 17:02:16" level=info msg="Record End" host= room="打游戏打游戏打游戏！"
> time="2020-07-15 17:02:28" level=info msg="Live Start" host= room="流行国语女唱见"
> time="2020-07-15 17:02:28" level=info msg="Record Start" host= room="流行国语女唱见"

直播间url求提供下

**Comment by anlo1220** [comment]
https://live.bilibili.com/21464873

**Comment by anlo1220** [comment]
很多个都这样 但都是不定时出现 有时候中断录播 又会好
应该跟主播没关系

**Comment by hr3lxphr6j** [comment]
![image](https://user-images.githubusercontent.com/12208550/87528560-3f862d80-c6c0-11ea-82c9-7513af92d53f.png)
四暗刻 获取主播名字的逻辑好几个版本都没变了啊

**Comment by anlo1220** [comment]
我用0.57 0.58 常常都这样 0.55就正常

**Comment by anlo1220** [comment]
0.57 0.58
试了用 -i 单个网址都正常
用 -c 才会有问题

**Comment by hr3lxphr6j** [comment]
> 0.57 0.58
> 试了用 -i 单个网址都正常
> 用 -c 才会有问题

感觉和这个没关系，发现我没判断获取主播名api的返回值，我发一个版本你再试试

**Comment by hr3lxphr6j** [comment]
> > 0.57 0.58
> > 试了用 -i 单个网址都正常
> > 用 -c 才会有问题
> 
> 感觉和这个没关系，发现我没判断获取主播名api的返回值，我发一个版本你再试试

试试0.5.9

**Comment by anlo1220** [comment]
> > > 0.57 0.58
> > > 试了用 -i 单个网址都正常
> > > 用 -c 才会有问题
> > 
> > 
> > 感觉和这个没关系，发现我没判断获取主播名api的返回值，我发一个版本你再试试
> 
> 试试0.5.9
bili 全
e="2020-07-15 21:01:43" level=error msg="internal error" url="https://live.bilibili.com/905813"
time="2020-07-15 21:01:48" level=error msg="internal error" url="https://live.bilibili.com/461192"
time="2020-07-15 21:01:53" level=error msg="internal error" url="https://live.bilibili.com/49728"
time="2020-07-15 21:01:57" level=error msg="internal error" url="https://live.bilibili.com/439559"
time="2020-07-15 21:02:02" level=error msg="internal error" url="https://live.bilibili.com/21763298"
time="2020-07-15 21:02:06" level=error msg="internal error" url="https://live.bilibili.com/45827"
time="2020-07-15 21:02:11" level=error msg="internal error" url="https://live.bilibili.com/823709"
time="2020-07-15 21:02:15" level=error msg="internal error" url="https://live.bilibili.com/555986"
time="2020-07-15 21:02:20" level=error msg="internal error" url="https://live.bilibili.com/1517910"
time="2020-07-15 21:02:24" level=error msg="internal error" url="https://live.bilibili.com/1039633"
time="2020-07-15 21:02:28" level=error msg="internal error" url="https://live.bilibili.com/675014"
time="2020-07-15 21:02:33" level=error msg="internal error" url="https://live.bilibili.com/573893"
time="2020-07-15 21:02:37" level=error msg="internal error" url="https://live.bilibili.com/1540114"
time="2020-07-15 21:02:42" level=error msg="internal error" url="https://live.bilibili.com/544843"
time="2020-07-15 21:02:46" level=error msg="internal error" url="https://live.bilibili.com/351859"
time="2020-07-15 21:02:51" level=error msg="internal error" url="https://live.bilibili.com/21758363"
time="2020-07-15 21:02:55" level=error msg="internal error" url="https://live.bilibili.com/21742849"

**Comment by hr3lxphr6j** [comment]
> > > > 0.57 0.58
> > > > 试了用 -i 单个网址都正常
> > > > 用 -c 才会有问题
> > > 
> > > 
> > > 感觉和这个没关系，发现我没判断获取主播名api的返回值，我发一个版本你再试试
> > 
> > 
> > 试试0.5.9
> > bili 全
> > e="2020-07-15 21:01:43" level=error msg="internal error" url="https://live.bilibili.com/905813"
> > time="2020-07-15 21:01:48" level=error msg="internal error" url="https://live.bilibili.com/461192"
> > time="2020-07-15 21:01:53" level=error msg="internal error" url="https://live.bilibili.com/49728"
> > time="2020-07-15 21:01:57" level=error msg="internal error" url="https://live.bilibili.com/439559"
> > time="2020-07-15 21:02:02" level=error msg="internal error" url="https://live.bilibili.com/21763298"
> > time="2020-07-15 21:02:06" level=error msg="internal error" url="https://live.bilibili.com/45827"
> > time="2020-07-15 21:02:11" level=error msg="internal error" url="https://live.bilibili.com/823709"
> > time="2020-07-15 21:02:15" level=error msg="internal error" url="https://live.bilibili.com/555986"
> > time="2020-07-15 21:02:20" level=error msg="internal error" url="https://live.bilibili.com/1517910"
> > time="2020-07-15 21:02:24" level=error msg="internal error" url="https://live.bilibili.com/1039633"
> > time="2020-07-15 21:02:28" level=error msg="internal error" url="https://live.bilibili.com/675014"
> > time="2020-07-15 21:02:33" level=error msg="internal error" url="https://live.bilibili.com/573893"
> > time="2020-07-15 21:02:37" level=error msg="internal error" url="https://live.bilibili.com/1540114"
> > time="2020-07-15 21:02:42" level=error msg="internal error" url="https://live.bilibili.com/544843"
> > time="2020-07-15 21:02:46" level=error msg="internal error" url="https://live.bilibili.com/351859"
> > time="2020-07-15 21:02:51" level=error msg="internal error" url="https://live.bilibili.com/21758363"
> > time="2020-07-15 21:02:55" level=error msg="internal error" url="https://live.bilibili.com/21742849"

`curl https://api.live.bilibili.com/live_user/v1/UserInfo/get_anchor_in_room?roomid=905813`
看一下结果

**Comment by hr3lxphr6j** [comment]
你录这么多，感觉是被限流了吧

**Comment by anlo1220** [comment]
> 你录这么多，感觉是被限流了吧

我用回0.58正常 只是问题一样 centos7

-bash-4.2# curl https://api.live.bilibili.com/live_user/v1/UserInfo/get_anchor_in_room?roomid=905813
{"code":0,"msg":"success","message":"success","data":{"info":{"uid":9361427,"uname":"清则子","face":"https://i2.hdslb.com/bfs/face/7550f0a571ff9fbde5187a8f4aa287063dbca45e.jpg","rank":"10000","platform_user_level":5,"mobile_verify":1,"identification":1,"official_verify":{"type":0,"desc":"bilibili直播签约主播","role":2},"vip_type":0,"gender":0},"level":{"uid":9361427,"cost":278183918,"rcost":2832290597,"user_score":"0","vip":0,"vip_time":"2020-01-13 01:03:24","svip":0,"svip_time":"2018-12-19 18:53:01","update_time":"2020-07-15 22:02:39","master_level":{"level":33,"color":16746162,"current":[6700000,27313810],"next":[9100000,36413810],"anchor_score":28322905,"upgrade_score":8090905,"master_level_color":16746162,"sort":708},"user_level":39,"color":10512625,"anchor_score":28322905},"san":12}}-bash-4.2#

**Comment by anlo1220** [comment]
正常了

**Comment by hr3lxphr6j** [comment]
> 正常了

什么鬼...
